### ISSUE TITLE
Comment Support

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#1]
It would be nice if it could display the comments of a video below its description.

**Comment by omarroth** [comment]
Sure! Couple thoughts:

Right now, only Reddit comments are displayed under videos if they have them, and are (on average) higher quality. Personally, I prefer no comments over YT comments.

Reddit comments have a couple other advantages: 
- Better moderation tools (e.g. multiple moderators)
- Better format for conversation (e.g. proper nesting of comments)
- Easy tools for accessing comments (note that sorting by `top` on YT does not show comments in the order)

**Comment by edu-cated** [comment]
> Sure! Couple thoughts:
> 
> Right now, only Reddit comments are displayed under videos if they have them, and are (on average) higher quality. Personally, I prefer no comments over YT comments.
> 
> Reddit comments have a couple other advantages:
> 
> * Better moderation tools (e.g. multiple moderators)
> * Better format for conversation (e.g. proper nesting of comments)
> * Easy tools for accessing comments (note that sorting by `top` on YT does not show comments in the order)

https://voat.co is similar in structure to Reddit. Please try to support that too. Dissenter has some popularity now, perhaps that could be integrated also.

by the way, for "prefered video format" what does -dash mean? Could you in clude the option for "original" as a format/resolution? Many people have bigger displays than the 720p option.

**Comment by omarroth** [comment]
Please open a new issue for feature requests.

I'd recommend looking at #34 for more information on DASH means. It's a streaming technique to provide resolutions >1080p. I don't believe YouTube provides access to the "original" files originally uploaded by the author.
