### ISSUE TITLE
Thumbnails not loading

### ISSUE THREAD

**Issue by Gleddified** [omarroth/invidious#1003]
Recently have had this issue on two separate computers, both running firefox on linux mint.  Disabling my various privacy extensions doesn't seem to make a difference.

![Screenshot from 2020-01-26 14-18-17](https://user-images.githubusercontent.com/53153358/73141225-97c96480-4079-11ea-8763-dfd1ed23f02b.png)

**Comment by unixfox** [comment]
Better use the version without the `www`: https://invidio.us/

**Comment by Gleddified** [comment]
Done, thanks, I never even considered that. Unfortunately the issue persists in both cases.

**Comment by PrestonN** [comment]
Is thin mode enabled in your settings?

**Comment by Gleddified** [comment]
That did it, I'm a goof. Is this an intended feature of thin mode?
