### ISSUE TITLE
Error in src/invidious.cr:1: can't find file 'prelude'

### ISSUE THREAD

**Issue by sevospl** [omarroth/invidious#1007]
```
Error in src/invidious.cr:1: can't find file 'prelude'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?

# "Invidious" (which is an alternative front-end to YouTube)

```

I got the prelude lib + added CRYSTAL_PATH, but still not working. Any idea?

**Comment by omarroth** [comment]
How did you install Crystal? What platform (OS, arch) are you running on?

**Comment by sevospl** [comment]
> How did you install Crystal? What platform (OS, arch) are you running?

FreeBSD 11, amd64. I took the latest crystal 12.8 from the FreeBSD repo (pkg.freebsd.org), which is 0.28.

(Upgrading to the newer FreeBSD is out of question, since I'm not a root.)

**Comment by omarroth** [comment]
The FreeBSD package appears to have been updated since you made your comment, which reflects the latest version of Crystal 0.32.1. You may try updating to see if that resolves your issue.

**Comment by sevospl** [comment]
> The FreeBSD package appears to have been updated since you made your comment, which reflects the latest version of Crystal 0.32.1. You may try updating to see if that resolves your issue.

Yes, you're right. But Crystal is updated only for FreeBSD 12. Looks like I might have to give up on using Invidious on this particular server. Thanks though!
