### ISSUE TITLE
[invidio.us site issue] Subscription feeds have stopped updating

### ISSUE THREAD

**Issue by clarjon1** [omarroth/invidious#1009]
Hello,

It appears that there is an issue with updating subscription feeds at the moment. 

The last video shown on my subscriptions page at the time of writing last updated 19 hours ago.

However, my main youtube subs list (which is a near mirror image as I imported my subscriptions list from YT) is showing updates.

Screenshots attached for subs list comparison:
YT, new vid approx 25 mins ago:
![image](https://user-images.githubusercontent.com/627845/73496686-28a88480-4387-11ea-8d26-f430b0c399ce.png)
invidio.us: 
![image](https://user-images.githubusercontent.com/627845/73496731-3e1dae80-4387-11ea-971e-c97417bc5d3f.png)

**Comment by omarroth** [comment]
Should be fixed.

**Comment by gloschtla** [comment]
We would be glad to benefit from the [RSS feed for search queries](https://github.com/omarroth/invidious/issues/565), without needing an account.
