### ISSUE TITLE
Feature Request: include trusted instances into one cluster

### ISSUE THREAD

**Issue by gloschtla** [omarroth/invidious#1014]
It would be useful if invidio.us would automatically forward to other healthy instances like yewtu.be and vice versa, whenever the server of the first domain is down. In this case, only trusted instances should be taken. Or maybe it can be done after the client has agreed the question to forward to another instance.

**Comment by omarroth** [comment]
Duplicate of #944, omarroth/instances.invidio.us#6.

**Comment by gloschtla** [comment]
Sorry.
