### ISSUE TITLE
Issue getting all the comments of a video

### ISSUE THREAD

**Issue by libransser** [omarroth/invidious#1017]
Hi, I'm using the Invidious API in a bash script to download all the comments of a video, but there's a particular video where I'm getting an error message and I can't figure out if it's something I'm doing wrong or if it's an issue with the API.

What I'm doing is sorting by new, as when sorted by top not every comment is available, and then cycling through each comment looking if there are replies and if any, downloading all of the replies and continue with next main comment.

The script has worked as expected for every other video I have tried, close to 1,000 videos I'm guessing, but this particular video is giving me an error at exactly the same place every time. At this time the video has 239 comments, but it always happens when I have already downloaded the 126th comment.

The video is: https://www.youtube.com/watch?v=IcFVxh2_HaU

And the URL used that returns the error is:

```
https://invidio.us/api/v1/comments/IcFVxh2_HaU?sort_by=new&fields=commentCount,comments(author,authorId,authorUrl,isEdited,content,published,publishedText,likeCount,commentId,authorIsChannelOwner,creatorHeart,replies),continuation&continuation=ADSJ_i1_31EN5AuUuDTEdNq8PUDAgSjccHvWxQOEgdqwcph2ghf1GJ0TbdkviXbLj5fUDLHqtTKSWDCurbpS1Aj5XOZL4wEINtm0Wr2Ugy8rjMpXSrMj7a7Fe1LxTUFV2IYUK6IcXyGu
```

It returns the following response along with a 400 HTTP status code.

```
{"error":"Missing hash key: \"comments\""}
```

If I leave the `fields` parameter out as a response I get:

```
{"error":"Missing hash key: \"runs\""}
```

If I only leave the continuation token:

```
{"error":"Could not fetch comments"}
```

If I run the script but this time I sort by top, the same thing happens but this time after the 160th comment and with the URL:

```
https://invidio.us/api/v1/comments/IcFVxh2_HaU?fields=commentCount,comments(author,authorId,authorUrl,isEdited,content,published,publishedText,likeCount,commentId,authorIsChannelOwner,creatorHeart,replies),continuation&continuation=ADSJ_i23X_EVB0GWm97wYTsRNH9WVq8GlQFpw5MPAY-pgqw7wsLB7GLjDOUaxxbaUBXNp5cSNUJgkXSwDo6oEPsDsbui3vQtUjej51_2qHzEBFFTU738cZaLbtayi-YXQWIokf6y2ljzsTGRqiBD-rQtlqvy-Rt8omqyzDBtlDPpLc-LSY9XG8RbgtE4vLU5RyX5QqWscuxU2qdbfLy_v_ok8oYEUq0MJWSIPHAqmzYDpQkrLnac5mJ-SkRTzN73oTWLM2LsmvialvE8ctBCsNF92cLiLhr3tFMrTursTA08ZZGRoQ6_9L53Om-GM2igFSc0KRO7scmXlyC5nxVAPSyG9qFqH2ALaNCdTJEYSIy3_Mh7D6IzuUJfaf5b3fsHi3wfWtV6YlgPNtGb8g_ho0jKHcm2nw3ZiZIeNdv1jManPW-f-ZyiC8tPZTW0bumv_hpRk0uYqea8qTd521RRqHK5JRU8DfXby0wLqGrBUB_3PTZBYjB1hPZADQPMVSad4nWTnDwr814rQCC3QxZZrxFyg6NvBDWocQ8ofPV-012UajeaOpelXCXz1A10mxrDYDlpE9KIytKFQZ3qBIR0JaC66PdUVlOJ9HT8NjBvd59pDwo3EY8lBJUKD_0I52JYuTEIFVrBex47JXf04aDIn-z5JSdz8V9vby_Xjqtu1GaQns5D8ZNuctWPJlQXuHggcJhbC19ImrDVowG7NJu7gGZIeSe5arDyE_MqdLd0Pdgv3I58mbtECaZZo7FeJmXg2D1x
```

Any clue?

**Comment by omarroth** [comment]
Should be fixed with 9841f74adc94a4845aea6aace8d2408c3255dfa7.
