### ISSUE TITLE
Issue with the duration of a long video shown when hovering over the progress bar

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#102]
I cannot see it (its font size is too small). I am using the latest version of Pale Moon.

**Comment by omarroth** [comment]
Could you provide a screenshot of what you're seeing? Using pale moon the duration appears to look fine.

**Comment by Zero3K** [comment]
Here's the video where the issue happened:

https://www.invidio.us/watch?v=OW9Bp6LhDlw

**Comment by omarroth** [comment]
Unfortunately I'm having trouble reproducing this in Pale Moon. Video.js has also been updated to 7.x, which may include a fix for this issue. In either case, the issue would appear to be in Video.js, not Invidious.
