### ISSUE TITLE
No video thumbnails are shown anymore

### ISSUE THREAD

**Issue by PureTryOut** [omarroth/invidious#1024]
Since a week or so, my instance completely stopped displaying video thumbnails. I now only see videos by their title, but it makes it way harder to distinguish them.

I think this happened when I moved my docker-compose to pull from @omarroth Docker Hub image, but I'm not entirely certain.

**Comment by PureTryOut** [comment]
Interesting, I just noticed this only happens for logged in users. If you're not logged in, the thumbnails show up fine.

**Comment by PrestonN** [comment]
Try disabling "Thin Mode" in your user settings.

**Comment by PureTryOut** [comment]
Well, I feel awkward now, that did the trick. Not sure how that got enabled, I didn't even know it _was_ a setting. Thanks!
