### ISSUE TITLE
Error 500 when logging in

### ISSUE THREAD

**Issue by stemy2** [omarroth/invidious#1026]
Hello,

Invidio.us works only when i'm not connected, but if i try, i have a page saying "service unavailable" or "Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com", and according the developer tools, a HTTP 500 error.

**Comment by Perflyst** [comment]
invidio.us was probably temporary overloaded / not available. Try to use [another instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances) if the main instance does not work.
