### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by wilsden** [omarroth/invidious#1029]
There is a powerful server, this inscription appears 2-3 times a day Read timed out
Does not show the video on the page, I reboot the server is working fine

**Comment by haizrul** [comment]
Same as #426 #587 #225 

This problem also happen on my instance, running on Debian 10 with apache reverse proxy. Right now i'm using cpulimit (https://github.com/opsengine/cpulimit) as a way to prevent read timed out server. I hope someone can find a solution for this problem.

**Comment by wilsden** [comment]
Yes, I also use the server on Debian 10

**Comment by haizrul** [comment]
This is the command i use for cpulimit:

`sudo cpulimit -e invidious -l 100 -k -b`

What this command will do is, everytime cpu usage reach 100%, cpulimit will kill the process and new process will be created automatically by invidious. You can also use `cpulimit -h` for help.

**Comment by wilsden** [comment]
> Это команда, которую я использую для cpulimit:
> 
> `sudo cpulimit -e invidious -l 100 -k -b`
> 
> Эта команда будет делать то, что каждый раз, когда загрузка процессора достигает 100%, cpulimit убивает процесс, а новый процесс автоматически создается invidious. Вы также можете использовать `cpulimit -h`для помощи.
