### ISSUE TITLE
Thumbnails missing

### ISSUE THREAD

**Issue by peterge1998** [omarroth/invidious#1034]
Since about a week the thumbnails of all videos are missing, which worked fine before:
![Screenshot_20200215_213240](https://user-images.githubusercontent.com/47355238/74594828-f95a6e80-503a-11ea-9fa4-b50de503d1eb.png)

Edit: Thumbnails work on my own instance. The problem persits with invidio.us. That means its not my browser/addons causing this.

**Comment by PrestonN** [comment]
Disable "thin mode" in your settings.

@omarroth has this become a default setting recently? A lot of people have been making issues about this.

**Comment by peterge1998** [comment]
Works now.

**Comment by omarroth** [comment]
> @omarroth has this become a default setting recently? A lot of people have been making issues about this.

No, it's been a persistent issue. I think it would make sense to either rename or remove it, since people appear to be enabling it by mistake.
