### ISSUE TITLE
how to combine 2 databases of two invidious?

### ISSUE THREAD

**Issue by wilsden** [omarroth/invidious#1041]
Hello!
I want to combine the databases so that the database is assembled on one 
invidious! how to do this? where to begin?

**Comment by omarroth** [comment]
I'd recommend taking a look at the documentation for [pg_dump](https://www.postgresql.org/docs/12/app-pgdump.html). You should be combine them like so:

```
$ pg_dump -d $your_first_database > db.sql
$ psql -d $your_second_database -f db.sql
```
