### ISSUE TITLE
Channel page and RSS feeds broken, when using channel name or username

### ISSUE THREAD

**Issue by garbageeperson** [omarroth/invidious#1048]
Previously channel page and RSS feeds would work with channel name or username, but now it gives an error instead.
Examples:
https://invidio.us/channel/bkraz333
https://invidio.us/feeds/videos.xml?user=bkraz333

Channel pages and RSS feeds with channel ID still work.
Examples:
https://invidio.us/channel/UCivA7_KLKWo43tFcCkFvydw
https://invidio.us/feeds/videos.xml?channel_id=UCivA7_KLKWo43tFcCkFvydw

Both of these are getting linked from various pages on invidio.us and elsewhere and work for youtube.com.
Also breaking URLs isn't nice.

Edit:
Doesn't seem to happen all the time, is this just some other problem?

**Comment by omarroth** [comment]
Status code for missing channel pages appears to have changed. Should be fixed with e21f77048579bc42f52d462bd3d41a68312fb157.
