### ISSUE TITLE
Site is down when watching a video

### ISSUE THREAD

**Issue by NoVa-UX** [omarroth/invidious#1054]

**Comment by NoVa-UX** [comment]
I'm not sure what's happening...if there is a just updates constantly or what, but there seems to be a bug or two to where it goes down.  For some odd reason

**Comment by grravity** [comment]
the sites been dying for the past few days. Maybe Google trying to block idk. Or just overloaded servers. But it's really fucking annoying lol

**Comment by talentlessguy** [comment]
I hate Invidious not working at all
