### ISSUE TITLE
MATLAB- Discrete wavelet decomposition dwt2() and wavedec2() for multiple images (for loop) and feature extraction into excel sheets

### ISSUE THREAD

**Issue by PhilipABIODUN** [omarroth/invidious#1056]
I am performing discrete wavelet decomposition. I want to do this for about 1000 images, then extract features from the images and save them in excel. Each row of the excel sheet containing the corresponding values of the features for each image. Here are the codes:
files2=dir('C:\Users\Abiodun\Desktop\PROJECT MATLAB ANALYSIS\Histogram Equalization\*.jpg');
for j=1:length(files2) %% Read the the Equalized Data % filename2=strcat('C:\Users\Abiodun\Desktop\PROJECT MATLAB ANALYSIS\Histogram Equalization\',files2(j).name);
 J=imread(filename2);%READS THE EQUALIZED IMAGES
    [ca,ch,cv,cd]=dwt2(J,'bior3.9');
    figure,imshow(ca);
    %%Multilevel Wavelet Decomposition %
    [c,s]=wavedec2(J,3,'bior3.9');
            %%Extraction of Coefficients %
            [ch,cv,cd]=detcoef2('all',c,s,3);
            % Second level decomposition
            ca2=appcoef2(c,s,'haar',2); % Approximation coefficient of the second level decomposition
            [ch2,cv2,cd2]=detcoef2('all',c,s,2); % Detail (horizontal, vertical and diagonal) coefficient of the second level decomposition
           figure,imshow(ca2);
            % Third level decomposition
             ca3=appcoef2(c,s,'haar',3); % Approximation coefficient of the third level decomposition
            [ch3,cv3,cd3]=detcoef2('all',c,s,3); % Detail (horizontal, vertical and diagonal) coefficient of the third level decomposition
            figure,imshow(ca3);
%% FEATURE EXTRACTION
            %%FOR THE FIRST LEVEL DECOMPOSITION
             %%MEAN OF THE MINIMUMS (FIRST LEVEL)
             Min_Mean_approx_comp_1=mean(min(ca));
             Min_Mean_horiz_comp_1=mean(min(ch));
             Min_Mean_vert_comp_1=mean(min(cv));
             Min_Mean_diag_comp_1=mean(min(cd));
%.....
%....
% and so on
end
The for loop is not working for all the images. It at a point sees j as 1 instead of 1:length(files2).
Any help will be appreciated

**Comment by omarroth** [comment]
I think you made an issue on the wrong project. This is a repository for a YouTube front-end.
