### ISSUE TITLE
Youtube dll In Php

### ISSUE THREAD

**Issue by hhuseyn** [omarroth/invidious#1059]
how to use youtube dll like inviodious in php.I use it in php but  as the request increases is not working?

**Comment by omarroth** [comment]
Hi, I'm having trouble understanding your question. How are you trying to use Invidious?

**Comment by hhuseyn** [comment]
Hello again. I want using your invidious sytems my php code.
Example youtube-dl i can using my php code 
<?php
 define('YOUTUBE_DL', '/usr/local/bin/youtube-dl'); // find your youtube-dl path and replace with it
$youtube_video = 'https://www.youtube.com/watch?v=e4Uq8O5ZhUA'; // replace with any youtube video
$video_json_command = YOUTUBE_DL.' ---print-json  '.$youtube_video;
echo $video_json_command;
?>
How can using invidous like youtube-dl ?
I need get video page data json. But i dont want using invidous api systems because /api sytems get long time.Possible i  using this get function my php code ?

**Comment by omarroth** [comment]
Invidious is not a direct drop-in replacement for youtube-dl. If https://invidio.us is not adequate I would recommend building it yourself from the `api-only` branch. You can then make requests to e.g. `localhost:3000/api/v1/videos/$ID`.

Is there a reason you want to use Invidious over youtube-dl?

**Comment by hhuseyn** [comment]
Yes i try api-only branch but this very slow. I want using invidous. But i want using invidious sytems my php code .How can using command get video data with php command  invidous  ? You can paid support me ???

**Comment by r-a-y** [comment]
youtube-dl already supports invidio.us links.  youtube-dl will just rewrite the links to use YouTube in that case.  They don't ping the Invidious API.

@hhuseyn - youtube-dl is not a PHP app.  However, there is a youtube-dl-php library that you can use: https://github.com/norkunas/youtube-dl-php

If you don't want to use youtube-dl and want to grab the details of a YouTube video with invidious, you need to learn how to do [Invidious API](https://github.com/omarroth/invidious/wiki/API) requests in PHP with [cURL](https://www.labnol.org/code/19998-php-curl-example).

You could use https://invidio.us as the base, but the site might not always be up.

**Comment by hhuseyn** [comment]
I need paid support please reply me
