### ISSUE TITLE
[Feature Request] Add a filter to select videos by duration

### ISSUE THREAD

**Issue by sebma** [omarroth/invidious#1060]
Hi,

Can you please add a filter to select videos by duration ?

**Comment by omarroth** [comment]
You can do this with `duration:long` or `duration:short`. See [search operators](https://github.com/omarroth/invidious/wiki/Search-operators).

Closing in favor of #179.

**Comment by sebma** [comment]
@omarroth Your documentation lacks an example.

I tried this but it does not work : https://invidio.us/search?q=joseph%20prince&duration:long

**Comment by sebma** [comment]
@omarroth I tried this but it does not work : https://invidio.us/search?q=joseph%20prince&duration:long

**Comment by sebma** [comment]
@omarroth Got it : https://invidio.us/search?q=joseph+prince+duration:long+sort:date 

Sorry for asking :)
