### ISSUE TITLE
[Feature Request] Add an option to order videos by date or relevance

### ISSUE THREAD

**Issue by sebma** [omarroth/invidious#1061]
Hi,

Can you please add an option to order videos by date or relevance ?

**Comment by omarroth** [comment]
You can do this with `sort:date` and `sort:relevance`. See [search operators](https://github.com/omarroth/invidious/wiki/Search-operators).

Closing in favor of #179.

**Comment by sebma** [comment]
Got it : https://invidio.us/search?q=joseph+prince+duration:long+sort:date
