### ISSUE TITLE
Unable to search Videos using YouTube link from phone. 

### ISSUE THREAD

**Issue by tankmohit** [omarroth/invidious#1062]
Whenever I try searching a specific video using YouTube URL starting with “http://www.youtube.com” or “http://youtube.com” it works fine. But searching using URL starting from “m.youtube.com” yields no search results. I have to remove that “m.” Part from the URL to see search results. 

Please fix this issue.

**Comment by omarroth** [comment]
Could you provide an example?

**Comment by tankmohit** [comment]
Here is the screen recording. 

https://streamable.com/8snov

**Comment by tankmohit** [comment]
Searching using URL staring with “m.” Gives no result. 
<img width="414" alt="M  Yt" src="https://user-images.githubusercontent.com/27958239/76530038-8251a380-6449-11ea-8edc-a3b3df4d1354.png">

But removing “m.” Does
<img width="414" alt="Regular " src="https://user-images.githubusercontent.com/27958239/76530054-88e01b00-6449-11ea-8189-c01eb4a39ed3.png">

**Comment by omarroth** [comment]
I can't reproduce this locally. Could you please provide the actual text you're using to search?

**Comment by tankmohit** [comment]
You can try with this link in phone

https://m.youtube.com/watch?v=8idr1WZ1A7Q

**Comment by omarroth** [comment]
YouTube appears to serve no results when searching with mobile links:
https://www.youtube.com/results?search_query=https%3A%2F%2Fm.youtube.com%2Fwatch%3Fv%3D8idr1WZ1A7Q&page=&utm_source=opensearch

**Comment by tankmohit** [comment]
Search the given link in invidious.

**Comment by omarroth** [comment]
The reason I linked to YouTube's search page is because Invidious is dependent on what YouTube provides. In this case the issue appears to be with YouTube since the search page is empty.

**Comment by tankmohit** [comment]
If that is the issue then invidious gives results for the link without “m.”  And can’t give result for URL starting with “m.”
