### ISSUE TITLE
Referer Filter Bypass

### ISSUE THREAD

**Issue by wfinn** [omarroth/invidious#1065]
Hi, I found a way to redirect to any site via the referer parameter.
Verified in chrome, here's the payload:
```
/%09/a.bc
https://invidio.us/login?referer=%2F%09%2Fa.bc
```
%09 (tab) will be removed by some browsers, and so the location header is read as //a.bc.

This might be dangerous for the login with google flow, but I don't want to go too far here so I didn't check.

Just to be clear, this seems to work everywhere where the referer parameter is used.

**Comment by omarroth** [comment]
Much appreciated. Should be fixed with 4011a113ccc1241b60f607ce76db982625f7b9b1.

**Comment by wfinn** [comment]
Looks nice, fast action!
