### ISSUE TITLE
Hello omarroth i am reday paid you now 100 dollar

### ISSUE THREAD

**Issue by muzika42** [omarroth/invidious#1066]
Hello omarroth i am reday paid you now 100 dollar. Please help me . I need very simply work.

**Comment by muzika42** [comment]
I need using this invidous script result get with php. How i can send request invidious with php

**Comment by muzika42** [comment]
I need you 30 minute. I paid 100 dollar before at work. Itis very simple work. I am reday  paid you paypal adress now

**Comment by omarroth** [comment]
Hi. If you would like help you need to provide more information.

Closing as duplicate of #1059.
