### ISSUE TITLE
"Mark as watched" doesn't work since March 15

### ISSUE THREAD

**Issue by rex4539** [omarroth/invidious#1069]
Steps:
In your subscriptions, click on the "Mark as watched" icon on the top left of the video image.

What happened:
Video is removed for a split second and then reappears.

Expected result:
Video is removed.

**Comment by rex4539** [comment]
@omarroth Do you know which commit broke it?

**Comment by omarroth** [comment]
It appears to work as expected for me. You may try a hard reload (Ctrl+Shift+R) to see if that fixes the issue.

Likely related to #1023.

**Comment by rex4539** [comment]
Hard reload fixed it.

**Comment by rex4539** [comment]
And today it's suddenly fixed. Weird...
