### ISSUE TITLE
Where did invidiou.sh go?

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#1070]
I used to watch videos on invidiou.sh but looks like the site is no longer available now. Is the admin here? I have an unused VPS if the admin of the site interested on continuing the site online. Hit me up on Skype : mazelanrahman if ur interested.

**Comment by haizrul** [comment]
@Perflyst that your instance right?

**Comment by haizrul** [comment]
closed, no response.

**Comment by Perflyst** [comment]
Sorry, I missed the issue. No it is not my instance, mine is still up. :)
invidiou.sh closed because the admin decided to close it, that's it.

**Comment by haizrul** [comment]
> Sorry, I missed the issue. No it is not my instance, mine is still up. :)
> invidiou.sh closed because the admin decided to close it, that's it.

Oo i see. Thanks for the info. 👍
