### ISSUE TITLE
Please update invidious instances

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#1071]
Please update instances list on https://uptime.invidio.us & https://instances.invidio.us . Some of the instances are offline but still listed there.

**Comment by Perflyst** [comment]
yewtu.be is up but it looks like the admin blocked the uptimerobot ;)

**Comment by haizrul** [comment]
> yewtu.be is up but it looks like the admin blocked the uptimerobot ;)

Its down last i checked 2 days ago. Looks okay now.

**Comment by omarroth** [comment]
uptime.invidio.us and instances.invidio.us both now appear to be up-to-date.

**Comment by haizrul** [comment]
Thank you @omarroth
