### ISSUE TITLE
Remove title tag from video player to prevent it being shown while watching video.

### ISSUE THREAD

**Issue by comicsads** [omarroth/invidious#1076]
Title says it all. When I'm watching videos in full screen I'll see a tool tip from title attribute in html that shows me the title of the video. It's annoying to have to move the mouse all the way over to the side of the screen to hide this. I feel like whatever the point of having the title attribute there would be better server by the alt attribute, though I'm not sure if that works for video elements.

**Comment by NoVa-UX** [comment]
It is pretty annoying to have to move it all the way to the side...

**Comment by Ileca** [comment]
So annoying. Moving it to the side will not help as long as you are on the video. You have to bear for the tag to show and then you can remove it by moving your mouse.

**Comment by omarroth** [comment]
Should be fixed with 0e58d99f4e17618d67fb78d79b10a11fb0b0811d.
