### ISSUE TITLE
Add option to sort videos on a channel by votes (top rated)

### ISSUE THREAD

**Issue by mendel5** [omarroth/invidious#1081]
**Current situation**
Invidious and YouTube.com currently have the option to sort videos on a channel by three parameters:
- newest
- oldest
- popular / most views

**Proposal**
Many content platforms support more sorting parameters than just these three. It would be great if Invidious had a sorting parameter to sort videos on a channel by their vote ratio. Maybe this can be called "top rated".

Sorting videos by this parameter lists them by their vote ratio in descending order. The video with the best ratio of upvotes/ downvotes is at the top and the worst at the bottom.

This allows users to better find interesting videos on their favorite channels.

**Example**
Channel:
https://invidio.us/channel/UCBx31Z-5XRe5Y2qYWVQa8yw

Current sorting options for videos on the channel:
https://invidio.us/channel/UCBx31Z-5XRe5Y2qYWVQa8yw?page=1&sort_by=newest
https://invidio.us/channel/UCBx31Z-5XRe5Y2qYWVQa8yw?page=1&sort_by=oldest
https://invidio.us/channel/UCBx31Z-5XRe5Y2qYWVQa8yw?page=1&sort_by=popular

Proposed new option:
https://invidio.us/channel/UCBx31Z-5XRe5Y2qYWVQa8yw?page=1&sort_by=top-rated

**Comment by omarroth** [comment]
In order for this to work, Invidious would need to track an internal list of all videos from a channel, which isn't really practical IMO.

I expect search filters will be limited to what YouTube provides for the foreseeable future.
