### ISSUE TITLE
What happened to old player ?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#1083]
what happened to the old player ? 
the old player was good for me because i was able to select quality of the video but not it get automatic and i not want that because my quota will die much faster now and most of websites now not support the option to get back to the old player so tell me how to select quality in that new player or bring back the support for old one.

NOTE: i tried change settings to YT player and made quality medium but still nothing change

I talk about video player that changed from: 
![Screenshot 2020-03-26 22:18:50](https://user-images.githubusercontent.com/28893833/77693001-8cbe8200-6f9f-11ea-8727-d4632df29b77.png) to: 
![Screenshot 2020-03-26 22:19:04](https://user-images.githubusercontent.com/28893833/77693047-a069e880-6f9f-11ea-893a-7d5769163674.png)

**Comment by EsmailELBoBDev2** [comment]
and i forgot to mention that comments too not appear so player not work and comments not appear (or not load from first place, not sure) 
![Screenshot 2020-03-26 23:18:06](https://user-images.githubusercontent.com/28893833/77697748-571d9700-6fa7-11ea-8291-b0a12c06addf.png) and by add label "bug" on my ticket is means you did not remove support for old player ? i thought you deleted old player so i came here as sorta of request to bring it back

**Comment by gwennshinguji** [comment]
bump. having the opposite issue though. when i have the player style set to "YouTube" rather than Invidious, it still uses the Invidious UI for the player.

tried on both https://invidio.us and https://invidious.snopyta.org.

**Comment by leonklingele** [comment]
Might be a caching issue. Have you tried to reproduce this in an Incognito window?

**Comment by EsmailELBoBDev2** [comment]
i tried in even other browser and still, yes

**Comment by omarroth** [comment]
Should be fixed with 3b2e142542cf051c89b7a6b678463b0693489b91.

**Comment by EsmailELBoBDev2** [comment]
Yup, i can confirm that form my side!
