### ISSUE TITLE
Requests blocked?

### ISSUE THREAD

**Issue by Poliwrath** [omarroth/invidious#1084]
```
invidious_1  | xxxx : Could not extract channel info. Instance is likely blocked. url: /browse_ajax?continuation=xxx&gl=US&hl=en
```
When I visit a channel page on a local instance, this appears in the log. (I edited it to display the url, too). 
When I open the page in a incognito mode tab and complete the captcha, this issue still happens.

This issue can apparently be bypassed on google searches by simply changing the domain (i.e google.com -> google.ca), so maybe a similar workaround can be implemented for youtube.com...

**Comment by Perflyst** [comment]
Your IP is blocked, yes. If you solve a captcha you can add the cookie into the invidious config as explained in the wiki, but that is annoying after some time.

The workaround is to use https://anti-captcha.com

**Comment by omarroth** [comment]
See #811, #886.
