### ISSUE TITLE
API can stream audio ?

### ISSUE THREAD

**Issue by stephane-r** [omarroth/invidious#1085]
Hello community :)

After reading your dev docs, i'm not really sur if your API can stream audio, without use frontend player ?

I've see MusicPiped sources, but i'm not good with Flutter :D 

Thank you !

**Comment by omarroth** [comment]
You can get the URLs for audio sources from the API, specifically `adaptiveFormats` which you can filter by `type`. [Example](https://invidio.us/api/v1/videos/aqz-KE-bpKQ?pretty=1&fields=adaptiveFormats(url,type)). Audio sources will have `type` starting with "audio".

**Comment by stephane-r** [comment]
Hi @omarroth , thank for your reponse :)

This sources need to be download, no "streaming" url ?
