### ISSUE TITLE
Change the country of the popular/trending videos?

### ISSUE THREAD

**Issue by sprite-1** [omarroth/invidious#1087]
It would be great if there was an option to change the country where the popular and trending videos are being fetched from. Currently, I believe it is set to the United States.

I thought changing the language would affect it but even if I changed the language to, say, FR, it's still showing the same vdeos

**Comment by elypter** [comment]
duplicate of  #331

you can do it already, just not in the ui.

**Comment by sprite-1** [comment]
Doesn't seem to work for the Popular videos

**Comment by elypter** [comment]
only trending

**Comment by omarroth** [comment]
Popular videos are provided by Invidious, not YouTube, and are specific to the instance. Currently I don't think it's practical to provide country-specific videos on the popular page.

As @elypter mentioned, you can do this with Trending by adding `&region=REGION` to the URL, although unfortunately it's not available in the UI yet.

Closing in favor of #331.
