### ISSUE TITLE
Multiple devices with the same account

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#109]
Currently, when logging into the same account on a second device, the first devce automatically gets logged out.

Someone who wants to browse on multiple devices either has to periodically sync their subscriptions between different accounts, or log in every time they change devices - unless one account can be used on multiple devices.

Tested with a non-Google account, I don't know how a Google account behaves when used from more than one device.

**Comment by omarroth** [comment]
Yep! With Google accounts, sessions are managed by Google, so it works fine on multiple devices. Expect this to be added soon.

**Comment by Discookie** [comment]
Implemented in 8adb465.
