### ISSUE TITLE
Display all tabs on a channel (e.g. Channels, About)

### ISSUE THREAD

**Issue by mendel5** [omarroth/invidious#1093]
**Description**

When you view a channel on YouTube.com, there are six tabs:
- Home
- Videos
- Playlists
- Community
- Channels
- About

When you view a channel on Invidious, there are only three tabs:
- Videos
- Playlists
- Community

The tabs "Channels" and "About" should also be displayed on Invidious. The "Home" tab can be displayed too, but might be not that important.

**Example**

On https://www.youtube.com/channel/UCBx31Z-5XRe5Y2qYWVQa8yw there are six tabs.

On https://invidio.us/channel/UCBx31Z-5XRe5Y2qYWVQa8yw there are only three tabs.

**Comment by mendel5** [comment]
Related:

- [ [Meta] Enhance and expand channel overview #483 ]( https://github.com/omarroth/invidious/issues/483 )
- [ Display if a youtube channel is verified #444 ]( https://github.com/omarroth/invidious/issues/444 )

**Comment by omarroth** [comment]
Thanks. Closing in favor of #483.
