### ISSUE TITLE
OAC reporting bug on some public instances, but not others

### ISSUE THREAD

**Issue by kubo6472** [omarroth/invidious#1094]
Same Channel:
Official instance, **logged in** (_working_): https://invidio.us/channel/UCPL1bYqxpxwkwqC7t1MAV8w
GGC-Proj., **logged in** (_not working_): https://invidious.ggc-project.de/channel/UCPL1bYqxpxwkwqC7t1MAV8w
13-ad, **not logged in** (_not working_): https://invidious.13ad.de/channel/UCPL1bYqxpxwkwqC7t1MAV8w
yewtube, **not logged in** (_working_): https://yewtu.be/channel/UCPL1bYqxpxwkwqC7t1MAV8w
Why is that on my sample size of four, two, one logged in, and one not logged in worked, and the other two, also not logged in on one, and logged in on the other didn't?

**Comment by omarroth** [comment]
They all appear to be working for me. What error did you encounter?

**Comment by kubo6472** [comment]
It said just that I found a bug in invidious and I should report it. So you are saying, that it's apparently client-side problem.



Von meinem Samsung Galaxy Smartphone gesendet.



-------- Ursprüngliche Nachricht --------
Von: Omar Roth <notifications@github.com>
Datum: 31.03.20 20:39 (GMT+01:00)
An: omarroth/invidious <invidious@noreply.github.com>
Cc: Jakub Doboš <kubo6472@gmail.com>, Author <author@noreply.github.com>
Betreff: Re: [omarroth/invidious] OAC reporting bug on some public instances, but not others (#1094)


They all appear to be working for me. What error did you encounter?

**Comment by omarroth** [comment]
> So you are saying, that it's apparently client-side problem.

Not necessarily. Are you still encountering this issue?

**Comment by kubo6472** [comment]
Right now, this exact channel is working, so thx 😃 I would re-open this if i would encounter any other channels with weird behaviours instance to instance.
Have a nice day.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
