### ISSUE TITLE
[suggestion] Make "&quality=dash" affect embeded videos

### ISSUE THREAD

**Issue by xykrr** [omarroth/invidious#1097]
Hello, this request pertains to this feature: https://github.com/omarroth/invidious/issues/34#issuecomment-457060326
It would be nice to make it so embeded video urls can be affected as well.
So, for example: https://invidio.us/embed/1Ph_ORewpE0&quality=dash would use dash in a similar way to how https://invidio.us/watch?v=1Ph_ORewpE0&quality=dash does.

**Comment by omarroth** [comment]
Should be https://invidio.us/embed/1Ph_ORewpE0?quality=dash. See #588.

**Comment by xykrr** [comment]
Ah, okay. Thanks.
