### ISSUE TITLE
Legacy annotation support

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#110]
Before 2017, YouTube allowed creating annotations on top of videos. Some older videos still utilize these.

Example: https://invidio.us/watch?v=8VaFE6RU4bI

**Comment by Discookie** [comment]
Does `https://www.youtube.com/annotations_invideo?video_id=` do this?
Seems to work for the [example](https://www.youtube.com/annotations_invideo?video_id=8VaFE6RU4bI).

**Comment by omarroth** [comment]
The main issue is with displaying them. For VideoJS, there does not seem to be a plugin that is capable of displaying annotations the same way as YouTube.

**Comment by Zero3K** [comment]
I found two plugins that might work:

https://github.com/contently/videojs-annotation-comments
https://github.com/brightcove/videojs-overlay

**Comment by omarroth** [comment]
Ooh, I like how [videojs-annotation-comments](https://github.com/contently/videojs-annotation-comments). I'd like to hear thoughts on how YouTube's annotations could be improved.

**Comment by elypter** [comment]
my first thought when looking at this was that it could be used to mark sponsoring or ads that are included in the video and potentially automatically skip them.

**Comment by elypter** [comment]
thanks for doing this. it's really a shame that they are removing millions of man hours just so they can make the expierience worse.

**Comment by glmdgrielson** [comment]
If need be, I can get you a few comparison images/videos so that it's easier to recreate.

**Comment by omarroth** [comment]
I've actually done some work making recordings with annotations already, namely [this](https://www.youtube.com/watch?v=XwxBJEzgqWU) video, which seems pretty comprehensive. If there's any videos that use some features that aren't included or you think would help, please do record them!

**Comment by glmdgrielson** [comment]
Ah. I was going to say that one of the channels I asked for is currently doing reuploads and I have a couple of screenshots that may be usable as references for how they should look. Do we have a recording of that one that won't break on the 15th?

**Comment by omarroth** [comment]
YouTube deleted all annotations around 15:00 UTC as expected. An estimated 1.4 billion videos have been archived, and I'm working through everything right now to make it suitable for Invidious and other projects to use.

There's a list of videos available [here](https://archive.org/download/archived_annotations_video_ids.csv/archived_video_ids.csv). If anyone has backups that aren't in the list I would love to have them!

**Comment by elypter** [comment]
in case you are not already in contact with them there were 2 other people archiving metadata https://www.reddit.com/r/Archiveteam/comments/afjkk4/hey_archiveteam_got_those_youtube_annotation_xml/edziryc/

**Comment by elypter** [comment]
btw, since this project is now completed is there a way to download the data for the sake of a backup?

**Comment by omarroth** [comment]
Expect to see an announcement in the next couple days with links to compressed data dumps on the Internet Archive, which I expect will be what you want to use for a backup. There should be a torrent link as well when it is available.

**Comment by dimqua** [comment]
> An estimated 1.4 billion videos have been archived

Do you know how many YouTube videos have annotations?

**Comment by omarroth** [comment]
Added with #303 :tada:.
