### ISSUE TITLE
[Feature Request] Add video by url, to support unlisted videos

### ISSUE THREAD

**Issue by cstamas** [omarroth/invidious#1101]
Currently, creating playlists is possible only by "Search". This makes impossible for example to add unlisted YT videos to Insidious playlists.

So, an "add by URL" functionality would be welcome.

**Comment by omarroth** [comment]
Also see #826.

**Comment by omarroth** [comment]
You can now add videos to a playlist from the watch page with 3f97bebd6956ee1b111a2c23057a4facd6cbef0a, which should cover your use case.

**Comment by alfredoivan** [comment]
> You can now add videos to a playlist from the watch page with [3f97beb](https://github.com/omarroth/invidious/commit/3f97bebd6956ee1b111a2c23057a4facd6cbef0a), which should also cover your use case.

This solution isn't working for me. I select a playlist, click on "add to playlist" and doesn't do anything.

os: ubuntu 14.04
browser: firefox: 66.0.3 (64-bit)

**Comment by alfredoivan** [comment]
> > You can now add videos to a playlist from the watch page with [3f97beb](https://github.com/omarroth/invidious/commit/3f97bebd6956ee1b111a2c23057a4facd6cbef0a), which should also cover your use case.
> 
> This solution isn't working for me. I select a playlist, click on "add to playlist" and doesn't do anything.
> 
> os: ubuntu 14.04
> browser: firefox: 66.0.3 (64-bit)

it started working in invidio.us instance . Nevermind. I think snopyta is still behind i guess.
