### ISSUE TITLE
High amount of HTTP 500's

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#111]
As the title says, every third or so page I open throws back a HTTP 500.
I've seen all sorts of pages erroring out, from subscription feeds to channel pages to videos to RSS feeds.
They seem to happen randomly, and usually fix themselves after a refresh or two.

**Comment by omarroth** [comment]
Sorry about that! Currently the database is being migrated for #109. Unfortunately there appears to be some connection issues, which should be fixed within the hour.

**Comment by Discookie** [comment]
Seems to be fixed now, but looks like the migration broke CAPTCHAs...

![image](https://user-images.githubusercontent.com/16914176/44175361-3a8c5e00-a0e6-11e8-80dd-9942c6f408a3.png)

**Comment by Zero3K** [comment]
I also see the issue with the login page that is being shown.

**Comment by Zero3K** [comment]
Its been fixed now.

**Comment by omarroth** [comment]
Appears to be fixed. I'm not encountering any other 500 errors and everything else appears to be working normally.  I'm going to tentatively call the migration complete, and close this and #109 unless anyone encounters any other problems. Thank you everyone so much for your patience!
