### ISSUE TITLE
This channnel does not exist & RSS: 601 Invalid XML

### ISSUE THREAD

**Issue by gloschtla** [omarroth/invidious#1113]
What happened to invidio.us ?

Channel pages are often not loaded: 
_This channnel does not exist_

Playlist RSS Feed is broken:
_Unable to load feed preview: 601 Invalid XML_

**Comment by omarroth** [comment]
Mind providing an example?

**Comment by gloschtla** [comment]
This seemed to be a temporary problem, while the instance had been being blocked. 
Next time I can make a screenshot in order to report it to you.

> 
> Mind providing an example?
