### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hhuseyn** [omarroth/invidious#1119]
Hi i run docker-compose  build show error.How can i fix this error?

 execution of command failed with code: 1: `cc "${@}" -o '/invidious/invidious' -lxml2 -llzma -rdynamic -static  /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a -lz -lyaml /usr/lib/libxml2.a /usr/lib/libsqlite3.a -lz -lz /invidious/lib/lsquic/src/lsquic/ext/libssl.a `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a /invidious/lib/lsquic/src/lsquic/ext/libcrypto.a `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` /usr/lib/libpcre.a /usr/lib/libm.a /usr/lib/libgc.a /usr/lib/libpthread.a /usr/lib/crystal/core/ext/libcrystal.a /usr/lib/libevent.a /usr/lib/librt.a -L/usr/lib -L/usr/local/lib`

**Comment by omarroth** [comment]
Do you see any other information when encountering this error?

**Comment by hhuseyn** [comment]
All error  this is:

/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lyaml (this usually means you need to install the development package for libyaml)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/invidious/invidious' -lxml2 -llzma -rdynamic -static  /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a -lz -lyaml /usr/lib/libxml2.a /usr/lib/libsqlite3.a -lz -lz /invidious/lib/lsquic/src/lsquic/ext/libssl.a `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a /invidious/lib/lsquic/src/lsquic/ext/libcrypto.a `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` /usr/lib/libpcre.a /usr/lib/libm.a /usr/lib/libgc.a /usr/lib/libpthread.a /usr/lib/crystal/core/ext/libcrystal.a /usr/lib/libevent.a /usr/lib/librt.a -L/usr/lib -L/usr/local/lib`
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"' returned a non-zero code: 1

**Comment by psvenk** [comment]
I encountered the same issue. This patch should solve it (save the patch as a file, then run `git apply filename.patch`):
```
diff --git a/docker/Dockerfile b/docker/Dockerfile
index 11ab6ed..a8eab55 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,7 +1,7 @@
 FROM alpine:edge AS builder
 RUN apk add --no-cache crystal shards libc-dev \
     yaml-dev libxml2-dev sqlite-dev zlib-dev openssl-dev \
-    sqlite-static zlib-static openssl-libs-static
+    sqlite-static zlib-static openssl-libs-static make
 WORKDIR /invidious
 COPY ./shard.yml ./shard.yml
 RUN shards update && shards install
@@ -9,8 +9,12 @@ RUN apk add --no-cache curl && \
     curl -Lo /etc/apk/keys/omarroth.rsa.pub https://github.com/omarroth/boringssl-alpine/releases/download/1.1.0-r0/omarroth.rsa.pub && \
     curl -Lo boringssl-dev.apk https://github.com/omarroth/boringssl-alpine/releases/download/1.1.0-r0/boringssl-dev-1.1.0-r0.apk && \
     curl -Lo lsquic.apk https://github.com/omarroth/lsquic-alpine/releases/download/2.6.3-r0/lsquic-2.6.3-r0.apk && \
+    curl -Lo yaml.tar.gz http://pyyaml.org/download/libyaml/yaml-0.2.3.tar.gz && \
     tar -xf boringssl-dev.apk && \
-    tar -xf lsquic.apk
+    tar -xf lsquic.apk && \
+    tar -xf yaml.tar.gz && \
+    cd yaml-0.2.3 && \
+    ./configure && make && make install && cd ..
 RUN mv ./usr/lib/libcrypto.a ./lib/lsquic/src/lsquic/ext/libcrypto.a && \
     mv ./usr/lib/libssl.a ./lib/lsquic/src/lsquic/ext/libssl.a && \
     mv ./usr/lib/liblsquic.a ./lib/lsquic/src/lsquic/ext/liblsquic.a
```

**Comment by hhuseyn** [comment]
> [<img alt="@psvenk" width="20" height="20" src="https://avatars1.githubusercontent.com/u/45520974?s=60&amp;v=4">](/psvenk) [psvenk](/psvenk) linked a pull request that will close this issue [ 2 days ago ](#ref-pullrequest-602302668)
