### ISSUE TITLE
Suggestion regarding the donation information

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#112]
Maybe you could put it on the site in order to get more donations, etc.

**Comment by omarroth** [comment]
I'm wary of placing it somewhere that would get in the way of a user's experience. Maybe in the footer?

**Comment by omarroth** [comment]
I think I'll consider this closed with 7c63c759f47d3d29f3c25ecdb2b8cbd35f56c350. I don't want to put it somewhere that people feel an obligation to donate. I'm happy to provide the service for free and I don't want to see that relationship turn into something like a transaction.
