### ISSUE TITLE
Unexpected Error on login

### ISSUE THREAD

**Issue by bennypr0fane** [omarroth/invidious#1147]
I get this error message when trying to login with my Google account:
![Screenshot_20200429_134238](https://user-images.githubusercontent.com/5002396/80592437-bd229180-8a1f-11ea-929e-53605faac9ad.png)
Login is unsuccessful.

**Comment by unixfox** [comment]
Probably a duplicate of #755

**Comment by bennypr0fane** [comment]
No, it's actually a duplicate of #754

**Comment by unixfox** [comment]
OK. Can you then close this issue?
