### ISSUE TITLE
Anti Captcha stopped working

### ISSUE THREAD

**Issue by mrpaul92** [omarroth/invidious#1148]
My instances was working properly with anti captcha but today i see 
`{
error: "Could not extract video info. Instance is likely blocked."
}`

and also i see no request going to anti captcha website for solving captchas, any one getting same issue ?

**Comment by mrpaul92** [comment]
when force_resolve ipv6 it seems to be getting blocked

**Comment by unixfox** [comment]
It appears that Google sometimes doesn't present a captcha at all on IPv6.
