### ISSUE TITLE
Remove youtube tracking from links in descriptions

### ISSUE THREAD

**Issue by jsawesome1** [omarroth/invidious#115]
Currently, clicking a link in the description of a video redirects you to a hooktube search of the "real" URL.

**Comment by Discookie** [comment]
You can click the icon next to the link to go to the website without a redirector, or to stay on invidious when opening a new video.

**Comment by omarroth** [comment]
+1. Should only `/redirect` URLs be swapped?

**Comment by omarroth** [comment]
That's fair enough, and with #121 it'll always be possible for a user to view the YouTube version if they choose to, so this'll be added soon.

**Comment by Zero3K** [comment]
How about having removing the link icon and having the linked URL point to the actual URL that then opens in a new tab when clicked on?

**Comment by omarroth** [comment]
Added with 0d8f036 :tada:
