### ISSUE TITLE
i can download videos on https://yt.maisputain.ovh/ but not invidio.us on mobile

### ISSUE THREAD

**Issue by lairichard** [omarroth/invidious#1155]
Not sure if this is a feature or a bug

**Comment by Perflyst** [comment]
Downloads on invidio.us are disabled, so it is as expected. Neither a bug nor a feature

**Comment by lairichard** [comment]
> Downloads on invidio.us are disabled, so it is as expected. Neither a bug nor a feature

I’ve seen the option available (invidio.us) to download on desktop before, not sure why it isn’t on mobile too

**Comment by Perflyst** [comment]
It was enabled in the past, but it is not anymore

**Comment by lairichard** [comment]
> It was enabled in the past, but it is not anymore

thx for clarifying
