### ISSUE TITLE
Unable to open Youtube video

### ISSUE THREAD

**Issue by MPeti1** [omarroth/invidious#1158]
invidio.us is unable to open the video below.

First I tried to download the stream with youtube-dl, but even after updating it, it still wasn't able to do that. Wanted to see if invidio.us can play it, but it can't.

PS: Can I link this issue to one in the youtube-dl repository? I know issue numbers can be referenced inside a repository, but don't know if it's possible cross-repository

https://www.invidio.us/watch?v=aevHiJlku-k

**Comment by MPeti1** [comment]
The video now opens and plays correctly. If you feel so you can close it, but I think it may still worth investigation why it didn't work yesterday

**Comment by derram** [comment]
From what I've seen some new videos will fail because the specific quality stream hasn't finished processing on youtube's end.

You can add &quailty=dash to force invidio to use whatever quality it can to play the video.

**Comment by MPeti1** [comment]
Thank you, it seems that was the problem. First invidio.us got working on 720p, and now youtube-dl works too with 1080p. Not sure why the latter hasn't tried to fall back to a lower quality, though.. but that's an other repo so nevermind :)
