### ISSUE TITLE
Is there an any way to subscribe to channels without an account

### ISSUE THREAD

**Issue by mutludev** [omarroth/invidious#1161]

**Comment by 13r0ck** [comment]
No. You do not need to login with a Google account, but you will at least need an Invidious account.

**Comment by Gert-dev** [comment]
Actually, yes. You can use the [RSS feeds](https://en.wikipedia.org/wiki/RSS) provided by Invidious. Go to the channel page you want to subscribe to (e.g. `https://invidio.us/channel/SomeChannelId`) and click on the "radarlike" icon to the right of the channel name.

You will need an RSS reader to handle these feeds. You can find a list of some popular ones [here](https://en.wikipedia.org/wiki/Comparison_of_feed_aggregators).

YouTube itself also still provides hidden RSS feeds, last time I checked, which you can find with some searching, if you don't mind Google receiving those requests.

**Comment by mutludev** [comment]
@Gert-dev thanks i didn't saw that.
