### ISSUE TITLE
Video not loading

### ISSUE THREAD

**Issue by neonJAhr** [omarroth/invidious#1163]
Link in question: https://invidio.us/watch?v=goeOUTRy2es

Cheers, I tried opening this video by either job looking for it through the search bar, then trying to access it via their (SXTN's) channel. 
I am using Firefox 75.0 (64-bit), updated to 76.0 yet there was no difference. 
If you need any other information, let me know

**Comment by haizrul** [comment]
Works for me using Opera 68.0.3618.63

**Comment by flori4nk** [comment]
Works for me - Firefox 76.0

**Comment by neonJAhr** [comment]
Nevermind, it works with VPN, I just got unlucky when trying it from two different places. 
Issue closed
