### ISSUE TITLE
Search requests sometimes returns no result

### ISSUE THREAD

**Issue by sebma** [omarroth/invidious#1169]
Hi,
It seems that today some search requests sometimes return no result : https://invidio.us/search?q=joel+osteen but other times it does return results.

Maybe it's depending on which node your load balancer is redirecting us to.

Maybe, one or more of your nodes is having a pb., can you check this ?

**Comment by Perflyst** [comment]
This is due to #1183, try to use [another instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances) until this issue got fixed.

**Comment by sebma** [comment]
https://instances.invidio.us/
