### ISSUE TITLE
Subscriptions don't update

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#117]
Subscriptions feed:
![image](https://user-images.githubusercontent.com/16914176/44231286-e349c480-a19d-11e8-81c0-97c918bc4586.png)

Channel 1 that has newer videos:
![image](https://user-images.githubusercontent.com/16914176/44231322-083e3780-a19e-11e8-8d74-0b6e55693b9b.png)

Channel 2 that has newer videos:
![image](https://user-images.githubusercontent.com/16914176/44231341-1b510780-a19e-11e8-8acc-ad6eb00e00fa.png)

The RSS feed is lagging behind too.

**Comment by omarroth** [comment]
Looks like a left over from #111. Everything should start be updating now.

**Comment by Discookie** [comment]
Seems to be all updated for now.
