### ISSUE TITLE
1080p and 60 fps?

### ISSUE THREAD

**Issue by notthefox** [omarroth/invidious#1170]
I really enjoy using invidious, but there is going to be an update that add 1080p or even 1080p60fps?

**Comment by Gert-dev** [comment]
Invidious actually already supports 1080p by activating the `dash` quality option in the settings. See also #34 for more information about supporting other formats.

**Comment by cloudrac3r** [comment]
You can also try my similar site CloudTube: https://cadence.moe/cloudtube/subscriptions

**Comment by unixfox** [comment]
With dash enabled if the original video has 1080p 60FPS available then you will have the same quality on Invidious.

**Comment by Perflyst** [comment]
As Gert-dev and unixfox said, with dash enabled invidious has 1080p support.
