### ISSUE TITLE
france inter

### ISSUE THREAD

**Issue by fretere** [omarroth/invidious#1171]
Hi, when i click on france inter's account, it shows a bug: https://invidious.fdn.fr/channel/UCJldRgT_D7Am-ErRHQZ90uw

Thanks.

**Comment by unixfox** [comment]
The invidious instance that you are using is blocked by Google and is thus unable to retrieve the info of the specific channel.
Try instead on the official instance: https://invidio.us/channel/UCJldRgT_D7Am-ErRHQZ90uw

**Comment by fretere** [comment]
Thanks, it works indeed!
