### ISSUE TITLE
Crowdsource translations

### ISSUE THREAD

**Issue by exilexi** [omarroth/invidious#1181]
I'm not a coder, but I'd love to help with translations. I couldn't find any documentation on where to contribute to translations, though - do you have a platform? If not, would you like to put the project on a platform like Crowdin?

**Comment by recette-lemon** [comment]
The weblate is here. Someone really should put it on the wiki page tho.
https://hosted.weblate.org/projects/invidious/translations/

**Comment by comradekingu** [comment]
@recette-lemon I think https://github.com/omarroth/invidious/pull/1197 suffices.
