### ISSUE TITLE
Pages in invidious.snopyta.org are broken

### ISSUE THREAD

**Issue by stevenfang1997** [omarroth/invidious#1189]
Currently, comments, video statistics and profile pictures of chanels can't be loaded on this instance. 

![croppedImage_1590257098229](https://user-images.githubusercontent.com/37974764/82737336-c7605300-9d73-11ea-80c9-cc97f12a94a5.png)

**Comment by Perflyst** [comment]
This is due to https://github.com/omarroth/invidious/issues/1183

May 23, 2020 20:05:46 stevenfang1997 <notifications@github.com>:
