### ISSUE TITLE
Instance blocked/Page not loading

### ISSUE THREAD

**Issue by WandeingLagomorph793** [omarroth/invidious#1193]
https://invidious.snopyta.org/watch?v=3jvCQvIbd20

For a test video, if I try it in Snopyta i get the "Format not supported" error, switching qualities to dash did not fix this.
https://invidio.us/watch?v=3jvCQvIbd20

That same video in the .us domain doesn't even load up, citing the instance is blocked, if I go to the channel then it says the channel does not exist, this all persists even after several reloads. I've tried with 5 different channels and it's the same result each time, search results bring up nothing.

Most things work in Snopyta, but some videos still give format errors such as the one linked above, there's also comments not loading which another issue touched upon. But .us seems broken at the moment when I use it.

**Comment by Perflyst** [comment]
This is due to https://github.com/omarroth/invidious/issues/1183

**Comment by NoVa-UX** [comment]
Honestly It gets really fucking annoying.  I mean haven't you already done this before?  Yeah its saying that but still...that should have been fixed...A LONG TIME ago.  Why does it keep coming back?

**Comment by Perflyst** [comment]
Feel free to use https://youtube.com

**Comment by OrionRandD** [comment]
I am getting -> 
Invidious
Could not extract video info. Instance is likely blocked. 
Is it related to this topic?
If so, how can I fix it?
I am using tampermonkey plugin/addon in firefox

**Comment by Perflyst** [comment]
You cannot fix it, youtube blocks requests from invidious. The anti captcha work around currently does not work. This issue is tracked in #1183
