### ISSUE TITLE
Can't Play Videos, Can't Search

### ISSUE THREAD

**Issue by Pomellion** [omarroth/invidious#1196]
Hi, first of all I want to thank you so much With this site, i am able to watch youtube videos from my ipad.

But today, when i entered the site (invidio.us) and tried to search all I got was a blank page. And then i tried to open some videos from homepage and it said, could not get the info. I tried reloading, rebooting my ipad and several things. Is it about my device or general thing? I am so sorry if I disturbed.

**Comment by aaronhooper** [comment]
Same issue on Debian + Firefox.
All the videos I clicked on the front page show 'instance is likely blocked' and search returns nothing.

**Comment by xypd** [comment]
Seems this might be to #1183

**Comment by Pomellion** [comment]
> Seems this might be to #1183

Oh :( will i be able to watch videos later then? Or is it gone forever?

**Comment by xypd** [comment]
You could find other instances till they are all block. I've gone through maybe 5/6 so far. :(

**Comment by Perflyst** [comment]
This is due to #1183 as xypd said.
