### ISSUE TITLE
search, rss feed, and display channel broken ?

### ISSUE THREAD

**Issue by captnblood** [omarroth/invidious#1198]
since yesterday i cannot seem to be able to perform a few tasks on invidio.us:
- search for anything (ex: "solar") gets zero results.
- click on a subscribed channel (manage subscriptions -> click on a channel) gets "channel doesn't exist"
- all my rss feed links gets http error 500

i tried with brave and safari browsers, logged-in or not, results are the same.
it was all working fine before.
am i the only one getting this ?

**Comment by exilexi** [comment]
Most of us have this, see #1183

**Comment by captnblood** [comment]
@exilexi 
thanks for telling !
