### ISSUE TITLE
Issue with viewing the site

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#12]
When I try viewing it via https://www.invidio.us, I am getting a "server not found" error. I didn't get that error earlier today/yesterday.

**Comment by omarroth** [comment]
Minor issue with DNS, should be fixed now.

**Comment by Zero3K** [comment]
I can confirmed that it has been fixed.

**Comment by omarroth** [comment]
Unfortunately also a problem with high load, same as #13.

**Comment by Zero3K** [comment]
Is the high load fixable or not?

**Comment by omarroth** [comment]
It'll probably be necessary to upgrade the server that the site is running on. For now though it should automatically restart if there's an issue accessing the site.

It would also be good to setup monitoring/status to better address issues with downtime.

**Comment by Zero3K** [comment]
And now its down again.
