### ISSUE TITLE
Remove YouTube link duplicate

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#120]
`View more comments on YouTube` link is a duplicate of `Watch video on YouTube` link.
I think one of them can be safely removed.

**Comment by omarroth** [comment]
The `View comments on YouTube` link is mostly a placeholder for a link that will properly link directly to YouTube comments, but since `/watch?v=ID#comments` doesn't appear to do anything, I think I'll probably replace it with a `View x comments` heading instead.

**Comment by omarroth** [comment]
Fixed with 71aa4d0.
