### ISSUE TITLE
I am Uploading Data Its Showing 413 Error!

### ISSUE THREAD

**Issue by arpittutor** [omarroth/invidious#1202]
When I am uploading my data regarding **[machine learning tutorial](https://intellipaat.com/blog/tutorial/machine-learning-tutorial/)** its, again and again, showing 413 error. I am sharing very useful and basic information regarding machine learning tutorials from where one can easily learn the basics of ML and its use with Python also.

**Comment by Perflyst** [comment]
Where do you upload that data? I dont understand what this has to do with invidious.
