### ISSUE TITLE
Docker Image failing to build

### ISSUE THREAD

**Issue by omar-elnaggar** [omarroth/invidious#1204]
docker-compose build is failing please see your last build attempt to see the error @omarroth 

https://travis-ci.org/github/omarroth/invidious/jobs/692256167

I am getting the same error on my server.

**Comment by tleydxdy** [comment]
most likely because of this https://github.com/omarroth/lsquic.cr/commit/392a57aa8fa195b438e3bcbf0aeef22f83feb602

**Comment by omarroth** [comment]
Should be fixed with 8305af8f1036e9cb2ffc8aab5eb738d73c9f5654.

**Comment by omar-elnaggar** [comment]
Perfect thank you!
