### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by hhuseyn** [omarroth/invidious#1207]
Hi. i install api version but dont install.show this error.How can fix this error?Please help me.
------i chance docker file with 

https://github.com/psvenk/invidious/commit/c74895cb0360f5b011b120821d423ed92897adf5

 ---> Running in ad350a930552
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_handshake.c.o): in function `lsquic_enc_session_get_server_cert_chain':
lsquic_handshake.c:(.text+0x5e4): undefined reference to `sk_new_null'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x601): undefined reference to `sk_push'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x634): undefined reference to `sk_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_handshake.c.o): in function `gen_rej1_data':
lsquic_handshake.c:(.text+0x106e): undefined reference to `SSL_CTX_get0_chain_certs'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x107a): undefined reference to `sk_num'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x111c): undefined reference to `OPENSSL_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x113f): undefined reference to `sk_value'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_handshake.c.o): in function `lsquic_enc_session_destroy':
lsquic_handshake.c:(.text+0x191c): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x1935): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x1951): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x1970): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_handshake.c.o): in function `get_sni_SSL_CTX':
lsquic_handshake.c:(.text+0x242d): undefined reference to `OPENSSL_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x248b): undefined reference to `BN_num_bytes'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x2696): undefined reference to `OPENSSL_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_handshake.c.o): in function `determine_diversification_key':
lsquic_handshake.c:(.text+0x2904): undefined reference to `EVP_aead_aes_128_gcm'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x2918): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x2934): undefined reference to `EVP_AEAD_CTX_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_handshake.c.o): in function `setup_aead_ctx':
lsquic_handshake.c:(.text+0x427e): undefined reference to `EVP_aead_aes_128_gcm'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x4292): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x42ac): undefined reference to `EVP_AEAD_CTX_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_handshake.c.o): in function `lsquic_enc_session_handle_chlo_reply':
lsquic_handshake.c:(.text+0x4c9d): undefined reference to `sk_new_null'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x4cad): undefined reference to `sk_push'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x4ccd): undefined reference to `sk_push'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x4d0f): undefined reference to `sk_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x4e90): undefined reference to `sk_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_handshake.c.o): in function `lsquic_enc_session_handle_chlo':
lsquic_handshake.c:(.text+0x655f): undefined reference to `EVP_aead_aes_128_gcm'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x6581): undefined reference to `EVP_AEAD_CTX_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x729a): undefined reference to `EVP_aead_aes_128_gcm'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_handshake.c:(.text+0x72bc): undefined reference to `EVP_AEAD_CTX_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_tokgen.c.o): in function `lsquic_tg_new':
lsquic_tokgen.c:(.text+0x190): undefined reference to `HKDF_extract'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_tokgen.c.o): in function `lsquic_tg_generate_sreset':
lsquic_tokgen.c:(.text+0x9aa): undefined reference to `HKDF_expand'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_crypto.c.o): in function `aes_aead_enc':
lsquic_crypto.c:(.text+0xbcd): undefined reference to `EVP_AEAD_CTX_seal'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_crypto.c.o): in function `aes_aead_dec':
lsquic_crypto.c:(.text+0xd0d): undefined reference to `EVP_AEAD_CTX_open'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_crypto.c.o): in function `PEM_to_key':
lsquic_crypto.c:(.text+0xf18): undefined reference to `EVP_PKEY_assign_RSA'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_crypto.c.o): in function `gen_prof':
lsquic_crypto.c:(.text+0x1081): undefined reference to `EVP_MD_CTX_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x10ba): undefined reference to `EVP_PKEY_CTX_set_rsa_padding'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x10cb): undefined reference to `EVP_PKEY_CTX_set_rsa_pss_saltlen'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x10df): undefined reference to `EVP_DigestSignUpdate'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x10fb): undefined reference to `EVP_DigestSignUpdate'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x1115): undefined reference to `EVP_DigestSignUpdate'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x112e): undefined reference to `EVP_DigestSignUpdate'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x1179): undefined reference to `EVP_MD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_crypto.c.o): in function `verify_prof0':
lsquic_crypto.c:(.text+0x1234): undefined reference to `EVP_MD_CTX_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x1299): undefined reference to `EVP_PKEY_CTX_set_rsa_padding'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x12aa): undefined reference to `EVP_PKEY_CTX_set_rsa_pss_saltlen'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x12be): undefined reference to `EVP_DigestVerifyUpdate'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x12da): undefined reference to `EVP_DigestVerifyUpdate'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x12f0): undefined reference to `EVP_DigestVerifyUpdate'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x1305): undefined reference to `EVP_DigestVerifyUpdate'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_crypto.c:(.text+0x1322): undefined reference to `EVP_MD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_crypto.c.o): in function `crypto_init':
lsquic_crypto.c:(.text+0x13a5): undefined reference to `CRYPTO_library_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `gen_hp_mask_aes':
lsquic_enc_sess_ietf.c:(.text+0x134): undefined reference to `EVP_CIPHER_CTX_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x189): undefined reference to `EVP_CIPHER_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `init_crypto_ctx':
lsquic_enc_sess_ietf.c:(.text+0x248): undefined reference to `EVP_AEAD_key_length'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x256): undefined reference to `EVP_AEAD_nonce_length'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x2f0): undefined reference to `EVP_AEAD_CTX_init_with_direction'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `get_peer_transport_params':
lsquic_enc_sess_ietf.c:(.text+0x35c): undefined reference to `SSL_get_peer_quic_transport_params'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `gen_hp_mask_chacha20':
lsquic_enc_sess_ietf.c:(.text+0x998): undefined reference to `CRYPTO_chacha_20'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `readf_cb':
lsquic_enc_sess_ietf.c:(.text+0xd4d): undefined reference to `SSL_provide_quic_data'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_new_session_cb':
lsquic_enc_sess_ietf.c:(.text+0xede): undefined reference to `SSL_get_peer_quic_transport_params'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0xf3f): undefined reference to `SSL_SESSION_to_bytes'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0xf66): undefined reference to `OPENSSL_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x10d8): undefined reference to `OPENSSL_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x1236): undefined reference to `OPENSSL_free'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_esf_global_init':
lsquic_enc_sess_ietf.c:(.text+0x1716): undefined reference to `SSL_get_ex_new_index'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `chsk_ietf_on_new_stream':
lsquic_enc_sess_ietf.c:(.text+0x1981): undefined reference to `SSL_CTX_set_min_proto_version'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x198e): undefined reference to `SSL_CTX_set_max_proto_version'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x19a3): undefined reference to `SSL_CTX_set_session_cache_mode'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x1a00): undefined reference to `SSL_CTX_set_custom_verify'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x1a14): undefined reference to `SSL_CTX_set_early_data_enabled'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x1a52): undefined reference to `SSL_set_quic_method'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x1b83): undefined reference to `SSL_set_quic_transport_params'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x1cc9): undefined reference to `SSL_set_tlsext_host_name'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x1e98): undefined reference to `SSL_SESSION_from_bytes'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_esfi_destroy':
lsquic_enc_sess_ietf.c:(.text+0x222f): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x2248): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `setup_handshake_keys':
lsquic_enc_sess_ietf.c:(.text+0x2302): undefined reference to `EVP_aead_aes_128_gcm'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x2363): undefined reference to `HKDF_extract'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x2585): undefined reference to `EVP_AEAD_key_length'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x2701): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x271e): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_esf_encrypt_packet':
lsquic_enc_sess_ietf.c:(.text+0x2f3b): undefined reference to `EVP_AEAD_CTX_seal'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `drop_SSL':
lsquic_enc_sess_ietf.c:(.text+0x342e): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x3446): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_esfi_shake_stream':
lsquic_enc_sess_ietf.c:(.text+0x35f7): undefined reference to `SSL_in_early_data'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x3799): undefined reference to `SSL_process_quic_post_handshake'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_esf_decrypt_packet':
lsquic_enc_sess_ietf.c:(.text+0x4559): undefined reference to `EVP_AEAD_CTX_open'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x4770): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x4f5b): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `cry_sm_set_encryption_secret':
lsquic_enc_sess_ietf.c:(.text+0x5250): undefined reference to `SSL_send_fatal_alert'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x526d): undefined reference to `EVP_aead_aes_128_gcm'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x5292): undefined reference to `EVP_AEAD_key_length'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x52a6): undefined reference to `EVP_AEAD_nonce_length'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x5427): undefined reference to `EVP_AEAD_key_length'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x54fd): undefined reference to `EVP_aead_chacha20_poly1305'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x5565): undefined reference to `EVP_aead_aes_256_gcm'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x5740): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x57c2): undefined reference to `EVP_AEAD_CTX_cleanup'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_esfi_init_server':
lsquic_enc_sess_ietf.c:(.text+0x58f2): undefined reference to `SSL_set_quic_method'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: lsquic_enc_sess_ietf.c:(.text+0x5958): undefined reference to `SSL_set_quic_transport_params'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_esf_get_server_cert_chain':
lsquic_enc_sess_ietf.c:(.text+0xcd3): undefined reference to `sk_deep_copy'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a(lsquic_hkdf.c.o): in function `lsquic_qhkdf_expand':
lsquic_hkdf.c:(.text+0x117): undefined reference to `HKDF_expand'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: O-penS-S-L-5858S-S-L-5858C-ontext5858C-lient.o: in function `add_modes':
/invidious/lib/lsquic/src/lsquic/patch.cr:144: undefined reference to `SSL_CTX_set_mode'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: O-penS-S-L-5858S-S-L-5858C-ontext5858S-erver.o: in function `add_modes':
/invidious/lib/lsquic/src/lsquic/patch.cr:144: undefined reference to `SSL_CTX_set_mode'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: O-penS-S-L-5858S-S-L-5858C-ontext5858S-erver.o: in function `set_tmp_ecdh_key':
/invidious/lib/lsquic/src/lsquic/patch.cr:133: undefined reference to `SSL_CTX_set_tmp_ecdh'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: O-penS-S-L-5858S-S-L-5858S-ocket5858C-lient.o: in function `initialize':
/invidious/lib/lsquic/src/lsquic/patch.cr:172: undefined reference to `SSL_set_tlsext_host_name'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/invidious/invidious' -lxml2 -llzma -rdynamic -static  /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a /usr/local/lib/libyaml.a /usr/lib/libxml2.a -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` /usr/lib/libpcre.a /usr/lib/libm.a /usr/lib/libgc.a /usr/lib/libpthread.a /usr/lib/crystal/core/ext/libcrystal.a /usr/lib/libevent.a /usr/lib/librt.a -L/usr/lib -L/usr/local/lib`
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"' returned a non-zero code: 1

**Comment by omarroth** [comment]
Closing in favor of #1204.
