### ISSUE TITLE
This might Blow your socks off

### ISSUE THREAD

**Issue by iAmNoVa-UXX** [omarroth/invidious#1215]
I've been browsing and comparing Invidious and YouTube to each other recently and I found some things about both.  One, it would be cool if we didn't have to go the search bar to look up certain channels that we typically watch.  For example I watch a YouTuber named Gladd.  I subbed to him thru Invidious.  It would be kind of nice to have it on the left hand side.  Just so I could go directly to his channel and not have to search it every single time.  Another thing I'm not sure if Keyboard shortcuts are a thing on Invidious or not.  I've really just been comparing UI's and what not.  But I think it would be cool (if its already in and I haven't seen it my bad).  Last but not least commenting.  I honestly think it would be really cool have a certain log in for Invidious and be able to "customize"  that account.  I know what you're thinking "this mans literally just said commenting why is he wanting to create a custom account?"  Glad u didn't ask but thought in your head.  To make it feel more like you is why.  Commenting as maybe an alt account or something to troll a huge friend or something like that would be kind of funny.  I totally get it if this cannot be done and its just my imagination going off.  Have a good rest of your day and please my friends...stay safe

**Comment by bugs181** [comment]
Could have did without the clickbait title. New title should be: List of feature requests

**Comment by bugs181** [comment]
Appreciate the down-vote. Let's be a little more constructive in your feedback.

>  It would be kind of nice to have it on the left hand side

I don't think you appreciate the amount of work that goes into rewriting user interface stuff. This would require either an invidious theme (if they exist), or the UI components themselves to be rewritten and restyled.

>  I've really just been comparing UI's

This is your first problem. The two systems are not made to look anything alike. Yes, the media is the same but these two systems behave much differently. Invidious is written as a replacement for privacy conscious users.

> it would be really cool have a certain log in for Invidious and be able to "customize" that account

Again, this would take an extraordinarily amount of work. The user accounts are on two completely different systems with completely different feature sets. 

Some day, Invidious may be able to give users the ability to incorporate more of YouTube's feature sets with the knowledge that you'll be trading privacy for features, but I doubt that day will come any time soon.

**Comment by iAmNoVa-UXX** [comment]
Mr Bugs

I do appreciate how much work and effort the devs put into their work.  Not saying I don't.  I was simply trying to say "It would be nice" not "Do this or else" I think you might have taken what I said out of context a little bit.  other than that I really have nothing else to say other than have a good rest of your day :)

**Comment by iAmNoVa-UXX** [comment]
> I don't think you appreciate the amount of work that goes into rewriting user interface stuff. This would require either an invidious theme (if they exist), or the UI components themselves to be rewritten and restyled.

I never once said up in the thread that I didn't appreciate what they do.  Think you might have wasted a little bit of time out of your day to quote me on a few things that really didn't matter.  Me...well...I don't do much anymore...and I'm not always on here either.  Other than that...maybe try to read things more carefully before you just drop in and be like "time to correct someone"  Have a good rest of your day/week/month/year :)

**Comment by elypter** [comment]
> For example I watch a YouTuber named Gladd. I subbed to him thru Invidious. It would be kind of nice to have it on the left hand side. Just so I could go directly to his channel and not have to search it every single time.

thats what the browser bookmarks are for. ctrl(+shift)+b on firefox, vivaldi and opera. and please calm down your inner karen. this has been a sane place up until now.
