### ISSUE TITLE
Build fails with last version of Crystal (Version 0.35.0)

### ISSUE THREAD

**Issue by DaarkMoon** [omarroth/invidious#1235]
Build fails when builded with the crystal version 0.35.0 (published on june 09th 2020). This version have some **breaking change** (see [changelog](https://github.com/crystal-lang/crystal/releases/tag/0.35.0)).

I use last version of crystal provided by https://dist.crystal-lang.org/apt for debian (as required in README).

Issue seems to only come from this breaking change (see Files section of [crystal 0.35.0 changelog](https://github.com/crystal-lang/crystal/releases/tag/0.35.0)).
>  **(breaking-change)** Move Flate, Gzip, Zip, Zlib to Compress.

This issue also affect the dependancy _kemal_ (but there is an [correction](https://github.com/kemalcr/kemal/commit/a8c0f09b858162bd13c96663febef5527b322a32))

[here](https://github.com/omarroth/invidious/files/4775017/crystal_0.35.0_suport.patch.txt) a patch that work on my system **it's only support crystal 0.35.0**. For support of 0.34.0 and 0.35.0 there is an interessing solution in [kemal source code](https://github.com/kemalcr/kemal/commit/a8c0f09b858162bd13c96663febef5527b322a32))

**Comment by Perflyst** [comment]
Feel free to submit a pull request

**Comment by Vertux** [comment]
I just run into the same issue:

```
~/invidious$ crystal build src/invidious.cr --release

Warning: Zlib is deprecated, use Compress::Zlib
Warning: Zip is deprecated, use Compress::Zip
Showing last frame. Use --error-trace for full trace.

In src/invidious/helpers/helpers.cr:900:5

 900 | Gzip::Writer.open(env.response) do |deflate|
       ^
Error: undefined constant Gzip::Writer

Did you mean 'Zip'?
```

```
~/invidious$ crystal -v
Crystal 0.35.0 [3c48f311f] (2020-06-09)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by omarroth** [comment]
Should be fixed with d30a972a909e66d963ee953349fe045a1d9a41ee.

**Comment by idanoo** [comment]
Great timing.. I was just attempting to install it.

Confirmed fixed - latest commit builds with no errors!

**Comment by m4teh** [comment]
Can't get it to build using Docker on master.

Using protodec (0.1.3)
Using lsquic (0.1.9 at 5261034)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6869k  100 6869k    0     0   963k      0  0:00:07  0:00:07 --:--:-- 1330k
Removing intermediate container c8ecb51de833
 ---> 4f4246d38a9a
Step 6/20 : COPY ./src/ ./src/
 ---> a00f10964231
Step 7/20 : COPY ./.git/ ./.git/
 ---> 9a5a0f0feccd
Step 8/20 : RUN crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     --link-flags "-lxml2 -llzma"
 ---> Running in 902a211f06fc
Showing last frame. Use --error-trace for full trace.

In src/invidious.cr:26:1

 26 | require "compress/zip"
      ^
Error: can't find file 'compress/zip'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     --link-flags "-lxml2 -llzma"' returned a non-zero code: 1
