### ISSUE TITLE
Captcha Image

### ISSUE THREAD

**Issue by charles1e62** [omarroth/invidious#1236]
Hi. I'm a beginner in crystal language and would like to know in with file the captcha image is generated.

**Comment by Perflyst** [comment]
Take a look at https://github.com/omarroth/invidious/blob/master/src/invidious/users.cr#L182

**Comment by charles1e62** [comment]
> Take a look at https://github.com/omarroth/invidious/blob/master/src/invidious/users.cr#L182

Thank you.
