### ISSUE TITLE
wrong external_port on invidio.us

### ISSUE THREAD

**Issue by Newbytee** [omarroth/invidious#1248]
## Description

I used Firefox' "Add Search Engine" feature to add invidio.us as a search engine in my browser, however when I attempt to search using it I'm taken to https://www.invidio.us:3000, which evidently is using the wrong port. 

## Reproduction

1. Add Invido.us as search engine in Firefox
2. Attempt to search using it and be greeted with an "Unable to connect"

**Comment by omarroth** [comment]
Thanks, should be fixed.

**Comment by Newbytee** [comment]
Works now, thank you!
