### ISSUE TITLE
/api/v1/channels/latest seems to be broken

### ISSUE THREAD

**Issue by PrestonN** [omarroth/invidious#1251]
Making a call to `/api/v1/channels/latest` returns an error on every channel sent to it.

`"Expected Hash for #[]?(key : String), not Array(JSON::Any)"`

I'm guessing this has something to do with the new Crystal version.  It was working fine until the update.

[Example URL](https://invidio.us/api/v1/channels/latest/UCXuqSBlHAE6Xw-yeJA0Tunw)

**Comment by omarroth** [comment]
Should be fixed as part of 056e7432bd976f375b3f79254f8fafbe21748706.

**Comment by PrestonN** [comment]
Yep! Seems to be fixed.

Thanks for all the hard work! :)
