### ISSUE TITLE
Playlists cannot be loaded anymore

### ISSUE THREAD

**Issue by gloschtla** [omarroth/invidious#1255]
the playlist overview page of a channel cannot load its content anymore. Also if you have the direct URL to one playlist, you see only the description text, but not the containing videos. And if you append the playlist ID to the URL of one video, then the playlist is no longer loaded above the list of similar videos.

**Comment by omarroth** [comment]
Closing in favor of #1260, should be fixed with 8c65b8c16fe06375b7b8c29514a065626a12fe04.
