### ISSUE TITLE
Add filters for searching

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#126]
It would be nice if there were search filters added that could let a user see videos uploaded during a certain time frame, sort them by date, etc.

**Comment by omarroth** [comment]
Absolutely! Invidious already supports them internally, they would just need to be exposed nicely. See #30 to see more on how they would probably be implemented. to provide some info here as well, it would probably look like `sort:relevance`, `date:today`, etc, similar to Reddit or DDG.

**Comment by omarroth** [comment]
Added with 2ba0063, you can see the supported options [here](https://github.com/omarroth/invidious/blob/master/src/invidious/search.cr#L31-L108). 

You can specify filters in your search query, for example:  
`sort:rating date:today query` will search for `query` from `today` sorted by `rating`. Currently `content_type` is **not** available, when it is supported in the API it will be added.

**Comment by Zero3K** [comment]
There's no date option when using sort: (using sort:date currently results in a 500 error). Also, I was hoping to see a box that is hidden by default and can be shown by clicking on a button or something that contains filtering options (like how Youtube does it).

**Comment by dimqua** [comment]
Yes, a more user-friendly advanced search would be nice to have.

**Comment by r-a-y** [comment]
Would it be possible to add the ability to filter videos by channel?

Let's say I'm on a channel page (`/channel/X`), the search box should be autopopulated with a `channel` filter such as `channel:X`.

Btw, great project!  Invidious loads way faster than the official YouTube site on Firefox.

**Comment by omarroth** [comment]
Absolutely! Unfortunately (from my testing at least), when searching a channel other search filters won't work, so I'd like to have some way of indicating that to the user.

**Comment by omarroth** [comment]
`type:TYPE` has been implemented, so users can now filter e.g. channels with `type:TYPE`, and per-channel search has been added with #165. I'd recommend opening new issues for additional functionality, user-friendly search is now tracked in #179.
