### ISSUE TITLE
Docker error?!

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#1264]
I try to build the docker image (*or in other words, i'm trying to deploy it on heroku*) and i'm getting this error 

```
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
The command '/bin/sh -c apk add --no-cache curl sqlite-static' returned a non-zero code: 2
 ▸    Error: docker build exited with Error: 2
```

**Comment by SuperSandro2000** [comment]
Not the fault of invidious. Your DNS/internet connectivity is faulty. Can be closed.

**Comment by EsmailELBoBDev2** [comment]
nah  i wanna more info. why it happens what in my settings wrong i can do to fix it — do not rush me like that

**Comment by Perflyst** [comment]
can you download `http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz` manually with wget or sth?

**Comment by SuperSandro2000** [comment]
> nah i wanna more info.

This is not a Docker Help Forum. I don't think we should discuss this types of issues on here.

**Comment by EsmailELBoBDev2** [comment]
@SuperSandro2000 man without being sad? you suck. you just refusing to help me because its not the right place? so what? i mean if you know answer but just not wanna say because its not right place then take this big fuck you from me.

@Perflyst stringy yes, im able to download it normal

**Comment by SuperSandro2000** [comment]
> you just refusing to help me because its not the right place?

Yes. For everything is a place and time and this is the place for invidious not docker alpine network connectivity is broken.

> you know answer

No, I do not magically know what is wrong with your network setup.

**Comment by EsmailELBoBDev2** [comment]
okay if that your excuse. lets go DM and try troubleshoot it together
