### ISSUE TITLE
[QUESTION] What server is serving my local instance?

### ISSUE THREAD

**Issue by hunkjazz** [omarroth/invidious#1266]
I am trying to figure out how to replace `localhost:3000` for a more friendly name.
After some searching, I learned about `/etc/hosts` and managed to set `my.vids:3000`. Although, this is still not as friendly.

After more searching, I realized that I cannot use `/etc/hosts/` to avoid typing port numbers and I should set a reverse proxy to achive that. Fortunately, you have a wiki explaning how to set a very basic reverse proxy.

Although, my local invidious instance doesn't seem to be running either on Apache or NGIINX:

- I tried stopping Apache service and dependent applications stopped working as soon as it happend, but Invidious kept running normally;
- NGIINX does not seem to be installed on my computer.

**What the hell is serving Invidious?**

---

- **OS**: Fedora 32.
- **Installation**:
  - Not using docker;
  - Followed steps described in `README.md` for installing Invidious on Linux.

**Comment by NotHenryOlson** [comment]
You can probably set the port to 80 and just alias 127.0.0.1 if that's what you want.

**Comment by hunkjazz** [comment]
@NotHenryOlson 

Nice catch, but I've got another app running on `localhost:80`, already.

All I need to know is how to serve Invidious on Apache, so I can set the reverse proxy.

Until now, no changes to httpd seems to affect Invidious.

**Comment by gripped** [comment]
Invidious has a built in webserver called kemal. Which is serving at localhost:3000

If you want more than one web app running on the same ip and port you can use virtual hosts https://httpd.apache.org/docs/2.4/vhosts/examples.html.

And this may also help:
https://github.com/omarroth/invidious/wiki/Apache2-Reverse-Proxy

Normally you'd use domains and sub-domains you own, but faking them with /etc/hosts works as well as long you only want local access.

**Comment by hunkjazz** [comment]
@gripped 

> Invidious has a built in webserver called kemal.

That's what I thought: kemal is serving Invidious. Thanks for clarifying!

>If you want more than one web app running on the same ip and port you can use virtual hosts

Yeah, but both of them would need to be running on the same server, right?
I can't figure out how to run Invidious on Apache, just on kemal (default). Is it even possible?

**Comment by hunkjazz** [comment]
**WHAT I WANNA DO**: set names like `ttrss.com` and `invidious.com` locally, so I can open these apps whithout the need to type in their correspondent ports (`invidious.com:3000`).

**WHAT I THINK I COULD DO**: 
- Run both Invidious and Tiny Tiny RSS on `localhost:80`;
- Set these hosts: `ttrss.com` and `invidious.com`
- Set virtual hosts to redirect the hosts to their DocumentRoot.

Now, the problem is: I can't set both kemal and Apache to listen to port 80, at the same time.

**Comment by SuperSandro2000** [comment]
> Yeah, but both of them would need to be running on the same server, right?

no

> I can't figure out how to run Invidious on Apache

Behind apache. Nothing is running on top of it.

> Is it even possible?

Yes

> WHAT I WANNA DO: set names like ttrss.com and invidious.com locally, so I can open these apps whithout the need to type in their correspondent ports (invidious.com:3000).

Hijack local DNS or hosts file and point them to the server where the services are running behind a reverse proxy.

> Run both Invidious and Tiny Tiny RSS on localhost:80

They can't.

> Set virtual hosts to redirect the hosts to their DocumentRoot.

Not document root. They would proxy it to the right port. https://httpd.apache.org/docs/2.4/mod/mod_proxy.html

> Now, the problem is: I can't set both kemal and Apache to listen to port 80, at the same time.

You don't need to. Your reverse proxy listens on port 80 and forwards the traefik to the right port and application base on hostname.
