### ISSUE TITLE
Setting domain: causes wrong URL generation

### ISSUE THREAD

**Issue by TheAssassin** [omarroth/invidious#1269]
Spin-off of https://github.com/omarroth/invidious/issues/1231#issuecomment-649196894.

I've recently set the `domain:` key on my Invidious instance. Unfortunately, this broke most URLs generated by Invidious (unless they're relative anyway). The URLs generated contains the internal port I use in Docker, which doesn't correspond to the real forwarding port (which is available from localhost only anyway, I use a reverse proxy to forward requests from the actual local domain).

I can confirm the issue for the storyboard URLs as well as `opensearch.xml`. All browsers I use now have the wrong URL, which required some annoying handiwork to get rid of the erroneous entries, after I removed the `domain:` setting again.

I would suggest to either replace `domain` with a true "base URL" setting, or to entirely use relative URLs (this is possible in some web frameworks, e.g., the micro framework [Flask](https://flask.palletsprojects.com/).

**Comment by SuperSandro2000** [comment]
You set the ``domain`` key to your FQDN.

**Comment by TheAssassin** [comment]
> You set the domain key to your FQDN.

That's what I did, yes. However, it broke the URLs. That's the entire problem...?

**Comment by SuperSandro2000** [comment]
Work for me.

**Comment by LatvjuAvs** [comment]
Ran into same problem.
API requests generated 500 response.

To fix this for now:
in "docker-compose.yml".
Add your domain and external port, set "https_only" to true.
Like:
**https_only: true
domain: invidious.plain.com
external_port: 443**

This will request direct sb, skipping api request.
Will return your domain url starting with https and will not add external(or internal) port at the end.

**Comment by TheAssassin** [comment]
I can confirm that setting `external_port: 80` (local instance in my case, HTTPS not really necessary) fixes the issue I had. previews. I guess we can close the issue as the configuration options are there, even if scattered across three settings instead of just one.
Thanks @LatvjuAvs!
