### ISSUE TITLE
The following video cannot be played

### ISSUE THREAD

**Issue by FireMasterK** [omarroth/invidious#1273]
I have tried to play this on a few different invidious instances, it just doesn't work.

Video URL: https://invidio.us/watch?v=3NN74IjlGTI

**Comment by llacb47** [comment]
Not an invidious issue, the video is region restricted. http://polsy.org.uk/stuff/ytrestrict.cgi?ytid=3NN74IjlGTI&auth=5ba28fe1d53f58118849ffc21bcda842

**Comment by FireMasterK** [comment]
Maybe we could have a suitable error message in that case?

**Comment by FireMasterK** [comment]
Maybe we could have a suitable error message in that case?

**Comment by Perflyst** [comment]
This already got requested multiple times, tracked in https://github.com/omarroth/invidious/issues/1194
