### ISSUE TITLE
Error in API, but works in frontend

### ISSUE THREAD

**Issue by FireMasterK** [omarroth/invidious#1274]
Example URL: https://invidio.us/api/v1/videos/Q0Pu1NV_65Q

Error response I get: `{"error":"Missing hash key: \"indexRange\""}`

The status code I get is `500 Internal Server Error`

**Edit**: The same thing happens with this livestream url: https://invidio.us/api/v1/videos/uVtdhB8UiX8

**Comment by FireMasterK** [comment]
After `8ed1c77`, there seems to be no streams in the api: https://invidious.snopyta.org/api/v1/videos/uVtdhB8UiX8?fields=adaptiveFormats

**Comment by llacb47** [comment]
> After `8ed1c77`, there seems to be no streams in the api: [invidious.snopyta.org/api/v1/videos/uVtdhB8UiX8?fields=adaptiveFormats](https://invidious.snopyta.org/api/v1/videos/uVtdhB8UiX8?fields=adaptiveFormats)

`https://invidious.snopyta.org/api/v1/videos/uVtdhB8UiX8?fields=hlsUrl`

**Comment by FireMasterK** [comment]
Thanks, that seems to be it.
