### ISSUE TITLE
403 on streaming video

### ISSUE THREAD

**Issue by FireMasterK** [omarroth/invidious#1275]
Example URL: https://invidio.us/watch?v=AOlVSngnC-o

![image](https://user-images.githubusercontent.com/20838718/86519373-e6b0cc80-be57-11ea-8532-d06715c673d4.png)

**Comment by llacb47** [comment]
Works fine for me

**Comment by FireMasterK** [comment]
I can't say the same, I get a message saying `The media could not be loaded, either because the server or network failed or because the format is not supported.`
If it matters: I am on a VPN connected to SG, but, SG is an allowed country.

**Comment by Perflyst** [comment]
> Provided to YouTube by Universal Music Group

Music is always problematic, further information can be found in  #92
