### ISSUE TITLE
esperanto translation of 'music' should be 'muziko'.

### ISSUE THREAD

**Issue by nathgit** [omarroth/invidious#1286]
the Esperanto word for music is muziko no musiko.
La Esperanta vorto por music estas muziko ne musiko.

**Comment by comradekingu** [comment]
@nathgit Heia, you can fix this on Weblate https://hosted.weblate.org/translate/invidious/translations/eo/?checksum=b80f6c8199ee8d30 :)

**Comment by comradekingu** [comment]
@nathgit I went ahead and fixed it.

**Comment by nathgit** [comment]
I suggested changes to a couple others too. 'Aboni' to 'abonu' & 'malaboni' to 'malabonu'. The imperative in Esperanto always ends in u. Ending in an 'i' makes it simply a verb. It's not a big deal though.

**Comment by comradekingu** [comment]
@nathgit you can log in with your GitHub account and make changes directly. We are happy to have you.
Love people that use imperative mood correctly. I accepted your changes. Also feel free to contribute to https://hosted.weblate.org/projects/remmina/remmina/eo/ :)
