### ISSUE TITLE
Question regarding its front page

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#13]
What happened to it? It used to display videos but now it no longer doesn't.

**Comment by omarroth** [comment]
When the server is restarted, Invidious starts a job that tries to find and update the top videos, you can see it [here](https://github.com/omarroth/invidious/blob/master/src/invidious.cr#L175-L214). There's a high load right now so the job is running much slower. It might be good to open a new issue regarding how top videos are selected.

**Comment by Zero3K** [comment]
Thanks for explaining.
