### ISSUE TITLE
What about legal threats?

### ISSUE THREAD

**Issue by SebKranz** [omarroth/invidious#130]
I am happy to see, that there are still attempts at circumventing YouTubes awful business/design strategy. 

However, every project that has attempted this so far, was eventually shot down by Google. Examples of such discontinued projects are HookTube and ProTube.

Is there anything stopping Google from shutting down this project too?

**Comment by Zero3K** [comment]
Its because they were using Youtube's API in a way that didn't involve the showing of ads. Invidious doesn't use Youtube's API so there's no reason for Google to get involved.

**Comment by omarroth** [comment]
Very good question! Yes, like @Zero3K said, ProTube and Hooktube both used the official API in a way that violated YouTube's terms of service.

Invidious works similarly to [NewPipe](https://github.com/TeamNewPipe/NewPipe) and [youtube-dl](https://github.com/rg3/youtube-dl), which YouTube appears to have left alone. Not to bury you in additional reading. but I'd recommend taking a look at rg3/youtube-dl#9810, TeamNewPipe/NewPipe#969, and TeamNewPipe/NewPipe#1160, which I think answer most questions about the legality of scraping and other parts of this project.

**Comment by omarroth** [comment]
I think I'll close this unless there are any other legal questions. To provide a little more clarification: Invidious is not (to my understanding) at risk of being taken down for the same reason as ProTube and Hooktube, as it does not use any of the official YouTube APIs. Feel free to reopen or comment with any other questions.
