### ISSUE TITLE
500 Server Error for logged in users

### ISSUE THREAD

**Issue by Avizini** [omarroth/invidious#131]
I am not able to view videos using Invidious, whenever I click on a link it takes me to a page which says "500 Server Error". When logged out everything works well.

![Wait for this gif to load... ~2MB](https://user-images.githubusercontent.com/37608661/44630932-8e077300-a954-11e8-8145-e16c6907a262.gif)

**Comment by omarroth** [comment]
Should be fixed by 0dbef6a.

**Comment by Avizini** [comment]
Yeah, all good now!
