### ISSUE TITLE
Links in the comments aren't clickable

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#134]
The links in the comments section aren't clickable for me in Pale Moon.

**Comment by omarroth** [comment]
Could you provide an example video? I'm having trouble finding videos with links in the comments.

**Comment by dimqua** [comment]
When you post a link like `youtu.be/XXXXX?t=1m10s`, it's displaying like `1:10` text. But on YouTube such text is clickable.

**Comment by Zero3K** [comment]
https://www.invidio.us/watch?v=UiagJYATgQM is an example of a video with links in the comments.

**Comment by omarroth** [comment]
Added with b3f9059. It also adds support for other text formatting, such as **bold text**, *italics*, and line breaks. Also to note is that there are **not** anchor icons next to links, instead the links themselves are updated, in line with #115 and #135.
