### ISSUE TITLE
Hide related videos

### ISSUE THREAD

**Issue by tillkrischer** [omarroth/invidious#137]
I dislike all the distractions that the standard Youtube interface provides.
So Invidious has been perfect for me.

I think it would be even cleaner in this regard if you could optionally hide the related videos column.

**Comment by dimqua** [comment]
See also: #123

**Comment by omarroth** [comment]
I'm glad it's been working well for you! Like @dimqua said, I think this is a duplicate of #123.

**Comment by omarroth** [comment]
Added with cb01b50.
