### ISSUE TITLE
Another video that isn't loading

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#138]
https://www.invidio.us/watch?v=5A-tlLv89vA is giving a "The media could not be loaded..." error.

**Comment by omarroth** [comment]
It appears to be working now. Although I think I know what the problem was, but unfortunately I can't test it now. Let me know if this occurs again.

**Comment by omarroth** [comment]
I think I'm going to close this for now, feel free to reopen if you encounter this issue again.
