### ISSUE TITLE
time_continue support

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#141]
YouTube embeds use the `&time_continue=` param when you click the "Watch on YouTube" button in the embedded player.
Looks like an alias to `&t=` and should be treated as such?

Example: https://www.youtube.com/watch?time_continue=53&v=fJP1caxDjgg

**Comment by omarroth** [comment]
I thought it already was supported but looking here: https://github.com/omarroth/invidious/blob/7fd0f93d029b8bd69409256c39bb0ead7929aa3a/src/invidious/videos.cr#L536 it looks like I'm only supporting `time_continu`, ha ha. Fixed with bdaa8a0.

**Comment by Discookie** [comment]
You should probably query for "time_continue" too instead of "t", because otherwise it 500's

https://github.com/omarroth/invidious/blob/bdaa8a06fda18f9895c2fe83cfc8d676b4936a0f/src/invidious/videos.cr#L536-L537

**Comment by omarroth** [comment]
Ah, good catch. Updated with 4022670.
