### ISSUE TITLE
Videos with no comments

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#142]
A video that has no comments (such as https://www.invidio.us/watch?v=PnNTVlG_G3o) is currently showing a spinning loading animation that never stops when it should just show nothing or say no comments available.

**Comment by omarroth** [comment]
Fixed with 7b135a6.

**Comment by Zero3K** [comment]
Now is just says "View 0 comments". It should say that there are no comments and have no +/- next to it.

**Comment by dimqua** [comment]
>It should say that there are no comments available

Or just display nothing.
