### ISSUE TITLE
Random 504 error when viewing Subscriptions

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#144]
I am getting a random 504 error when viewing the Subscriptions page.

**Comment by Discookie** [comment]
Encountering this a lot myself.
Sometimes it randomly clears the unseen notifications too.

Also, most of the times the bell doesn't show notifications.
But once the bell shows notifs, the 504 disappears too.

**Comment by omarroth** [comment]
Probably time to upgrade the DB server. The reason this is happening is because it's taking too long for the server to build a list of subscriptions, so the web server just times out.

**Comment by Zero3K** [comment]
Why does it happen on video pages then?

**Comment by omarroth** [comment]
It still needs to pull number of notifications. I'm assuming it only 504s when you're logged in? If so, then the DB is probably overloaded.

**Comment by omarroth** [comment]
Just bumped the DB by about 4x. Subscriptions now load almost instantly for me. If notifications are still not appearing, then we can continue to diagnose the problem, otherwise I'll probably consider this closed.

**Comment by omarroth** [comment]
Also before this is closed I would like to verify that notifications are also properly delivered.

**Comment by Discookie** [comment]
They are delivered properly now, got notifications after not opening invid for 9 hours.

**Comment by GauthierPLM** [comment]
I still encounter this issue and can't go to my subscription for few days now.

**Comment by Zero3K** [comment]
GauthierPLM: Are you getting a 504 error or something different?

**Comment by omarroth** [comment]
Everything appears to be working normally, I'm assuming it's working for you @Zero3K? If so, then I'll probably close this for now.

**Comment by Zero3K** [comment]
Yes, its working fine for me.

**Comment by omarroth** [comment]
Great! Feel free to reopen this or create a new issue if it starts happening again.
