### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#146]
It would be nice if Invidious could tell Discord what video is being currently played.

**Comment by Discookie** [comment]
What do you mean by that - a video embed?
That doesn't really seem possible unless @discordapp gets involved.

It already does a pretty good job at getting a preview:
![image](https://user-images.githubusercontent.com/16914176/44933935-4d03ca00-ad6b-11e8-91ad-1027fb6d3360.png)

**Comment by omarroth** [comment]
I'm glad to see it's properly serving metadata. Is what you're asking for something that is provided by YouTube videos? Could you provide a screenshot if so?

**Comment by Zero3K** [comment]
I mean, it should show in the user's status what video is being played. Basically, instead of "Playing GAMENAME" or "Listening to Spotify" it should show "Watching VIDEONAME" underneath the user's name.

**Comment by Discookie** [comment]
Yep, they support some services like Youtube, Spotify or Imgur:
![image](https://user-images.githubusercontent.com/16914176/44934496-4ece8d00-ad6d-11e8-9677-c40bc0587428.png)

It has to be explicitly implemented by them - otherwise it only grabs previews like the one I already linked.

**Comment by Discookie** [comment]
@Zero3K That's not possible without a dedicated app with an integration of their Rich Presence plugin:
https://github.com/discordapp/discord-rpc

**Comment by Zero3K** [comment]
So, the only way for it to be possible is if someone were to develop a program that monitors web browsers for Invidio.us urls, grabs the video title, and sends it to Discord via RP.

**Comment by omarroth** [comment]
Thank you for the info @Discookie. It doesn't look like there's much I can do to better support Invidious on Discord without working directly with the @discordapp team.
