### ISSUE TITLE
Speed up subscription notification

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#148]
I am seeing that videos which are posted on channels that I am subscribed to aren't being shown in the subscriptions page for a few minutes. Please fix it so they show up in the page when they are uploaded.

**Comment by omarroth** [comment]
Currently, the way Invidious finds new uploads is by polling YouTube for them. Currently it is able to update about 20,000 channels every 20 minutes, which works but is obviously not ideal. I'd be interested in any thoughts or alternate ways to do this that might be faster. Also see #37.

**Comment by Zero3K** [comment]
I don't have any thoughts regarding it.

**Comment by omarroth** [comment]
I'd have to do a couple benchmarks to verify the speed at which videos are delivered to a user's feed, but generally it's pretty fast for me. 

Unfortunately I don't know of any way to speed up subscriptions except for increasing the number of nodes crawling YouTube, so I think I'll do that and close this. If there are any other issues with videos not appearing in your feed, feel free to open a new issue.

**Comment by elypter** [comment]
wouldn't it be possible for the server to be informed by e-mail or push messages? i am also having delays that are often several hours. this can be a problem if i miss a video because it gets sorted in not in the first place because there is a newer video already that i already watched.

**Comment by omarroth** [comment]
Without using the YouTube API, there's not really a good way to subscribe to updates from a channel. Currently Invidious pulls from the RSS feed, which is generally pretty fast, but it has to do that for all the channels users on the site are subscribed to, which is likely the largest source of latency.
