### ISSUE TITLE
Link redirection not working

### ISSUE THREAD

**Issue by Avizini** [omarroth/invidious#149]
I redirect everything from youtube.com/* to invidio.us/*

Take this video, [Invincible -NCS](https://www.invidio.us/watch?v=J2X5mJ3HDYE).

![Wait for this to load...](https://user-images.githubusercontent.com/37608661/44993468-38514d00-af8a-11e8-893c-6fe145017504.png)

When you click  on the link, it takes you to `https://www.invidio.us/redirect?redir_token=avJytxXwtv9ga5Dr3qopp_YybFB8MTUzNjA3Mjk1MkAxNTM1OTg2NTUy&event=video_description&v=J2X5mJ3HDYE&q=http%3A%2F%2Fncs.io%2FUsagePolicy`. 

Here Youtube.com was replaced by invidio.us

That takes me to this page:
![Wait for this to load...](https://user-images.githubusercontent.com/37608661/44993556-85352380-af8a-11e8-8e73-affef854f43e.png)

Expected behaviour: It redirects me to the link

Suggestion: Replace those links in description and directly take the user to the link instead of `youtube.com/redirect?blah-blah`

**Comment by dimqua** [comment]
It's a duplicate of #115. :-)

**Comment by Avizini** [comment]
Oh! Didn't see it, thanks.
