### ISSUE TITLE
Tor Browser 8.0 support

### ISSUE THREAD

**Issue by xqk94524** [omarroth/invidious#150]
for some reason invidio.us isn't work anymore on Tor Browser 8.0, it's probably related to some noscript issue

**Comment by xqk94524** [comment]
`Content Security Policy: Couldn’t process unknown directive ‘report-to’
Loading failed for the <script> with source “https://unpkg.com/video.js@6.12.0/dist/video.min.js”.
watch:36
Loading failed for the <script> with source “https://unpkg.com/videojs-hotkeys@0.2.22/build/videojs.hotkeys.min.js”.
watch:37
Loading failed for the <script> with source “https://unpkg.com/silvermine-videojs-quality-selector@1.1.2/dist/js/silvermine-videojs-quality-selector.min.js”.
watch:38
Loading failed for the <script> with source “https://unpkg.com/videojs-markers@1.0.1/dist/videojs-markers.min.js”.
watch:39
Loading failed for the <script> with source “https://unpkg.com/videojs-share@1.1.0/dist/videojs-share.min.js”.
watch:40
Content Security Policy: The page’s settings blocked the loading of a resource at https://unpkg.com/video.js@6.12.0/dist/video.min.js (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://unpkg.com/videojs-hotkeys@0.2.22/build/videojs.hotkeys.min.js (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://unpkg.com/silvermine-videojs-quality-selector@1.1.2/dist/js/silvermine-videojs-quality-selector.min.js (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://unpkg.com/videojs-markers@1.0.1/dist/videojs-markers.min.js (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://unpkg.com/videojs-share@1.1.0/dist/videojs-share.min.js (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: 
var options = {
  
  aspectRatio: "16:9....
watch:113
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: 
function toggle(target) {
  body = targ....
watch:274
Specified “type” attribute of “video/3gpp; codecs="mp4v.20.3, mp4a.40.2"” is not supported. Load of media resource https://r4---sn-ab5l6ndy.googlevideo.com/videoplayback?source=youtube&pl=49&signature=25BE73A815624D75064D53B67A765F80657F7840.0E7E2637BF5C441586F0CC6E5140D00F13978EAD&initcwndbps=145000&gir=yes&c=WEB&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&fvip=6&mime=video%2F3gpp&txp=5531332&lmt=1536070854455245&dur=232.756&key=yt6&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&itag=36&beids=9466585&id=o-AOTt_d-2bg6puaiLcT6SLnJ9WMJGeGM99ElYV4lcJagu&mm=31%2C26&mn=sn-ab5l6ndy%2Csn-p5qlsnzd&ipbits=0&clen=6436021&requiressl=yes&expire=1536120726&mt=1536099014&mv=m&ei=NgOPW6z_H9Lr8wT905v4Bg&ms=au%2Conr failed.
watch
All candidate resources failed to load. Media load paused.
watch
`

**Comment by xqk94524** [comment]
![image](https://user-images.githubusercontent.com/34273204/45103146-36f46180-b0fd-11e8-8359-b91d8ccf4c4c.png)
Content Security Policy: Couldn’t process unknown directive ‘report-to’ 
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead video.min.js:1:30651

**Comment by xqk94524** [comment]
this was at safer level

**Comment by xqk94524** [comment]
https://dist.torproject.org/torbrowser/8.0/
https://gitweb.torproject.org/builders/tor-browser-build.git/tree/projects/tor-browser/Bundle-Data/Docs/ChangeLog.txt

**Comment by omarroth** [comment]
Thanks @xqk94524. I can report the same issue in Tor Browser 7.5.6. Disabling JavaScript should work as a temporary fix. The problem appears to be VideoJS blocking playback because it isn't handling `type='video/mp4; codecs="blah blah"'` correctly in the Tor browser. 93e12d9 should hopefully fix the issue.

**Comment by omarroth** [comment]
As a temporary fix, disabling JS completely should allow videos to play. Unfortunately, you won't be able to change quality, speed, etc. except through your preferences or query params.

**Comment by xqk94524** [comment]
I noted, this is a problem related to TB 8.0, not invidious

TB 7.5.6
![image](https://user-images.githubusercontent.com/34273204/45168561-8dc76d00-b1c9-11e8-8458-e794d6457007.png)

TB 8.0
![image](https://user-images.githubusercontent.com/34273204/45168852-4d1c2380-b1ca-11e8-854f-f737aaa62304.png)

**Comment by omarroth** [comment]
This appears to be a related issue on the Tor issue tracker: https://trac.torproject.org/projects/tor/ticket/27429.

**Comment by T4eus** [comment]
Look, xqk94524 was my account too, but as I have had problems with login, and was unable to recover my previous account, I created this one.

As it isn't a issue with invidious, you can close this.

**Comment by omarroth** [comment]
Alright great!
