### ISSUE TITLE
Proxy images

### ISSUE THREAD

**Issue by theel0ja** [omarroth/invidious#153]
I understand why you can't proxy videos, but please at least proxy images...

<img width="222" alt="screen shot 2018-09-05 at 20 30 10" src="https://user-images.githubusercontent.com/5832930/45110301-8c0a9480-b14a-11e8-8df1-2db01041a1a3.png">

**Comment by dimqua** [comment]
Not only images, but external CSS and JS also.

**Comment by omarroth** [comment]
As a short update: assets are now hosted locally with 3ec684ae710529f681ea731a3cbd5f6fc9bee6a6.

**Comment by omarroth** [comment]
Thumbnails are now proxied with 429a4b2deca8b94b04f73fbaf0f50f26c93bac39, it also automagically pulls the highest resolution thumbnail for videos, which is pretty nice. I think the only thing that needs to be proxied now is author thumbs, and we can close this.

**Comment by theel0ja** [comment]
Great. However, some pages like https://invidio.us/watch?v=yErnuebA9Yo are still downloading some video thumbnails from Google/YouTube.

**Comment by theel0ja** [comment]
Could it be this line?

https://github.com/omarroth/invidious/blob/429a4b2deca8b94b04f73fbaf0f50f26c93bac39/src/invidious/videos.cr#L670

**Comment by omarroth** [comment]
What error is it returning?

**Comment by theel0ja** [comment]
In the title, there was "Error - Invidious". However, it's working now.

**Comment by theel0ja** [comment]
Fixed 😄 (user photos not yet though)

**Comment by theel0ja** [comment]
#168 for user photos
