### ISSUE TITLE
Some videos are missing the player

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#160]
I am missing the player on https://www.invidio.us/watch?v=EI6Zg7Nl65Q. I am using the latest version of Pale Moon. Here's one of the messages shown in the Error Console regarding it:

Timestamp: 9/10/2018 7:15:53 PM
Warning: Error in parsing value for ‘right’.  Declaration dropped.
Line: 0
Source Code:
-NaNpx

**Comment by roranicus** [comment]
I have the same issue, also with Palemoon. Restarting in safe mode did seem to fix it though, so I'm inclined to believe addons may be involved. Even stranger is that your video works for me if it's the first thing I watched upon opening the browser, but if I do other things first, such as login on to type this comment, for example, then the bug occurs. 

Have you tried safe mode? If you get the same behavior as me, then I guess we could compare addons and see what we have in common. Could make it easier to find the culprit.

**Comment by AlertDOTEXE** [comment]
Might actually be related to ublock origin, at least for me. When I disable it for invidious, the player comes back. I have no idea why this issue is happening because I am not blocking anything on the page, this becomes an issue on a site when I do want to use ublock but want watch an embedded video.

**Comment by omarroth** [comment]
Unfortunately I'm having trouble replicating this in Pale Moon. I wouldn't be surprised if NoScript was blocking some videos or other resources, which was a problem some folks reported [here](https://trisquel.info/en/forum/invidious-youtube-redirect-site-agplv3-no-js-required?page=1#comment-135658). Also see #151.

**Comment by AlertDOTEXE** [comment]
> 
> 
> Might actually be related to ublock origin, at least for me. When I disable it for invidious, the player comes back. I have no idea why this issue is happening because I am not blocking anything on the page, this becomes an issue on a site when I do want to use ublock but want watch an embedded video.

My apologies, I meant to specify that I am using Firefox Developer Edition 63.0.

**Comment by roranicus** [comment]
Disabling ublock on invidio does solve the issue for me. It's weird, because Ublock doesn't seem to be blocking anything. Disabling it on invidio seems to fix the issue for now. Seems like we may have a culprit.

**Comment by T4eus** [comment]
> 
> 
> Disabling ublock on invidio does solve the issue for me. It's weird, because Ublock doesn't seem to be blocking anything. Disabling it on invidio seems to fix the issue for now. Seems like we may have a culprit.

same issue as #161 
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-pre-fetching
just uncheck "Disable pre-fetching" at Ublock Origin settings, and it will work

**Comment by omarroth** [comment]
Appears to be blocked by [Fanboy Annoyances List](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt) ([website link](https://www.fanboy.co.nz/)). Namely this line:
```css
##.vjs-share
```
which blocks the entire player.

**Comment by AlertDOTEXE** [comment]
Not sure if it's specific to me or not, but neither disabling Fanboy Annoyances List nor disabling pre-fetching allowed the video to appear for me. I did find a work around which was to disable one of two scripts that loads. 

https://invidio.us/js/videojs-share.min.js

https://invidio.us/js/videojs.hotkeys.min.js

Blocking one of these, doesnt matter which, via ublock's global URL dynamic filtering feature allows the player to load like normal.

**Comment by Zero3K** [comment]
You probably have more than one filter that is blocking that entry.

**Comment by AlertDOTEXE** [comment]
![capture](https://user-images.githubusercontent.com/13185099/45587616-9cafcd00-b8f7-11e8-9496-eda2e1df6192.PNG)

**Comment by Zero3K** [comment]
What does the logger state when you click on a blocked entry when using it to log the requests to the Invidio.us video page?

**Comment by T4eus** [comment]
did you use Nano Defender? was tried to disable for precaution?

**Comment by T4eus** [comment]
put the console log here, may have something useful

**Comment by AlertDOTEXE** [comment]
I disabled Nano Defender and nothing yielded. I isolated every addon and ublock origin is the only addon that creates this issue.

My apologies, but you have me at a disadvantage. You meant a screenshot of the logger correct?
![capture](https://user-images.githubusercontent.com/13185099/45588106-d801ca00-b8fe-11e8-9287-6b3eb7df818c.PNG)

**Comment by omarroth** [comment]
Also to note is that both Fanboy's Social Blocking *and* Fanboy's Annoyance List appears to the player.

**Comment by AlertDOTEXE** [comment]
This is correct, disabling these lists allows the player to load in my case.

**Comment by T4eus** [comment]
those lists don't have any effect here

**Comment by AlertDOTEXE** [comment]
The Fanboy's Social Blocking and Fanboy's Annoyance List and actually really useful for me so disabling the lists entirely wouldn't be ideal. Unfortunately, you can not directly edit the lists unless you download the .txt file and upload it somewhere like dropbox then import it.

What I learned from the ublock wiki is that you can overwrite the filer lists with your own rules, so what I did was append "invidio.us .vjs-share * allow" without quotes to the my rules tab and made it permanent. This seems to work for me at least at the moment.I am an extreme novice at the configuration of ublock so I am sure I am doing something incorrect. I'm certain someone more experienced can confirm or optimize it to make it better.

**Comment by Discookie** [comment]
Seems like a typo inside [videojs-share](https://github.com/mkhazov/videojs-share/):

https://github.com/mkhazov/videojs-share/blob/fb04cff70a5f0e73450aa9560a49a64432616af2/src/plugin.js#L38

They mistakenly add the class to the entire player, instead of only `.vjs-videojs-share`. They only check for the existence of `.vjs-videojs-share` later in the code.

**Comment by T4eus** [comment]
https://adblockplus.org/filters
https://adblockplus.org/filter-cheatsheet
Try this rule

`@||invidio.us$generichide,genericblock`

**Comment by AlertDOTEXE** [comment]
Tried both that rule and the rule I posted before. It seems like they both work initially, but after a while, the player stops appearing again. The most consistent method for me is either disable the Fanboy rules (which is something I am reluctant to do) or disable javascript until mkhazov/videojs-share#12 is fixed.

**Comment by Zero3K** [comment]
It looks like it has been fixed somehow.

**Comment by omarroth** [comment]
:tada:.  Looks like this and mkhazov/videojs-share#12 can be closed. If possible, I'd like to make sure it's working for @AlertDOTEXE as well before closing.

**Comment by AlertDOTEXE** [comment]
After enabling the javascript, I have verified this is also working for me. Thanks everyone!

**Comment by Discookie** [comment]
Re: mkhazov/videojs-share#12
That cannot be closed yet, because the sites using it have to be specifically whitelisted - on other sites using it, it still blocks the entire player by default.
