### ISSUE TITLE
subscriptions not showing up

### ISSUE THREAD

**Issue by ChloeMackey** [omarroth/invidious#163]
I'm subscribed to ycombinator https://invidio.us/channel/UCcefcZRL2oaA_uBNeo5UOWg, they posted two videos yesterday and they still aren't on my subscription feed. I know there is another channel I'm subscribed to that posted a video recently and its also not showing up.

**Comment by Discookie** [comment]
Seconded, there's been no new videos showing up for ~22 hours on my feed.

**Comment by ChloeMackey** [comment]
Seems to be working for me as well. Just to confirm, playlists don't work on invidious? Like i cant take a youtube playlist and watch it on invidious, correct?

**Comment by Discookie** [comment]
You can take a playlist that's in the form of `/playlist?list=PLxxxxx`, and it will display the contents of the playlist for you. 
But playlists in the form of `/watch?v=xxxx&playlist=PLxxxxx` don't work yet.

I can confirm it's working properly too.

**Comment by ChloeMackey** [comment]
So It cant autoplay through a playlist yet?

**Comment by omarroth** [comment]
Not yet unfortunately. Playback functionality is tracked in #16 and something I'm working on adding soon. If you have any other questions that seem off-topic or aren't related to the original issue feel free to hop on the [Freetube Matrix Server](https://riot.im/app/#/room/#freetube:matrix.org) and ask there.

I think I'll close this issue for now, sorry for the inconvenience everyone. Absolutely reopen this or open a new issue if it becomes a problem again.
