### ISSUE TITLE
Issue with searching in IE 11

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#167]
Nothing happens when I try pressing Enter to submit the search term.

**Comment by omarroth** [comment]
That's rather strange. It works for me when testing with [Browserling - IE11, Win7 | Invidio.us](https://www.browserling.com/browse/win/7/ie/11/https%3A%2F%2Fwww.invidio.us%2F).

**Comment by T4eus** [comment]
works here

Windows 10 64-bits 1803
IE11 version:
![image](https://user-images.githubusercontent.com/43221359/45554489-97be2100-b804-11e8-973a-127d58e8eeab.png)

**Comment by T4eus** [comment]
also works at browserling

what is your operating system? win7sp1? or high?
did you use any extension or plug-in?
some custom settings?

**Comment by Zero3K** [comment]
My OS is Windows 10. I am using the Internet Explorer 11 engine via TubeDigger (http://www.tubedigger.com).

**Comment by omarroth** [comment]
I'm having trouble replicating this in Firefox 62. It may be the case that the video player is capturing keyboard strokes, which might explain why a page refresh would fix it (unless of course it happens on other pages than the `/watch` page).

**Comment by Zero3K** [comment]
It is happening on the main page for me.

**Comment by T4eus** [comment]
off-topic:
if you use TubeDigger to download videos, I recommend Youtube-DL instance, if you known to use command-line-interface it will be better than TubeDigger.

alternatively you can use "inspect element > network" on some browsers

**Comment by Zero3K** [comment]
I use TubeDigger to record RTMP, etc. streams.

**Comment by T4eus** [comment]
At least it works, in the normal IE11?

**Comment by Zero3K** [comment]
I do not have Internet Explorer 11 installed.

**Comment by T4eus** [comment]
I recommend you to contact the TubeDigger support, because, this bug doesn't look to be a bug related to IE11, but a bug specifically related to TubeDigger.

https://www.tubedigger.com/contact.html

**Comment by omarroth** [comment]
Seconded. I think close this since it doesn't appear to be a bug in Invidious or in IE11.
