### ISSUE TITLE
Proxy profile pictures

### ISSUE THREAD

**Issue by theel0ja** [omarroth/invidious#168]
<img width="437" alt="screen shot 2018-09-15 at 16 39 01" src="https://user-images.githubusercontent.com/5832930/45586847-df78a180-b905-11e8-8571-e931913f8d1d.png">

link where this occurs: https://invidio.us/watch?v=dQw4w9WgXcQ

**Comment by theel0ja** [comment]
For proxying: https://github.com/atmos/camo

**Comment by omarroth** [comment]
Added with 35bee98 :tada:.
