### ISSUE TITLE
4:3 videos are getting too big without javascript

### ISSUE THREAD

**Issue by T4eus** [omarroth/invidious#169]
as the players lined by width, 3: 4 get a lot bigger in the height, this occurs with javascript disabled

firefox 62

**Comment by omarroth** [comment]
This should already be fixed by 6753294ee1044823f37edc9387918ac504df3957, although you may have to clear your cache. If the issue still remains, do you mind posting an example video/screenshot?

**Comment by T4eus** [comment]
https://invidio.us/watch?v=xFWVFu2ASbE
![image](https://user-images.githubusercontent.com/43221359/45588224-5d758200-b8df-11e8-9c11-3318dd8a41d7.png)

https://invidio.us/watch?v=iY1we7AX3m0
![image](https://user-images.githubusercontent.com/43221359/45588230-6e25f800-b8df-11e8-94b5-925301c41a38.png)

both too long for my screen (captured with firefox screenshots tool)

**Comment by omarroth** [comment]
Can confirm with Firefox 62 with Javascript disabled. c74cc1123f01c321da5453dc31c5ba85fd90a95e appears to fix it (you may have to clear your cache).

**Comment by T4eus** [comment]
looks fine, thanks
