### ISSUE TITLE
Allow user to subscribe to playlist

### ISSUE THREAD

**Issue by omarroth** [omarroth/invidious#17]
As a follow-up to #16, a user should be able to subscribe to playlist changes. Playlist subscriptions should share the same feed as channel subscriptions.

Wondering about any implications of this.

**Comment by beefeater7** [comment]
I was always dissatisfied with the lack of this in regular YouTube. However creators are used to the current model and need an incentive to keep their playlists up to date. Many of them just maintain several channels instead, I think it's a pity. 

Tags appear to be gaining relevance, on the other hand.

**Comment by omarroth** [comment]
Smaller channels still do this, since having multiple channels fragments their audience, which I think is a definite incentive. I've never seen more than about 3-4 separate channels from the same author, while each channel may have many times as many playlists. I'd recommend opening a new issue for tags, since I haven't seen them much and would be very interested if you could provide more info.

Most channels I've encountered still do keep their playlists up to date, and with #114 it will be possible for users to keep them updated themselves (and for other users to follow those), so I think there's still value here.

**Comment by elypter** [comment]
it would be nice to also be able to subscribe to search results. this way you could be informed about reuploads, video responses, trends/memes, news and niche topics of interest.
