### ISSUE TITLE
Links inside comments do open outside of invidious

### ISSUE THREAD

**Issue by AlertDOTEXE** [omarroth/invidious#174]
When clicking on a link that is inside of a comment, the page loads the link inside of invidious with a 404 error instead of following the link to the external site. 

Example: https://invidio.us/watch?v=ax27VgI-lVE&autoplay=1

Expanding the first comment shows the particular link I am referencing.

![capture](https://user-images.githubusercontent.com/13185099/45778077-238dde00-bc47-11e8-85a7-2d1e774043c2.PNG)

**Comment by omarroth** [comment]
Good catch! Should be fixed with 2c6f8022e6a8c9053231d6b2765cb6fdb4904791.
