### ISSUE TITLE
uBlockOrigin hides Invidious's Video player

### ISSUE THREAD

**Issue by Avizini** [omarroth/invidious#175]
uBlockOrigin hides Invidious's Video player when cosmetic filtering is enabled and I guess that is enabled by default. 

Earlier it didn't hide the player even with cosmetic filtering enabled.

![Wait for this to load..](https://user-images.githubusercontent.com/37608661/45792865-24426680-bc7f-11e8-9a6d-9993286704af.png)

**Comment by omarroth** [comment]
You might see if you have Fanboy's Social or Annoyance Filter enabled. If disabling that fixes the issue, then it's likely a duplicate of #160 and we can close this.

If that doesn't work, would you mind checking uBlock's logger to see if it says anything? There are also a couple notes in #161, #160, and #151 that might help in finding the problem.

**Comment by Avizini** [comment]
Yes disabling Fanboy's Annoyance filter fixes this.
