### ISSUE TITLE
Channels don't always show 60 videos on a page

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#181]
This issue happens on random pages of random channels:
https://invidio.us/channel/UC3ifTl5zKiCAhHIBQYcaTeg?page=5
https://invidio.us/channel/UC3ifTl5zKiCAhHIBQYcaTeg?page=7
https://invidio.us/channel/UC5nc_ZtjKW1htCVZVRxlQAQ?page=17
(I also saw a page that had only 58, but I can't find it anymore)
![image](https://user-images.githubusercontent.com/16914176/45982191-12363e80-c058-11e8-88b2-4cf6a281e971.png)

On all of the pages I linked, there's only 59 videos, so the "Next page" button doesn't show.
But if you manually increment the page count, it displays the next page properly.

On Youtube there is also a video missing around that area, because it messes up the video count on the last row of the Videos page.
![image](https://user-images.githubusercontent.com/16914176/45982158-f59a0680-c057-11e8-8fd6-3071894f9729.png)

Might be related to removed/unlisted videos or copyright issues?

**Comment by omarroth** [comment]
My guess is that geo-blocked videos are hidden. For example [this channel](http://invidio.us/api/v1/channels/UCUzpZpX2wRYOk3J8QTFGxDg) has several videos missing that are available only in JP, for example https://invidio.us/watch?v=7KSfDyainYU , and are hidden in the channel page.

This can be confirmed by using a JP proxy (from [here](https://www.proxynova.com/proxy-server-list/country-jp/)). Using a proxy, the last four videos look like this:
YouTube:
![image](https://user-images.githubusercontent.com/14208607/46093047-f461fa00-c17b-11e8-8da9-f638832d9d3c.png)

Invidious:
![image](https://user-images.githubusercontent.com/14208607/46093116-1e1b2100-c17c-11e8-8fb8-527e2be01ad8.png)

[This](https://invidio.us/watch?v=m7m0f7e7Llk) is the missing video, which is whitelisted only in JP.

I'll have to look into this a bit more to see if there's anyway of detecting region locks for channels.

**Comment by omarroth** [comment]
I'd consider this "fixed" with 245d0b571fdf234f4ac646aa4221b537b92dbffb, still looking into detecting and bypassing region locks.

**Comment by Discookie** [comment]
Yep, looks fixed here!

My issue was more with channels not having a "Next page" option since geo-restrictions are an entirely separate issue. I guess I'll close this, and region-lock related findings can always go into #92.
