### ISSUE TITLE
Missing quality options

### ISSUE THREAD

**Issue by TylerHobanDotCom** [omarroth/invidious#187]
Over the past few days the quality options I had before are no longer showing, even on the same videos. It seems like no matter what video I go to there is only a `medium - mp4` option.

 
Device info:

Mozilla/5.0 (X11; CrOS x86_64 10895.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.95 Safari/537.36

string:
family: Chrome
major: 69
minor: 0
patch: 3497
device: Other 0.0.0

os
string: Chrome OS 10895.56.0
family: Chrome OS
major: 10895
minor: 56
patch: 0

ua
ua: Mozilla/5.0 (X11; CrOS x86_64 10895.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.95 Safari/537.36
browser
name: Chrome
version: 69.0.3497.95
major: 69
engine
name: WebKit
version: 537.36

os
name: Chromium OS
version: 10895.56.0
name: Chrome
version: 69.0.3497.95
layout: Blink

**Comment by Discookie** [comment]
I've noticed this too, mainly on videos that contain music.
Youtube simply doesn't serve the regular 720p on these videos for some reason.

**Comment by dimqua** [comment]
Can you provide any example(s), please?

**Comment by Discookie** [comment]
Sure, here's 4:
https://invidio.us/channel/UCw49uOTAJjGUdoAeUcp7tOg
https://invidio.us/channel/UC3ifTl5zKiCAhHIBQYcaTeg
https://invidio.us/channel/UC9ecwl3FTG66jIKA9JRDtmg
https://invidio.us/channel/UC5nc_ZtjKW1htCVZVRxlQAQ

Notice that they're music channels.

**Comment by omarroth** [comment]
I've noticed this as well. I don't think this is an issue with Invidious however, as the problem appears to be that YouTube is not providing any other qualities.

**Comment by dimqua** [comment]
It provides only 720p @ DASH.

**Comment by TylerHobanDotCom** [comment]
Hmm. Maybe @omarroth can add DASH support to the player then? You can add DASH support to VideoJS. (See https://videojs.github.io/videojs-contrib-dash/)

Also did YouTube just recently stop serving 720p mp4 files for music? I could have sworn many of the videos worked before.

**Comment by omarroth** [comment]
DASH support is currently in beta. You can enable it in your preferences by changing your `preferred quality` to `dash`,  see #34.

I've also only noticed it recently, so it may be another attempt by YouTube to restrict access to videos.

**Comment by omarroth** [comment]
I think I'll close this, since the issue appears to be that YouTube is not providing any other non-DASH streams, which isn't really something that's possible to fix.
