### ISSUE TITLE
"Mix" playlists

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#188]
Currently the "Mix" playlists are 0 items long.

One such playlist can be seen here as a search result:
https://invidio.us/search?q=The+Crystal+Method+%E2%80%93+Roll+It+Up

They seem to be of the format [RDxxxxxxxxxxx](https://www.youtube.com/watch?v=luy5ySQWCPc&start_radio=1&list=RDluy5ySQWCPc) where xxx is the base video ID, in this case [luy5ySQWCPc](https://invidio.us/watch?v=luy5ySQWCPc).
They seem to have no playlist page.

So either the Mix needs to link to the base video, Invidious should somehow get the playlist contents, or these results should be hidden altogether.

**Comment by omarroth** [comment]
Added mixes with 20130db.

Instead of being a continuous feed (which relies on YouTube/Google's tracking), accessing a feed returns only the first 50 videos. You can create a mix with `RDxxxxxxxxxxx` with a `seed` video ID, as mentioned above.
