### ISSUE TITLE
Youtube Red/Premium Videos Send Notifications At Least Once A Day

### ISSUE THREAD

**Issue by JackWilb** [omarroth/invidious#190]
I've been using this viewer for a little while and recently I've noticed an issue that I couldn't find with the issue search. 

Videos that are youtube red (premium?) keep appearing in my subscription box. This happens at least once a day and I'd guess it's based on when the channels refresh. 

This means that I sometimes have around a hundred notifications when there are only really 10 new videos.

**Comment by JackWilb** [comment]
I'm still getting them in my sub box. I'm using https:invidio.us/ and I'm accessing it through safari on both ubuntu and mac. This afternoon I had 40 notifications and 35 were from youtube red/premium videos. Let me know if I can provide more details or if it's because I'm using your web client. Thanks

**Comment by omarroth** [comment]
No, that was my mistake. I forgot to push it. It's been pushed now though and I've stopped encountering this issue, let me know if you find the same.

**Comment by JackWilb** [comment]
Looks like it's fixed, thanks!
