### ISSUE TITLE
Fix CSS that removes "search" input's features on webkit.

### ISSUE THREAD

**Issue by jlennox** [omarroth/invidious#191]
On a mobile it's very annoying to need to hold down the "back" button to clear the entire search field.

This css inside "pure-min.css" is causing this built in feature of <input type="search" /> to be removed.

```
input[type=search]::-webkit-search-cancel-button,input[type=search]::-webkit-search-decoration {
    -webkit-appearance: none
}
```

**Comment by omarroth** [comment]
Removing it produces this in Chrome:
![image](https://user-images.githubusercontent.com/14208607/46237232-bb2ab500-c348-11e8-98b0-32e3f0a54b33.png)

I'd happily accept a PR to add styling for mobile. I agree that it shouldn't be hidden. Removing that line still results in a search bar with no "x" or clear option (at least on iOS). I'm having trouble finding anything else that might be causing it.

**Comment by omarroth** [comment]
Added with 6fd24ad54fc39ced6d76bcc01cfbcfc6563bb81e. Unfortunately I'm having trouble using it when testing it on my device, Chrome works as expected.
