### ISSUE TITLE
Feature request: continuous playback

### ISSUE THREAD

**Issue by MadMage999** [omarroth/invidious#192]
Loving invidious so far, but I notice it doesn't play another video after the one I've selected ends.

Would you please add the ability to select an option so that invidious chooses a related video that it hasn't played in the last say 15 videos and plays it after the current video ends?

**Comment by omarroth** [comment]
Unfortunately not, although I'm open to adding it. I'd recommend rewording the issue/title so it looks more like a feature request if you'd like it to be added.

**Comment by omarroth** [comment]
Added with 4b76b93.
