### ISSUE TITLE
View YouTube comments

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#199]
There's a possibility to view Reddit comments, but you can't switch back to YouTube ones.

**Comment by omarroth** [comment]
![image](https://user-images.githubusercontent.com/14208607/46678526-799cd400-cbaa-11e8-8b7d-2bd3ea2a44ca.png)

Could you provide a link to a specific video?

**Comment by dimqua** [comment]
No, when you click to **view Reddit comments**, but there is none of them, then you can't switch back, since the switcher is not there.

**Comment by dimqua** [comment]
https://www.invidio.us/watch?v=tAG2cCGbQi0

**Comment by omarroth** [comment]
The above video appears to be working for me. Could you open devtools to see if it's producing any errors?

**Comment by dimqua** [comment]
Ctrl+Shift+K? No errors. 

Also note that there are no problems, when there is at least one Reddit comment for a video.

**Comment by omarroth** [comment]
Should be fixed with 57d88ff, you might have to clear your cache.
