### ISSUE TITLE
YT comments' pictures are shrunk

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#201]
Example: https://invidio.us/watch?v=nVHn7SVkpew

![image](https://user-images.githubusercontent.com/16914176/46685954-0c636000-cbf7-11e8-974d-f721ae274afe.png)

This only affects the last 3 or so comments, but it also happens on larger comment sections.

**Comment by omarroth** [comment]
Should be fixed with 02335f3.

**Comment by Discookie** [comment]
Yep, fixed on all videos I've seen this on.
