### ISSUE TITLE
Add duration to video thumbnails

### ISSUE THREAD

**Issue by omarroth** [omarroth/invidious#202]
Videos on YouTube are displayed with a duration in the bottom right corner that is useful when deciding what to watch. Invidious should also provide this information to the user.

**Comment by omarroth** [comment]
Partial support added with 4875aa1. Duration currently isn't available in subscription feed, since it requires a migration, but should be added soon.

**Comment by dimqua** [comment]
LGTM!

**Comment by omarroth** [comment]
Added duration to videos in subscription feeds with 8794e26e67fc11ded8d83393a25c816784ec1d10, unfortunately it means that each feed will need to be regenerated, which shouldn't take more than about a minute for each person's feed.

**Comment by omarroth** [comment]
Finished with migration, everything appears to be working.
