### ISSUE TITLE
Allow users to view comments with JS disabled

### ISSUE THREAD

**Issue by omarroth** [omarroth/invidious#204]
Currently Invidious uses Javascript to decrease first page load for the `/watch` page. Unfortunately, this means that users cannot view comments if they have Javascript disabled.

Likely through a config option, (or if it's possible to redirect users with Javascript disabled) users would be directed to a page that loads everything initially, which will result in higher load time but allow users to view more content on the page without JS.

_Originally posted by @Jtasiu in https://github.com/omarroth/invidious/issues/132#issuecomment-428531049_

**Comment by omarroth** [comment]
Added with 19516ea. It will respect a user's preferred comments. Some information is currently missing, which will be added soon with a refactor most likely.

**Comment by Jtasiu** [comment]
Thanks @omarroth. Wondering how to use this..do I add `&nojs=1` into the url?

**Comment by omarroth** [comment]
Yep, that should work fine. If you have JS disabled you should also see a message like this:
![image](https://user-images.githubusercontent.com/14208607/47959417-a5e12000-dfb1-11e8-946c-77dd3a723c98.png)

and clicking will add `&nojs=1`.

**Comment by Jtasiu** [comment]
I noticed clicking view replies doesn't show the reply comments. I'm guessing it's a bug or maybe it's something that will be part of the refactor?

**Comment by omarroth** [comment]
Replies are normally loaded with JS as well, although hopefully it will be possible to load them initially after a refactor. Whatever the case I will be sure to provide an update here.

**Comment by omarroth** [comment]
Keeping this closed in favor of #409.
