### ISSUE TITLE
Private feed not working

### ISSUE THREAD

**Issue by MatiasConTilde** [omarroth/invidious#208]
In Firefox, `https://invidio.us/feed/private?token=notgonnatellyou` looks like this:
![image](https://user-images.githubusercontent.com/7951833/47239125-bbb4e980-d3e4-11e8-8e4a-009710119f0d.png)

In other readers (I've tried Feeder and Flym on Android) it also doesn't work.

Inspecting the source, it looks like it's working on the server side, so I thought maybe it's a wrong format that isn't parsed correctly:
```
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <link type="text/html" rel="alternate" href="https://invidio.us/feed/subscriptions"/>
  <link type="application/atom+xml" rel="self" href="https://invidio.us/feed/private?token=notgonnatellyou"/>
  <title>Invidious Private Feed for someone</title>
  <entry>
    <id>yt:video:dQw4w9WgXcQ</id>
    <yt:videoId>dQw4w9WgXcQ</yt:videoId>
    <yt:channelId>UC38IQsAvIsxxjztdMZQtwHA</yt:channelId>
    <title>Rick Astley - Never Gonna Give You Up (Video)</title>
    <link rel="alternate" href="https://invidio.us/watch?v=dQw4w9WgXcQ"/>
    <author>
      <name>RickAstleyVEVO</name>
      <uri>https://invidio.us/channel/UC38IQsAvIsxxjztdMZQtwHA</uri>
    </author>
    <published>2009-10-24T00:00:00+00:00</published>
    <updated>2009-10-24T00:00:00+00:00</updated>
    <media:group>
      <media:title>Rick Astley - Never Gonna Give You Up (Video)</media:title>
      <media:thumbnail url="/vi/dQw4w9WgXcQ/mqdefault.jpg" width="320" height="180"/>
    </media:group>
  </entry>
</feed>
```
Maybe this is a client problem, but if such mainstream readers don't support that format, maybe it should be changed from Atom to something more supported? I have no idea about RSS feeds so I'm just guessing

**Comment by omarroth** [comment]
I modeled it almost entirely after Github's private feed, which appers to be expected, so I can only assume there's some breaking difference. I haven't tested it much, but my feed feed appears to work as expected with [Akregator](https://userbase.kde.org/Akregator), [The Old Reader](https://theoldreader.com) (likely the most popular platform), and [Feedly](https://feedly.com).

Unfortunately, Mozilla is [discontinuing support for RSS and Atom feeds](https://goodereader.com/blog/digital-publishing/firefox-is-going-to-get-rid-of-rss-and-atom-feeds), so it's unlikely to be supported. Discussion on HackerNews [here](https://news.ycombinator.com/item?id=18202028).

**Comment by omarroth** [comment]
I don't have an Android device to test on, but the web version of [Feeder](https://feeder.co) appears to work as well, so I think this is likely a client problem.

I'm going to close this for now just because of inactivity, but feel free to reopen with any other details if it's still not working for you.
