### ISSUE TITLE
Add option for user to import/export their data.

### ISSUE THREAD

**Issue by omarroth** [omarroth/invidious#21]
For folks who want to run their own instance, they should be able to export subscriptions, preferences, etc and upload to their own instance. Should also be able to migrate subscriptions/preferences e.g. from Google to Invidious account, and vice versa.

**Comment by xKeiro** [comment]
Not sure if possible, but it would be awesome if you could import/export and merge your data from [Newpipe](https://newpipe.schabi.org/) as well!

**Comment by xKeiro** [comment]
@omarroth 
This is exactly how it exports (I didn't zip it it was zipped already):
[NewPipeData-20180728_173624.zip](https://github.com/omarroth/invidious/files/2238086/NewPipeData-20180728_173624.zip)

**Comment by omarroth** [comment]
Subscriptions-only look easy enough.
 It looks like watch history is included in the first export though, so I think I'll close #40 before tackling it. 

Looks like NewPipe uses the OPML file from YouTube, so Invidious can just export that.
