### ISSUE TITLE
'Default to Listen mode' setting

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#210]
Sometimes I'm using Invidious to listen to music.
I usually search for the song I want to listen to, but I'm not interested in the video, so I go to listen mode.
It takes an extra click on every video to achieve that.

It would be useful to have a "Default to Listen mode" checkbox in the preferences to skip video mode, and go to listen mode by default.
Of course I should still be able to switch back to video mode via the button on the page.

**Comment by holkaa** [comment]
Hello please write me you facebook adress

**Comment by omarroth** [comment]
Added with e39dec9.

**Comment by Discookie** [comment]
Good stuff, thank you!
