### ISSUE TITLE
Please help me Omarroth

### ISSUE THREAD

**Issue by holkaa** [omarroth/invidious#211]
Please help me Omarroth.Please wirte me you facebook or email adress. I cannot install this

**Comment by holkaa** [comment]
I ready donate to your projects

**Comment by holkaa** [comment]
My fb adress https://www.facebook.com/aqsin.allahevrediyev

**Comment by holkaa** [comment]
i install this script but not work http://162.208.11.144/

**Comment by holkaa** [comment]
Why no reply me ?

**Comment by omarroth** [comment]
I provided instructions for Ubuntu in #209, which I believe answers your original question. If you have any other issues installing or running the project, feel free to send an email to omarroth@hotmail.com or omarroth@protonmail.com . 

Please don't open multiple issues for the same problem. I'll make sure to add instructions for Ubuntu to the README. In the meantime, I'm closing this in favor of #209.
