### ISSUE TITLE
Videos don't load - missing hash key

### ISSUE THREAD

**Issue by Wittmaxi** [omarroth/invidious#214]
When I try to watch a video, say this one : https://www.invidio.us/watch?v=U41VfSy93kg, I am not shown any real content, instead I get the message " Missing hash key: "view_count" ". This happens for every video.

i'm using TOR, with the current version hosted at invidio.us.

Given that It ran well earlier, I can speculate a bit about what happened.
-Either, youtube added / removed (former is more likely) a key to something that invidious can't parse
-Or, invidio.us was updated and now it doesn't work. 

Good luck fixing the bug!

-Maxi

**Comment by omarroth** [comment]
You hit the nail on the head. YouTube moved a couple things around internally that weren't quite expected. Fixed with c92f6e4.

**Comment by Wittmaxi** [comment]
The error is gone. However, now I get a 500 server error

**Comment by Wittmaxi** [comment]
not anymore. Works!
