### ISSUE TITLE
invidious generates invalid HTML

### ISSUE THREAD

**Issue by Wittmaxi** [omarroth/invidious#218]
Having built invidious myself, I have looked into the HTML code generated by it with Firefox.
The last body tag is highlighted in red (which signifies an error) and on hovering I get the message "Body tag was found but prior unclosing tags were found" (shaky 7:41 am translation)

**Comment by Wittmaxi** [comment]
![the on-hover-message](https://user-images.githubusercontent.com/16443184/47981983-de721e00-e0c5-11e8-93ab-fb037c87e2c5.png)

**Comment by omarroth** [comment]
Hm, that's interesting, is there a specific page where this is encountered?

**Comment by Wittmaxi** [comment]
It was on the main page (localhost:3000)

**Comment by omarroth** [comment]
Whoops, thought I already commented here. Should be fixed with 1dcca858198ac99f3745b573e5ab82cbd14c4f06.

**Comment by Wittmaxi** [comment]
perfect!
