### ISSUE TITLE
Error 504 on empty parameter 'v=' in URL

### ISSUE THREAD

**Issue by jlgrall** [omarroth/invidious#219]
For URLs like:
- https://invidio.us/watch?v=
- https://invidio.us/watch?listen=1&v=

I get an error 504 after ~1 minute:
> # 504 Gateway Time-out
> The server didn't respond in time.

This happens when I incorrectly copy-paste the YouTube video id to the URL. It doesn't bother me, but I hope that it doesn't consume too much server resources.

**Comment by omarroth** [comment]
Thanks! Should be fixed with 9e022f3b04ca5edc3922b1d31624a21b85e2ba04

**Comment by jlgrall** [comment]
It is working. Good job.

Now maybe it would be better to show a message about invalid parameter instead of redirecting to the homepage.

Maybe the same message as with an invalid parameter: https://invidio.us/watch?v=_

This way it is easier to edit the url and add the missing value without needing to rewrite it entirely. Also if the url was generated automatically, it would make it easier to find the problem because the user would see an error message that he can report.

_Note: in PHP [How do I check if a $_GET parameter exists but has no value?](https://stackoverflow.com/questions/12503364/how-do-i-check-if-a-get-parameter-exists-but-has-no-value/12503504#12503504)_

**Comment by omarroth** [comment]
I was just following what YouTube does, but I agree showing an error would be more helpful.

**Comment by omarroth** [comment]
Updated with 570e093.

**Comment by jlgrall** [comment]
Nice. Working great.

**Comment by omarroth** [comment]
Should be fixed with df7480b.

**Comment by Jtasiu** [comment]
Thanks, working now.
