### ISSUE TITLE
[FEATURE REQUEST] Exposed API

### ISSUE THREAD

**Issue by Wittmaxi** [omarroth/invidious#220]
I think that it would be benefitial for invidious to have an exposed API that way other youtube clients don't have to do all the heavy DRM grinding etc. 

I only see a few objections:
1) too high server load generated by that
2) some legal threat by youtube
3) the current architecture doesn't accomodate that

PS: I'd be willing to work on that API a bit

**Comment by omarroth** [comment]
See [here](https://github.com/omarroth/invidious/wiki/API) :). Already used by [FreeTube](https://github.com/FreeTubeApp/FreeTube) and [CloudTube](https://github.com/cloudrac3r/cadencegq), although it could be made more visible.

**Comment by Wittmaxi** [comment]
Looks like we can close that issue
