### ISSUE TITLE
Search results problem

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#221]
It's hard to distinguish videos from playlists in the search results. 

For instance, playlists' thumbnails should not have video duration:

![](https://i.imgur.com/CJalkH8.png)

Probably you can add a "playlist mark" (and the number of videos) instead. This is what YouTube does.

![](https://i.imgur.com/a3aeO6G.png)

**Comment by omarroth** [comment]
Fixed with 316a73f07e08de179cdaed89bbfdb0b9a3c32604. I'll probably add the playlist mark in a subsequent commit.

**Comment by omarroth** [comment]
Moved video count into thumbnail with b535de690e494aeb38ecb9db57ee173dd896bdb2.
