### ISSUE TITLE
Comment timestamps don't respect other page settings

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#226]
Example: lil walrus's comment on https://invidio.us/watch?v=GsbU-KTSNf4&list=RDhYzr3wWtWrs&listen=1&autoplay=1&speed=1.0

![image](https://user-images.githubusercontent.com/16914176/48259229-a47f7f80-e417-11e8-98fd-3861ce7e3855.png)

**Comment by Discookie** [comment]
It's fixed indeed for JS comments!

Although, for No-JS comments, nothing's respected - not even the `&nojs=1` param.  
Not sure timestamps would work without JS anyway.

**Comment by omarroth** [comment]
Timestamps do not work without JS unfortunately. There is actually a fallback included for nojs that opens a new page (with the timestamp applied), but since that is non-functional, it can be removed.
