### ISSUE TITLE
[FEATURE REQUEST] autoplay in non-playlists

### ISSUE THREAD

**Issue by Wittmaxi** [omarroth/invidious#230]
There should be an autoplay mode that automatically plays the top most recommended video, kinda like the youtube autoplay

**Comment by Discookie** [comment]
+1!
I'd recommend optionally playing a Mix instead, when available. Mixes usually have more relevant videos.

**Comment by Wittmaxi** [comment]
well yea, but i can't always rely on mixes. sometimes I just want to have invidious play music in the background - without caring where it will take me

**Comment by omarroth** [comment]
Agreed, see #192.

**Comment by omarroth** [comment]
Added with 4b76b93.
