### ISSUE TITLE
Controls not available if video cannot be loaded.

### ISSUE THREAD

**Issue by elypter** [omarroth/invidious#236]
please do not make the controls disappear if the video file cannot be loaded. another quality or encoding might work but it is impossible to select it without the controls.

**Comment by omarroth** [comment]
This appears to be a limitation in [video.js](https://github.com/videojs/video.js), and as far as I know there's not much that can be done to change it. I'd be very happy to be proven wrong though.

**Comment by elypter** [comment]
i posted an issue on their github https://github.com/videojs/video.js/issues/5597

**Comment by omarroth** [comment]
You might also take a look at #90 and #92. It appears the issue you're having is that sources are failing to load, rather than that they are unsupported. Would you mind opening dev tools and seeing if any errors are being reported? I expect there's something like a 403 when attempting to play some videos.

**Comment by elypter** [comment]
yes, i often have errors with videos that should work. https://dev.invidio.us/watch?v=9vYdfsy4l5Y for example gives me a 403 error

**Comment by omarroth** [comment]
You might try proxying streams by changing your `preferred preferences` to `dash`, see [#187](https://github.com/omarroth/invidious/issues/187#issuecomment-425289121) or [#34](https://github.com/omarroth/invidious/issues/34#issuecomment-424171888) for more info.

**Comment by elypter** [comment]
unfortunately the pc is too slow for anything above 480p

**Comment by omarroth** [comment]
I don't have an immediate solution for that unfortunately. In the future I expect all streams to be proxied (including 480p), which I expect will solve your problem.

**Comment by elypter** [comment]
this sounds great but doesnt this use up enormous amounts of bandwidth?

**Comment by omarroth** [comment]
That's why it's currently only opt-in. I'd like to roll it out quite slowly so that any issues (like with bandwidth) can be addressed.

**Comment by elypter** [comment]
they replied to the report and said a dead player can be prevented with error handling

https://github.com/videojs/video.js/issues/5597#issuecomment-439270522

**Comment by omarroth** [comment]
Sounds good. I think you can close that issue then, and I can work on adding it.

**Comment by omarroth** [comment]
Rather, I meant to close videojs/video.js#5597 in favor of this issue.

**Comment by elypter** [comment]
oh, sure

**Comment by omarroth** [comment]
Added some extra handling with b38a2bbd127fc787216e4722f2dc6a720abda415 and ff09a7255ac03dfd7d828aaaf872b263c4c9cee4, which should close this.
