### ISSUE TITLE
"Server Not Found"

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#238]
i see "Server Not Found" a lot these days

**Comment by omarroth** [comment]
That's really strange. Could you provide a screenshot if possible?

**Comment by EsmailELBoBDev2** [comment]
![bandicam 2018-11-17 23-44-07-925](https://user-images.githubusercontent.com/28893833/48666039-f8423680-eab1-11e8-832f-c5419dbd9cdc.jpg)

**Comment by omarroth** [comment]
I can replicate using an Egypt proxy. Connecting to http://invidio.us produces the expected response (redirect to https://), while connecting to https://invidio.us fails.

My guess is based on [this](https://ooni.torproject.org/post/egypt-network-interference/) article which would suggest heavy throttling of HTTPS connections to DigitalOcean data centers. From the article:
>As part of our research we found that one way to consistently reproduce a network interference is by sending HTTPS requests to the network sub-nets belonging to DigitalOcean’s Frankfurt data center (including, but not limited to 46.101.128.0/24, 46.101.172.0/24, 46.101.179.0/24 — AS201229). Our experiment showed consistent and heavy throttling of HTTPS services located in the network: only 3% of TCP connection attempts succeeded.
>
>Our latency analysis suggests that all the packets that the client was receiving were timeout-based TCP re-transmissions and that a network device was consistently dropping the first occurrence of each TCP packet.

Although I'm not entirely sure why it would only be throttled during a certain time of day.

**Comment by EsmailELBoBDev2** [comment]
so i must replace https:// with http:// when the website get down for me right ?

**Comment by omarroth** [comment]
Unfortunately, it looks like you cannot watch videos without HTTPS, so I would recommend using a VPN.

**Comment by EsmailELBoBDev2** [comment]
@omarroth fortunately, it looks like your website works fine, thx for trying help btw ;)
