### ISSUE TITLE
README.md, Liberapay, and Patreon description confusion.

### ISSUE THREAD

**Issue by zipline808** [omarroth/invidious#247]
In the README.md and the Liberapay and Patreon descriptions of Invidious the first feature listed in the feature list is *"Audio-only (and no need to keep window open on mobile)"*, which might be confusing to some who are unfamiliar with Invidious. It makes it sound like Invidious is an audio only thing, when what it meant is that there is an audio only mode. 

I suggest changing that feature list entry from:
- Audio-only (and no need to keep window open on mobile)

to:

- Audio-only mode (and no need to keep window open on mobile)

**Comment by omarroth** [comment]
Agreed, fixed with b10794bc64fd1351bd91a60724e4d096eaa526b0, and I'll update the descriptions on Liberapay and Patreon to match.
