### ISSUE TITLE
Invidious is not respecting my config.yml

### ISSUE THREAD

**Issue by DUOLabs333** [omarroth/invidious#2473]
I used Docker to set up an Invidious instance. However, when I ran `docker-compose up`, it's only available from port 3000, even tough in my config.yml, I specified port 8080.

**Comment by unixfox** [comment]
If you are using docker we recommend using the INVIDIOUS_CONFIG env instead of the config.yml file.

**Comment by unixfox** [comment]
Issue resolved then?

**Comment by DUOLabs333** [comment]
Since there seems to be no way around it, I guess I'll close this now.
