### ISSUE TITLE
Option to hide Watched button

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#248]
It would be nice to have an option to hide that button, as I have no use for it, and it's kind of obnoxious.

Also apparently the video title is not clickable any more on the subscriptions page.

**Comment by omarroth** [comment]
Titles should be fixed with d6d73bd33630add1ff0d114fd468685ce88c3795. I also shrank the icon a bit with 60c6778344c647ef0ebec58624f03926fdaf25fc.

I might consider hiding the icon unless the user has `unseen_only` enabled.

**Comment by Discookie** [comment]
Thanks, it's much more managable now.
