### ISSUE TITLE
[Bug] Role "kemal" does not exist

### ISSUE THREAD

**Issue by JimDude7404** [omarroth/invidious#2485]
**Describe the bug**

**Steps to Reproduce**
!-- Steps to reproduce the behavior:
1.  Follow the installation guide
2. When trying to run you get "postgres_1   | 2021-10-09 11:14:55.553 UTC [968] FATAL:  role "kemal" does not exist"

**Logs**

postgres_1   | 2021-10-09 11:14:55.553 UTC [968] FATAL:  role "kemal" does not exist

**Screenshots**

**Additional context**

**Comment by Skeppy14pinecone** [comment]
**Steps to Reproduce**

**Comment by Skeppy14pinecone** [comment]
I am using the docker installtion method. I follow everything inside of the install guide exactly. Its hosted on OVH and I used their preinstalled docker image. and everything seems to work except for the database entirely doesn't work. it just gives me that error

**Comment by SamantazFox** [comment]
Can you replace, in the `docker-compose.yml` file, the line:
`       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]`

with:
`       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]`

**Comment by SamantazFox** [comment]
> [SNIP]
> It then stops after that
> 
> yep, that's all good, then! click on the URL at the bottom and you'll see invidious!

**Comment by SamantazFox** [comment]
> Do u know how to expose another port or smth idk how

By default, it restricts the port to 127.0.0.1 because most users will either use it locally or have a reverse proxy like nginx.

You can replace those lines:
```yaml
    ports:
      - "127.0.0.1:3000:3000"
```

with
```yaml
    ports:
      - "3000:3000"
```

to achieve what you want

**Comment by Skeppy14pinecone** [comment]
k thank u

**Comment by SamantazFox** [comment]
@Skeppy14pinecone you're welcome :)
