### ISSUE TITLE
Website not optimized with search engines

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#249]
when i search on google ,duck duck go & start page by "invidio" i don't find the website but when i search by "invidio.us" (which mean search by whole link) i find the website so you can make search engines find your website like hook tube, free tube & you tube (without typing whole link) ?

**Comment by cloudrac3r** [comment]
It's because the website is not called "invidio". It's called "invidious". Naturally, since Invidious is a dictionary word, definitions of the word rank highly in search results. The website is the 8th link on DDG, and the first non-definition link. I don't think any work needs to be done.

**Comment by EsmailELBoBDev2** [comment]
i mean owner add tags or something to make a easy way to find

**Comment by omarroth** [comment]
Added description to the homepage with 568e55d, but I agree there's not much else to be done in regards to SEO.

**Comment by EsmailELBoBDev2** [comment]
i tried searching with your tags & still with no luck
