### ISSUE TITLE
[Bug] "Uncaught type error: nextVideo is null" at the end of a playlist since new playlist fix (https://github.com/iv-org/invidious/pull/2257)

### ISSUE THREAD

**Issue by FranciscoPombal** [omarroth/invidious#2500]
**Describe the bug**

After the last video of a playlist, no video will play next because of a null dereference.
If there are no remaining videos in a playlist, `nextVideo` should be set to some other "related" video when the option "Play next by default" is active.

**Steps to Reproduce**
1. Go to a playlist in an instance that has the patches from https://github.com/iv-org/invidious/pull/2257 applied.
2. Wait until the next video (or go directly to it, the URL should look like `https://<host>/watch?v=<video_id>&list=<playlist_id>&index=<length(playlist) - 1>`).
3. The error will occur a short while after the page of the last video of the playlist loads, as code in `watch.js` is executed.
4. Check the stack trace in the browser console (see also the example in the `Logs` section below).

**Logs**

Here is the stack trace obtained from reproducing the bug on the [vid.puffyan.us](https://vid.puffyan.us) public instance, which reported version `2021.10.11-39c27f0c @ master` at the time of writing:

```
TypeError: nextVideo is null
    onreadystatechange https://vid.puffyan.us/js/watch.js?v=f13fb80b:153
    get_playlist https://vid.puffyan.us/js/watch.js?v=f13fb80b:148
    <anonymous> https://vid.puffyan.us/js/watch.js?v=f13fb80b:452
    EventListener.handleEvent* https://vid.puffyan.us/js/watch.js?v=f13fb80b:450
    watch.js:153:17
    onreadystatechange https://vid.puffyan.us/js/watch.js?v=f13fb80b:153
    (Async: EventHandlerNonNull)
    get_playlist https://vid.puffyan.us/js/watch.js?v=f13fb80b:148
    <anonymous> https://vid.puffyan.us/js/watch.js?v=f13fb80b:452
    (Async: EventListener.handleEvent)
    <anonymous> https://vid.puffyan.us/js/watch.js?v=f13fb80b:450
```

**Additional context**

 - Browser: Firefox 93.0, but it should be reproducible on any browser.

**Comment by SamantazFox** [comment]
I can't seem to reproduce. Could you please provide a video where that happens?
