### ISSUE TITLE
Want Help By Translating!

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#251]
i want translate website into AR but i searched in your project files & i didn't find single word xD so can you help me how/where find words to translate it ?

**Comment by omarroth** [comment]
I would definitely appreciate it! I haven't pulled out any of that info yet unfortunately. See #180, and I'll let you know when it's ready for translating.

**Comment by EsmailELBoBDev2** [comment]
already saw it :P & i didn't find `locales/en-US.json` & ok i will be right here wating

**Comment by omarroth** [comment]
Added `en-US.json` with d211d8fc05bdfa95377ec37bbde5929e57b9f507. Feel free to hop on the [FreeTube Matrix Server](https://riot.im/app/#/room/#freetube:matrix.org) (if you haven't already) or email me privately if you have any questions on how to translate things.

**Comment by EsmailELBoBDev2** [comment]
oh wow alot of words xD & what you did with your website close at night in my country ?

**Comment by omarroth** [comment]
Haha, don't feel the need to translate everything. Probably pushing changes for the day, although there shouldn't be any downtime while that's happening, so it's strange if that's what you're experiencing.

**Comment by EsmailELBoBDev2** [comment]
that what i have rn, its get down at 5PM & get up at 12 AM

**Comment by EsmailELBoBDev2** [comment]
& translate 2 raws of first raw or second raw only ?

**Comment by omarroth** [comment]
Just the second.

**Comment by elypter** [comment]
made a german translation https://pastebin.com/w1v6pvtk

**Comment by omarroth** [comment]
Invidious has been approved for hosting by Weblate, see https://hosted.weblate.org/translate/invidious :tada:

**Comment by elypter** [comment]
the link gives me a 404. this one works however https://hosted.weblate.org/projects/invidious/

**Comment by EsmailELBoBDev2** [comment]
@omarroth i already translated half file, i not want translate it again ._.

**Comment by omarroth** [comment]
It is the number of people that liked a video / number of people that viewed a video. Synonyms might be "participation percent". Hopefully that helps.

**Comment by EsmailELBoBDev2** [comment]
well, take this (the new file with that strange word translated): https://upload.vaa.red/27uYSy#c99a95b85a70c8686b986619f59fc806 & when translation will release ?

**Comment by dimqua** [comment]
Liked + disliked, I suppose.

**Comment by omarroth** [comment]
It's hard to say, but I expect to have them supported within the next 2 weeks. If anything changes I'll be sure to mention here.

**Comment by omarroth** [comment]
Added support for translations with a160c645c9c6299553a7cc0c89e5182f5d1288bb. You can change your preferred language in preferences, or add `hl=LOCALE` to the end of any request, for example https://invidio.us/?hl=ru, where `LOCALE` is any of: `ar`, `de`, `en-US` (default), `nl`, `pl`, or `ru`. Currently they are case sensitive, so https://invidio.us/?hl=RU will not work.

If there are any errors in the translations feel free to edit them on [Weblate](https://hosted.weblate.org/projects/invidious/translations/), or edit the [files directly](https://github.com/omarroth/invidious/tree/master/locales) and open a PR.

I think I'll close this since support for translations has been added. If anyone has questions on how to translate anything, feel free to contact me [here](https://riot.im/app/#/room/#freetube:matrix.org) or email at omarroth@protonmail.com or omarroth@hotmail.com.

Thank you so much to everyone for helping to translate the site!

**Comment by elypter** [comment]
just a few things i discovered when using a translation:

the "search" in the search bar does not change according to the selected language.

times like "4 days" are also not translated and "Language:" and "Fallback comments:" in the settings english only as well.

**Comment by dimqua** [comment]
@elypter do all languages affected?

**Comment by omarroth** [comment]
I expect so. I mentioned elsewhere, but translation logic, such as forming dates and pluralizing words, hasn't been implemented yet. 

Added missing translations with a5af6f49564d4df2096727b726d138bbd420fb49.

**Comment by EsmailELBoBDev2** [comment]
1. come on @omarroth, you didn't tell me you added new words
2. what " Fallback comments " mean ?

**Comment by EsmailELBoBDev2** [comment]
it's first time for me to do a "pull request" so forgive me if i did something wrong + i updated my translation file :smile:

**Comment by elypter** [comment]
you can watch a project in weblate and you can chose to be informed when a new translation string is added https://hosted.weblate.org/accounts/profile/#subscriptions

those notifications are sent via email

**Comment by elypter** [comment]
if you dont want to use that service you have to watch the commits

**Comment by Perflyst** [comment]
We know have AR in locales: https://github.com/omarroth/invidious/blob/master/locales/ar.json
Is this issue "fixed"? I see some discussion here which is not releated to the issue. Maybe join some rooms which are listed in readme: https://github.com/omarroth/invidious/#contact

**Comment by EsmailELBoBDev2** [comment]
@Perflyst who are you ? & what you want from AR file ?

**Comment by Perflyst** [comment]
I just wondered if this issue isn't already solved.

**Comment by EsmailELBoBDev2** [comment]
@Perflyst wow you online xD & tbh idk, you can ask @omarroth

**Comment by omarroth** [comment]
Looks like everything is resolved as mentioned [here](https://github.com/omarroth/invidious/issues/251#issuecomment-449175480).
