### ISSUE TITLE
Filter by text and date on channel page.

### ISSUE THREAD

**Issue by zipline808** [omarroth/invidious#255]
I think it would be good if we could apply a text filter and/or a date filter to a channel.

For example: `/channel/UCB_qr75-ydFVKSF9Dmo6izg?filter=team+radio`
This would show only videos containing the filter words for that channel.

And: `/channel/UCB_qr75-ydFVKSF9Dmo6izg?date-from=DDMMYY`, or `/channel/UCB_qr75-ydFVKSF9Dmo6izg?date-to=DDMMYY`, or `/channel/UCB_qr75-ydFVKSF9Dmo6izg?date-from=DDMMYY&date-to=DDMMYY`
These would show videos that were published by the channel after a specific date, before a specific date, or between two specific dates respectively.

**Comment by Discookie** [comment]
You can use the search bar to do that, as in #126, although I've been having issues with it.

For example: when I type `channel:UCB_qr75-ydFVKSF9Dmo6izg team radio`, it shows no results, but when I type `channel:formula1 team radio`, it shows the results correctly.  
Apparently the `channel` filter is broken for long channel names?
