### ISSUE TITLE
Video not loading: Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by jeroen7s** [omarroth/invidious#265]
Some video's just don't seem to load properly
when i check the dev console in chrome it shows:
Failed to load resource: the server responded with a status of 403 ()
on fetching the googlevideo.com URL
when on youtube, the video loads perfectly fine

**Comment by omarroth** [comment]
Mind providing an example? Also see #90.

**Comment by jeroen7s** [comment]
https://invidio.us/watch?v=Vs2StGdkGGI
seems like i missed that issue
can confirm it's the same issue, video works when connecting over a VPN server in US
