### ISSUE TITLE
[Subscription] Channel doesn't appears in "Manage my subscriptions" despite being subscribed

### ISSUE THREAD

**Issue by GauthierPLM** [omarroth/invidious#266]
I subscribed to the channel [Paul Taylor](https://invidio.us/channel/UC9pVaOtZ8vdLBrlHu5xaaOA) but the last videos doesn't appear in my feed nor in my subscription list (despite being marked as subscribed).

Is there any limits on the number of channels I can subscribe to (manager page says I subscribed to 40 channels but this number isn't updated when I subscribe/unsubscribe to the channel above) or is it something else ?

**Comment by Discookie** [comment]
It's starting to update now.

It usually boils down to database issues, also see #207.

**Comment by omarroth** [comment]
The above channel appears to have a different name in subscription feed ("What's Up France ?") than it does in on the channel page. Likely a bug in the channel extractor.

**Comment by GauthierPLM** [comment]
What's up France ? is the old name of the channel, that changed few months ago.

**Comment by omarroth** [comment]
Should be fixed with 843606db658609483824f2a88dd077b2d2d68b29.

**Comment by omarroth** [comment]
The channel mentioned appears to be updated in my subscriptions, as well as a couple others whose names have changed, so I'm going to close this. If it's still an issue, feel free to mention here or open a new issue.

**Comment by 2a747** [comment]
I have the same problem with a few channels. For example all videos of these channels do not appear in my subscription feed:

https://invidio.us/channel/UCv0j-6tXIlnxmOu9FA3qFtw
https://invidio.us/channel/UCB1FbokreuwgEpAHDEi7kOA

**Comment by omarroth** [comment]
If you're still encountering this, would you mind opening a new issue? I believe you may be encountering a different problem, and I can't find any problems with the channels you mentioned that might be causing the issue. Are they missing from `/subscription_manager`, as they were for Gauthier?
