### ISSUE TITLE
[feature request] Redirect to main page on empty search

### ISSUE THREAD

**Issue by Stypox** [omarroth/invidious#274]
I use Firefox so I added the keyword "yt" to search on invidio.us. Sometimes I just need to go to the homepage, so I do an empty search (i.e. I write in the search bar "yt" followed by nothing, as I used to do with youtube.com). But in invidious it doesn't work: I get an [empty page](https://www.invidio.us/search?q=&page=1).
It would be useful if an empty search redirected to the main page (i.e. invidio.us), just like youtube.com does.

**Comment by omarroth** [comment]
Added with 2fdf3d24e3443da9888b7fc4ddd33d4072edcdcb.

**Comment by Stypox** [comment]
Thank you, it works as expected now :-)
