### ISSUE TITLE
Hardware donations?

### ISSUE THREAD

**Issue by elypter** [omarroth/invidious#279]
Do you have need for hardware donations? Something you could use for the project or just personally. People might have hardware that is just sitting in a corner and are more willing to donate this instead of money. in what country do you live? - so people know if shipping makes sense.

**Comment by TylerHobanDotCom** [comment]
@omarroth is hosting this on cloud services. I don't know if hardware would help him much. I would still suggest you ask him though.

**Comment by omarroth** [comment]
That's very kind. I don't believe I have a need for hardware donations, since as mentioned I'm using DigitalOcean to host the site. Anything that is donated I would like to go directly to supporting the project, so I don't plan on accepting hardware.

**Comment by TylerHobanDotCom** [comment]
<s>hey since this isn't closed yet if you have hardware i can use it</s>
