### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by MegaArthur** [omarroth/invidious#28]
It would be nice for the site to have a dark theme option

**Comment by omarroth** [comment]
Already been added, should be able to enable it in your preferences.

**Comment by MegaArthur** [comment]
Does editing preferences require a log-in?

If so, it'd be nice if it was possible to edit them without logging in, probably by just setting a cookie/DOM Storage, (like startpage.com does it) with the appropriate warning, of course.

**Comment by omarroth** [comment]
Absolutely! Do you mind opening that as a new issue?

**Comment by dimqua** [comment]
I think this issue can be closed for now.
