### ISSUE TITLE
500 Error on Every Video

### ISSUE THREAD

**Issue by ewdissi** [omarroth/invidious#282]
Hi,

since today i get an 500 error on every video:
https://tube.latz.it/watch?v=0I647GU3Jsc

-->
2019-01-11 14:36:44 +01:00 200 GET /favicon-16x16.png 57.0µs
Exception: Missing param name: "avg_rating" (KeyError)
  from /usr/share/crystal/src/indexable.cr:444:19 in '[]'
  from src/invidious.cr:396:12 in '???'
  from lib/kemal/src/kemal/route.cr:255:3 in '->'
  from lib/kemal/src/kemal/route_handler.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from lib/kemal/src/kemal/static_file_handler.cr:0:18 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???

2019-01-11 14:36:53 +01:00 500 GET /watch 29.94ms
<--

Any Ideas? Any logs i can provide you?

Regards dissi

**Comment by omarroth** [comment]
I actually fixed it yesterday. You'll need to pull and rebuild.

**Comment by ewdissi** [comment]
works :) Thanks

**Comment by omarroth** [comment]
https://invidio.us runs master. The breaking change from YouTube is fixed with 138a6b1. I tagged that commit with 0.13.1 and marked it as the latest stable release if you would like to use the release tags. 

Not many people have hosted their own instances yet, There's lots that can still be improved so it's easier for them to do so.

Each major release is generally the 5th of each month.
