### ISSUE TITLE
Hide watched videos from front page

### ISSUE THREAD

**Issue by tmiland** [omarroth/invidious#285]
Hi, 

i was wondering how i can hide watched videos from my account from public view on the front page?

Running my own instance. 

*Edit

Nevermind. 

Regards.

**Comment by Perflyst** [comment]
How did you solved this?

**Comment by tmiland** [comment]
> How did you solved this?

Hi, i "solved" it by removing the links from "/views/index.ecr"

Changed to: 

`<% content_for "header" do %>
<meta name="description" content="<%= translate(locale, "An alternative front-end to YouTube") %>">
<title>Invidious</title>
<% end %>

<div class="h-box pure-g">
    <div class="pure-u-1-4"></div>
</div>`

Only problem is, it can still be viewed by accessing the url's. 

Let's hope it can be added as an option to turn it off in the future.

Regards.

**Comment by Perflyst** [comment]
This is a hacky solution and not really nice. An option to configure this would be better as described in #294

**Comment by Perflyst** [comment]
For anyone who reads this in the future, the file is located at `invidious/src/invidious/views/index.ecr`

**Comment by tmiland** [comment]
> This is a hacky solution and not really nice. An option to configure this would be better as described in #294

Of course it's not nice. Nothing but a temporary "solution" 🤓

**Comment by omarroth** [comment]
Closing in favor of #294.
