### ISSUE TITLE
[Enhancement] Show Youtube channel verification

### ISSUE THREAD

**Issue by jonas-w** [omarroth/invidious#2857]
> I found no other issue with this being asked.  

**Is your enhancement request related to a problem? Please describe.**

Maybe it's not wanted in Invidious. But I miss the verification check mark next to comments or on the channel page. But Maybe I'm the only one.

**Describe the solution you'd like**

Add the youtube channel verification check mark to the comments and next to the channel.

**Describe alternatives you've considered**

Adding own Invidious verification check marks (e.g. Verified FOSS Content Creator, ...)

**Additional context**

> If this isn't wanted in Invidious i can understand that. I just want to know the reasons why it doesn't exist till now.

**Comment by unixfox** [comment]
This seems like a very simple feature to implement, would you be interested to contribute?

**Comment by jonas-w** [comment]
Yes I would be interested. But I'm not familiar with the invidious codebase and crystal language. Is it complicated to get into it?

**Comment by unixfox** [comment]
It's not that complicated. If you like programming, you will like programming in crystal.

Here is the documentation for installing Invidious locally: https://docs.invidious.io/Installation.md and how to contribute: https://github.com/iv-org/invidious#contribute

We can also try to help you to get into it, we have : 
- a matrix channel: https://matrix.to/#/#invidious:matrix.org
- an IRC channel: https://web.libera.chat/?channel=#invidious

**Comment by jonas-w** [comment]
Could the docs be outdated. I'm currently going through the manual installation. I'm using Manjaro (sorry im lazy) and on the "Setup Postgresql" Part i get permission denied on e.g. `psql invidious kemal < /home/invidious/invidious/config/sql/channels.sql`. I Solved this by using the invidious user. 
And in the shards update and install part i needed to use root priviliges because it got permission denied on "/home/manjaro/bin/pkg-config". And also the compiling part is only working on root priviliges.

**Comment by unixfox** [comment]
It's probably because we assume the user is running in root, which to be fair we shouldn't assume that.

If you think the documentation should be adapted, then you can submit some modifications on this file: https://github.com/iv-org/documentation/blob/master/Installation.md 😃.

**Comment by jonas-w** [comment]
But in the docs you assume that the crystal commands get executed by the user invidious because of the `sudo -iu invidious`. Or did i oversee something?

**Comment by unixfox** [comment]
Oops sorry, you are right. The one time I used the documentation for installing manually way ages ago and back then IIRC it assumed you used root, so that's why I thought it was still the case.

**Comment by jonas-w** [comment]
Okay good that the documentation will be updated. 
I got it working on the channels view page to be displayed like this:
![Screenshot from 2022-02-03 21-56-45](https://user-images.githubusercontent.com/32615971/152427434-634fe04f-7edb-4b5c-ad35-7ac8ba3bfdba.png)

But as far as i looked into the codebase the rest is gonna be a little bit tougher!

**Comment by SamantazFox** [comment]
@jonas-w mind sharing what you've done so far?

**Comment by jonas-w** [comment]
Wait are draft pull requests not visible for others?

**Comment by SamantazFox** [comment]
## Video watch page

HTML template is here:
https://github.com/iv-org/invidious/blob/df599c0fc3226cdb5ce4cccfd26c02228976cac3/src/invidious/views/watch.ecr#L238-L245

the data is extracted here:
https://github.com/iv-org/invidious/blob/df599c0fc3226cdb5ce4cccfd26c02228976cac3/src/invidious/videos.cr#L1036-L1045

And here is the corresponding JSON structure:
```json
"videoSecondaryInfoRenderer": {
  "owner": {
    "videoOwnerRenderer": {
      "badges": [
        {
          "metadataBadgeRenderer": {
            "icon": {
              "iconType": "CHECK_CIRCLE_THICK"
            },
            "style": "BADGE_STYLE_TYPE_VERIFIED",
            "tooltip": "Verified",
[SNIP]
```

---

## Related videos

HTML template is here:
https://github.com/iv-org/invidious/blob/df599c0fc3226cdb5ce4cccfd26c02228976cac3/src/invidious/views/watch.ecr#L315-L321

Data is parsed here:
https://github.com/iv-org/invidious/blob/df599c0fc3226cdb5ce4cccfd26c02228976cac3/src/invidious/videos.cr#L810

Associated JSON structure:
```json
"compactVideoRenderer": {
  "ownerBadges": [
    {
      "metadataBadgeRenderer": {
        "icon": {
          "iconType": "CHECK_CIRCLE_THICK"
        },
        "style": "BADGE_STYLE_TYPE_VERIFIED",
        "tooltip": "Verified",
[SNIP]
```

**Comment by SamantazFox** [comment]
(Comments initially posted on the PR)

**Comment by SamantazFox** [comment]
Closed by https://github.com/iv-org/invidious/pull/2859
