### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by FivosM** [omarroth/invidious#287]
I'm getting a 500 on every video.
(Might be related: my subscriptions show 0 unseen notifications while there are clearly new videos uploaded on my subscribed channels)

**Comment by omarroth** [comment]
I'm having trouble reproducing, you may try logging out and logging back in if you can. Or if seeing while logged out you are able to watch videos.

**Comment by FivosM** [comment]
I didn't do anything and it fixed itself. That is weird...

**Comment by omarroth** [comment]
I'll close this then, leave a message if it happens again.
