### ISSUE TITLE
Subscription feed stuck at 12. januar

### ISSUE THREAD

**Issue by fliegentoeter** [omarroth/invidious#288]
Hi,

my subscription feed is stuck at videos from 12. januar. (2-3days ago).
Videos are sorted py published date. 
Everything was working fine until now.

Is this a known issue? Anything I can do?

Thanks

**Comment by elypter** [comment]
can confirm. i have the same problem and was about to report as well

**Comment by omarroth** [comment]
Appears to be updated for me.
