### ISSUE TITLE
Webextension Addon for Firefox

### ISSUE THREAD

**Issue by apfelchips** [omarroth/invidious#29]
Hi I've forked [@2vek](https://gitlab.com/2vek)'s [hooktube-redirector](https://addons.mozilla.org/en-US/firefox/addon/hooktube-redirector/) to use Invidious instead. I've already made a merge request with the original project and I hope he will soon upload it to AMO.

[my YTalt-redirector fork on Gitlab](https://gitlab.com/attero/YTalt-redirector)

**Comment by 2vek** [comment]
Hey, released new addon named [Alternate Tube Redirector](https://addons.mozilla.org/en-US/firefox/addon/alternate-tube-redirector/) with invido.us support. Check it out!

**Comment by apfelchips** [comment]
@omarroth Please add a reference to the README.md and maybe also in the footer of the main page so this gets more visible and we can close this issue.

**Comment by dimqua** [comment]
[Invidious Redirect](https://greasyfork.org/ru/scripts/370461-invidious-redirect) userscript can be used instead.

**Comment by omarroth** [comment]
Added! For future reference: folks wanting to have their extension listed should open a new PR with a short description of their it's functionality. Thank you!
