### ISSUE TITLE
[Suggestion] Serve the wrong mime type for video/3gpp files.

### ISSUE THREAD

**Issue by TylerHobanDotCom** [omarroth/invidious#291]
Chrome refuses to play HTML5 video with the mime `video/3gpp` but when the wrong mime is put in the video tag like `video/mp4` even though the file is the same it works for some reason.

When using this with a 3gp video in chrome it works correctly
```<video width="320" height="240" controls>
  <source src="{link here}" type="video/mp4">

Your browser does not support the video tag.
</video>
```
When using
```<video width="320" height="240" controls>
  <source src="{link here}" type="video/3gpp">

Your browser does not support the video tag.
</video>
```
the video doesn't play. 

I understand that this probably isn't the best idea but at least having it as an option in settings would be good.

I know this is mostly a chrome issue but figured that reporting here will get at least some option.

**Comment by omarroth** [comment]
I can reproduce the issue in Firefox variants as well, so I'd be okay with a change like this if it allows. Unfortunately, from my testing I can only get audio to work using this patch.

**Comment by TylerHobanDotCom** [comment]
Very weird. The vid works fine in Chromium based browsers for me so idk. I have also gone ahead and reported this bug to the Chrome dev team.

**Comment by omarroth** [comment]
If you have an issue number from the Chrome team, would you mind linking it here?

**Comment by TylerHobanDotCom** [comment]
Sorry for late response, the chrome team has fixed the bug. The issue number was 923081.

The revision is as follows:
https://chromium.googlesource.com/chromium/src.git/+/98898bb887f57d0c4266f10e83bc41499b7532bd

**Comment by omarroth** [comment]
YouTube has stopped providing 3gpp files, so this is no longer applicable. As mentioned above though, this appears to have been a bug in Chrome, not in Invidious.
