### ISSUE TITLE
[Bug] One of your urls popular page is blank

### ISSUE THREAD

**Issue by ChristophHoward** [omarroth/invidious#2911]
**Describe the bug**

The https://invidious.namazso.eu/feed/popular url's popular page is just blank. 
**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by Stormfur24** [comment]
This was my first bug report on github so I am not sure what went wrong but below is some more info-----
The issue is just the popular page for that url is blank, I am using one of your other urls to browse but thought it would be useful to notify you.
 - Browser (if applicable): Firefox Version 97

**Comment by unixfox** [comment]
Hi, we have no control over the public instances so we can't fix this issue sorry.

**Comment by Stormfur24** [comment]
No problem, thanks for the reply

**Comment by Marty** [comment]
@unixfox On my fresh instance it is also empty. What is it supposed to show? Popular on yt, or popular on this instance? That would be very neat, so you could share an instance with your friends and family e.g. and watch similar/same content.

**Comment by unixfox** [comment]
> @unixfox On my fresh instance it is also empty. What is it supposed to show? Popular on yt, or popular on this instance? That would be very neat, so you could share an instance with your friends and family e.g. and watch similar/same content.

Please read the documentation for the section `The "popular" feed/page on my instance is empty!`: https://docs.invidious.io/faq/#table-of-contents

**Comment by IASAH** [comment]
> > @unixfox On my fresh instance it is also empty. What is it supposed to show? Popular on yt, or popular on this instance? That would be very neat, so you could share an instance with your friends and family e.g. and watch similar/same content.
> 
> Please read the documentation for the section `The "popular" feed/page on my instance is empty!`: https://docs.invidious.io/faq/#table-of-contents

I believe what he is traying to explain that the page is not empty it's blank you can't even see the header where is login and search bar they're not there
