### ISSUE TITLE
Create wiki page with public instances (You host an instance? Comment here with the url)

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#296]
Please create a wiki page and allow edits from people who have an account on github like here: https://github.com/hackmdio/codimd/wiki/CodiMD-Instances

This is a great project and I don't think we should only focus on https://invidio.us.
Users should be spread over instances like it is with the search engine searx.

**Comment by omarroth** [comment]
Done, available [here](https://github.com/omarroth/invidious/wiki/Invidious-Instances). You should also now be able to add your own instances.

**Comment by Perflyst** [comment]
Thanks!
