### ISSUE TITLE
Search Subscriptions Only

### ISSUE THREAD

**Issue by Sidneys1** [omarroth/invidious#30]
One of the features desperately needed on youtube is the ability to search videos of all of your own subscriptions.

E.g., I'm subscribed to Channel A and Channel B. If I search my subs for "asdf", I should get all of the videos from Channel A and Channel B that match that search.

Use case: I often will find a game that intrigues me, and want to search for LPs of that game. Before I find a new channel to watch it on, I want to know if any of my existing subs has published content from that game before.

**Comment by omarroth** [comment]
Absolutely! I think advanced search is an excellent thing to have, similar to Reddit or DuckDuckGo. Maybe a flag to toggle the feature in the search bar, Something like `subscriptions:true`?

**Comment by omarroth** [comment]
Added with f39ed3d145a58aa967b194805fd616769b5a9b21, but I'd like to fix it up a bit before I close this.

You can now search only your subscriptions with `QUERY subscriptions;true`. Currently, other filters will *not* work with `subscriptions:true`, which I hope to fix before I close this. Also to note is that it will only search videos that have been mirrored by Invidious (see #37 for more details), so it will likely take some time before channels are completely updated. It's also pretty slow for me, so I'll probably also try to optimize it a bit.

Just wanted to give everyone an update, I'm still working on adding this.

**Comment by omarroth** [comment]
Looks like Invidious has been able to mirror just about everything, and is acceptably fast. I'll probably open lack of search filters in a new issue, and close this one for now.
