### ISSUE TITLE
Android App Support

### ISSUE THREAD

**Issue by 3cbb53c73415ba373448c11dacc69b05** [omarroth/invidious#306]
Could you build a Android app for smartphone users?

**Comment by 3cbb53c73415ba373448c11dacc69b05** [comment]
Oh, yes, sorry. I will request this on NewPipe Repo, keep working, man ;)

**Comment by omarroth** [comment]
You might also take a look at [SkyTube](https://github.com/ram-on/SkyTube), which is a similar project. NewPipe actually is an Android app, so I don't think you'll need to request anything :)
