### ISSUE TITLE
https://invidio.us/ privacy policy and data retention

### ISSUE THREAD

**Issue by gerroon** [omarroth/invidious#308]
Hi

Can you please clarify your position on these issues. Some apps (Like Freetube) also use that API and it is not clear what kind of practices are applied to the data that goes through https://invidio.us/

There is no information about privacy policy on the site.

thanks

**Comment by omarroth** [comment]
@rozbb Account deletion is mentioned in the second paragraph of "Removal of data".

I just updated the privacy policy to provide better clarification of how data is stored for Google accounts, privacy regarding googlevideo.com, and the actual information that is stored on the site. 

You can view changes by clicking "edited > (most recent)". Here is the patch version as well:

```patch
7c7,25
< Data that you provide to the website for the purpose of the site's operation (for example: an account name, account password, or channel subscription) will be stored until the user decides to remove it. This data will not be intentionally shared with anyone or anything.
---
> Data that you provide to the website for the purpose of the site's operation (for example: an account name, account password, or channel subscription) will be stored in the website's database until the user decides to remove it. This data will not be intentionally shared with anyoneor anything.
>
> Information stored about a registered user is limited to:
>
> - a list of session tokens for reminaing logged in across devices
> - the last time an account was updated (to provide accurate notifications)
> - a list of video IDs identifying notifications from a user's subscriptions
> - a list of channel UCIDs the user is subscribed to
> - a user ID (for persistent storage of subscriptions and preferences)
> - a json object containing user preferences
> - a hashed password if applicable (not present on google accounts)
> - a randomly generated token for providing an RSS feed of a user's subscriptions
> - a list of video IDs identifying watched videos
>
> The above list reflects [this code](https://github.com/omarroth/invidious/blob/master/src/invidious/users.cr#L14-L51).
>
> Users can clear their watch history using the [clear watch history](/clear_watch_history) page.
>
> If a user is logged in with a Google account, no password will ever be stored. This website uses the session token provided by Google to identify a user, but does not store the information required to make requests on a user's behalf without their knowledge or consent.
29a48,49
>
> This website provides links to googlevideo.com to provide audio and video playback. googlevideo.com is owned by Google and is subject to their [privacy policy](https://policies.google.com/privacy).
```

**Comment by omarroth** [comment]
Added with 21ebc398fa30d6a3ceb66e47a3d0fa637d9cd685. Since #41 has been added since this was opened, this clause has also been added:
> This website also provides an option to store site preferences, such as the theme or locale, without an account. Using this feature will store a cookie in the visitor's browser containing their preferences. This cookie is sent on every request and does not contain any identifying information.

If there are any questions feel free to mention here, or open a PR with any proposed changes.

**Comment by Perflyst** [comment]
I would like to have a redirect from https://invidio.us/delete_account if the user is *not* logged in to the login page.

**Comment by omarroth** [comment]
Mind providing some reasoning for redirecting to `/privacy` instead of the homepage? I don't believe that page is accessible if the user is not logged in (except when viewing the privacy policy).

`/clear_watch_history` should redirect to the homepage, same as `/delete_account`. You might open a new issue if it's just returning an empty page.
