### ISSUE TITLE
Fix width of mobile player controls

### ISSUE THREAD

**Issue by knightfallx66** [omarroth/invidious#310]
Below are two images of Invidious open in Safari and Firefox (respectively) on IOS 12. As you can see the fullscreen buttons are obscured on both. On Firefox the control bar goes beyond the edge of the page and on safari you have to rotate the screen to see the whole thing. 

![4dce236c-8dab-4b46-a911-e35bb80f1458](https://user-images.githubusercontent.com/1860540/51492741-da7aa180-1d80-11e9-80fb-d4542e9684e3.jpeg)
![3e2b1cc1-acc5-424c-8188-e44271f4c1d4](https://user-images.githubusercontent.com/1860540/51492742-da7aa180-1d80-11e9-8ce4-d98861a69ad3.jpeg)

**Comment by omarroth** [comment]
Should be fixed with e25249ce4dce6ed0819ebfa34742aa8234e69ad5.

**Comment by Noeliel** [comment]
This commit broke the control bar on desktop, at least in Firefox:
![invidious](https://user-images.githubusercontent.com/6787990/53203888-a0741800-362a-11e9-88d9-03326f54667a.png)
"Popups" - including the quality and playback speed selection - appear below the video frame due to

```
overflow-x: auto;
overflow-y: hidden;
```

**Comment by omarroth** [comment]
Sorry about that. I've reverted the commit for now. I'll try to find a better solution.

**Comment by omarroth** [comment]
The fix mentioned above will now only be applied for screens where it's possible to overflow, 57635c0d24d1d889d596ece91aea47d7f5f978ec.
