### ISSUE TITLE
Going from a video to settings and clicking on toggle theme redirects back to video

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#316]
Steps to reproduce:

1. Login to your account  
2. Open any video (e.g. https://invidio.us/watch?v=FzG4uDgje3M)  
3. Click on preferences (-> https://invidio.us/preferences?referer=%2Fwatch%3Fv%3DFzG4uDgje3M)  
4. Click on Toggle Theme (-> https://invidio.us/toggle_theme?referer=%2Fwatch%3Fv%3DFzG4uDgje3M)

After the theme is toggled you get back to the video instead to preferences.

**Comment by omarroth** [comment]
Should be fixed with 352e409a6e5df40bb62b00e4053c4294390dd5a3, although it appears it's already been fixed (with JS enabled) by #384.
