### ISSUE TITLE
 Missing param name: "title" 

### ISSUE THREAD

**Issue by frommMoritz** [omarroth/invidious#318]
### Description
When you manipulate the `?v=` in the url so that the video is isn't existing there are two possible outcomes. 
When you leave it the same length as a youtube video id normal would be (11 characters), you get told ` This video is unavailable.`
But when you make the video id **shorter** than the mentioned 11 characters, you see the message ` Missing param name: "title" `. IMO you should get the same `This video is unavailable.`

### Example
`https://invidio.us/watch?v=mX0MXqZv6uo` - ` This video is unavailable. `
`https://invidio.us/watch?v=mX0MXqZv6u` - `Missing param name: "title" `

**Comment by omarroth** [comment]
Fixed with 9e73e3b15326bfac7c94a2cd997f742abbe66305.
