### ISSUE TITLE
Option to disable captcha

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#320]
Probably it's a good idea to add an option to disable captcha on self-hosted instances, for example, to avoid this problem: https://github.com/omarroth/invidious/wiki/Issues-with-Captcha-on-Debian-and-Ubuntu

**Comment by Perflyst** [comment]
Reference to #312

**Comment by omarroth** [comment]
Added with a39b1583dacff31664830fd4f8966014f8869fa0.
