### ISSUE TITLE
FreshRSS - invidious video extension

### ISSUE THREAD

**Issue by tmiland** [omarroth/invidious#321]
Hi, 

i have forked the [FreshRSS - YouTube video extension](https://github.com/kevinpapst/freshrss-youtube) to work with Invidious.

You can find the plugin here: [FreshRSS - Invidious video extension](https://github.com/tmiland/freshrss-invidious)

Added domain option in settings for custom instances.

Enjoy Invidious in your FreshRSS Invidious feed! 😎

**Comment by tmiland** [comment]
Excellent! My pleasure 😃

**Comment by kevinpapst** [comment]
You might want to add your extension here as well: https://github.com/FreshRSS/Extensions
Thanks for the credits^^

**Comment by omarroth** [comment]
Since #322 has been merged and the extension is listed in the wiki I'm going to close this. Thank you so much!
