### ISSUE TITLE
delayed subscription feed updates

### ISSUE THREAD

**Issue by elypter** [omarroth/invidious#326]
i think you already said that this is fixed but it is still a problem for me. at the time being [this video](https://invidio.us/watch?v=MjjrLVGnS8Q) hasnt shown up in the feed although it is already 21 hours old. it happens wih all sorts of videos and it also messes with the order in which the videos appear in the subscriptionb page. could it be a regession or is it account or region specific?

**Comment by omarroth** [comment]
The issue appears to have been a misconfig. In the config:
```
full_refresh: false
```
was set to `true`, so channels were updating much slower than they would be normally.

There's a backlog of channels that are being updated. Things should start appearing soon.
