### ISSUE TITLE
Feature Request: allow cors access to api

### ISSUE THREAD

**Issue by devkral** [omarroth/invidious#336]
Currently it isn't possible to access the API with javascript APIs in webbrowsers. The problem here is CORS.
A fix would be to add the:
Access-Control-Allow-Origin: *
Header to API responses.

**Comment by omarroth** [comment]
CORS has likely been the biggest pain point working on this project.

Fixed with d0a690c30314d41661f706d66f868e6be56a0f66.

**Comment by devkral** [comment]
thanks a lot
