### ISSUE TITLE
Add permalinks of the comments on Invidious

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#340]
Basically the same as we have for YouTube. Is it possible to implement?

**Comment by omarroth** [comment]
Related: #101, #204. Comments need to be reworked for various reasons, so expect this to be added with a refactor. It may make sense to open a new issue for tracking this and #101, similar to how things are organized in #312.

I just haven't gotten around to it yet, expect this to be added soon.

**Comment by omarroth** [comment]
Added with #334.
