### ISSUE TITLE
VEVO videos don't work

### ISSUE THREAD

**Issue by LoveIsGrief** [omarroth/invidious#348]
Maybe when the root cause is known the title can be changed, but for now it's been pretty consistent that VEVO videos don't work e.g https://invidio.us/watch?v=F1B9Fk_SgI0 . They do work directly on youtube.

This is in the Netherlands atm, but confirmed during a trip to Germany.

Browsers tested:

 - Firefox Nightly 67.0a1 (2019-02-06) (64-bit)
 - Chromium 71.0.3578.98
 - Pale Mon 28.3.1

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

Then it starts looping trying to make playback requests to google 
[request.json.txt](https://github.com/omarroth/invidious/files/2840657/request.json.txt)

Further one can only download the video without the audio, but that's another issue.

**Comment by omarroth** [comment]
There was some discussion on this in the Matrix Server, as some other folks have also encountered this. 

The issue with VEVO links is likely related to #92. For some videos, YouTube will limit playback to the region where the video was requested, even though it's available in other regions. You might try accessing the video with `quality=dash`, e.g. https://invidio.us/watch?v=F1B9Fk_SgI0&quality=dash . If that fixes the issue for you we can close this in favor of #92.

**Comment by LoveIsGrief** [comment]
Appending `quality=dash` fixed the issue for me. I'll fallback to that when stuff doesn't work.

Cheers
