### ISSUE TITLE
manage subscriptions is empty

### ISSUE THREAD

**Issue by elypter** [omarroth/invidious#354]
the manage subscription page does not show a single channel anymore. the subscription feed is still updated howerver. this is likely a regression because it stopped showing channels just recently.

**Comment by omarroth** [comment]
Everything appears to be showing for me. How many channels are you subscribed to?

**Comment by elypter** [comment]
i cant see it anymore but i guess around 30 or 40

**Comment by omarroth** [comment]
Rolling out 1590393fcc461e8279bbca75162d5f6af0fc5b0b now, which should speed things up a bit.
