### ISSUE TITLE
[Feature request] Possibility to change video quality in livestreams.

### ISSUE THREAD

**Issue by ghost** [omarroth/invidious#3546]
In YouTube, for example, it is possible to change the video quality of livestreams.
I did not find such a function in Invidious, the video quality of livestreams depends on some conditions I do not understand, because sometimes the video quality of livestreams is perfect, and sometimes it is so terrible that the text in livestreams is absolutely unreadable.

**Comment by unixfox** [comment]
Do you have dash enabled?
