### ISSUE TITLE
Add `/api/v1/stats`

### ISSUE THREAD

**Issue by omarroth** [omarroth/invidious#356]
Diaspora provides `/nodeinfo/1.0` and `/nodeinfo/2.0` on instances that have them enabled. Example: https://framasphere.org/nodeinfo/2.0.

Invidious could provide an endpoint `/api/v1/stats` that provides similar statistics. Statistics would be disabled by default and enabled either in `config.yml` or as part of #312.

**Comment by dimqua** [comment]
In addition, short statistic such as a version number can be added to the footer of the website. This way you can be sure which version you use.

**Comment by omarroth** [comment]
Using the example from above:
```json
{
  "version": "2.0",
  "software": { "name": "diaspora", "version": "0.7.9.0-p00846856" },
  "protocols": ["diaspora"],
  "services": { "inbound": [], "outbound": ["twitter", "tumblr", "wordpress"] },
  "openRegistrations": true,
  "usage": {
    "users": { "total": 56091, "activeHalfyear": 12026, "activeMonth": 4715 },
    "localPosts": 657359,
    "localComments": 641679
  },
  "metadata": {
    "nodeName": "Framasphere*",
    "xmppChat": false,
    "camo": { "markdown": true, "opengraph": true, "remotePods": false },
    "adminAccount": "podmin"
  }
}
```

The relevant fields would be `version`, `openRegistrations` #293, `users`, and `adminAccount` for #312.

There would also likely be `localPlaylists` once #114 is implemented.

**Comment by aaferrari** [comment]
To get the number of users, this could be used with PostgreSQL:
```
select json_build_object(
    'total', (select count(*) from users),
    'activeHalfyear', (select count(*) from users where updated between (current_timestamp - interval '6 months') and current_timestamp),
    'activeMonth', (select count(*) from users where updated between (current_timestamp - interval '1 month') and current_timestamp)
);
```
Which would return something like
`{"total" : 1, "activeHalfyear" : 1, "activeMonth" : 1}`
Although it is not clear to me if the `updated` field is modified when the user starts session, when adjusting the prefencias and/or when subscribing to a channel.

**Comment by omarroth** [comment]
The `updated` field is used for delivering new notifications and is set to the current time whenever a user visits their subscription feed.

Unfortunately `count(*)` gets quite slow whenever the number of rows gets too large, see [here](https://wiki.postgresql.org/wiki/Count_estimate). Running the above query takes around 4-6 seconds for https://invidio.us.

I can see that being reasonable though if you pull it out into a job like [this](https://github.com/omarroth/invidious/blob/master/src/invidious.cr#L134-L141) so statistics are updated separately from the main query.

**Comment by omarroth** [comment]
Added with 4be82c5ca618a27b8729c4c1406c549651b6d37a.

Statistics are disabled by default. You can see statistics for the official instance [here](https://invidio.us/api/v1/stats?pretty=1). Example response (as of writing):

```json
{
  "version": "2.0",
  "software": {
    "name": "invidious",
    "version": "0.14.1-25bd27e"
  },
  "openRegistrations": true,
  "usage": [
    {
      "users": {
        "total": 3165,
        "activeHalfyear": 2853,
        "activeMonth": 1029
      }
    }
  ],
  "metadata": {
    "updatedAt": 1551493022,
    "lastChannelRefreshedAt": 1551493022
  }
}
```

Statistics are updated roughly once every minute, the time it was updated designated by `updatedAt`. 

The schema is based on [this spec](http://nodeinfo.diaspora.software/ns/schema/2.0). Several fields are omitted, such as the `services` and `protocols`, as they are not currently applicable.
