### ISSUE TITLE
Unable to login on iOS Safari

### ISSUE THREAD

**Issue by sarahgould** [omarroth/invidious#358]
When I try to log in on Safari / iOS (latest) / iPad Pro, it sends me to a page that says “looks like you found a bug.” Tried 3 times with correct captchas; the two times I messed up the captcha (cause apparently I am bad at reading analog clocks!) the page said “invalid answer” instead, suggesting that the bug only happens on a successful login attempt.

**Comment by omarroth** [comment]
Just pushed a couple fixes so you might try logging in again.

**Comment by sarahgould** [comment]
Yay it works! Thanks!
