### ISSUE TITLE
Exception: no rows (DB::Error)

### ISSUE THREAD

**Issue by tmiland** [omarroth/invidious#359]
Howdy,

get this error when i try to log in on latest pull.

Have all database changes been added to the migration scripts?

<details>
  <summary>Click to expand</summary>

`Exception: no rows (DB::Error)
  from /usr/share/crystal/src/gc/boehm.cr:71:5 in 'query_one:as'
  from src/invidious.cr:169:16 in '???'
  from lib/kemal/src/kemal/filter_handler.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???

Unhandled exception on HTTP::Handler
Missing hash key: "locale" (KeyError)
  from /usr/share/crystal/src/int.cr:189:13 in 'get'
  from src/invidious.cr:28:21 in '->'
  from lib/kemal/src/kemal/exception_handler.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???
Exception: no rows (DB::Error)
  from /usr/share/crystal/src/gc/boehm.cr:71:5 in 'query_one:as'
  from src/invidious.cr:169:16 in '???'
  from lib/kemal/src/kemal/filter_handler.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???

Unhandled exception on HTTP::Handler
Missing hash key: "locale" (KeyError)
  from /usr/share/crystal/src/int.cr:189:13 in 'get'
  from src/invidious.cr:28:21 in '->'
  from lib/kemal/src/kemal/exception_handler.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???
`

</details>

**Comment by omarroth** [comment]
The issue appears to be [these](https://github.com/omarroth/invidious/blob/master/src/invidious.cr#L166-L169) lines.
```crystal
email = PG_DB.query_one?("SELECT email FROM session_ids WHERE id = $1", sid, as: String)

if email
  user = PG_DB.query_one("SELECT * FROM users WHERE email = $1", email, as: User)
```

So it's able to find the session, but the email assigned to that session doesn't exist. I'm not quite sure how that could happen. I just pushed a couple fixes so you might try pulling again.

**Comment by tmiland** [comment]
Still same error. This error popped up on the website after fiddling around: 

> relation "videos" does not exist 

So it's definitely the database migration that is causing the issue.

**Comment by tmiland** [comment]
Ookay... 700 MB + postgresql logfile 😂

`2019-02-12 10:30:50.970 CET [11614]  STATEMENT:  SELECT id, wilson_score, published FROM videos WHERE views > 5000 ORDER BY published DESC LIMIT 1000
2019-02-12 10:30:50.970 CET [11614]  ERROR:  relation "videos" does not exist at character 41`

**Comment by omarroth** [comment]
I'm not quite sure how you would drop the `videos` table after doing a migration. And `users` also appears to be corrupted or out of sync with sessions? If you're still encountering errors after starting fresh (as you mentioned in #362) feel free to open a new issue, otherwise it seems like an issue configuring the DB.
