### ISSUE TITLE
[suggestion] provide a link to a raw list of video urls for every playlist

### ISSUE THREAD

**Issue by elypter** [omarroth/invidious#360]
it is handy for many tasks to be able to easily access a raw list of youtube video urls or ids. eg: for batch processing, standalone players, bulk downloads and more. it would be nice if you could add a something like this maybe above the rss symbol

**Comment by omarroth** [comment]
I would probably recommend using the [API](https://github.com/omarroth/invidious/wiki/API) for this, since it's much more flexible than what I could provide through the UI.

**Comment by elypter** [comment]
for applications, sure. i was looking for a solution to interact with gui applications. something like jdownloader. it scans the clipboard for links. if you for example copy something like 

> https://www.youtube.com/watch?v=k0vcCkMN6IY
> https://www.youtube.com/watch?v=ewGQ7pSBirs
> https://www.youtube.com/watch?v=E_KOhUPJkn0

it automatically scans for the video files and allows you to download them all in one step. this is really helpful if you are going on a trip with no or slow/expenisve internet.

**Comment by omarroth** [comment]
The problem with providing a flat list is that it requires pulling each page of videos first and then compiling them, which presents problems for a web app.

This is going to be a `wont-fix` unfortunately, since it's application specific. Here's a script that should do what you want using the API. You can change `playlistId` to your desired playlist. 

```bash
#!/bin/bash

playlistId=PL1A24F26EE5263522;
index=0;
page=1;
let "videoCount=$(curl -s https://invidio.us/api/v1/playlists/$playlistId | jq -r ".videoCount")";
while [ $index -le $videoCount ]; do
  curl -s https://invidio.us/api/v1/playlists/$playlistId\?page\=$page | jq -r '"https://www.youtube.com/watch?v=\(.videos|.[].videoId)"' ;
   let "page++" ; 
  let "index += 100"; 
done
```

Best.

**Comment by elypter** [comment]
i thought invidios could fetch those all in one api call. this makes it indeed quite more complicated. but maybe reconsider it if you add native invidio.us playlists.
