### ISSUE TITLE
[question] admin settings lost after restart

### ISSUE THREAD

**Issue by RainrZufall** [omarroth/invidious#3678]
When I restart my Invidious instance, my administration settings are reset.
My other "user settings" remain saved.

To reproduce the problem:
- Change admin setting
- Restart Docker instance `docker restart invidious`
- Go to website (not logged in)

![image](https://user-images.githubusercontent.com/116357136/223137936-273fc9fd-1f35-4718-9f51-fcb12a191a92.png)

**Comment by RainrZufall** [comment]
oh ok, thanks for the hint.

I just want to change the home page. can you help me which setting i have to enter in my yml?
The "Popular" page should not appear at all.
I couldn't find anything about this in the documentation and example config.
This is how I always have it in the settings:
![image](https://user-images.githubusercontent.com/116357136/223145098-3e4a59b0-6cc5-4f73-8085-23f5586b51f7.png)

**Comment by unixfox** [comment]
We have completely documented the config.yaml: https://github.com/iv-org/invidious/blob/master/config/config.example.yml
Please give a try and get back to us if you really don't find a solution.
