### ISSUE TITLE
DASH playback without JS

### ISSUE THREAD

**Issue by Jtasiu** [omarroth/invidious#370]
Could the be added some way dash playback using the URL parameter work without having to enable JS?

**Comment by dimqua** [comment]
AFAIK, JS is required to use the Invidious player, which is needed to play DASH videos.

**Comment by omarroth** [comment]
It is not possible to combine audio and video streams without using JS, so no.

At some point it may be possible using [mediaGroups](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/mediaGroup), however this is currently completely unsupported.

I'm looking into combining audio+video serverside for #83, which may help here, but I don't expect it to be practical in this case and wouldn't expect it to be possible anytime soon.
