### ISSUE TITLE
Localisation is missing few strings

### ISSUE THREAD

**Issue by eutampieri** [omarroth/invidious#373]
As the title, for example on the subscription pages with the French locale the Shared `x` ago looks like this:
![image](https://user-images.githubusercontent.com/10284268/53097170-1b510c00-3521-11e9-931e-32431b068223.png)
It seems that `x` isn't localised.

**Comment by eutampieri** [comment]
Also with the ``x` ago` string: 
![image](https://user-images.githubusercontent.com/10284268/53098696-805a3100-3524-11e9-883b-8fe08bb7c84a.png)

**Comment by omarroth** [comment]
That's still something that I need to implement. Expect it to be fixed soon.

**Comment by eutampieri** [comment]
If you want I could try… the only problem is that I don’t know crystal and I have never had a look to your code!

**Comment by omarroth** [comment]
Should be fixed with 8349323.

**Comment by eutampieri** [comment]
Is it deployed instantaneously?

**Comment by eutampieri** [comment]
Yeah, fixed

**Comment by eutampieri** [comment]
Anyway, is it normal to have strings such as `Shared 14.607139832222222 hours ago`?

**Comment by omarroth** [comment]
Just an issue with the implementation, fixed with 9a1f4de323973fd475ac5603c974799b2e5fb6e8.
