### ISSUE TITLE
[Bug] sort_by=upload_date does not work

### ISSUE THREAD

**Issue by greenfoo** [omarroth/invidious#3734]
Calling the search endpoint with `sort_by=upload_date` does not return the results ordered by upload date.

Examples:
* https://watch.thekitty.zone/api/v1/search/?q=Real+Madrid&sort_by=upload_date
* https://invidious.snopyta.org/api/v1/search/?q=Real+Madrid&sort_by=upload_date

I would expect (maybe I'm wrong?) for the results to be sorted according to the "published" property so that they match the order returned by this equivalent YouTube search:
* https://www.youtube.com/results?search_query=real+madrid&sp=CAI%253D

But #2824 is similar, but not the same, as there is no colon in any of the parameters.

**Comment by DrSocket** [comment]
Same issue here, sort_by: upload_date doesn't actually sort by date, but private browser window search by upload_date gives different ordered results than normal search so it seems to be a bug with invidious

**Comment by ChunkyProgrammer** [comment]
sort=date and sort=views seem to be used instead. 

@SamantazFox should the api docs be updated or should the code be updated to support both? The parameter name (sort_by => sort) and some of the values (upload_date => date, view_count => views) in the api docs don't match what is used in Invidious

**Comment by ChunkyProgrammer** [comment]
PR is still open in the docs repo so this can stay open
