### ISSUE TITLE
[Question] Document missing endpoints

### ISSUE THREAD

**Issue by greenfoo** [omarroth/invidious#3735]
This endpoint (which returns the list of videos in a channels) works but is not [documented](https://github.com/iv-org/documentation/blob/master/docs/api.md).

Example:
* https://watch.thekitty.zone/api/v1/channels/UCSMOQeBJ2RAnuFungnQOxLg/videos

By the way... at least 1 (maybe 2?) years ago this endpoint also accepted the "sort_by" argument, but now it returns an error when you try to use it. Example: https://watch.thekitty.zone/api/v1/channels/UCSMOQeBJ2RAnuFungnQOxLg/videos/?sort_by=oldest

**Comment by ChunkyProgrammer** [comment]
Channel endpoints are shown on this page: https://docs.invidious.io/api/channels_endpoint/#get-apiv1channelsidstreams
