### ISSUE TITLE
Auto localise

### ISSUE THREAD

**Issue by eutampieri** [omarroth/invidious#374]
Would it be possible to display the interface for a not logged in user in its language and, if the localisation isn't present, fallback to English?

**Comment by omarroth** [comment]
I'm a little skeptical of having "Auto-" anything. With #41 it'll be possible for a user to change their locale without making an account, so I would prefer that over having it picked out for them.

**Comment by eutampieri** [comment]
Yeah, I see. And I can even agree to a certain extent. However, if there is the possibility as per #41 is definitely fine!
Thanks and keep this awesome project going!
