### ISSUE TITLE
[Bug] Cookie to save settings is sometimes created on a non-existent subdomain of the instance's domain.

### ISSUE THREAD

**Issue by ghost** [omarroth/invidious#3768]
It has been noticed that for some unknown reason, sometimes a "PREFS" cookie is created on a non-existent subdomain of the instance's domain, causing the settings to stop changing until you delete this cookie yourself.
For example, when using the "invidious.vpsburti.com" instance, a settings cookie is sometimes created on ".invidious.vpsburti.com".
How it looks in the information about the cookie is shown in the screenshots.
![unnamed](https://user-images.githubusercontent.com/126508037/234360253-1a4c3b90-b10f-4ffe-a57d-4c604f254882.png)
![unnamed2](https://user-images.githubusercontent.com/126508037/234360257-5f0c661b-a4fd-448e-8c66-32a2b26edb6f.png)

**Comment by SamantazFox** [comment]
Can you provide more details, please?
What version of invidious, what browser are you using, etc?

I recall seeing this as a Firefox bug, but I can't find which one it was.

**Comment by unixfox** [comment]
Probably related issue: https://github.com/iv-org/invidious/issues/2854

Make sure you are not running privacy redirect or you may just run into the same result as this guy:

> It then immediately clicked that this feature is part of the Privacy Redirect addon which has the ability to "persist invidious preferences". So in other words the issue has nothing to do with invidious at all. Sorry for the noise!
