### ISSUE TITLE
feed doesn't update

### ISSUE THREAD

**Issue by cyaniventer** [omarroth/invidious#381]
Related: #37 #207 #326 

issue: feed doesn't update but I can see new videos on channel page.

**Comment by omarroth** [comment]
Appears to be updated for me. As mentioned in #207, #164 and #356 should help resolve these sorts of problems much faster.

**Comment by cyaniventer** [comment]
how are #164 & #356  related?

my feed got updated today, yesterday it was out of sync for like 2 days. how does invidious update feeds? does it check every channel after some interval or something else?

**Comment by omarroth** [comment]
The issue in this case was a misconfig, similar to [#326](https://github.com/omarroth/invidious/issues/326#issuecomment-462083569). The reason I mentioned the above issues is because some form of metrics would help identify these sorts of issues more quickly.

**Comment by cyaniventer** [comment]
yes that would probably help.

> The issue in this case was a misconfig
so that closes this issue!
