### ISSUE TITLE
Found a video that doesn't play

### ISSUE THREAD

**Issue by ghost** [omarroth/invidious#382]
https://invidio.us/watch?v=CBPXJlJrv9E

Previously it used to display that it would be published in (x) minutes, both on IV and YT, but now it is published on YT but on IV it says "The media could not be loaded, either because the server or network failed or because the format is not supported." (as of the time of writing this issue)

**Comment by Perflyst** [comment]
Appears to work with dash, https://invidio.us/watch?v=CBPXJlJrv9E&quality=dash
and also on another instance https://invidious.snopyta.org/watch?v=CBPXJlJrv9E

Probably #92 related?

**Comment by zorbakus** [comment]
For me it works with dash, but not on the other instance (same error)

**Comment by omarroth** [comment]
Dash refers to multiple qualities that the browser chooses depending on network conditions.

You may see if https://invidio.us/watch?v=CBPXJlJrv9E&local=true plays for you, if so we can close this in favor of #92.
