### ISSUE TITLE
'Looks like you've found a bug' - video won't load

### ISSUE THREAD

**Issue by atomGit** [omarroth/invidious#383]
`https://www.youtube.com/watch?v=_2vpcABWJiY`

invidious.snopyta.org says "Looks like you've found a bug in Invidious."

snopyta.org URL:
`https://invidious.snopyta.org/watch?v=_2vpcABWJiY`

**Comment by omarroth** [comment]
It appears to work on the official instance: https://invidio.us/watch?v=_2vpcABWJiY, so I expect the issue is an outdated version.

**Comment by Perflyst** [comment]
Version is not outdated, there is latest commit from master installed

**Comment by Perflyst** [comment]
@omarroth just fixed it in https://github.com/omarroth/invidious/commit/0a404cc9a6d2453a4d9090c6630e7a3820c80f29
Video is working now.
