### ISSUE TITLE
googlevideo.com as third party even if DASH is enabled

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#389]
Sometimes there is still third party from googlevideo.com even if dash is enabled via settings and stored in the cookie or "forced" via `&quality=dash`
I think it is a bad idea in this case to use a fallback to googlevideo.com because if you have DASH enabled you probably do *not* want a connection to google.

**Comment by ealgase** [comment]
If it's that much of an issue, you could block googlevideo.com with uBlock Origin.

**Comment by Perflyst** [comment]
I already do but this is not always possible

**Comment by BurnyBoi** [comment]
Yeah, I tried this, and if I block the request to googlevideo.com with quality=dash, I get an error messaging covering the video window that says "Video playback aborted due to network error"

**Comment by omarroth** [comment]
See also #402. Using `&local=true` should fix the issue. It will also make `&quality=dash` redundant if you only want to avoid a connection from `googlevideo.com`.

**Comment by Perflyst** [comment]
Is it configurable via settings or config file too?

**Comment by omarroth** [comment]
Added option to preferences with e738e57e262e3b65930632e49d9988855abe8b36.If you'd like to open a new issue for changing the default user preferences the config, I think it would be good to have. For now you can change them [here](https://github.com/omarroth/invidious/blob/e738e57e262e3b65930632e49d9988855abe8b36/src/invidious/users.cr#L30).

**Comment by Perflyst** [comment]
Works as expected, closing this.
