### ISSUE TITLE
Topic videos don't appear to play (but play on YouTube)

### ISSUE THREAD

**Issue by Gert-dev** [omarroth/invidious#392]
Hello

It seems that no video I open from a `- Topic` channel works. Usually the following error shows:

```
The media could not be loaded, either because the server or network failed or because the format is not supported.
```

An example is [this video](https://invidio.us/watch?v=jboR8ORlcjc).

It may be worth mentioning that this video works when I open it on YouTube as well as in mps-youtube. 

There are other `- Topic` videos that really just aren't available to me on YouTube either, but I selected this one in particular since it works fine in other places but not on Invidious.

Not sure if this is helpful, but the console shows the following:

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
video.min.js:1:30685

    Ze https://invidio.us/js/video.min.js:1 error https://invidio.us/js/video.min.js:1 error https://invidio.us/js/video.min.js:6 handleTechError_ https://invidio.us/js/video.min.js:6 n https://invidio.us/js/video.min.js:2 n https://invidio.us/js/video.min.js:2 dispatcher https://invidio.us/js/video.min.js:1 
```

This is when I enable JavaScript. It also doesn't work when I disable JavaScript. I _do_ notice that the network request to Google Video gives me a `403 Forbidden`.

Other videos seem to work fine. Am I perhaps missing something I need to enable (on Firefox)?

This is a split from #302 as this appears to be related but is not the same issue.

Thanks!

**Comment by dimqua** [comment]
I doesn't work for me as well.

**Comment by Perflyst** [comment]
This one works for me with dash enabled, https://invidio.us/watch?v=jboR8ORlcjc&quality=dash
and also on my instance: https://invidious.snopyta.org/watch?v=jboR8ORlcjc without dash

Probably #92 again just it happens to happen to `- Topic` for you.

**Comment by Gert-dev** [comment]
I can confirm it works with `&quality=dash` after it. Although could it be due to region/geo blocking if the video works fine on YouTube itself (i.e. I'm not actually blocked from the content on YouTube)?

It may also be worth mentioning that the workaround only works with the JavaScript player and not in HTML mode.

**Comment by omarroth** [comment]
See also #402. As mentioned in #92, YouTube will sometimes still block access to files if they are requested from a different region, even though the videos themselves aren't geo-blocked.

Adding `&local=true` should allow you to view the videos without JS.

**Comment by opusforlife2** [comment]
@omarroth  https://invidious.snopyta.org/watch?v=e95-Gaj2iXM doesn't play even with invidious proxy enabled, nor do any other such videos which have "auto generated by Youtube" in the description.
