### ISSUE TITLE
(really) old videos in subscription feed.

### ISSUE THREAD

**Issue by Stypox** [omarroth/invidious#396]
Since some weeks the [subscription feed page](https://invidio.us/feed/subscriptions) diplays really old videos and every day it seems like it is going back in time. The channel pages of my subscriptions are all up-to-date.

For example: instead of seeing the [last video](https://invidio.us/watch?v=WTPt07NO61A) from Alan Becker I see [this](https://invidio.us/watch?v=M0nyG5BvBR8). But if I open [his channel](https://invidio.us/channel/UCbKWv2x9t6u8yZoB3KcPtnw) I see all of his videos as excepted.

I already tried relogging and logging in from another computer but nothing changed.

This is my subscription feed at the moment:
![my subscription feed](https://user-images.githubusercontent.com/36421898/53757661-7b9a6300-3ebc-11e9-969d-02a31ab4c698.png)

**Comment by omarroth** [comment]
Strange, mind sharing your subscription preferences?

**Comment by Stypox** [comment]
Redirect homepage to feed: YES
Number of videos shown in feed: 40
Sort videos by: published
Only show latest video from channel: YES
Only show unwatched: NO
Only show notifications (if there are any): NO

**Comment by dimqua** [comment]
I have the same preferences, except for ` Only show latest video from channel: NO`.
Probably, you are subscribed to a bunch of really old and abandoned channels?

**Comment by omarroth** [comment]
Thanks, should be fixed with 2a1befb41a7fa2bc8f15bff704761a79847b51ba.

**Comment by Stypox** [comment]
I can confirm it is now working as excepted. Thanks :-D
