### ISSUE TITLE
SUGGESTION: resume video ?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#398]
like a youtube, netflix or even peertube, add a auto resume option

**NOTE**: peertube is open source right ? so why not steal codes from there ? 😂😂

**Comment by omarroth** [comment]
Duplicate of #343?

**Comment by EsmailELBoBDev2** [comment]
yup but you not replied + he didn't talk about peertube :P :joy:

**Comment by omarroth** [comment]
Unfortunately I haven't had much time to respond to requests to new features, I did see it though. I'd suggest mentioning PeerTube there or any other resources you think would be helpful. I'd like to keep discussion in one issue rather than opening multiple if there hasn't been much activity.

**Comment by EsmailELBoBDev2** [comment]
@omarroth okay np, seems good to me

**Comment by dimqua** [comment]
SkyTube has this feature too.
