### ISSUE TITLE
support timestamps in URLs (again)

### ISSUE THREAD

**Issue by DJCrashdummy** [omarroth/invidious#399]
on youtube you can share URLs like `https://youtu.be/XXXXXXXXXXX?t=70`, `...?t=70s` or `...?t=1m10s` resp. `https://youtube.com/watch?v=XXXXXXXXXXX&t=70`, `...&t=70s` or `...&t=1m10s` and `https://www.youtube.com/watch?v=XXXXXXXXXXX&start=80` to start the video at a given timestamp.

some time ago at least some of these parameters also worked with invidious, but now it seems that none of them work anymore. :slightly_frowning_face: it would be really nice to support them again, that invidious-URLs i shared (with timestamp) work correctly again... and that i can use invidious again when i want to point to an explicit section of a video.
btw i guess there are/were also parameters for end-timestamps, but i have no idea if they are still supported (by youtube) and their syntax. - anyway (also if youtube ditched them) supporting end-timestamps would be a nice additional feature of invidious.

**Comment by omarroth** [comment]
Would you mind linking a specific example on Invidious that isn't working, or provide more details? These all work as expected for me:
- https://invidio.us/aqz-KE-bpKQ?start=1m&end=1m10s&loop=1
- https://invidio.us/embed/aqz-KE-bpKQ?start=1m&end=1m10s&loop=1
- https://invidio.us/watch?v=aqz-KE-bpKQ&start=1m&end=1m10s&loop=1

Although YouTube reports a `&end=` parameter [here](https://developers.google.com/youtube/player_parameters), I wasn't able to get it to work for any of the examples above, so the documentation may be out of date.

**Comment by DJCrashdummy** [comment]
ok, now it gets "interesting"... none of your examples worked for me either.

it took me a while, but i (at least partly) nailed it down:
this happens to me when i have [uBlockO](https://github.com/gorhill/uBlock/) (a content-blocker) activated with the filterlists [*Fanboy's Annoyance List*](https://easylist.to/easylist/fanboy-annoyance.txt) and/or [*Fanboy's Social Blocking List*](https://easylist.to/easylist/fanboy-social.txt) enabled.
the only line in both lists i found with `invidio.us` in it was `invidio.us,video.khl.ru#@#.vjs-share`. and that's the point where my knowledge ends. - i have no idea if this line is really the cause and if so, why... and also no idea how it has to be changed to fix it.

hopefully someone can give some hints before reporting to https://easylist.to/ resp. are you sure @omarroth  that there is nothing what can/should be fixed on the side of invidious?

**Comment by omarroth** [comment]
Appears blocking videojs-share was preventing some functionality in the player from loading, should be fixed with a659982.

**Comment by DJCrashdummy** [comment]
awesome! works like a charm again.
thank you very much @omarroth for so quickly responding and fixing (and of course invidio.us in general)! :clap: 

so, no need to report anything to https://easylist.to?

**Comment by omarroth** [comment]
No need to report anything.
