### ISSUE TITLE
A suggestion for its design

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#4]
The white space on both sides should be used by the site. A suggestion on how to use the space is to move the related videos displayed below the video to the right-hand side (and add a Related Videos header).

**Comment by omarroth** [comment]
Could you clarify? I'm not quite sure what you mean.

**Comment by Zero3K** [comment]
Basically, you should consider having it use the right side like how Youtube does instead of leaving white space.

**Comment by omarroth** [comment]
I don't have a good solution to this, as it's mostly opinion. Having recommended videos take up the right side makes it look unbalanced IMO. It's mostly designed based off YouTube's big picture mode, with two columns on either side of the video description. Adding a `Recommended videos` header would be a good idea though.

**Comment by dimqua** [comment]
> It's mostly designed based off YouTube's big picture mode

I think it's exactly what @Zero3K propose: enlarge videoplayer, so more white space cab be used on both side.

**Comment by Zero3K** [comment]
Yes, that is what I want. It'll also keep the comments, etc. from being as cramped.

**Comment by omarroth** [comment]
I'll consider this closed since #33 has been implemented. Obviously the UI can still be improved so if there are any improvements I'd very much appreciate them. Feel free to open a new issue or PR with some proposed changes.
