### ISSUE TITLE
Show only unseen videos

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#40]
Currently, you can define a max number of videos shown in feed. I would like to have an option to only see videos, which I haven't seen yet. If there aren't any, all recent videos should be shown in the feed.

P.S. "Only show latest video from channel" option is not exactly what I need. :-(

**Comment by omarroth** [comment]
Sounds good! So an "only show unwatched" checkbox? And then when both it and "latest video" is checked, it'll show the latest I watched video for each channel, if that's what you mean when you say it doesn't quite cut it. Everything else looks straightforward.

**Comment by dimqua** [comment]
"Latest video" option is not really useful in such case, probably, it should be unavailable if "only unwatched" is checked.
