### ISSUE TITLE
"Corrupted Content Error" when logged in and front page is set to Trending

### ISSUE THREAD

**Issue by spriteclad** [omarroth/invidious#400]
When I have "Redirect homepage to feed" turned on, and I have set the default homepage to Trending via the admin panel, whenever I go to the front page (by clicking on the Invidious logo), Firefox gives me a "
Corrupted Content Error." Any idea why this is?

**Comment by omarroth** [comment]
Should be fixed with bc9d70109c9f6e966b5d27a0ab617e578cdfc604.

**Comment by spriteclad** [comment]
Seems to have done it. Thanks!
