### ISSUE TITLE
subscriptions feed completely broken

### ISSUE THREAD

**Issue by cyaniventer** [omarroth/invidious#404]
I see videos that are 2-3 days old in my feed and invidious reports that they're 3-120 minutes old, when I check that channel's page it reports correct data. 

![invidious subscription feed showing wrong data](https://i.sigavpn.com/img/3051297823.jpg)

In that image invidious reports that video was uploaded 5 minutes ago but it was uploaded on 28-02-19.

**Comment by omarroth** [comment]
Should be fixed with b9c750101258fce1cf1bc0819bd857a8d61faa84. Unfortunately Invidious was writing the `updated` time as the `published` time. I reset the DB where possible, everything should update fairly quickly.

**Comment by cyaniventer** [comment]
yes everything was fixed except a few channels like `vice` (only one video)
