### ISSUE TITLE
/videos endpoint returns an invalid URL

### ISSUE THREAD

**Issue by PrestonN** [omarroth/invidious#406]
Calling `/videos` returns an invalid URL for the videoThumbnails property.  The endpoint returns `https://.invidio.us` instead of the usual URL.  I'd imagine this is quick fix.

**Comment by omarroth** [comment]
Yep, should be fixed with c4d77bc18a726941823dfcc6a0b8e2159d73517e.

**Comment by PrestonN** [comment]
That fixed it.  Thanks!
