### ISSUE TITLE
Dark Mode URL Parameter

### ISSUE THREAD

**Issue by BurnyBoi** [omarroth/invidious#407]
I currently use Invidious without storing any cookies. I was wondering if it is possible to enable dark mode using a URL parameter instead of a cookie preference?

I have tried using ?dark_mode=true and ?dark_mode=1 in the URL, and neither are working. If this is currently not possible, I would like to request this.

**Comment by dimqua** [comment]
`theme=dark` would be better, IMHO.

**Comment by BurnyBoi** [comment]
It's dark_mode in the cookie string, so at the very least it seems like they should match

**Comment by omarroth** [comment]
There was some discussion on adding new themes in #367. Currently though, since the only themes available are `light` and `dark`, I agree that it makes sense to keep things consistent. Added with 46e985b306b06fe37cd066cc1ecd69b504316fb0.
