### ISSUE TITLE
Allow users to save preferences without making an account

### ISSUE THREAD

**Issue by omarroth** [omarroth/invidious#41]
Closes #28.

Allow users to save their preferences/subscriptions/etc as a browser cookie or WebStorage, similar to [FreeTube](https://github.com/FreeTubeApp/FreeTube/).

**Comment by elypter** [comment]
also make it possible to import from and export to invidio.us accounts

**Comment by RuthlessRuler** [comment]
Yes. I was basically searching way to enable Dark Mode since its mentioned as feature and found out that we have to sign in to do so. If Possible please make it possible so that we can do it without signup.

**Comment by aaferrari** [comment]
@elypter maybe it would be possible to do something similar to [DuckDuckGo's preferences](https://duckduckgo.com/settings), unfortunately I couldn't find information about how they have this implemented.

**Comment by omarroth** [comment]
Added with ebcb21dbfe73e4d74465e796d595e0e4e704436c.

Preferences will be imported when creating a new Invidious account or when logging into a Google account. When logging in they will be overwritten.

Preferences are stored as a `PREFS` cookie.

**Comment by r-a-y** [comment]
Thanks for implementing this feature!

I created a Wiki page outlining the `PREFS` cookie and what settings are available:
https://github.com/omarroth/invidious/wiki/Preferences
