### ISSUE TITLE
Search results filtering & sorting

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#420]
Would be nice to have an UI for sorting and filtering search results. By this I mean:
* Filtering by type (video, playlist, etc.);
* Filtering by upload date (for videos);
* Sorting by relevance / upload date / view count / rating;
* Filtering by video quality (4K, HD; 3D, HDR, VR180, [360°](https://github.com/omarroth/invidious/issues/172));
* Filtering by features like "Has subtitles", "Licensed by CC", "Live now".

**Comment by omarroth** [comment]
Duplicate of #179?

**Comment by dimqua** [comment]
Oops, yes.
