### ISSUE TITLE
Recently, playing videos without JS can cause parts of page to get covered

### ISSUE THREAD

**Issue by BurnyBoi** [omarroth/invidious#422]
I've noticed for at least the past few days now, playing a video without JavaScript enabled can cause the video player to cover parts of the page. It's usually covering the title underneath the video, but I've also seen the video player overlap with the recommended video tiles too. 

Here's a screenshot with JS enabled, looking as expected:
https://imgur.com/a/VhaHvlg

And here's what it looks like with JS disabled (notice the title is covered, and the player is getting close to covering the autoplay checkbox):
https://imgur.com/a/GKvmi2l

**Comment by omarroth** [comment]
Should be fixed with 7a54b1d36a5936a6f59d02fa173aa5e421756372.
