### ISSUE TITLE
[Feature Request] Bookmarklet to open a new invideo-tab for the current youtube-tab

### ISSUE THREAD

**Issue by guzszisvww** [omarroth/invidious#428]
Hello.

Would you make a bookmarklet to open a new invideo-tab for the current youtube-tab, please?

Thanks.

**Comment by omarroth** [comment]
You might take a look at [Extensions](https://github.com/omarroth/invidious/wiki/Extensions), which should have what you need.

**Comment by guzszisvww** [comment]
I know about them. Bookmarklet consumes significantly less computer resources than extension. It would be good if a bookmarklet **also** existed.
Thank you.

**Comment by omarroth** [comment]
Added [this](https://omar.yt/722e5c15832840fe1ae8830b7c590254b9e0a45c/invidious-bookmarklet.html) bookmarklet to the list of extensions.

**Comment by guzszisvww** [comment]
Thank you so much.
