### ISSUE TITLE
[Bug] Subscriptions not showing up again

### ISSUE THREAD

**Issue by ghost** [omarroth/invidious#4299]
**Describe the bug**
This has been an issue in previous versions, however I haven't been getting subscription updates for more than a week now, despite setting a proxy for videos.

**Steps to Reproduce**
1. Visit invidious instance
2. see notification bell -> no new subscriptions
3. klick notification bell -> no new videos
4. klick subscribed channel -> new videos shown!

**Comment by absidue** [comment]
Is it your own instance? If it is, did you setup the hourly restart that is mentioned in the post-install configuration?

https://docs.invidious.io/installation/#post-install-configuration
