### ISSUE TITLE
Exception: unknown result set attribute: live_now (DB::MappingException)

### ISSUE THREAD

**Issue by tmiland** [omarroth/invidious#431]
Hi, 

updated to latest master, getting this error: 

> Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com. 

https://invidiou.sh/feed/subscriptions

From the log: 

`Exception: unknown result set attribute: live_now (DB::MappingException)
  from /usr/share/crystal/src/gc/boehm.cr:71:5 in 'read'
  from lib/db/src/db/query_methods.cr:203:9 in 'query_all:as'
  from src/invidious.cr:0:20 in '->'
  from lib/kemal/src/kemal/route.cr:255:3 in '->'
  from lib/kemal/src/kemal/route_handler.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from lib/kemal/src/kemal/static_file_handler.cr:67:9 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???`

What to do?

**Comment by Perflyst** [comment]
Did you updated like described in the wiki? Or, did you have runned the migration scripts from config folder?

**Comment by tmiland** [comment]
> Did you updated like described in the wiki? Or, did you have runned the migration scripts from config folder?

I ran the commands manually as I'm on my own fork.

**Comment by tmiland** [comment]
Did i miss anything?

**Comment by tmiland** [comment]
Tried from the original branch, with the update method in the wiki:

```shell
for i in `git rev-list --abbrev-commit $currentVersion..HEAD` ; do file=./config/migrate-scripts/migrate-db-$i.sh ; [ -f $file ] && $file ; done
NOTICE:  drop cascades to 7 other objects
DETAIL:  drop cascades to materialized view subscriptions_6159fe57
drop cascades to materialized view subscriptions_dbd4d0fb
drop cascades to materialized view subscriptions_a7314f79
drop cascades to materialized view subscriptions_f1210382
drop cascades to materialized view subscriptions_5daf3f0a
drop cascades to materialized view subscriptions_269301b4
drop cascades to materialized view subscriptions_69b078bf
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ERROR:  column "premiere_timestamp" of relation "channel_videos" already exists
ERROR:  column "live_now" of relation "channel_videos" already exists
UPDATE 30446
ALTER TABLE
ALTER TABLE
UPDATE 1873
ERROR:  column "subscribed" of relation "channels" already exists
ERROR:  column "subscribed" is of type timestamp with time zone but expression is of type boolean
LINE 1: UPDATE channels SET subscribed = false;
                                         ^
HINT:  You will need to rewrite or cast the expression.


```

**Comment by tmiland** [comment]
Database has been reset, and all users and data lost.

**Comment by Perflyst** [comment]
How has the database reset? Did you droped it?

**Comment by tmiland** [comment]
> How has the database reset? Did you droped it?

Yes, just as i did the last time #359. Tried to restore from backup, which ended up with even more errors.

**Comment by omarroth** [comment]
Apologies for not responding earlier. What errors are you encountering when attempting to restore from backup?

**Comment by tmiland** [comment]
> Apologies for not responding earlier. What errors are you encountering when attempting to restore from backup?

From the log:

```text
Exception: relation "subscriptions_dbd4d0fb" does not exist (PQ::PQError)
  from lib/pg/src/pq/connection.cr:157:7 in 'read'
  from lib/pg/src/pq/connection.cr:152:7 in 'expect_frame'
  from lib/pg/src/pg/statement.cr:19:5 in 'query_all:as'
  from src/invidious.cr:0:20 in '->'
  from lib/kemal/src/kemal/route.cr:255:3 in '->'
  from lib/kemal/src/kemal/route_handler.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in '???'
  from lib/kemal/src/kemal/static_file_handler.cr:67:9 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???

```

Also tried to restore just the users, but there where none in the backup file, so the more i tried to get it working, the worse it got, so the easiest thing to do then is to start all over. 

Unfortunate for the users though. :disappointed:

**Comment by tmiland** [comment]
Tried all possible ways now to restore the db, but not successfully. 

So, what I'm wondering is; What are the exact commands i need to run, to safely update the database (without breaking anything), without using the migration scripts?

I'm on PostgreSQL 11.

If a simple update.sh script could be provided, with the required commands, I'd be very glad!

This is just way too bothersome to work with...  :cry:
