### ISSUE TITLE
Downloading 720p - video/mp4 results in file with duplicate extension (.mp4.mp4)

### ISSUE THREAD

**Issue by emanruse** [omarroth/invidious#432]
#### STR

0. Example: https://invidio.us/watch?v=zymRNmdzF2k
1. Select e.g. 720p - video/mp4
2. Click 'Download'

#### Expected

Filename `Colorful Big Discoball _ 4K Relaxing Screensaver-zymRNmdzF2k.mp4`

#### Actual

`Colorful Big Discoball _ 4K Relaxing Screensaver-zymRNmdzF2k.mp4.mp4`

Doesn't happen with 360p - video/mp4.

**Comment by omarroth** [comment]
Should be fixed with 13924a83537040e6101f17dc07f8197edb12eab4.
