### ISSUE TITLE
Embedded videos should use user preferences such as proxying

### ISSUE THREAD

**Issue by ajvsol** [omarroth/invidious#435]
Related: #177 
If Google domains are blocked then embedded Invidious videos don't load properly, despite being logged into Invidious and having proxy preferences switched on so that the videos still load properly when viewing them directly on the Invidious website.

**Comment by omarroth** [comment]
Added with c15790f230ae9d7da13fd894de54eb73772ce7ea.

**Comment by ajvsol** [comment]
Is this live on the main site now? Doesn't seem to work yet for me.

**Comment by omarroth** [comment]
It is live and appears to be working for me. I'm able to use the `Proxy videos?` when using an embed on another site. Is there an example you could provide that isn't working for you, or is the console showing any errors?

**Comment by ajvsol** [comment]
I'm using the [Embed Invidious](https://addons.mozilla.org/en-GB/firefox/addon/hooktube-embed/) browser extension to change YouTube embeds to Invidious ones. I'm not sure if it works differently from normal Invidious embeds but I can't get it to proxy.

**Comment by ajvsol** [comment]
Nevermind, I worked out it's because of the First Party Isolation preference in Firefox. Thanks for the feature!
