### ISSUE TITLE
Add "go back" option to livestreams

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#437]
On Youtube you can (if the streamer has enabled it) start the livestream from beginning if the streamer is still live or choose a specific time stamp on where you start watching or re-watch sth.

**Comment by Perflyst** [comment]
Was this added? I can now go back to beginning in livestreams...

**Comment by omarroth** [comment]
Forgot there was an open issue for this, added as part of 4345b1d930e30832b1248ace108eb64cfcb04d68.

**Comment by Perflyst** [comment]
Cool, thanks!
