### ISSUE TITLE
Click on a time in video description does nothing

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#443]
If there is a time, e.g. `15:00` in the video description invidious just offers `javascript:void(0)`. On YouTube you get `https://www.youtube.com/watch?v=<videoID>&t=900s` (video position with the minutes in seconds)

**Comment by omarroth** [comment]
Links should have an `onclick="player.currentTime(900)` so that it is able to skip to the specified time without reloading the page. Could you provide an example where clicking doesn't work?

**Comment by Perflyst** [comment]
Ah, maybe there is no "go back" in livestream which I have mentioned in another issue. That is probably why

**Comment by Perflyst** [comment]
I have tested again with https://invidio.us/watch?v=tBiPumGnVT4 and it works as expected. Didn't find this bug anymore, but found something else mentioned in #627
