### ISSUE TITLE
Theme change when refreshing

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#447]
When refreshing the page, sometimes the theme will change on its own (light to dark - dark to light)
I also noticed that sometimes the website will directly open with the dark theme setup and change back to the light theme when changing page / refreshing.

Gif : https://i.imgur.com/zHpTMI8.gif (no cookies were stored)

**Comment by omarroth** [comment]
Should hopefully be fixed with 388e58bf1e33c1caea1ce9bfb266c2ade4103a34. Unfortunately I'm only able to reproduce on invidio.us, so I suspect the issue only occurs with low memory/high usage.
