### ISSUE TITLE
Thin Mode doesn't work

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#448]
According to https://github.com/omarroth/invidious/pull/43 , enabling Thin Mode "removes all images from the site, except for the CAPTCHA and the video thumbnail on the watch page."

After enabling it the only images that are removed are the one used by the recommended videos

**Comment by omarroth** [comment]
Should be fixed with 7a0f0ca5cecb0dc5cc65effa878a456cc3cce4aa.
