### ISSUE TITLE
[Feature Request] SearchEngine-like page

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#449]
Having a page that looks like a search engine, including only a search box and some basic stuff might be a good idea.

Example (Searx) : https://i.imgur.com/i18iPGd.jpg

**Comment by omarroth** [comment]
See also #295.

**Comment by PopeRigby** [comment]
Why would you do that exactly?

**Comment by omarroth** [comment]
You can now do this now by setting "Default home" to "" in your preferences. You can also remove the feed menu by setting all entries in "Feed menu" to "".

**Comment by TheFrenchGhosty** [comment]
Amazing, thanks for that.

One more thing, can you add a way to have it centered vertically (like SearX or every other search engine)?
