### ISSUE TITLE
Annotations support

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#45]
It would be nice if the player it uses supported Annotations (such as the ones that appear in the corner and the clickable boxes).

**Comment by omarroth** [comment]
I'm looking into this, but I'm having trouble finding a good way to display them without using the official YouTube player.

**Comment by Zero3K** [comment]
Its okay if it doesn't get implemented.

**Comment by Zero3K** [comment]
Unless you or someone else can come up with a way to do it later on.
