### ISSUE TITLE
Disable proxy option server wide 

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#453]
Add an option to completely disable proxy videos (expect e.g. livestreams) and also dash serverwide.

I know ppl who do not have unlimited traffic but want to host an instance. If they exceed the limit their traffic will be very pricy. So using less traffic is better for them.

**Comment by johnwmail** [comment]
Hi, what is proxy mean?

if enable proxy, then
client/browser --> invidious/server --> proxy server/proxynova --> youtube?
or client/browser --> proxy server/proxynova --> youtube?

and if disable proxy?
client/browser --> youtube
or client/browser --> invidious/server --> youtube

thanks.

**Comment by omarroth** [comment]
If "Proxy videos?" is enabled, then Invidious will proxy videos through itself, so:
client/browser --> invidious/server --> youtube

If a video is blocked where the instance is hosted, then it will be:
client/browser --> invidious/server --> proxy server --> youtube

If that option is disabled, then it will look like this:
client/browser --> youtube

This is only for videos. Images, thumbnails, and requests for video/channel info are still proxied.

**Comment by johnwmail** [comment]
Ok, understand now, thank you.

**Comment by omarroth** [comment]
Looking into this right now. From a quick glance, this would appear to disable `local=true`,  livestreams, DASH playback, and the download widget, since they all use proxying.

I think the original issue suggests an exception for livestreams. Should there by any other exceptions?

**Comment by Perflyst** [comment]
I don't know what exactly needs the most traffic.
Maybe you can create a basic option to disable "proxy" serverwide with subcategories for e.g. "Download", "Livestream", "Dash" (maybe Livestream and Dash together?)

**Comment by omarroth** [comment]
Added with 2cc25b1e6e5fec79b393d077ecb7b1ceee332b48. Supported options are `'dash', 'livestreams', 'downloads', 'local'`. Example `config.yml`:

```yaml
disable_proxy:
  - downloads
  - dash
```

It's also possible to use `disable_proxy: true` to disable all forms of proxying.

**Comment by Perflyst** [comment]
Added to the wiki https://github.com/omarroth/invidious/wiki/Configuration

Works as expected.
