### ISSUE TITLE
Video thumbnails are not cached

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#456]
Right now, invidious don't cache the videos thumbnails in the browser, this is not ideal in term of loading time (client) / data usage (client/server) / load (server).

https://i.imgur.com/gHTQwNe.gif

**Comment by cyaniventer** [comment]
@omarroth also css, fonts and favicons should be cached.

**Comment by Perflyst** [comment]
CSS takes around 130-170ms
Images take up to 4s

This font `https://invidio.us/fonts/ionicons.woff2?v=4.4.1` takes around 1s to load

**Comment by cyaniventer** [comment]
It's not about you, many have slow internet connection and limited bandwidth. Also caching images, css, fonts & favicon would save lots of bandwidth both for end user and the server. Currently my feed is about 700KB gzipped and without images it is <20KB, see the difference?

**Comment by omarroth** [comment]
As mentioned in the Matrix server, Invidious includes headers from YouTube that should make the client cache thumbnails:
![image](https://user-images.githubusercontent.com/14208607/55297547-cbe9df80-53ec-11e9-9175-55885710f43d.png)

They unfortunately appear not to be working as expected, which is why this is labeled as a bug.

Static resources hosted on Invidious are already cached, see [here](https://github.com/omarroth/invidious/blob/master/src/invidious.cr#L4491).

**Comment by cyaniventer** [comment]
is something wrong with this report then? -> https://gtmetrix.com/reports/invidio.us/Xaf7Ix4a

**Comment by omarroth** [comment]
The report appears correct. Invidious does not cache as aggressively for various reasons that results in it being scored quite poorly by that site, which recommends static assets by cached for a minimum of 1 month.

Is there anything from the report that I missed?

**Comment by cyaniventer** [comment]
It says that css, fonts and favicon is cached for 1 day and those images for 5 minutes. I think that 5 minutes time should be longer and for favicon and fonts it should be infinite. I can't say about css, is that altered often?

**Comment by Perflyst** [comment]
@cyaniventer as far as I can see in this report, the images are cached for 5 minutes?

**Comment by cyaniventer** [comment]
@Perflyst 

![gtmetrix report for invidio.us](https://user-images.githubusercontent.com/47819045/55494686-de685100-5658-11e9-9af0-bffae3f18e3e.png)

See below it has information about favicons, css and fonts too.

**Comment by omarroth** [comment]
Added partial fix for images with 62a4c82e95212a45608708dddd967072b478157f. Headers for caching weren't being correctly processed.

**Comment by omarroth** [comment]
JS, CSS, favicons, and fonts are now cached for 1 month with a `?v=` to provide new versions. 

As mentioned above, thumbnail caching should now be handled as expected. Video thumbnails support additional headers (`ETag`, `If-None-Match`, etc.) that provide better caching than 5-minutes and isn't reflected in the above report.
