### ISSUE TITLE
Share button to provide a short URL

### ISSUE THREAD

**Issue by gloschtla** [omarroth/invidious#461]
Would you add a SHARE button? Let people know that "_watch?v=_" can be removed from the URL. example: 
https://invidio.us/xpWu4_hp00M 

Or even better: 
If someone visits the full-length URL to a video, invidio.us should always redirect to a shorter URL by default.

https://invidio.us/**watch?v=**xpWu4_hp00M

**Comment by omarroth** [comment]
You can use this button:

![Screenshot_20190405_203254](https://user-images.githubusercontent.com/14208607/55663340-7180c280-57e2-11e9-8573-071732bbbc7f.png)

To get a direct link, embed, or options for sharing using other services.
