### ISSUE TITLE
Improve TLS protocols and cipher suites

### ISSUE THREAD

**Issue by emanruse** [omarroth/invidious#463]
Currently invidio.us supports TLS 1.0 and 1.1 but not TLS 1.3. Additionally it uses several weak ciphers:

https://www.ssllabs.com/ssltest/analyze.html?d=invidio.us&hideResults=on

**Comment by Perflyst** [comment]
You can set your own rules in your webserver if you host your own instance.

invidio.us does run with the internal "crystal webserver" which probably does not have support for higher TLS version

**Comment by omarroth** [comment]
TLS for invidio.us is handled by the load balancer provided by DigitalOcean. If there is a major issue that I should report to them then please mention it here. The report linked however still appears to give the site an 'A' ranking.

dev.invidio.us does directly expose the Crystal webserver, and returns [similar results](https://www.ssllabs.com/ssltest/analyze.html?d=dev.invidio.us&hideResults=on). Other [major](https://www.ssllabs.com/ssltest/analyze.html?d=google.com&s=216.58.195.238) [sites](https://www.ssllabs.com/ssltest/analyze.html?d=youtube.com&s=172.217.164.110) support the same ciphers considered "weak", so I do not believe this is an issue with Invidious.

**Comment by emanruse** [comment]
A is not A+. Security is not a single score. Look at the details, SSL labs shows quite well what the issues are.

Also - why would you compare yourself with "major sites" which don't care about user privacy? If Google and YouTube use plain HTTP - would you do that because they are "major"?

TLS 1.0 and 1.1 will be deprecated in 2020. Some providers have already done that.

https://www.digitalocean.com/ uses CloudFlare - the biggest MITM decrypting proxy network, contrary to a privacy respecting site. What is even worse: they don't even use what CloudFlare gives for free - strong ciphers and TLS 1.3. This means lots of negligence on top of everything else.

**Comment by omarroth** [comment]
> Security is not a single score.

This is an excellent point. Testing using [sslanalyzer](https://sslanalyzer.comodoca.com/?url=invidio.us) reports no warnings, [ssldecoder](https://ssldecoder.org/?host=invidio.us&port=&csr=&s=) reports 1 warning, and [wormly](https://www.wormly.com/test_ssl/h/invidio.us/i/165.227.255.23/p/443) gives the site a 100%.

> Also - why would you compare yourself with "major sites" which don't care about user privacy? If Google and YouTube use plain HTTP - would you do that because they are "major"?

My point is that SSLLabs does not consider the issues mentioned serious enough to significantly affect their score. If you'd prefer not to compare against the sites I listed, you could compare against [duckduckgo.com](https://www.ssllabs.com/ssltest/analyze.html?d=duckduckgo.com&s=184.72.104.138&hideResults=on), [snopyta.org](https://www.ssllabs.com/ssltest/analyze.html?d=snopyta.org&s=95.216.24.230&latest), or [ssllabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=ssllabs.com) itself. 

YouTube does not use plain HTTP. Attempting to access `http://youtube.com` will automatically redirect to `https://youtube.com`.

> https://www.digitalocean.com/ uses CloudFlare

Can you provide a source for this? The certificate for `digitalocean.com` is signed by DigiCert. The certificate for `invidio.us` is signed by LetsEncrypt.

Could you please provide specific details on what issues need to be addressed by this project?

**Comment by emanruse** [comment]
> My point is that SSLLabs does not consider the issues mentioned serious enough to significantly affect their score.

My point was exactly the same, i.e. - details need to be fixed, and not just ignored because of the overall good score. Of course you will always be able to find sites which don't do it. Still the argument "it can be worse" doesn't really make it excellent ;)

BTW here is a nice comparison of various services and their scores in various tests. Mainly mail related but you can also use them for evaluation of this project.

> Can you provide a source for this?

```
[~]: host www.digitalocean.com
www.digitalocean.com has address 104.16.25.4
www.digitalocean.com has address 104.16.24.4
[~]: curl -s https://ipinfo.io/104.16.25.4
{
  "ip": "104.16.25.4",
  "city": "",
  "region": "",
  "country": "US",
  "loc": "37.7510,-97.8220",
  "org": "AS13335 Cloudflare, Inc."
}
```
> Could you please provide specific details on what issues need to be addressed by this project?

In the context of the current issue - everything that the SSL Labs test shows as orange/red. Perhaps also consider the tests on the dismail table (btw dismail.de itself has impressive SSL Labs results).

In general - as we said security has many dimensions. Even if I was an expert in all of them I couldn't possibly provide specific details in full as it needs a lot of time and tests. But if you can fix the issues I reported so far it would be a great first step. If I notice something else I will report that too.

**Comment by omarroth** [comment]
This is not an issue with Invidious.

Invidious uses the default cipher suites provided by the [Crystal standard library](https://github.com/crystal-lang/crystal/blob/3817a99db9b1a9bb2fa007a91ef0c857d80d097f/src/openssl/ssl/context.cr#L15), which in turn uses the default security suites as recommended by [Mozilla](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29). 

The official instance is behind a load balancer provided by DigitalOcean, which uses the same default security suites.

If you believe this is an issue with either the Crystal standard library, or services provided by DigitalOcean I would recommend raising an issue with them. Otherwise I don't believe there is anything else mentioned in this issue that needs to be addressed.

**Comment by emanruse** [comment]
@omarroth

As of today the SSL Labs report shows an A+ overall rating. However there is still work to be done (enable TLS 1.3, disable 1.1, 1.0 and weak ciphers, use DNS CAA, perhaps also SNI). 

If entity X has limitations or recommends something which can't match available (and surely not exotic but fairly standard) technology possible options are:

- report the issue upstream
- not use product/services by entity X

Obviously I cannot report issues on your behalf. What I can (and have done) is to report here what I have noticed. The rest is simply beyond my reach.

**Comment by Perflyst** [comment]
> enable TLS 1.3, disable 1.1, 1.0 and weak ciphers, use DNS CAA

If the crystal webserver supports 1.3 this is a very good idea.
DNS CAA is very easy and can be enabled right now probably.

```
invidio.us.            14400   IN      CAA     0 iodef "mailto:security@invidio.us
invidio.us.            14400   IN      CAA     0 issue "letsencrypt.org"
invidio.us.            14400   IN      CAA     0 issuewild "letsencrypt.org"
```

The last one is optional. If you do not use a wildcard certificate than better remove the last one. Uptimerobot is also compatible, they use a normal LE certificate.

**Comment by omarroth** [comment]
> If entity X has limitations or recommends something which can't match available (and surely not exotic but fairly standard) technology

The current configuration matches what I would consider standard for the reasons mentioned above. SSLLabs uses the same, and Mozilla recommends it as the default for supporting a wide variety of clients.

It should be noted that TLS 1.3 is considered experimental by SSLLabs: https://www.ssllabs.com/ssltest/analyze.html?d=invidiou.sh

> not use product/services by entity X

There is a non-trivial amount of effort associated with switching to a different service. Unless there is an imminent security threat, then I'll absolutely look into it.

I trust both DigitalOcean and the fine folks working on Crystal to provide correct defaults rather than try to configure things myself. As mentioned, if there appears to be an imminent security threat I will absolutely raise an issue with them.

**Comment by emanruse** [comment]
Using weak ciphers for being compatibility with older clients will not invite users to update their clients, so it practically encourages insecurity. Of course a decent new client would use the strongest available cipher but if we follow that logic we could similarly switch to plain HTTP or very old insecure things :) As for what Mozilla recommends - I wouldn't care too much. A company which teams up with Google and enables telemetry and all kinds of other stuff by default in their browser, calling that "privacy respect" is simply not to be trusted easily.

> It should be noted that TLS 1.3 is considered experimental by SSLLabs: https://www.ssllabs.com/ssltest/analyze.html?d=invidiou.sh

The issue was opened about indvidio.us, not about invidiou.sh. Obviously the later has TLS 1.0 and 1.1 disabled and different cipher suites.

As for 1.3 it was defined as a standard in August 2018:

https://tools.ietf.org/html/rfc8446

As you can see it obsoletes 1.2 (RFC 5246). Perhaps SSL Lab's tools are not updated?

> There is a non-trivial amount of effort associated with switching to a different service. Unless there is an imminent security threat, then I'll absolutely look into it.

Having TLS 1.0 and 1.1 enabled is exactly such an imminent thing. I don't know what else you might mean. Are you expecting to somehow get notified about traffic for particular users being decrypted by an adversary?

> I trust both DigitalOcean and the fine folks working on Crystal to provide correct defaults rather than try to configure things myself. As mentioned, if there appears to be an imminent security threat I will absolutely raise an issue with them.

Why not share the current discussion with them and see what did they answer?

**Comment by leonklingele** [comment]
SSL Labs score is up to `A+` now. The site still supports TLS1.0 and TLS1.1, but personally I feel like this should be kept as-is as long as the service is not used by devices which only support TLS1.0.

@omarroth in case you decide to deploy a custom TLS configuration, make sure to enable `OCSP stapling`. The Mozilla recommendation https://ssl-config.mozilla.org/ might be of interest too.

**Comment by omarroth** [comment]
Will do. With regards to TLS1.0:

> Starting on August 20th 2019, all DigitalOcean's Load Balancer will stop accepting TLS 1.0 connections, and on October 15th 2019 and we will also stop TLS 1.1 connections. These versions are out of date and can be potential vectors for abuse.
>
> Major browsers and CDNs will stop supporting these connections in March 2020 and the more modern versions, TLS 1.2 and 1.3, are broadly supported and provide a safe path for growth. Our Load Balancers currently support TLS 1.2 and we will add support for 1.3 in the future.
