### ISSUE TITLE
2 things [running & video preview] 

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#464]
1. how run invidious on hosting website like infinitefree 
2. add preview of videos like youtube (when you drag your mouse in bar & see pic from vid)

**Comment by omarroth** [comment]
I'm unfortunately not familiar with the service you mentioned. Invidious requires Crystal and Postgres, which I expect may be a problem when using free services. There is some work on supporting Heroku, see #162.

See #379. Animated thumbnails are signed by YouTube, so it's only possible to provide them for specific parts of the site, or by using JS.

**Comment by EsmailELBoBDev2** [comment]
> See #379. Animated thumbnails are signed by YouTube, so it's only possible to provide them for specific parts of the site, or by using JS.

nope! i mean when you move your mouse in video bar & see what come next at video

**Comment by cyaniventer** [comment]
@EsmailELBoBDev2 That would be complex (because will have to mess with video.js, record user's mouse movement) and imo not necessary.

**Comment by omarroth** [comment]
Currently there are two plugins available for handling preview thumbnails:
- https://github.com/dirkjanm/videojs-vtt-thumbnails
- https://github.com/blacktrash/videojs-sprite-thumbnails

Both support previews in the format provided by YouTube: [example](https://i9.ytimg.com/sb/V2pLEZds1iE/storyboard3_L1/M0.jpg?sqp=ovOX_wMGCLOp4uMF&sigh=rs$AOn4CLD7efL1Xss8tEOQGC3TdfwRVFy_SA). These are signed by YouTube but should be possible to provide on the watch page.

Looks like the only thing that would need to be added is support for storyboard URLs (`/sb/:id/...`), then integration into the player should hopefully be fairly straight-forward.

**Comment by EsmailELBoBDev2** [comment]
well, looks like you understand you will do to make it work so MAKE IT!

**Comment by cyaniventer** [comment]
@omarroth wouldn't that make the page more js heavy and work real slow for some users? Maybe disable this too with thin mode, otherwise this looks like a good idea.

@EsmailELBoBDev2 don't write in caps. It is mostly used to express anger on the internet.

**Comment by EsmailELBoBDev2** [comment]
@cyaniventer aaaa caps for me to mean anger its more like shout or make word clear for reader so yeah i not mean to fight ofc!

**Comment by EsmailELBoBDev2** [comment]
oops i closed it xD

**Comment by omarroth** [comment]
Added support for storyboard URLs with 62a4c82e95212a45608708dddd967072b478157f.

**Comment by omarroth** [comment]
I would like video previews to be added to the player before closing.

**Comment by EsmailELBoBDev2** [comment]
@omarroth okay! i just tried to decreased the number of tickets.

**Comment by omarroth** [comment]
No worries, just helps me keep track of things :)

**Comment by omarroth** [comment]
Added with 6d92775ab546969230366b5bddbe51d36f73e7c7.

**Comment by EsmailELBoBDev2** [comment]
yeah but... not want break happy but there is no minutes shown when i move mouse (like yt)

**Comment by omarroth** [comment]
Tracked in chrisboustead/videojs-vtt-thumbnails#6.
