### ISSUE TITLE
make seperate buttons for register/login

### ISSUE THREAD

**Issue by cyaniventer** [omarroth/invidious#467]
Buttons for register and login should be different because people may type their usernames wrong and the procedure for both is same - type user/pass -> pass captcha test -> done. Same steps for both register and login, users may by mistake create a new account.

**Comment by omarroth** [comment]
The flow is actually different for register and login.

For login: user/pass -> done
For register: user/pass -> captcha -> done

Notice on the CAPTCHA page the text is "Register", rather than "Register/login".

**Comment by cyaniventer** [comment]
> The flow is actually different for register and login.

Oh! I didn't notice that.

> Notice on the CAPTCHA page the text is "Register", rather than "Register/login".

Yes I saw that but I think it's very easy to miss it. I did miss it 1st time and created a new account while I discovered #468
