### ISSUE TITLE
login issues with hidden service

### ISSUE THREAD

**Issue by cyaniventer** [omarroth/invidious#468]
I am not able to login to invidious from http://kgg2m7yk5aybusll.onion/ & http://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion/

# cases

## I type in correct user/pass

- Nothing happens, invidious just takes me to home page as if nothing ever happened. 

## I type wrong user/pass

- It says wrong password if password is wrong and takes me to register page if username is wrong.

**Comment by omarroth** [comment]
I am able to login on both. I suspect the case is that an extension or setting in the browser is blocking a session cookie from being stored. I'm assuming you're using TBB?

**Comment by cyaniventer** [comment]
No I am using firefox and I do use uMatrix. I have whitelisted invidious hidden service in uMatrix, also checked that both invidio.us and hidden service have same policies. 

> I am able to login on both.

Then that closes this. Maybe the browser is messsing up because it's weird url and over insecure connection (firefox thinks so).

**Comment by omarroth** [comment]
If you're still encountering this I would like to spend more time trying to reproduce. If you're using Firefox, mind providing a few more details on how you're accessing the hidden service?

**Comment by cyaniventer** [comment]
I am using the socks5 proxy to proxy dns request along with my traffic through Tor.

**Comment by cyaniventer** [comment]
Same behaviour with firefox's safe mode too. Also, nothing shows up in storage tab under developer tools.

**Comment by omarroth** [comment]
Appears to be a misconfig when issuing cookies, should be fixed.

**Comment by cyaniventer** [comment]
Now it shows `Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com. `. I am logged in and every request's response is this.

**Comment by omarroth** [comment]
I'm able to login in as normal using the config you described (Firefox w/ tor proxy). Are you able to login through https://invidio.us, or are you encountering errors wherever you try to login?

**Comment by cyaniventer** [comment]
oh, yes it works now.
