### ISSUE TITLE
Download subtitles

### ISSUE THREAD

**Issue by Jtasiu** [omarroth/invidious#470]
Is it possible to add the ability to download subtitles? 

Adding all auto generated subtitles to download options could make the list long so I think it would be good to just to have download options for all proper subtitles, English auto generated subtitles and if possible a .zip file download option for all proper subtitles and all auto generated subtitles.

**Comment by cyaniventer** [comment]
I use youtube-dl to download both subtitles and video, you might want to look into https://github.com/ytdl-org/youtube-dl#subtitle-options

**Comment by Jtasiu** [comment]
Yes, youtube-dl is great but having this for invidious is much better in terms of convenience and local downloads.

**Comment by omarroth** [comment]
Unfortunately I would consider this out of scope for the project. The amount of customizability required for making this a worthwhile feature is not really worth it IMO, and something that youtube-dl is designed to accomplish much better.

I believe I've mentioned in #83, but downloading requires a couple things that make it more resource intensive for the server. In this specific case you could likely this with the help of a [JS library](https://stuk.github.io/jszip/) to produce the requested file, although this adds what I would consider unnecessary bloat.

The download functionality is designed to meet the basic needs of most users, who only need to download a single video or audio file. For more advanced users, people who want custom filenames, downloading multiple assets/resolutions, and muxing the audio+video (for higher resolutions), I can personally recommend youtube-dl.

**Comment by Jtasiu** [comment]
Oh, didn't know that. Invidious provides each video and audio format so I thought subtitles wouldn't be much more intensive. Would providing just available proper subtitles and English auto generated subtitles be possible or is it intensive regardless of which subtitles?

**Comment by cyaniventer** [comment]
Invidious already has subtitles option so it downloads the subtitles anyways, you can get it here -> `https://invidio.us/api/v1/captions/<video-id>?label=English&hl=en-US`

replace <video-id> with the video id of the url (after ?v=).

@omarroth Maybe adding a simple download subtitles and then asking users which language would be better?

**Comment by omarroth** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/14208607/55689141-d1907980-5946-11e9-9132-c41fb84d57cf.png)

**Comment by Jtasiu** [comment]
@omarroth Yep that is what I had in mind.

**Comment by cyaniventer** [comment]
Yes, adding option to download zip is not necessary imo.

**Comment by omarroth** [comment]
Added with 5e141e869d0817ab179e287967451a7def135674.
