### ISSUE TITLE
Add locale URL parameter

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#476]
Hi!

I know there is already an option to change the locale using a cookie but I would like to be able to update this cookie with an URL parameter.

Says I want to change the locale for french, I would type something like : `https://invidio.us/?locale=fr_FR`

What do you think?

**Comment by omarroth** [comment]
You can use `?hl=LOCALE` the same as you would on YouTube. Supported options are `ar, de, en-US, es, eu, fr, it, nb_NO, nl, pl, ru` and are case sensitive.

**Comment by Booteille** [comment]
Oh! Great! Thanks!

Is it wanted to have for two of them region subtags instead of having just the country code?

**Comment by omarroth** [comment]
I believe that is to distinguish different dialects, e.g. `en_US` vs `en_GB`, although `en-US` should probably be renamed to `en_US`.

**Comment by Booteille** [comment]
Yes, I guess so. This is just weird it's only for English and Norwegian languages!
But anyway, thanks for your answers. Except if you have ideas about enhancing this, I think you can close the issue!

Thanks!
