### ISSUE TITLE
Go to settings and return to same video and same playlist

### ISSUE THREAD

**Issue by CSDUMMI** [omarroth/invidious#477]
If you open a video in a Playlist and then go to the settings
and click `save preferences`, you get back to the same video, but not to the list.

**Comment by CSDUMMI** [comment]
Where is the settings view defined?
Where could this bug be fixed?

**Comment by CSDUMMI** [comment]
This is the request resulting from the change to preferences from a playlist:

`https://invidio.us/preferences?referer=/watch?v=XMB0ri4qgwc&
list=PL3yXMgtrZmDqhsFQzwUC9V8MeeVOQ7eZ9`

I think this URI is interpreted wrong:
Instead of appending the `&list` to
the `referer` parameter, `list` is another
GET Parameter and once you want
to go back to your playlist, invidious
uses the content from `referer` and ignores `list`
completely. 

I think  a simple `encodeURI` could solve the problem.

**Comment by omarroth** [comment]
Apologies for not getting to this sooner, should be fixed with ad8750b40d7faab76548fb6501d1d52b7899d371.

**Comment by CSDUMMI** [comment]
https://github.com/omarroth/invidious/blob/ad8750b40d7faab76548fb6501d1d52b7899d371/src/invidious/views/template.ecr#L67
There too, perhaps?

**Comment by CSDUMMI** [comment]
But I think it now actually works.

**Comment by omarroth** [comment]
> https://github.com/omarroth/invidious/blob/ad8750b40d7faab76548fb6501d1d52b7899d371/src/invidious/views/template.ecr#L67
> 
> 
> There too, perhaps?

`current_page` is only used in views and so is already escaped [here](https://github.com/omarroth/invidious/blob/ad8750b40d7faab76548fb6501d1d52b7899d371/src/invidious.cr#L261). `referer` is used directly in some places so needs to be escaped in views.

If it works as expected we can close this.
