### ISSUE TITLE
Add playlists support in embeds

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#478]
Invidious lacks support for playlists in embeds, as you can see by opening [this link](https://invidio.us/embed/videoseries?list=PLRwUc8Zs1_DTar9C4s5z856k1e7hYgUpD).

We already discussed about it on Matrix but I open an issue to follow up the thread.

Thanks!

**Comment by omarroth** [comment]
Thanks for the follow-up! Added with 9a7fea0447f606840cb2227c0254501b908a3a3a.

**Comment by Booteille** [comment]
Thank you! Great to see this added that fast! Keep the good work going!
