### ISSUE TITLE
Add a webpage and an API to manage existing instances

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#479]
As discussed on Matrix, I open this issue.

I propose to add a better way to manage known instances, as PeerTube does : instances.joinpeertube.org

Anyone can propose to add an instance (maybe we should add some checks somewhere to be sure it's an Invidious instance) to the list. We already have https://uptime.invidio.us/ but it needs to be updated by admins and depends on third party. More, with the add of such feature, we could offer an API for Third-Party apps and extensions. So they would be able to list automatically existing instances and maybe choose the better one based on the ping or other parameters.

**Comment by omarroth** [comment]
Related: #164.

Currently, roughly half of the instances listed [in the wiki](https://github.com/omarroth/invidious/wiki/Invidious-Instances) have  `/api/v1/stats` enabled, which provides information useful for exposing an API as proposed (version, user count, etc).

It was suggested that uptime.invidio.us could pull directly from the wiki to provide a list of instances. For an instances.invidio.us , I can imagine a similar method would be useful here. Example flow:
- Pull list of instances from the wiki
- Filter instances that don't respond to `/api/v1/stats` (or have it disabled), filter by version or any other parameters
- Pull uptime info from [uptime.invidio.us](https://uptime.invidio.us/api/getMonitorList/Am9LrCXJA)  (optional)
- Present in format similar to instances.joinpeertube.org

I likely won't have time to do this for a while, but anyone that would like to help work on it please get in touch.

**Comment by Booteille** [comment]
I was off for some weeks. 

Did anyone showed his/her interest in working on that or Matrix?

**Comment by omarroth** [comment]
I don't believe so, although obviously there's still interest in having something like this exist :)

**Comment by Booteille** [comment]
Yeah, okay. I will not be able to make it but I think I'll update a simple text file for my own purposes until someone works on it.

Thanks for your answer, Omar!

**Comment by omarroth** [comment]
See if https://instances.invidio.us suits your needs.

**Comment by Booteille** [comment]
Great! I was just looking this thread yesterday! You've read my mind!

Is it possible for an user to add an instance by himself? 
Like on https://instances.joinpeertube.org/instances

Anyway, that's a great step forward for having more instances, IMO.

I was thinking about integrating an automatic instance selector in Invidition, with fallback to a healthy instance if the one choosed is not working at the time.

Thanks, Omar!

**Comment by omarroth** [comment]
Yes, instances are pulled from [the wiki](https://github.com/omarroth/invidious/wiki/Invidious-Instances), which is open for anyone to edit.

For other questions or issues I'd recommend creating a new issue in the [relevant repo](https://github.com/omarroth/instances.invidio.us).

Cheers.
