### ISSUE TITLE
[Feature-request] Download text related to video, description and all the comments

### ISSUE THREAD

**Issue by deriv** [omarroth/invidious#480]
As title states, I think it would be a very nice feature to be able to download description and all comments with replies, just plain text-file would be nice and no special formatting required. Available as an additional item in the Download-options. Something like this:

> Bob
> 
> What kind of frontend you use for watching YouTube?
> 2 days ago | YT |  0
> 
> Hide replies
> 
> Alice
> 
> Invidio.us naturally, there can be only one.
> 3 days ago | YT |  0
>

**Comment by omarroth** [comment]
Thoughts on this are very similar to #360. The main issue is that it takes longer to provide the more comments there are, which can result in a timeout. Similarly in the issue I linked:

> The problem with providing a flat list is that it requires pulling each page of videos first and then compiling them, which presents problems for a web app.

Providing it in the format you described seems application-specific. Is there a reason to prefer plaintext over using [`/api/v1/comments`](http://invidio.us/api/v1/comments/CvFH_6DNRCY?pretty=1)? I expect writing a script similar to the one in the linked issue will be much more useful.

Similarly you can download a video's description as part of [`/api/v1/videos`](https://invidio.us/api/v1/videos/CvFH_6DNRCY?pretty=1).

I'm also concerned that the requested functionality is very user-specific. The [API](https://github.com/omarroth/invidious/wiki/API) provides a much more flexible way to do what you want. To print comments in the above format for example:
```
$ curl 'https://invidio.us/api/v1/comments/CvFH_6DNRCY?pretty=1' -s | jq -r '.comments|.[]|"\(.author)\n\(.content)\n\(.publishedText) | [YT] | \(.likeCount)\n\n---------\n\n"'
Alan Petruj
I loved it at 12 years old. Still love it today at 59 years old.
1 years ago | [YT] | 8079

---------


Suthern Savage
Everyone's comments are all sophisticated and I'm over here like this is dope
1 months ago | [YT] | 2098

---------


Captain Ghost
When the last human on the earth nearly die, this will be the piece to close our existence
1 months ago | [YT] | 1586

---------

...
```

There's also [youtube-comment-suite](https://github.com/mattwright324/youtube-comment-suite) and [youtube-comment-downloader](https://github.com/egbertbouman/youtube-comment-downloader) which I expect are better suited for this purpose.

**Comment by deriv** [comment]
My the example was just mimicking viewing comments below a video on a desktop webbrowser. Thus the plaintext-suggestion was more due to simplicity and clarity, reading comments without any formatting,  metadata, user profile links whatnot is just most useful way for me when I store educational videos.  At best it can be much more pleasant experience than reading comments from the webbrowser, as opening replies sometimes fails and when video has huge amount of comments, clicking load more and viewing all the replies can be time consuming.

To be honest, I was quite clueless of the api-possibilities, especially with invidio.us before your handy piped curl-command, unfortunately I'm not that well versed in the art of cli fu.

**Comment by deriv** [comment]
Also, I guess this is related to the sheer total amount of  comments you mentioned earlier but there's no replies at all in `/api/v1/comments` , no matter what video.

**Comment by omarroth** [comment]
That's a mistake on my part. The endpoint you want is `/api/v1/comments/:id` where `:id` is the video ID, so for example [`/api/v1/comments/CvFH_6DNRCY`](https://invidio.us/api/v1/comments/CvFH_6DNRCY).

I don't expect this to be directly integrated into the UI for the reason mentioned above, but if you or anyone else would like help writing a tool to do something like what I commented above feel free to hop on the [Matrix server](https://riot.im/app/#/room/#invidious:matrix.org).

You might also take a look at [youtube-comment-downloader](https://github.com/egbertbouman/youtube-comment-downloader) and [youtube-comment-suite](https://github.com/mattwright324/youtube-comment-suite) which provide more tools for downloading and processing comments.
