### ISSUE TITLE
https://invidio.us/c/<user>/live not working

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#481]
On YouTube you get via /c/<user>/live to the livestream if the user is live.
Invidious already can identify the user via /c/<user> and goes to the channel. Adding /live just redirects back to invidio.us

```
$ curl -I https://invidio.us/c/<user>/live
HTTP/1.1 302 Found
Content-Type: text/html
X-Frame-Options: sameorigin
Location: /
Content-Length: 
```

**Comment by omarroth** [comment]
Marked as enhancement since this hasn't been added yet. Should be fairly simple to add.

**Comment by omarroth** [comment]
Added with 5c4defdb8e4594df940e3713ee71cbebbaf59726.
