### ISSUE TITLE
[Enhancement] Separate Media RSS feeds for [Shorts, Videos, Live Streams]

### ISSUE THREAD

**Issue by APT37** [omarroth/invidious#4846]
**Problems**
- Some creators upload shorts just to please the algorithm, but I don't wan't to watch those.
- On the other hand, some creators (e.g. [NileBlue](https://www.youtube.com/channel/UC1D3yD4wlPMico0dss264XA/shorts)) upload interesting short content, which I do want to see.

**Solution**
As the title says, separate feeds for each kind of video. 

**Alternative**
Adding corresponding tags to the existing feed. Even if this is possible, it still requires feed readers to be able to filter by those tags.

**Comment by unixfox** [comment]
You mean subscription feeds, right?

**Comment by ChunkyProgrammer** [comment]
Should already be possible to use atom feeds for shorts only/live streams only/videos only

Nile Blue channel Id: UC1D3yD4wlPMico0dss264XA

Shorts: (replace UC from channel Id with UUSH and that's your playlist id)
https://redirect.invidious.io/feed/playlist/UUSH1D3yD4wlPMico0dss264XA

Live: (replace UC from channel Id with UULV and that's your playlist id)
https://redirect.invidious.io/feed/playlist/UULV1D3yD4wlPMico0dss264XA

 Videos: (replace UC from channel Id with UULF and that's your playlist Id)
https://redirect.invidious.io/feed/playlist/UULF1D3yD4wlPMico0dss264XA
