### ISSUE TITLE
Invidious displays wrong number of videos in playlist

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#485]
If a playlist has a lot videos than Invidious just displays "0 videos", example: https://invidio.us/channel/UCCj956IF62FbT7Gouszaj9w/playlists ("Trailers - BBC")

This playlist has for real 2098 videos.
![Trailers - BBC](https://user-images.githubusercontent.com/26308977/56017147-ab7c2800-5cfe-11e9-8b43-b18256c827d3.png)

**Comment by omarroth** [comment]
Should be fixed with 80a567bf1ecaa4dc141294c426bf0a92638a1fd1.
