### ISSUE TITLE
Show "views" on video search results for livestreams

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#487]
YouTube does display the views on the videos already on the search results

This also is available on livestreams with "X watching"

**Comment by omarroth** [comment]
Added with b51fd7fc1325ed0008c5aa7043585013ef62c86a. Currently it isn't supported in user's feed or on `popular` page, since they both use [this struct](https://github.com/omarroth/invidious/blob/0.16.0/src/invidious/channels.cr#L11). Likely will be added soon, but will need DB changes.

**Comment by Perflyst** [comment]
Works now as expected

**Comment by Perflyst** [comment]
Views are not shown for livestreams on search results. You can only see them on the left side if I have opened the livestream.

**Comment by omarroth** [comment]
Should be fixed with f08d53b0c6c32bc4a696765d98af3efa3039348a, currently shows "`x` watching" as "`x` views".

**Comment by Perflyst** [comment]
Is fixed, thanks
