### ISSUE TITLE
Share via mail "forces" mail.ru?

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#489]
Share via mail does force mail.ru, why? I would suggest replacing it with a `mailto:`.

**Comment by omarroth** [comment]
Added with mkhazov/videojs-share#20. Updated from omarroth/videojs-share@49072a7c2446a6bb26c64e39073c56259e385067 with e8c5246645c2d09ddbe6b1e85d0ebcc1478e7e30.

**Comment by Perflyst** [comment]
Works now as expected, thanks!
