### ISSUE TITLE
Feature request: toggle "Listen by default"

### ISSUE THREAD

**Issue by johnwmail** [omarroth/invidious#491]
Hi, it is more convenient, if invidious can toggle "listen only" on view/watch page.
(not only on setting page, just for this video), thanks.

When I watch/listen invidious on mobile/3G network and the network is slow,
I could toggle on "listen only" for this video.

**Comment by omarroth** [comment]
This button:

![Screenshot_20190414_131649](https://user-images.githubusercontent.com/14208607/56097285-c80f9000-5eb7-11e9-98ac-f5398856ab92.png)

Will toggle audio only on the watch page.

**Comment by Booteille** [comment]
Maybe that would be a good idea to change the icon for something more intuitive? I am thinking about "Headset" as NewPipe does.
Maybe adding a label could be more explicit for users, too.

![Screenshot_20190414-234310_NewPipe](https://user-images.githubusercontent.com/2203721/56099628-c2de2f80-5f0f-11e9-9277-3fbf999a122d.png)

**Comment by omarroth** [comment]
Consistency with NewPipe is good. Changed icon to `ion-md-headset` with ca515f2eae41cdfe79ac0186926a1b56371f16a4.

There's already hover text for "Audio mode". To add text underneath it would probably make more sense to move it into the left side with view count etc.

**Comment by johnwmail** [comment]
Yes, It work, thanks.

**Comment by Booteille** [comment]
> Consistency with NewPipe is good. Changed icon to `ion-md-headset` with [ca515f2](https://github.com/omarroth/invidious/commit/ca515f2eae41cdfe79ac0186926a1b56371f16a4).
> 
> There's already hover text for "Audio mode". To add text underneath it would probably make more sense to move it into the left side with view count etc.

Yeah. I think there could be a better place for this option. Close to the title, I always have the feeling it's a part of it.

**Comment by Hahlh** [comment]
Same for me. I searched for this feature and was only able to find it through @omarroth s answer.
The first place I expected this feature to be, was in the quality selector menu for the video.
This could also be a good place for the "audio-only-mode toggle".

Another possibility would be the same symbol toggle directly besides this setting. 

![image](https://user-images.githubusercontent.com/45669613/58159147-93e07980-7c84-11e9-9e25-f542e68e9c6f.png)
