### ISSUE TITLE
Add "Autoplay" button for playlists embeds

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#492]
Hi!

I think there should be an option to autoplay (not just load it) videos from a playlist once the user enabled it.

**Comment by omarroth** [comment]
Duplicate of #268?

**Comment by Booteille** [comment]
Sorry, I didn't well explained what I had in mind.

I was thinking about a specific button, incorporated on the embed player. 

But after I've read your last comment on this issue, I think it can be considered as a duplicate, yeah.
