### ISSUE TITLE
Add "continue" URL parameter to playlists

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#493]
Since I wanted to have a feature to autoplay videos (for music) when I click on "autoplay next videos" only, I added the functionnality to Invidition. With that video does not just load but actually really autoplay the video.
I check the `continue` URL parameter and if it's present, I enable the `autoplay` parameter.

If you don't plan to add an autoplay (not just the autoload next video), could you please add `continue` parameter to videos loaded automatically by a playlist?

It's useful for 3d party apps since we can rely on this parameter to know when a video has been loaded automatically. I don't want the player to start automatically when the user manually loads it but only if it has been triggered by the `continue` feature.

**Comment by omarroth** [comment]
Similar to #492, a corresponding `continue_autoplay=1` or similar is expected to be added as part of #268. It will be enabled by default so I don't think it will be necessary for any additional logic in plugins/extensions.

**Comment by Booteille** [comment]
Oh, neat! Thanks!

**Comment by omarroth** [comment]
Added with bb5a1ad5136d9c85dd89def312921ae61bd4f856.
