### ISSUE TITLE
[Bug] cannot subscribe to any new channel - RSS rate limits

### ISSUE THREAD

**Issue by illnesse** [omarroth/invidious#4949]
suddenly can't subscribe to any channels via api or web

http://invidious.xxxxxxx:3000/channel/UCGoa2AvvdmZMgk01cEYMC1A
clicking subscribe button does nothing (500 Internal Server Error, see log below)

updating to latest revision didn't help
Current version: 2024.09.25-8d160887 @ master

for some reason i can unsubscribe and resubscribe to channels i'm already subscribed to, though

```
Exception: Deleted or invalid channel (InfoException)
from src/invidious/channels/channels.cr:175:5 in 'fetch_channel'
from src/invidious/channels/channels.cr:151:15 in 'get_channel'
from src/invidious/routes/subscriptions.cr:49:9 in '->'
from lib/kemal/src/kemal/route.cr:13:9 in '->'
from src/invidious/helpers/handlers.cr:30:37 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:32:7 in 'call_next'
from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:32:7 in 'call_next'
from src/invidious/helpers/handlers.cr:94:12 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:32:7 in 'call_next'
from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
from /usr/share/crystal/src/fiber.cr:143:11 in 'run'
from ???

```

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4121

**Comment by unixfox** [comment]
![Screenshot_20240925-233058.png](https://github.com/user-attachments/assets/8e5bba4e-0921-4f8a-8951-a2d4dff51dcb)

**Comment by VnkCCENcXH0c3AhnijQ0y7SBeZx27** [comment]
[screen-capture.webm](https://github.com/user-attachments/assets/4b5c1f78-e14e-4844-8f12-d1c63f5b04c3)

**Comment by VnkCCENcXH0c3AhnijQ0y7SBeZx27** [comment]
[screen-capture1.webm](https://github.com/user-attachments/assets/c23c930a-6a7c-4a33-9d4b-b1cc8cc3bc2c)
