### ISSUE TITLE
Gain volume?

### ISSUE THREAD

**Issue by johnwmail** [omarroth/invidious#495]
Hi, Is it possible gain volume to, let say 120% or 150%?
Thanks.

**Comment by proyb6** [comment]
I’m curious what is the reason to increase pass 100%?

**Comment by johnwmail** [comment]
Why? because some youtube/video volume is too low.
and hard to listen even 100% volume.

**Comment by omarroth** [comment]
See [this answer](https://stackoverflow.com/a/46264832) on SO. It's possible using the Web Audio API, but the source needs to be CORS-compatible and does not currently appear work with the player Invidious uses.
