### ISSUE TITLE
reset speed to 1x once the player has caught up with the source (livestreams)

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [omarroth/invidious#497]
nonsense example
[speed=2](https://invidio.us/watch?v=XPJYO2kB0rk&quality=dash&speed=2
)

you can't watch in future

**Comment by Perflyst** [comment]
If #437 is added than speed=2 is useful.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
yes or even if you pause and play it faster afterwards. but the title says: initially. shouldn't initially be startable with speed >1x. in real live mode

**Comment by Perflyst** [comment]
Okay, I see what you mean. But you add the url parameter manually or is there any link which adds it? If you added it manually than just dont do it

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
i did it just for demonstration. but if you set preferences to something above 1x speed. this affects livestreams also. safe effect. please exclude them from speed config?

**Comment by omarroth** [comment]
Livestreams start with some amount of buffer (e.g. 5 seconds). Rather than exclude livestreams from the config, speed should reset to 1x once the player has caught up with the source.

**Comment by omarroth** [comment]
Added with 4345b1d930e30832b1248ace108eb64cfcb04d68.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Cool that you made this improvement :)
