### ISSUE TITLE
"Recorded" livestreams not treated like a video

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#499]
Some streamers put their livestream online as "video" either listed or unlisted on their channel.
Invidious still recognizes them as livestream, e.g. you cannot change video quality.

But, you can navigate in the video timeline and skip parts etc.

**Comment by Perflyst** [comment]
I just mentioned that it is impossible to download such a video, the dropdown is just empty.

Nex to this, the "audio only mode" just displays the video as normal and is not working as intended. Comments are also not shown.

**Comment by omarroth** [comment]
Could you provide an example?

**Comment by Perflyst** [comment]
Did you changed anything here? It seems like it is now treated as a normal video.

**Comment by omarroth** [comment]
I don't believe so, it may be a per-video issue or a bug in the extractor. Would you mind providing an example?

**Comment by Perflyst** [comment]
Closing this because the cause was found on the matrix channel.

YouTube has probably not finished processing the video.
