### ISSUE TITLE
Livestream support

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#5]
It would be nice if it supported the playback of Livestreams. Right now I get a "No compatible source was found for this media" error message when trying to view one.

**Comment by omarroth** [comment]
The main issue with this is that YouTube adds [CORS headers](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) on all assets, which functionally means you can't make XHR requests (which are required for viewing livestreams). There is already a [feature](https://github.com/omarroth/invidious/blob/master/src/invidious.cr#L976-L1040) in Invidious that allows you to get around this, but it's not been tested fully.

**Comment by Zero3K** [comment]
The feature should be added/enabled on the site so I can test it.

**Comment by omarroth** [comment]
I misspoke: there are a couple of issues with that are still being fixed. Namely: how to properly generate a working manifest and how to serve the necessary assets. You can generate a manifest for the given video by asking `/api/manifest/dash/id/:id`. It will also probably be necessary to append `?local=true` to swap the links in the manifest with those that have a corrected header. Currently it seems like only [youtube-dl](https://github.com/rg3/youtube-dl) can use it. If you have youtube-dl installed you can do `youtube-dl https://invidio.us/api/manifest/dash/id/:id?local=true`; the [reference player](https://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/) seems to be having trouble.

Main point is that there are still some issues that need to be worked out, but expect it to be added soon.

**Comment by Zero3K** [comment]
I wonder if it is possible to view the chat along with the livestream. If it is, please consider implementing it.

**Comment by Zero3K** [comment]
How much longer until it is supported?

**Comment by omarroth** [comment]
Not currently, although I would recommend opening that as a new issue "Add live chat" or similar. 
In addition, it seems pretty closely related to #68. Most of the value of live chat it seems to me would be in being able to respond to the video and others in real time, which requires a Google account.
