### ISSUE TITLE
Add shortcuts (same as on YouTube)

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#501]
YouTube has a lot of shortcuts, you can find a list [here](https://support.google.com/youtube/answer/7631406)

**Comment by omarroth** [comment]
Invidious already supports quite a few of these, `spacebar`, `k`, `j`, `l`, `f`, `m`, other player shortcuts should be fairly straightforward. Invidious also supports changing playback rate with `Shift+<` and `Shift+>` which does not appear to be listed.

Several others also appear not to be listed that appear with `Shift+?` on the YT player.

**Comment by Perflyst** [comment]
Didn't noticed that as the shortcuts only work if the player is "focused". If I have multiple windows opened and click back to the browser window which is opened than shortcuts dont  work.

Also noticed that l and j only jumps 5 seconds, not 10.
An interesting shortcut is `Shift` and a number (0, 1-9) to skip the a specifc timestamp in the video

**Comment by alexgleason** [comment]
My partner and I switched to Invidious on our HTPC. She keeps smashing spacebar to pause during a conversation, and says "dammit" when it scrolls to the comments.

Would be awesome if spacebar paused the video regardles of whether it's focused! Thank you.

**Comment by Perflyst** [comment]
YouTube also does not pause the video and scrolls to the comments if not focused. This is normal behaviour, at least for me.

**Comment by alexgleason** [comment]
Hmm I think maybe it's because on YouTube the video stays fullscreen between videos. We've gotten used to leaving it not fullscreen since the autoplay feature causes the page to refresh. Maybe this is why the video stays focused on YouTube but not Invidious.

**Comment by omarroth** [comment]
I think on YouTube the player is focused by default. Likely would make sense for Invidious to behave similarly.

**Comment by practik** [comment]
> I think on YouTube the player is focused by default. Likely would make sense for Invidious to behave similarly.

I believe on YouTube it's only focused after the video has started playing, so no autoplay = no keyboard shortcuts. The ability to have shortcuts enabled with autoplay disabled was one of my favorite things about Iridium (https://github.com/ParticleCore/Iridium/wiki/Features#shortcuts_always_active), and I'd love to see it become a part of Invidious as well.

**Comment by nikolayhg** [comment]
The YouTube shortcuts work no matter whether the focus is on the video or on the title, description or comments - which of course is very user friendly. Would be nice, if invidious behaves the same.

**Comment by omarroth** [comment]
Implemented by #678.
