### ISSUE TITLE
Add support for Web Notifications API

### ISSUE THREAD

**Issue by aurora-of-earth** [omarroth/invidious#502]
So that when a new video is received, a notification is sent to the client browser.

- <a href="https://www.w3.org/TR/notifications/">w3.org/TR/notifications</a>
- <a href="https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API">developer.mozilla.org/en-US/docs/Web/API/Notifications_API</a>
- <a href="https://developer.chrome.com/apps/notifications">developer.chrome.com/apps/notifications</a>

**Comment by omarroth** [comment]
Expect this to be added as part of #195 once #469 is implemented.

**Comment by omarroth** [comment]
Added with 0338fd42e15ee9803068e6d6eeb04d78b94f321c. You can enable them by clicking "Enable web notifications" in preferences.
