### ISSUE TITLE
Can't import NewPipe subs

### ISSUE THREAD

**Issue by oxxz** [omarroth/invidious#505]
I cant import my subscriptions .json-file from my NewPipe to Invidious. The only error i get is  "Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to [mail]. I really dont know what info to give more than that its exported yesterday with the latest NewPipe.

**Comment by omarroth** [comment]
I'm having trouble reproducing this with subscriptions exported from NewPipe 0.16.1. The issue may be the number of subscriptions being imported. 

If you don't mind, could you provide the file you're trying to import? If you don't want to provide it here you can send it to omarroth@protonmail.com .

**Comment by theScrabi** [comment]
@TobiGr maybe something we should be interested in.

**Comment by oxxz** [comment]
@omarroth i've sent the .json file to your mail. I think it's around 150 subs, it that too much too handle? I tried to make a new .json with just 1 subscription and that worked fine to import on invidious.

**Comment by omarroth** [comment]
Appeared to be an issue importing channels with `/user/:user`, should be fixed with 19ed5bf993a070534e1c0745de16f03c7409b738.

**Comment by oxxz** [comment]
@omarroth seems like that problem is solved, but now im just getting "504 Gateway Time-out", is this because of a big file or something up with the server, or is it a new bug with that commit? i tried 3 times, but i get 504 every time

**Comment by omarroth** [comment]
Likely the size of the import. I've pushed f15b7cebac9d9383340a33f4f091badc5d07d2ca which should prevent timeout.

**Comment by heio123** [comment]
Hey, I am also having trouble importing my subscriptions and I think its because its of the size of the import. Anything I can do to help fix this bug?

**Comment by heio123** [comment]
Hey, I am also having trouble importing my subscriptions and I think its because its of the size of the import. It just goes to the https://invidio.us/data_control?referer=/ page and endlessly loops. Anything I can do to help fix this bug?

**Comment by oxxz** [comment]
late answer, but now everything works awesome! big up to you!
