### ISSUE TITLE
Add the HTML lang attribute

### ISSUE THREAD

**Issue by jorgesumle** [omarroth/invidious#514]
So that non-humans can know the language of the website (useful for screen readers, search engines, etc.). [According to the HTML 5.2 Recommendation](https://www.w3.org/TR/html52/semantics.html#the-html-element):

> Authors are encouraged to specify a lang attribute on the root html element, giving the document’s language. This aids speech synthesis tools to determine what pronunciations to use, translation tools to determine what rules to use, and so forth.

**Comment by omarroth** [comment]
Added with f1f96a30a73539842ea7a6dc848f98a5b7115e1d.
