### ISSUE TITLE
Python SSL breaking.

### ISSUE THREAD

**Issue by Orthdron** [omarroth/invidious#515]
Environment Description:
Self hosted. Reverse proxied
Running inside tmux session
Videos are not proxied

Issue:
Starting the instance, no issues. 
After about 5 minutes of usage, the site just runs too slow. Looking at the output of invidious I noticed SSL flags and latency of 40,000 ms

Attaching image of the same
![Screen Shot 2019-04-28 at 12 27 30 PM](https://user-images.githubusercontent.com/41769111/56867298-a03d2380-69b1-11e9-9a00-c014c52753b9.png)

**Comment by omarroth** [comment]
Would you mind sharing the output of `uname -srm` and distro?

Content of `config.yml` is also helpful, although I assume you're using default options. I'm also assuming you've compiled from source using `crystal build src/invidious.cr --release`.

**Comment by Orthdron** [comment]
![Screen Shot 2019-04-28 at 2 27 05 PM](https://user-images.githubusercontent.com/41769111/56868562-d7b3cc00-69c1-11e9-943c-f42128e5f2ad.png)

**Comment by Orthdron** [comment]
Output of uname srm: Linux 4.15.0-47-generic x86_64

Config file:
channel_threads: 8
feed_threads: 8
db:
  user: kemal
  password: somepassword
  host: something.com
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
domain: yt.something.com
registration_enabled: false

Replaced domain and password. Everything else was default. 
And yes, it was compiled from source.

**Comment by omarroth** [comment]
`feed_threads` and `channel_threads` are likely the issue. Does the service slowdown when either of them is set to `0`, and does it still occur when both are `0`?

**Comment by Orthdron** [comment]
I am using ubuntu.
Trying to set feed_threads and channel_threads to 0 now.
Will post back if successful.

**Comment by Orthdron** [comment]
It has been 13 hours and it is working fine now.
As a developer, I would like to know why the issue happened because of threads?
Maybe I can issue a patch if needed.

**Comment by omarroth** [comment]
Likely an issue in either [refresh_channels](https://github.com/omarroth/invidious/blob/c6c92184d995d9247db37fe46709b07a45f6aa1e/src/invidious/helpers/jobs.cr#L1) or [refresh_feeds](https://github.com/omarroth/invidious/blob/c6c92184d995d9247db37fe46709b07a45f6aa1e/src/invidious/helpers/jobs.cr#L45). I expect a thread isn't cleaning up after itself properly, which is why you would be experiencing slowdown.

Would you mind testing:
```yaml
channel_threads: 0
feed_threads: 1
```
and
```yaml
channel_threads: 1
feed_threads: 0
```

To help determine which or if both have this issue?

**Comment by Orthdron** [comment]
I did set both of them to 1 last night and once again, the instance just crashed.
Now testing with these 2 different configs to see what broke.
will keep you posted.

**Comment by Orthdron** [comment]
this config broke the system.
`channel_threads: 1`
`feed_threads: 0`

Now testing with
`channel_threads: 0`
`feed_threads: 1`

**Comment by Orthdron** [comment]
`channel_threads:0
feed_threads: 1`

this config worked so i think channel_threads is the issue

but the problem with this config is that my subscriptions are not getting refreshed.

**Comment by Orthdron** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/41769111/56997457-d4f9d800-6b75-11e9-952a-4eac710e3a58.png)

Now even with both set to 0. the instance is facing issues.

**Comment by omarroth** [comment]
Would you mind providing the output of `openssl version`?

**Comment by Orthdron** [comment]
OpenSSL 1.1.0g  2 Nov 2017

**Comment by omarroth** [comment]
`crystal --version`?

**Comment by Orthdron** [comment]
'Crystal 0.28.0 [639e4765f] (2019-04-17)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu'

**Comment by Orthdron** [comment]
`Crystal 0.28.0 [639e4765f] (2019-04-17)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
`

**Comment by omarroth** [comment]
Likely related to crystal-lang/crystal#7383. Would you mind uncommenting [this](https://github.com/omarroth/invidious/blob/6d1c150ff5fbc0f69d29f05a6067b7d29378fb80/src/invidious/helpers/handlers.cr#L200) line to see if it fixes the issue for you?

**Comment by Orthdron** [comment]
I did. no affect. it"appears" to be worse now.

**Comment by omarroth** [comment]
Here's a quick attempt at a fix. Let me know if it works for you and if so I can merge it into master.

```diff
diff --git a/src/invidious/helpers/handlers.cr b/src/invidious/helpers/handlers.cr
index 98087ec7..bc1a3896 100644
--- a/src/invidious/helpers/handlers.cr
+++ b/src/invidious/helpers/handlers.cr
@@ -200,9 +200,12 @@ class DenyFrame < Kemal::Handler
 end
 
 # Temp fix for https://github.com/crystal-lang/crystal/issues/7383
-class HTTP::Client
-  private def handle_response(response)
-    # close unless response.keep_alive?
-    response
+class HTTP::UnknownLengthContent
+  def read_byte
+    ensure_send_continue
+    if @io.is_a?(OpenSSL::SSL::Socket::Client)
+      return if @io.as(OpenSSL::SSL::Socket::Client).@in_buffer_rem.empty?
+    end
+    @io.read_byte
   end
 end
```

**Comment by Orthdron** [comment]
Sorry for the delay. I did not get a notification.
Testing it now.

**Comment by Orthdron** [comment]
Tested it for 24 hours, did not work.

**Comment by omarroth** [comment]
I've pushed a couple changes to master that may help with this issue, so you'll want to make sure you're up to date if you're not already.

Since I'm having trouble reproducing I'd also recommend hopping on the [Matrix server](https://riot.im/app/#/room/#invidious:matrix.org) so it's a bit faster/easier to test out any changes.

**Comment by Orthdron** [comment]
On latest version.
Been running for a week now. No issues.
Thanks for fixing.
