### ISSUE TITLE
Docker container `libc` build error

### ISSUE THREAD

**Issue by fredfortier** [omarroth/invidious#517]
I'm trying to Docker build from the master branch using: `docker-compose build`. Here is the output:
```
Using kemal (0.25.2)
Using radix (0.3.9)
Using kilt (0.4.0)
Using exception_page (0.1.2)
Using pg (0.16.1)
Using db (0.5.1)
Using sqlite3 (0.11.0)
crystal: /usr/lib/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/../lib/libicuuc.so.64)
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c sed -i 's/host: localhost/host: postgres/' config/config.yml &&     shards update && shards install &&     crystal build src/invidious.cr' returned a non-zero code: 1
```
My host Linux kernel is: `5.0.7-200.fc29.x86_64`

**Comment by omarroth** [comment]
Mind posting the output from `docker-compose --version` and `docker --version`?

I'm having trouble reproducing. You may try `docker-compose build --force-recreate` to see if it was a temporary issue.

**Comment by m0se** [comment]
I'm facing the same issue when building the docker image directly with `docker --no-cache -t inv -f docker/Dockerfile .`.

I also did a `docker pull archlinux/base` to be sure I have the latest version of the FROM image, but still getting:
```
crystal: /usr/lib/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/../lib/libicuuc.so.64)
```
My Docker version is `18.09.3` and my Kernel is `4.9.0-4`

**Comment by omarroth** [comment]
Added suggested fix with e3f37c14db1ab5673df042f936dbba6cb5ed8444. 

There is an Alpine dockerfile provided in #361, which I expect is better maintained and is reported to be lighter, so something to look into switching to.

**Comment by omarroth** [comment]
My mistake. Issue should be open until @fredfortier can confirm the fix works for him as well.

**Comment by theScrabi** [comment]
Hei I have the problem that my container gets stuck when it comes to the line
`Using sqlite3 (0.11.0)`
@omarroth could this be the same problem, or should I open up a new issue?

**Comment by omarroth** [comment]
If it gets stuck after `Using sqlite3...` it may just be taking a long time compiling. Assuming you're up-to-date this issue should be resolved, although I'd like to close after @fredfortier can confirm this is fixed for him as well.

You might try using the Dockerfile provided in [#517](https://github.com/omarroth/invidious/issues/361#issuecomment-463247424) to see if that resolves your issue. Otherwise I'd suggest opening a new issue with `Docker image gets stuck after installing dependencies`/`Docker image is slow to compile` or similar title with your Docker version.

**Comment by m0se** [comment]
@theScrabi Just out of curiosity, does this happen consistently when you try to build? 
I had this same issue yesterday. After waiting for some time at `Using sqlite3 (0.11.0)` I aborted the build and started a new one which was successful.

**Comment by theScrabi** [comment]
@m0se it only happens on my vServer with Ubuntu 18.04.2 and docker 18.09.5 installed.
On my notebook locally it builds just fine.

**Comment by theScrabi** [comment]
The docker file from #512 lacks a dependency fore `mime`:
```
Installing sqlite3 (0.11.0)
Error in src/invidious.cr:19: while requiring "kemal"

require "kemal"
^

in lib/kemal/src/kemal.cr:6: while requiring "./kemal/helpers/*"

require "./kemal/helpers/*"
^

in lib/kemal/src/kemal/helpers/helpers.cr:1: while requiring "mime": can't find file 'mime'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?

require "mime"
^

ERROR: Service 'invidious' failed to build: The command '/bin/sh -c shards install && crystal build src/invidious.cr --release' returned a non-zero code: 1
```

I am opening a [new issue](https://github.com/omarroth/invidious/issues/551).

**Comment by omarroth** [comment]
I'm going to close this for now, if this is still an issue for @fredfortier or anyone else please mention and I'll be happy to re-open.
