### ISSUE TITLE
Feature Request: Buffer whole audio track in listen=1 mode

### ISSUE THREAD

**Issue by gloschtla** [omarroth/invidious#518]
How much of the audio is buffered, when I start listening while having my browser app in the background? This feature would be great, if you wanna listen to a podcast or music track while going out (mobile data connection). So you would like to buffer the whole audiotrack before disconnecting from WiFI (local wLAN).

**Comment by elypter** [comment]
i think this is not possible to control with the current player

**Comment by omarroth** [comment]
My understanding is that this is not possible, since buffering is determined by the browser, not the player. See videojs/video.js#1725. 

I would recommend using the download button to achieve similar functionality. Audio-only streams are already provided so it should be possible to playback on most devices.

**Comment by elypter** [comment]
would it be possible to save it to localstorage and then create an url for videojs? i know about base64 urls but maybe there is something more elegant.

**Comment by johnwmail** [comment]
Why not just download the audio file, before you disconnect wifi?

**Comment by gloschtla** [comment]
Not everyone knows how to download. 
I compared invidious' downloaded file with that from t.me/AudioTubeBot 
And I prefer the latter, because it creates smaller OGG files with OPUS codec in mono channel. Perfect for Podcasts.

**Comment by johnwmail** [comment]
> Not everyone knows how to download.

![Screenshot_2019-05-01 r MiniLadd BEST Of ALL TIME Reddit Posts #2(1)](https://user-images.githubusercontent.com/1752235/57010275-5f305380-6beb-11e9-91b5-211a5ea82923.png)

**Comment by Perflyst** [comment]
You will probably do it on mobile. There is the download button not that present.

**Comment by elypter** [comment]
but that is a minor issue on its own and a function like this needs to be placed somewhere as well. i understand that for some it would feel a little too cumbersome to download jsut to save a little bandwidth but they would do it if it was jsut a single button and you dont have to remove the file afterwards.  i personally dont need it but i can get behind the convenience factor which is the driving force in most user behavior

**Comment by Pentaphon** [comment]
@gloschtla The player is too basic for this kind of thing. You should download the entire audio file, and play it on something like an audiobook app so you can scrub around, bookmark your position, not lose your position when changing apps, etc.

**Comment by omarroth** [comment]
Closing for now since I don't believe this is currently possible to implement.
