### ISSUE TITLE
Translation Problems

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#521]
so as you know iam the Arabic translator & i found problems in variables (the 'x' things) when i switch invidio.us to English i see something like "100 views" but when i get back to Arabic i see "'x' مشاهدون" so what i can do to fix it (or it's just code problems ?

**Comment by omarroth** [comment]
Appears to be an issue using <code>`</code> (Grave) vs `'` (Single-quote). Should be fixed with 92450920d4087a487252e4028cf7e5070dca01d9.

**Comment by EsmailELBoBDev2** [comment]
wow, i did not noticed that xD & thx :D
