### ISSUE TITLE
Very long videos show wrong length on search results

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#525]
![Screenshot_20190511_160148](https://user-images.githubusercontent.com/26308977/57570803-6daa1680-7406-11e9-9d0f-5fcfa00b0e1d.png)

For examples look here: https://invidio.us/search?q=48h+video

Another one is this one: https://invidio.us/watch?v=8dZoMF2Y8NY
Real duration is `52:13:57` but Invidious shows only `4:13:57` on the search results.

**Comment by Perflyst** [comment]
Got fixed in https://github.com/omarroth/invidious/commit/bdfe170c3b8721c5afe5f7e1fc7abe14308dd98a

**Comment by StefanLobbenmeier** [comment]
Please reopen: I just had this video https://invidio.us/watch?v=P5atYpVtpfA displayed like this: 
![85953E82-E62E-4C05-8E8F-C988B473D892](https://user-images.githubusercontent.com/36509607/80348217-bf44ee80-886d-11ea-9c1a-e96de4935aa3.png)
