### ISSUE TITLE
Captions settings drop down menus have "bad" color

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#526]
I used this video for testing: https://invidio.us/watch?v=I4jqq4Tml1s

![Screenshot_20190511_160643](https://user-images.githubusercontent.com/26308977/57570824-c7aadc00-7406-11e9-9571-03ddaf262cb5.png)

**Comment by Perflyst** [comment]
Fixed in https://github.com/omarroth/invidious/commit/bb15dc57a45a392f53b211883a45fec0bb370b13

**Comment by omarroth** [comment]
Should be fixed with bb15dc57a45a392f53b211883a45fec0bb370b13.
