### ISSUE TITLE
Port 8081 added to links in RSS feeds (Tor instance)

### ISSUE THREAD

**Issue by emanruse** [omarroth/invidious#531]
For the Tor instance the links in the RSS articles of channels have a port `8081` and clicking such a link gives an error in browser:

```
http://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion:8081/watch?v=...<videoID>
```
Removing manually that port number creates a working link.

**Comment by omarroth** [comment]
Appears to be a misconfig, should be fixed.

**Comment by emanruse** [comment]
Seems fixed now.
Thanks!
