### ISSUE TITLE
Preferences not saved using .onion domains

### ISSUE THREAD

**Issue by 86476451** [omarroth/invidious#534]
Using Tor Browser with security set to High. Allowing `media`, no scripts when using Invidious.

To watch videos without enabling scripts or connecting to Google I have to append `&local=true` to every video watched.

**Comment by Perflyst** [comment]
> To watch videos without enabling scripts or connecting to Google I have to append &local=true to every video watched.

On the official onion invidious instances you do not need local=true
It is already enabled by default there.

**Comment by 86476451** [comment]
Oh, that's good! However, unofficial instances have better throughput from my location. 

Out of the two .onion v3 domains I see listed in the wiki, only the one below is reachable currently. Do you know who operates this instance? 

http://fz253lmuao3strwbfbmx46yu7acac2jz27iwtorgmbqlkurlclmancad.onion/

**Comment by Perflyst** [comment]
Don't know, but it is just a reverse proxy to invidio.us

**Comment by 86476451** [comment]
Oh, I thought the unofficial instances connected directly to Youtube. So the connection should really be slower than using the official instance? If that proxy is hosted in Europe, the data would go to the official instance in the US anyways?

**Comment by Perflyst** [comment]
As far as I remember the first two ones listed there are just a reverse proxy to invidio.us
I am currently fixing the third one.. (hosted in Finland)

**Comment by omarroth** [comment]
As mentioned in Matrix, the issue using a reverse proxy is that preferences will be issued for `.invidio.us`, rather than the onion URL. Appears to be fixed.
