### ISSUE TITLE
No issue, only congratulations

### ISSUE THREAD

**Issue by StanGets** [omarroth/invidious#535]
Hi,

Congratulations don't belong to an issue department, but where else may I address my most enthusiastic congratulations and many thanks for such an excellently carried-out project?

_**Invidious**_ is awesome. It allows and demonstrates the full power of html5 when not polluted by a myriad of parasite scripts.

I now have totally abandoned a default video rendering site in favor of _Invidious_ (I use an instance located in Germany given it's closest to my device and runs perfectly the `Dash` quality). Together with the _Invidition_ extension here on Firefox 65.0.5 (x64) / Windows 7 (x64) I now have a context of freedom, privacy, velocity for viewing videos I never would have imagined.

I'd say there has been a before and an after _Invidious_. Brilliant.

**Comment by Perflyst** [comment]
The best place for feedback is either https://matrix.to/#/#invidious:matrix.org or #invidious on freenode. Omarroth is also on reddit /u/omarroth :)

**Comment by StanGets** [comment]
OK, @Perflyst , thanks for the links :)

**Comment by omarroth** [comment]
Very much appreciated, thank you.

**Comment by XXLCXX** [comment]
Invidious is awesome, thank you!
