### ISSUE TITLE
Clicking "View Reddit comments " if no reddit comments are present results in nothing

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#540]
If you click "View Reddit comments" if there are no reddit comments than it looks like something is broken because nothing happens. Maybe some information output would be good here.

**Comment by omarroth** [comment]
I think it makes sense to include this as part of #539 since it appears to refer to the same issue unless I'm missing something.

**Comment by Perflyst** [comment]
On #539 you need to have reddit comments enabled by default. This issue is with youtube comments by default

**Comment by omarroth** [comment]
It should switch back to YouTube comments automatically if it's unable to provide Reddit comments.

The suggestion in #539 is to provide a button to swap to YouTube comments and show something like `No Reddit comments available.`. Wouldn't that also close this issue?

**Comment by Perflyst** [comment]
If it will work also for this one, yes. 

-> If not, I will re-open it in the future.
