### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by trymeouteh** [omarroth/invidious#545]
A handy thing to have will be an extension for when your viewing a YouTube video, channel or playlist on youtube to be able to click the extension button and be taken to the same video, channel or playlist on invidio.us.

**Comment by Perflyst** [comment]
This is probably out of range here. Better request this on the addon Invidition: https://addons.mozilla.org/en-US/firefox/addon/invidition/

**Comment by omarroth** [comment]
I'd recommend looking through [Extensions](https://github.com/omarroth/invidious/wiki/Extensions). Likely the "View on Invidious" bookmarklet is what you want (see #428).

**Comment by trymeouteh** [comment]
The bookmarklet works great! I was looking for some sort of extension which was a button that you will click which can load your current youtube page on invidious.

The bookmarklet does work and it does work on mobile, all you need to do is search for the bookmark name in your URL bar and then tap the bookmark to be redirected.
