### ISSUE TITLE
[Feature request] MP3 download

### ISSUE THREAD

**Issue by stemy2** [omarroth/invidious#546]
Hello,

Audio download is only possible in mp4 and webm. But mp3 downlobd would be better because it is a more common format.

**Comment by omarroth** [comment]
Currently Invidious provides files that can be downloaded directly from YouTube. I don't think it's reasonable to convert them to another format, since it would either have to be done server-side, which I don't think is practical for the number of users, or client-side, which I don't believe is possible using JavaScript.

Similar discussion in TeamNewPipe/NewPipe#507.

**Comment by omarroth** [comment]
I'm going to close this for now since I unfortunately don't believe it's possible in a web app.

**Comment by dimqua** [comment]
Is it ppssible to extract opus or vorbis encoded audio from webm container on server-side and provide the direct links to them?

**Comment by omarroth** [comment]
Unfortunately I don't believe it's practical. Assuming it's possible to extract and repack in a different container without having to store the file, I expect it would still be quite resource intensive and not generally practical for the number of users.

**Comment by talentlessguy** [comment]
It's possible to extract audio on client-side. The feature would be very useful!

here's an example:

```js
const offlineAudioContext = new OfflineAudioContext(numberOfChannels, sampleRate * duration, sampleRate);
let soundSource = offlineAudioContext.createBufferSource();
...
reader.readAsArrayBuffer(blob); // video file
reader.onload = () => {
  let videoFileAsBuffer = reader.result; // arraybuffer
  audioContext.decodeAudioData(videoFileAsBuffer).then((decodedAudioData) => {
    myBuffer = decodedAudioData;
    soundSource.buffer = myBuffer;
    soundSource.connect(offlineAudioContext.destination);
    soundSource.start();

    offlineAudioContext.startRendering().then((renderedBuffer) => {
      console.log(renderedBuffer); // outputs audiobuffer
    }).catch((err) => console.log('Rendering failed: ' + err));
  });
};
```

[reference](https://stackoverflow.com/a/49182456/11889402)
