### ISSUE TITLE
Loading a new video with "Autoplay next video" does not keep "local" URL parameter.

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#549]
I am using uMatrix and I didn't allow googlevideos.com since I am using the "local=true" URL parameter.
I wanted to listen to some musics through Invidious and then clicked on "Autoplay next video".
Even if it loads the next video, it does not keep the "local" parameter so the video won't load.

**Comment by omarroth** [comment]
Should be fixed with de77c710421d515272d1d0fcb2e585243ae2089c.
