### ISSUE TITLE
Proxy Broken in Safari Browser

### ISSUE THREAD

**Issue by sadsafari** [omarroth/invidious#550]
Using proxy by adding "&local=true" to the url on Safari is broken in both iOS and MacOS. Without proxy, videos play flawlessly. With the proxy, it returns the error "The media could not be loaded, either because the server or network failed or because the format is not supported."

I am unable to recreate the error on other MacOS browsers, but it unfortunately effects all browsers on iOS. I'm not sure if it is a WebKit issue.

The following information was obtained using Safari on MacOS:

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (videoplayback, line 0)

VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Comment by Perflyst** [comment]
Would you mind linking some examples? Or do you have this issue on **all** videos (pick some random ones on the startpage)?

**Comment by sadsafari** [comment]
It occurs on every video. The following from the startpage play on Safari fine without the proxy but return the above error when trying to proxy.

https://invidio.us/watch?v=cxneWhjeBnI
https://invidio.us/watch?v=1bHT6n5KUCE
https://invidio.us/watch?v=gkAO2_RKqTo
https://invidio.us/watch?v=yGJLE1UXBjo

**Comment by Perflyst** [comment]
Could you test e.g. https://invidio.us/watch?v=cxneWhjeBnI&quality=dash instead of local=true, please?

**Comment by sadsafari** [comment]
That plays without error in Safari, but it does phone Google.

**Comment by Perflyst** [comment]
This can't be. Dash requires that  is proxied through the server.
Did you check this with the browsers console?

**Comment by sadsafari** [comment]
This is from the console using the Dash url. The Dash url also will not play in Firefox when using uBluck Origin to prevent connections to googlevideo.com.

curl 'https://r2---sn-vgqskned.googlevideo.com/videoplayback?id=o-ABpLRt-UDH5HWuyLA1wB-prLbRhQQo1sWCChWRnLzHr_&itag=18&source=youtube&requiressl=yes&pl=24&ei=3iLoXO7ZDMzXhwbXormABA&mime=video%2Fmp4&gir=yes&clen=17868993&ratebypass=yes&dur=252.122&lmt=1558699875901456&fvip=2&c=WEB&txp=5531432&ip=2604%3Aa880%3A400%3Ad1%3A%3A827%3Ac001&ipbits=0&expire=1558738750&sparams=clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,lmt,mime,mip,mm,mn,ms,mv,pl,ratebypass,requiressl,source&signature=80C63A82B80F43B712EFF21915B5F4E0AE4BAE66.3B60C08279980A3F5B12DB6A4B57C92264822011&key=cms1&host=r2---sn-ab5l6n6e.googlevideo.com&redirect_counter=1&rm=sn-ab5e7k7l&req_id=795f74485b3ca9b1&cms_redirect=yes&ipbypass=yes&mip=199.116.115.142&mm=31&mn=sn-vgqskned&ms=au&mt=1558717611&mv=m' \
-XGET \
-H 'Accept: */*' \
-H 'Range: bytes=0-1' \
-H 'Host: r2---sn-vgqskned.googlevideo.com' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15' \
-H 'Accept-Language: en-us' \
-H 'Accept-Encoding: identity' \
-H 'Connection: keep-alive' \
-H 'X-Playback-Session-Id: 9F905A1A-FABE-4CC5-A5B9-2AE182039039'

**Comment by omarroth** [comment]
A `500` would indicate Invidious is likely not handling the request sent from Safari. Unfortunately I'm not able to test this locally. Would you mind copying the URL (as curl) that returns 500 when using `local=true` on MacOS?

**Comment by sadsafari** [comment]
Here you go! Hopefully this is what you need.

Summary
URL: https://invidio.us/latest_version?id=cxneWhjeBnI&itag=18&local=true
URL: https://invidio.us/videoplayback?id=o-ACbI_fCKjALCzZprgt8t4HAZHqwpaLUMbAeEX6zuvNnq&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-ab5szn7z%2Csn-ab5l6n6e&ms=au%2Crdu&mv=m&pl=49&ei=mY_qXN3EIZLNhgbt3Ze4Cw&initcwndbps=166250&mime=video%2Fmp4&gir=yes&clen=17868993&ratebypass=yes&dur=252.122&lmt=1558699875901456&mt=1558875927&fvip=2&c=WEB&txp=5531432&ip=2604%3Aa880%3A400%3Ad1%3A%3A92a%3Ab001&ipbits=0&expire=1558897657&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&signature=84F647E20DFA762E60653180466388B7814D6342.0C4B18BE0E23E261D65DEC3BC355233CE368EEAD&key=yt8&host=r2---sn-ab5szn7z.googlevideo.com
Status: 500 Internal Server Error
Source: Network
Address: 165.227.255.23:443

Request
GET /latest_version
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
Range: bytes=0-1
Accept: */*
Connection: Keep-Alive
Accept-Encoding: identity
X-Playback-Session-Id: 6EB018C0-BAE0-4ADA-9EE4-2F7F0F325D2F

Redirect Response
302 Found
Location: /videoplayback?id=o-ACbI_fCKjALCzZprgt8t4HAZHqwpaLUMbAeEX6zuvNnq&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-ab5szn7z%2Csn-ab5l6n6e&ms=au%2Crdu&mv=m&pl=49&ei=mY_qXN3EIZLNhgbt3Ze4Cw&initcwndbps=166250&mime=video%2Fmp4&gir=yes&clen=17868993&ratebypass=yes&dur=252.122&lmt=1558699875901456&mt=1558875927&fvip=2&c=WEB&txp=5531432&ip=2604%3Aa880%3A400%3Ad1%3A%3A92a%3Ab001&ipbits=0&expire=1558897657&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&signature=84F647E20DFA762E60653180466388B7814D6342.0C4B18BE0E23E261D65DEC3BC355233CE368EEAD&key=yt8&host=r2---sn-ab5szn7z.googlevideo.com
Referrer-Policy: same-origin

Request
GET /videoplayback HTTP/1.1
Accept: */*
Range: bytes=0-1
Host: invidio.us
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: identity
Connection: keep-alive
X-Playback-Session-Id: 6EB018C0-BAE0-4ADA-9EE4-2F7F0F325D2F

Response
HTTP/1.1 500 Internal Server Error
Content-Type: video/mp4
Access-Control-Allow-Origin: *
Last-Modified: Fri, 24 May 2019 12:11:15 GMT
Content-Security-Policy: default-src blob: data: 'self' https://invidio.us 'unsafe-inline' 'unsafe-eval'; media-src blob: 'self' https://invidio.us https://*.googlevideo.com:443
X-XSS-Protection: 1; mode=block
Expires: Sun, 26 May 2019 13:08:17 GMT
Referrer-Policy: same-origin
Cache-Control: private, max-age=21260
Date: Sun, 26 May 2019 13:08:17 GMT
Content-Length: 8084
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
Content-Range: bytes 0-1/17868993
X-Frame-Options: sameorigin
Server: gvs 1.0
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

Query String Parameters
id: o-ACbI_fCKjALCzZprgt8t4HAZHqwpaLUMbAeEX6zuvNnq
itag: 18
source: youtube
requiressl: yes
mm: 31,29
mn: sn-ab5szn7z,sn-ab5l6n6e
ms: au,rdu
mv: m
pl: 49
ei: mY_qXN3EIZLNhgbt3Ze4Cw
initcwndbps: 166250
mime: video/mp4
gir: yes
clen: 17868993
ratebypass: yes
dur: 252.122
lmt: 1558699875901456
mt: 1558875927
fvip: 2
c: WEB
txp: 5531432
ip: 2604:a880:400:d1::92a:b001
ipbits: 0
expire: 1558897657
sparams: ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ei,initcwndbps,mime,gir,clen,ratebypass,dur,lmt
signature: 84F647E20DFA762E60653180466388B7814D6342.0C4B18BE0E23E261D65DEC3BC355233CE368EEAD
key: yt8
host: r2---sn-ab5szn7z.googlevideo.com

**Comment by omarroth** [comment]
Thanks! Should be fixed with 208bb2d72ffd9559b6df64f1c038392bfa7083ea.

**Comment by sadsafari** [comment]
Thank you! We are back up and running!
