### ISSUE TITLE
Several queries to youtube.com every minute

### ISSUE THREAD

**Issue by yungdan1** [omarroth/invidious#555]
Self-hosted Invidious queries youtube.com several times every minute. Would it be possible to expose a setting to set how often Invidious would query? For example every 5 minutes.

**Comment by Perflyst** [comment]
Setup a local dns caching system like dnsmasq.
"several queries every minute" is nothing. There are probably hundreds and more in a second

**Comment by yungdan1** [comment]
>You want that Invidious only connects every 5 minute to youtube.com? 
Yes. I am assuming that these queries are related to subscriptions. I do not have the need for subscriptions to be updated so often.

**Comment by omarroth** [comment]
If you don't need subscriptions, then you should be able to set `feed_threads` and `channel_threads` to `0` in `config.yml`:
```yaml
channel_threads: 0
feed_threads: 0
# ...
```

Which should cut down substantially on the number of requests.
