### ISSUE TITLE
Registering a new user doesn't check for max length password

### ISSUE THREAD

**Issue by PureTryOut** [omarroth/invidious#556]
When registering an user, the length of the password is never checked. In my case just after setting up Invidious, I registered myself with a password of 60 characters. When trying to log in from a different browser, it always said my password was incorrect, even though I copied it directly from my password manager. Trying to change my password from the original browser also failed, because it both didn't accept my old password, and it required my new password to be less than 55 characters.

I had to wipe my user from the database manually, and after registering again but with a password of less than 55 characters, I can now login everywhere successfully.

**Comment by Perflyst** [comment]
What if you only enter the first 55 chars of your 60 chars password?

**Comment by PureTryOut** [comment]
Like I said, I copy the password from my password manager, so no that is not the case.

**Comment by omarroth** [comment]
It should raise an error when attempting to register with a password longer than 55 characters. 

Testing on both https://invidio.us and locally I'm not able to reproduce the issue. You might double-check to make sure you're up-to-date.

Also added some extra handling with f820706e4f6cfdaea8990c03bfb6bfceaf4188be which should fix handling for passwords < 55 Unicode characters but > 55 bytes.

**Comment by PureTryOut** [comment]
I was running the latest Git. The issue does seem to be resolved now with f820706, thanks!

**Comment by Perflyst** [comment]
@PureTryOut out of interest, would it be possible that you share this password you used there here?

**Comment by PureTryOut** [comment]
Sorry, that is not possible. It's a generated one by my password manager (and way too hard to remember), and I already replaced it with the new one I use now. I don't have a backup either, sorry.
