### ISSUE TITLE
[Feature] Add I2p Instance

### ISSUE THREAD

**Issue by ghbjklhv** [omarroth/invidious#558]
**Feature**: Add I2p instance for better privacy.

**Related Links**:
https://www.invidio.us/watch?v=2ylW85vc7SA

https://geti2p.net/en/about/media

https://geti2p.net/

https://www.wikipedia.org/wiki/I2p

**Comment by dimqua** [comment]
I2pd is more lightweigh and quite stable choice.

**Comment by Perflyst** [comment]
I did not find any setup guide on command line. Do you have a link to some tutorial or example which uses cli to setup a i2p site? Is this even possible?

**Comment by dimqua** [comment]
@Perflyst yes, a short example: https://github.com/PurpleI2P/i2pd/wiki/Using-i2pd#browsing-and-hosting-websites

**Comment by Perflyst** [comment]
Can anyone try this?
http://owxfohz4kjyv25fvlqilyxast7inivgiktls3th44jhk3ej3i7ya.b32.i2p/

It feels incredible slow for me

**Comment by Perflyst** [comment]
Even a demo plaintext site loads longer than 10s
It is probably impossible to use Invidious on I2P

**Comment by dimqua** [comment]
@Perflyst yes, it is slow, but I believe it's still useful with both "thin mode" and "listen by default" options enabled.

**Comment by Perflyst** [comment]
Added mine to the wiki: https://github.com/omarroth/invidious/wiki/Invidious-Instances#eepsite-i2p

Dunno if @omarroth wants to publish an official I2P site for invidio.us database too, if not we can probably close this.

**Comment by dimqua** [comment]
If he doesn't, you can take invidious.i2p domain. :-)

**Comment by omarroth** [comment]
I probably won't have time to for a while. If you'd like feel free to grab the `invidious.i2p` as @dimqua mentioned.

I'd very much like to hear any feedback from @ghbjklhv, otherwise I agree this can probably be closed.

**Comment by Perflyst** [comment]
I have "registered" invidious.i2p on inr.i2p
