### ISSUE TITLE
Can't save any settings/open accounts on my own instance

### ISSUE THREAD

**Issue by samuncle** [omarroth/invidious#561]
Hi first of all a big thanks for your work. I'm now using regularly invidious and its amazing.

I tried to install it on my own ubuntu server, to play around (and maybe contribute).

However when I try to save preferences (like theme/autoplay/etc) it doesn't save them and I can't open an account (it just refresh the page).

Do you have an idea how I can debug this/fix it? I used the auto install script, I also tried to start manually invidious and both worked.

**Comment by omarroth** [comment]
You'll want to make sure `domain: ` is set in `config/config.yml` for the instance. You might also take a look at some of the other options in [Configuration](https://github.com/omarroth/invidious/wiki/Configuration).

**Comment by samuncle** [comment]
Okay, it works now :)

Thanks for the fast reply
