### ISSUE TITLE
Request: Define playback speed in sharing link

### ISSUE THREAD

**Issue by gloschtla** [omarroth/invidious#564]
I love to use invidio.us for listening to podcasts. 
Some of the speakers are only interesting when they speak more quickly.

Request #1: 
When I click on "share", I wish to define a sharing link which contains the playback speed.
??? &speed=1.3x ??? 

Request #2: 
When I click on "share", I wish to get a short link: without watch?v=

Request #3: 
When I click on "share", I wish to define the time, from where the video/audio shall start playing.
t=1m11s  

This is how I would share a podcast:
invidio.us/vid_ID?list=PL_ID&listen=1&t=1m11s  
AND ??? &speed=1.3x ???

**Comment by omarroth** [comment]
[`&speed=1.3`](https://github.com/omarroth/invidious/wiki/List-of-URL-parameters) is the supported option for changing player speed. Updated share plugin to use the short URL with 8521f0408709b26ce57e707f179721d9f78a6807.

I'd suggest opening a new issue for a "Share at current time" or any additional functionality for configuring the share link.

**Comment by tuxayo** [comment]
> I'd suggest opening a new issue for a "Share at current time"

#586

**Comment by omarroth** [comment]
Cheers, closing in favor of #586.
