### ISSUE TITLE
Support Raw mode in Listen mode

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#567]
Currently, when an Invidious link has both `&listen=1` and `&raw=1`, it loads the direct link for a video stream, not an audio stream.

Eg: https://dev.invidio.us/watch?v=ZdKwB6Hp6aw&listen=1&raw=1

**Comment by omarroth** [comment]
Should be fixed with 8cecce75707a31f9aa31d5ecbdb2999afd2dae70.

**Comment by Discookie** [comment]
Yep, thanks!
