### ISSUE TITLE
Cannot watch live records

### ISSUE THREAD

**Issue by outloudvi** [omarroth/invidious#572]
I've seen #330 and #386 but think that this may not be a duplicate since they are talking about live stream while this is talking about live records. (Interestingly, I am able to watch livestreams with default setting of uBlock Origin.)

I experience such problems while attempting to watch a live stream record:

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
HTTP load failed with status 403. Load of media resource https://www.invidio.us/latest_version?id=fQLrjKH6Ijw&itag=22 failed.
An error occured in the player, reloading...
```

Network tab:

![Network tab details](https://user-images.githubusercontent.com/19144373/58756420-f52d0600-852a-11e9-9662-289b1d36a899.png)

Link regarding this video: https://www.invidio.us/watch?v=fQLrjKH6Ijw

Other live records for testing:
* https://www.invidio.us/watch?v=8fFrsKHJ6mE
* https://www.invidio.us/watch?v=_APn4u9DesI

For myself, I'm using a Firefox Developer Edition 68.0b6 on Arch Linux.

**Comment by Perflyst** [comment]
Live records are? Old livestreams? Than these are just normal videos I think

Adding local=true (https://www.invidio.us/watch?v=fQLrjKH6Ijw&local=true) appears to be working for me.

**Comment by outloudvi** [comment]
Adding local=true also works for me.

**Comment by omarroth** [comment]
Closing in favor of #92.
