### ISSUE TITLE
Feature Request: Subscription & Notifications

### ISSUE THREAD

**Issue by trymeouteh** [omarroth/invidious#573]
On YouTube there is the Subscribe button and the bell button, the subscribe button is used to add the channel to your list of "favorite channels". The Bell button will notify you when that channel posts new videos.

On Invidious I have subscribe to over 50 channels and I get tons of videos in my notifications daily and I only usually care about maybe several channels for a period of time.

Please add a settings to choose what channels your subscribe will have notifications on new videos. This way you can sub to 500 channels and only have a dozen channels appear in your notification.

**Comment by omarroth** [comment]
Would it make sense to implement this as part of #482? Then you'd have a specific "bell" tag used for filtering out specific channels.

**Comment by omarroth** [comment]
Closing in favor of #482.
