### ISSUE TITLE
Add support for /attribution_link

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#575]
Examples:
https://www.youtube.com/attribution_link?a=irkzHCoKGXs&u=%2F%3Ffeature%3Dem-subs_digest
https://www.youtube.com/attribution_link?a=J7oeoL6RGpE&u=%2Fwatch%3Fv%3Drmiu4Zx4ZDo%26feature%3Dshare

Looks like it's functionally the same as a `/redirect` link, except it redirects to `&u=` instead of `&q=`.

**Comment by omarroth** [comment]
Added with 1c9085556c2fdf5c645011b740ab9d614254585d.

**Comment by Discookie** [comment]
Yay, thank you!

**Comment by elypter** [comment]
what is the purpose for this? isnt this just so google can track you better? i thought the main purpose of invidio.us was to reduce tracking. this appears more like an anti feature

**Comment by Discookie** [comment]
The purpose of `attribution_link`, as well as `redirect`, is tracking, yes, but that's not a reason for not implementing the endpoint.

If someone were to use something like the Youtube to Invidious userscript, they would be redirected to `invidio.us/attribution_link?[...]`, and they would expect to be redirected to the actual video.  
Without the endpoint, they would be redirected to the front page, or to an error page, which is definitely not the expected behavior.

**Comment by elypter** [comment]
i thought the attribution data is optional. the second link contains a video id. maybe just use it if the id is not in the url

**Comment by Discookie** [comment]
I don't think the current implementation contacts Youtube at all. It just takes the `&u=` URL parameter, and redirects to it.  
I've also seen attribution links to certain playlists or feeds, so it's not only videos that can be accessed via them.
