### ISSUE TITLE
Suggestion regarding the subscriptions page

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#58]
It should have a Drop Down Box to let you choose which subscribed channel's videos to view a list of.

**Comment by omarroth** [comment]
You'll have to provide more detail. Could you provide an example or a sample of what you mean?

**Comment by dimqua** [comment]
I guess a drop-down menu, so you can only see new videos from a particular subscribed channel.

**Comment by omarroth** [comment]
That makes sense, although then I'm confused as to why you wouldn't use the `/channels` page, unless this is part of a larger issue on filtering subscriptions (something more similar to #30).

**Comment by Zero3K** [comment]
The channels page gives me a 500 error.

**Comment by omarroth** [comment]
Is it a specific channel or all channels? Are you trying to access `/channel/:ucid` or `/channels/:ucid`? I need more information.

**Comment by Zero3K** [comment]
I am not doing that. You put /channels in the previous reply so I thought that was a valid page.

**Comment by omarroth** [comment]
Sorry about that!

**Comment by omarroth** [comment]
I think I'm going to close this, as the suggested functionality would duplicate that of the `/channel/:ucid` page. If that page gives you an error, I would recommend opening that as a new issue.

Feel free to reopen this with more details if you're suggesting functionality that is not already implemented.
