### ISSUE TITLE
Generated passwords - can't login

### ISSUE THREAD

**Issue by Robin-Wils** [omarroth/invidious#589]
**What?**  
I use keepassxc and generated my password.  
I can't seem to login with my password... and this happened two times.

**How?**  
I used extended ASCII in my password on the first account,  
and '/*-_...' characters in my second account.

My account-names are 'rmw' and 'rmw_'. I can give you the password of my second account if that is needed, but I would rather sent it in a secure way. The password of my first account  is removed from my database so I can't recover that password.  

I am not sure of the accounts can be recovered, I will wait until I get some replies before I make a new account.

**Comment by omarroth** [comment]
Is there a specific error you're encountering when attempting to login? Or does login time out, or redirect to the homepage with no changes?

If you'd like to send an email to omarroth@protonmail.com I'll be happy to help recover your account.

**Comment by Robin-Wils** [comment]
It just returns "Wrong username or password".  
Email isn't the safest option out there to share passwords, but I will do it, since there is probably a way to change my password.

**Comment by omarroth** [comment]
Should be fixed with fcf377d26b3e54c9b5f72d0a3c497d9504259f56.
