### ISSUE TITLE
Feature Request: click-to-go-to-invidio.us on embedded videos

### ISSUE THREAD

**Issue by jones137** [omarroth/invidious#595]
I started using Invidition Firefox addon and it replaces all YT embedded videos with invidio's proxied ones. However, I lose the ability to quickly open the video on full website (be it youtube.com or invidio.us) - I have to click the share button, copy the link and enter it manually in new tab. On YT's native embed I could just hover and click the video's title to open it instantly in new tab.

Please just include a small arrow button or something like that to accomplish this.

**Comment by elypter** [comment]
there is the icon in the top left corner

**Comment by robrobinbin** [comment]
I'm in a similar situation as @jones137 and have the same request. 

I do not see any icon in the top left corner.

**Comment by elypter** [comment]
maybe it is just part of [this userscript](https://greasyfork.org/en/scripts/375264-youtube-to-invidious). btw i use this one instead of the firefox addon because it doesnt redirect me back if i click the "watch on youtube" link on invidio.us

**Comment by StanGets** [comment]
I do have a top-left icon on embedded redirected to invidious youtube videos but clicking on it strats the video in the same way clicking elsewhere on the video. Having the ability to quickly open the video on on Invidious (as to Youtube when not redirected) would be welcomed.

I guess the above mentioned top-left corner icon corresponds to this, which is what i'm referring to:
![EmbeddedInvidious](https://user-images.githubusercontent.com/42912760/59549242-f9a9e380-8f5a-11e9-85ab-6c4a0a5f6f09.jpeg)

Thanks!

**Comment by omarroth** [comment]
Maybe something like this?

![image](https://user-images.githubusercontent.com/14208607/59558096-d3faf980-8faf-11e9-944a-e1a841360191.png)

**Comment by omarroth** [comment]
Appears to be duplicate of #145, although I was having trouble finding it.

**Comment by StanGets** [comment]
Just my 2 cents and because we're evoking what is finally a lightweight enhancement.
Maybe positioning the link to _Invidious_ elsewhere than on the top-center, considering that some videos may already occupy that zone, as in this example:

![PageSaver-2019-06-16-10 08 05](https://user-images.githubusercontent.com/42912760/59561354-9d5cc780-901f-11e9-94ed-381a9961f526.jpeg)

I have in mind right-clicking on the top-left icon with the option to _Open on your instance of Invidious_, for instance. But this very enhancement is really not an issue, rather a cherry on a nice and tasty cake :=)

**Comment by robrobinbin** [comment]
IMO, it does makes a lot of intuitive sense that if you have a title there, that it is clickable.

It is still a bit counter-intuitive though that you have to actually pause the video before the title shows up. But I can imagine that displaying the title each time on hover takes up a bit too much real estate...

**Comment by omarroth** [comment]
Added the clickable title with 485459b8b24fd3fd11f8d8c28d846eb6fd3636fe.

I agree it could be made a little more intuitive, although as mentioned it's difficult to find more space for a dedicated button.

> I have in mind right-clicking on the top-left icon with the option to *Open on your instance of Invidious*, for instance.

Unfortunately it's not possible to add options to the context-menu, but it might make sense to add an icon in the top-right, similar to the official embed.

**Comment by robrobinbin** [comment]
@omarroth The iframe with the embed becomes empty when I click the link... Maybe make the link `target="_blank"`?

**Comment by Discookie** [comment]
Would it make sense to replace the Share button with a Go to invidious button in embeds?

It's 1 or 2 extra clicks to get the video URL that way, and I don't see a reason why anyone would need the embed codes/sharing to other sites without going to the website.

**Comment by omarroth** [comment]
Added `target="_blank"` with 1477f99c2c79cae476d8e2f0ecd536cbcd788dd3.

> Would it make sense to replace the Share button with a Go to invidious button in embeds?

Maybe, if possible though I'd much prefer to not change existing behavior.

**Comment by StanGets** [comment]
I'm not sure if what follows is related or not to `Added target="_blank"` but left-clicking on the new top-center link to open the video on Invidious doesn't work, only adds an Invidious search form on top of the video. **Nevertheless middle-clicking does open the link on Invidious:**

Embedded video at start:
![1](https://user-images.githubusercontent.com/42912760/59591820-03fce680-90ef-11e9-9181-abba6f952377.jpeg)

Embedded video after left-clicking on the top-center link:
![2](https://user-images.githubusercontent.com/42912760/59591832-0b23f480-90ef-11e9-959e-9dc991998825.jpeg)

This might be related to my Firefox 37.0.2 (x64) configuration on Windows 7 (x64), not sure though.

**Comment by Perflyst** [comment]
update your firefox, you run v37?!

**Comment by StanGets** [comment]
> update your firefox, you run v37?!

Lol! That was 67 (67.0.2), I corrected when commenting, you must have been notified before my correction...

**Comment by jones137** [comment]
That's why I love community-based projects - you can actually communicate with devs and have a chance of your request getting implemented, and so quickly!

**Comment by omarroth** [comment]
@StanGets I'm having trouble reproducing this in Firefox 67.0.3. If it's still an issue for you would you mind opening a new issue with an example embed?

**Comment by StanGets** [comment]
@omarroth , thanks for coming back to this. The issue I had incidentally mentioned above has vanished.

Above I had mentioned that the link to send the video to my Invidious instance would work only with middle-clicking on the top-center text/icon. I've just tested again an embedded video and this time left-clicking the text/icon sent me directly to my Invidious instance. Latest Firefox here as well (67.0.3).

So : all is fine (even if it wasn't a true issue) : Invidious is great, weather is warm, birds sing and I as well!

No problem, no new issue to open :=)

And... hum ... really thanks for Invidious and for keeping committed to it. This is true love, lol!
