### ISSUE TITLE
Video overview on channel page does not always fill page

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#603]
I sometimes mention that the video overview on a channel is not filled completely but there would be videos on the next page which could be shown on the first page also

**Comment by omarroth** [comment]
Mind providing an example? I'm assuming you mean a channel page shows less than <60 videos, in which case see #181.

**Comment by Perflyst** [comment]
Yes that is the issue. Don't have an example right now, but can share it if I find one again. If this is "fixed" with the "Next page" than we can also close the issue

**Comment by omarroth** [comment]
Closing for now. If there's an example where a channel isn't correctly displaying feel free to mention it here and I'll be happy to re-open.

**Comment by Perflyst** [comment]
Not on invidio.us but found this one: https://fi.invidious.snopyta.org/search?q=asd

There is the last video missing in bottom right.
