### ISSUE TITLE
Slow loading, lots of buffering (but not on the actual youtube site)

### ISSUE THREAD

**Issue by Rafnsvartr** [omarroth/invidious#605]
I can watch a video on the YouTube site itself and it streams just fine, but if I load it on invidio.us, I get the first 10-20 seconds or so almost instantly, then it buffers like crazy and takes forever to load.

I tried a number of things; proxy/no proxy, dash/hd720, addons disabled, Firefox, Chrome, Vivaldi... nothing makes a difference.

The videos are being streamed from google, right?

**Comment by omarroth** [comment]
Might be related to #532. Does this occur on any other [instances](https://github.com/omarroth/invidious/wiki/Invidious-Instances), or is it just https://invidio.us?

**Comment by Rafnsvartr** [comment]
A few days ago I tried 2 other instances with no change, but for now it seems to be working fine. I'll test more when/if it happens again.

**Comment by omarroth** [comment]
Sounds good, feel free to mention here if you encounter it again and I'll be happy to re-open.
