### ISSUE TITLE
IPv6 for invidio.us

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#608]
Currently invidio.us does not have an IPv6 in its DNS records. You host at DO and I am quite sure they offer IPv6. Is it possible that you offer v6 support?

Are there issues with HAProxy?

**Comment by omarroth** [comment]
Although most services provided by DO support IPv6, unfortunately load balancers currently do not, see [here](https://www.digitalocean.com/docs/networking/load-balancers/overview/#limits).
