### ISSUE TITLE
impoort glitch

### ISSUE THREAD

**Issue by ss-private** [omarroth/invidious#609]
wanted to import youtube
[YTCHANNELS2.txt](https://github.com/omarroth/invidious/files/3319128/YTCHANNELS2.txt)
[YTCHANNELS2.txt](https://github.com/omarroth/invidious/files/3319130/YTCHANNELS2.txt)

 subs. youtube won't export opml anymore.
got my sub id's and wrote my own opml using the invidious export as a model.
my opml looks fairly innocent but i got "Looks like you've found a bug in Invidious."
 
the file name was originally blabla.opml. is that file type a problem? does it have to be txt?
inquiring minds want to know.
cheers
s

**Comment by omarroth** [comment]
I'm able to import both files as expected. Are you using https://invidio.us or another [instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances)?

**Comment by omarroth** [comment]
Closing for now. If you'd like to provide more info I'll be happy to re-open.
