### ISSUE TITLE
Feature Request: Posts

### ISSUE THREAD

**Issue by trymeouteh** [omarroth/invidious#611]
I do not have a Youtube/Google account but when I visited Youtube.com recently and watched a few videos I noticed that the channels had something called posts and were able to create them. This will be a cool thing to add to invidious were you can see the posts of your favorite subscribed channels and get updates when a channel makes a new post.

**Comment by omarroth** [comment]
Are you referring to the [Community](https://www.youtube.com/user/BBC/community) tab provided on some channels? If not, would you mind linking an example? Otherwise I think this can be closed in favor of #483.

**Comment by omarroth** [comment]
Added with bcd239ac2b438ec721ffe35868371a9c81573f0a.
