### ISSUE TITLE
Video suddenly stops

### ISSUE THREAD

**Issue by gleb09** [omarroth/invidious#613]
I don't know if there's some log/evidence I can leave. But over the last few weeks videos have suddenly stopped playing with an odd cut sound and scrambled video. I've had to use FreeTube and MPV to watch videos.

**Comment by omarroth** [comment]
The following would be helpful:
- Which browser are you using?
- Does this happen on more than one [instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances), or https://invidio.us?
- Are you using `Proxy videos` or `&local=true`? If so, does it still occur with it disabled?

**Comment by gleb09** [comment]
Thanks for your reply. It happened on Firefox 67.0. I found out about instances and switched to one and it worked fine. Regular invidio.us seems to be working fine now and I don't know if I used Proxy videos or &local=true, so sorry for the lack of information.

**Comment by omarroth** [comment]
No worries. In that case I'm going to close this for now. If it happens again please feel free to mention here and I'll be happy to re-open.
