### ISSUE TITLE
Feature request: Make captions background a little wider (and taller!)

### ISSUE THREAD

**Issue by gianccm** [omarroth/invidious#614]
It'd be nice to expand the background even just a couple pixels. The margins for width and height should be proportional. This should make them look so much nicer!

This image below shows how the ends are tight.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/24861416/60381522-acfcf700-9a88-11e9-9039-2ae26e552f26.png">

**Comment by omarroth** [comment]
Sounds good, added with 8fad0af935275d6894ad11442b6024f9065f59f7.
