### ISSUE TITLE
Channel banner and thumbnail not cached (reload results in broken images)

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#615]
Channel banner and the profile image are not cached and if you reload a channels page the images are both broken.

1. Open https://invidio.us/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw
2. Press F5 to reload
-> Images both broken
3. Press Shift + F5 to fix broken images

**Comment by omarroth** [comment]
Check to see if 351ecfae0f249347a48c0d9daf2e492fdacce89c fixes the issue for you.

**Comment by Perflyst** [comment]
Works now as expected.
