### ISSUE TITLE
Channel name is too clickable

### ISSUE THREAD

**Issue by stefnb** [omarroth/invidious#617]
I'm having a very frustrating time watching videos on Invidious since this patch a few days ago: https://github.com/omarroth/invidious/commit/0d0d3edeae1e632afc302e240b5ef7481c21b4b0#diff-0330229ce03cc31ae80c6c623a38d581

The problem is that the channel link now encloses the `.channel-profile` div and so the click area is really big. I keep clicking onto the page in a seemingly-empty spot (for example to regain focus or to scroll) and ending up on the Channel page, then having to go back, restart the video, find the spot I was at, etc.. Super frustrating!

A solution would be to move `<a href="/channel/<%= video.ucid %>">` inside `.channel-profile` (it could still enclose the `img` and `span`).

Thanks! <3

**Comment by omarroth** [comment]
Should be fixed with 501b523680864e5eecf9af9290f86b33f01d89be.

**Comment by stefnb** [comment]
Nice!

**Comment by stefnb** [comment]
(FYI it doesn't work on Firefox, you'll need to add a `-moz-fit-content` too which sorts it)

**Comment by omarroth** [comment]
Gotcha, should be fixed with 1485ee80279100d02a3e47c3aac8171e291d503a.

**Comment by stefnb** [comment]
You're the bomb!
