### ISSUE TITLE
Startup error: "feed_needs_update" does not exist

### ISSUE THREAD

**Issue by yungdan1** [omarroth/invidious#619]
Jul 04 01:51:08 debian systemd[1]: Started Invidious (An alternative YouTube front-end).\
Jul 04 01:51:09 debian invidious[15299]: Unhandled exception in spawn: column "feed_needs_update" does not exist (PQ::PQError)\
Jul 04 01:51:09 debian invidious[15299]:   from lib/pg/src/pq/connection.cr:163:7 in 'read'\
Jul 04 01:51:09 debian invidious[15299]:   from lib/pg/src/pq/connection.cr:158:7 in 'expect_frame'\
Jul 04 01:51:09 debian invidious[15299]:   from lib/pg/src/pg/statement.cr:19:5 in 'query'\
Jul 04 01:51:09 debian invidious[15299]:   from src/invidious/helpers/jobs.cr:53:12 in '->'\
Jul 04 01:51:09 debian invidious[15299]:   from /usr/share/crystal/src/fiber.cr:255:3 in '???'\
Jul 04 01:51:09 debian invidious[15299]:   from ???\
Jul 04 01:51:09 debian invidious[15299]: GC Warning: Repeated allocation of very large block (appr. size 1159168):\
Jul 04 01:51:09 debian invidious[15299]:         May lead to memory leak and poor performance\

What would be the easiest way to solve this? Invidious works but the subscription feed is not updating.

**Comment by omarroth** [comment]
You may try running the relevant migration script in `config/migrate-scripts`, or setting `check_tables: true` in your `config/config.yml`. In this case I believe you want [migrate-db-701b5ea.sh](https://github.com/omarroth/invidious/blob/master/config/migrate-scripts/migrate-db-701b5ea.sh).

Generally, when [updating](https://github.com/omarroth/invidious/wiki/Updating), the relevant migrate scripts should be run automatically which should resolve issues like the one you're encountering.

**Comment by yungdan1** [comment]
`check_tables: true` was the easiest fix.
