### ISSUE TITLE
Comments not loading on iPad mobile browser 

### ISSUE THREAD

**Issue by hellomcbug** [omarroth/invidious#623]
Tried Safari and Chrome on an iPad running iOS 9. No comments for videos are loading. Tried both YT and Reddit comments in the options but nothing displays. Can anyone confirm on iOS mobile?

**Comment by omarroth** [comment]
Testing with iOS 12, I am able to view both YouTube and Reddit comments on https://invidio.us.

Are you only unable to view comments for a specific video? Does it only occur for a specific instance?

**Comment by hellomcbug** [comment]
They're not showing for any video I try on invidio.us. I don't think it's an issue with my network, since I can see them on my desktop PC.

**Comment by omarroth** [comment]
In that case I expect there's a browser feature that isn't supported on iOS 9, although looking through I don't see anything in particular that might be causing problems.

If you have Safari installed on your desktop, it should be possible to debug mobile Safari (see [here](https://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787) and [here](https://stackoverflow.com/questions/26014850/debugging-mobile-safari-in-ios-8-and-ios-9)) using the included Web Inspector.

**Comment by hellomcbug** [comment]
I've now tried it on another iPad running iOS 11 and it's working. Seems it's just the one running iOS 9 that has some issues. Will try a few more things later and let you know, thanks!

**Comment by hellomcbug** [comment]
I've now tried several other browsers (Dolphin, UC, Mercury) on the iOS 9.3.5 iPad and still no comments. So it would seem that there's an issue on iOS 9 (or older?). Without another non-updated iOS device I can't confirm.

**Comment by cloudrac3r** [comment]
I believe function default parameters are not supported in iOS 9. From watch.js:

    function get_youtube_comments(retries = 5) {

I don't have any iOS 9 devices to test with, but I believe the syntax `name = value` in function definitions is unsupported. It can be changed to this equivalent:

    function get_youtube_comments(retries) {
        if (retries === undefined) retries = 5;

http://es6-features.org/#DefaultParameterValues
