### ISSUE TITLE
Add support for /embed/live_stream

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#624]
Today I encountered a weird way to embed a live stream:  
https://www.youtube.com/embed/live_stream?channel=UCOJFIYDaaDWQK1GX3gtnbwg&enablejsapi=1&=1&playsinline=1

Apparently this URL grabs the latest livestream on a channel, and plays it, even if it has already ended.

I've also tested https://www.youtube.com/embed/live_stream?channel=UCXuqSBlHAE6Xw-yeJA0Tunw which works the same way.

**Comment by omarroth** [comment]
Added with 607d6125fc50839115edd856e2862e5ccdcf3085.
