### ISSUE TITLE
Add support for playlist embedding

### ISSUE THREAD

**Issue by OdinGitDat** [omarroth/invidious#629]
Hi, some websites like to embed a playlist on their website so that it always shows the most recent video from said playlist without updating the embed. Currently my '[youtube to invidious](https://greasyfork.org/en/scripts/375264-youtube-to-invidious)' script cannot deal with these embeds because they are not supported.

This is an example of such a url:
[https://www.youtube.com/embed/?list=PL96C35uN7xGJu6skU4TBYrIWxggkZBrF5](https://www.youtube.com/embed/?list=PL96C35uN7xGJu6skU4TBYrIWxggkZBrF5)
It would be nice if this worked:
[https://www.invidio.us/embed/?list=PL96C35uN7xGJu6skU4TBYrIWxggkZBrF5](https://www.invidio.us/embed/?list=PL96C35uN7xGJu6skU4TBYrIWxggkZBrF5)

**Comment by omarroth** [comment]
Added with cfe9d47fa000bb7ba1add20ef41408c19e0df33d.

**Comment by OdinGitDat** [comment]
Thanks, added support in my script as well.
