### ISSUE TITLE
Unable to login with google.

### ISSUE THREAD

**Issue by SolAZDev** [omarroth/invidious#630]
Good Evening. It appears that whenever I try to login with google, I get the Incorrect Password error. I only got to login once in another browser (which is sadly also logged out now) and I **did** change the password recently.

However on close inspection, I did get this in a response.

```default-src blob: data: 'self' https://invidio.us 'unsafe-inline' 'unsafe-eval'; media-src blob: 'self' https://invidio.us https://*.googlevideo.com:443```

I am uncertain if that can be of use.

**Comment by NathanPrice** [comment]
Just thought I'd report I'm getting this issue as well. I even tried logging in normally (I don't have an account yet, I was seeing what would happen) and was met with [this ](http://easycaptures.com/fs/uploaded/1292/3227923980.png)screen. Just found out about this site the other day and I thought it was strange that I couldn't sign in. Hopefully @omarroth can take a look at this to see what's going on.

**Comment by omarroth** [comment]
I pushed a couple changes with 1a7b341745d2d2fd08bde1ee5ffe58a5827b187a that should fix the "Incorrect password" error. Unfortunately Google is slowly making it more difficult for external services to sign in, so I expect this will mostly be a temporary fix. See also youtube-dl: ytdl-org/youtube-dl#11270 and the relevant fix ytdl-org/youtube-dl@baf67a6.

> I even tried logging in normally (I don't have an account yet, I was seeing what would happen) and was met with this screen.

Are you encountering this when using https://invidio.us or with another instance?

**Comment by NathanPrice** [comment]
For me at least I was using the official https://invidio.us instance. I just tried it again and got [this ](http://easycaptures.com/fs/uploaded/1294/2321107142.png)message. I don't have 2FA setup on my account so it could be possible that Google changed something else as well. If need be, I could always export my subscriptions, make an account, then import them. I have development experience, just haven't had time yet to set this up on my local machine and debug this. Nevertheless I'm just sharing this so that you're aware of it.

**Comment by SolAZDev** [comment]
So I was unable to try it upon @omarroth 's posting time range, but I did try today. I should mention I do **not** have F2A.

``Expected Array for #[](index : Int), not Int64
Traceback:
Getting lookup...done, returned 200.
Getting challenge...done, returned 200.
User has 2FA.
Selecting challenge 9...done.```

**Comment by omarroth** [comment]
Thanks, check to see if d97a272aa5735126fa3d704173fd28ece0e7a25b fixes the issue for you.

**Comment by omarroth** [comment]
Strange, would you mind clearing cookies and attempting to login again?

**Comment by SolAZDev** [comment]
I can't confirm that clearing cookies helped, I simply retried to login and everything worked well.

**Comment by omarroth** [comment]
In that case I'll consider this closed. If you encounter any issues with login please feel free to open a new issue with a similar error message to what's provided above.
