### ISSUE TITLE
Add 1.75 play speed

### ISSUE THREAD

**Issue by geditorit** [omarroth/invidious#632]
Youtube has this speed in options, so i ask to add it to Invidious too.

**Comment by TemporaryUsername12481** [comment]
Even better, an "enter custom" option would be great.

**Comment by omarroth** [comment]
Added with e8a56e0fea8364d62f3113f4c6d0074ef47ec0d6.

> Even better, an "enter custom" option would be great.

Currently tracked in #533.

**Comment by geditorit** [comment]
Thanks.
