### ISSUE TITLE
Videos all autoplaying on community pages is a mess

### ISSUE THREAD

**Issue by recette-lemon** [omarroth/invidious#634]
If autoplay is enabled and you visit a community page with multiple videos, they all play, which becomes an incomprehensible mess. Probably best to disable autoplay for community pages.

**Comment by omarroth** [comment]
Should be fixed with 290c7e60091f608c23acfaeb93122a262912e057.

**Comment by recette-lemon** [comment]
Ye, works fine now. Cool and good.
