### ISSUE TITLE
Can't see the video feed 

### ISSUE THREAD

**Issue by wongfeihung1984** [omarroth/invidious#635]
Hi everyone, when I use your website i can listen to videos but there is no images displayed, as if some layer was covering the video feed. 

The strange thing is 
1) when I hover the mouse icon over the timestamp bar I can see still pictures 
2) when I don't do that, I can see the video playing but only where the timestamp bar is
https://ibb.co/Fw8xh7R
https://ibb.co/qdH4Nkg

I hope you can help me resolve this mystery

Regards

**Comment by wongfeihung1984** [comment]
I have found the culprit: a script blocked by UBlock. All is good now.

**Comment by omarroth** [comment]
Apologies for the delay, glad to hear it's working for you!

**Comment by wongfeihung1984** [comment]
Hi, it's me again. Today I tried to watch videos using Invidious and the old bug happened all over again....but I didn't change anything from last time I watched videos and everything was working fine. 

I found the new culprit : Dark Reader. 

All is good now.
