### ISSUE TITLE
Impossible to go to the next page in the playlists list 

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#638]
If you click "Next Page" on the list of the playlists of some channels, it redirect to a broken link containing nothing

Example : 
If I click "Next Page" on this list : https://invidio.us/channel/UC7qPftDWPw9XuExpSgfkmJQ/playlists

The link appearing is : https://invidio.us/channel/UC7qPftDWPw9XuExpSgfkmJQ/playlists?continuation=AIOkY9HBzGyh3OqYZxSfe1TJN4Sg8tLxuvCWJfg6K5oUfvkKZRPeRxtMQX5CyP8VGlAp58d-VH_Q

Leading to nothing : [Screnshot](https://user-images.githubusercontent.com/47571719/61580167-23c46780-aafe-11e9-8a77-2300ad1c0575.png)

Note : It doesn't happen in every channel and it doesn't seem consistent : for example I tried https://invidio.us/channel/UCXuqSBlHAE6Xw-yeJA0Tunw/playlists 3 times and it didn't work, I then went trying on another channel and when I went back trying on Linus Tech Tips it did work for 3 pages, then broke again when I tried to go in the fourth one

**Comment by omarroth** [comment]
Should be fixed with e7366269535368a33598e49c1844da21c97522ba.
