### ISSUE TITLE
[Feature request] Add subscription groups/tags

### ISSUE THREAD

**Issue by watzon** [omarroth/invidious#641]
Something that I've been wanting in YouTube is to have subscription groups, or have the ability to add subscriptions to a specific tag/category. This is because I subscribe to several types of YouTuber's as a coder, amateur artist, and cat video connoisseur. This could allow you to group recommendations easier as well.

**Comment by omarroth** [comment]
Duplicate of #482?

**Comment by watzon** [comment]
I suppose it is
