### ISSUE TITLE
Channel links on video pages aren't be generated properly

### ISSUE THREAD

**Issue by jodizzle** [omarroth/invidious#647]
Arbitrary example: https://invidio.us/watch?v=MMHPxaAkK-w

The `href` of the channel link is just `/channel/`.  As far as I can tell, this is true on every video page.

**Comment by omarroth** [comment]
Should be fixed with f6431751564fcab712e798ea31f2397b841b5c27.

**Comment by jodizzle** [comment]
@omarroth Yep, seems so.  Thanks.
