### ISSUE TITLE
Here's a script that I use for redirecting Youtube to Invidious

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#65]
*subject*

[Youtube_to_Invidious.txt](https://github.com/omarroth/invidious/files/2255513/Youtube_to_Invidious.txt)

Rename it from .txt to .user.js.

**Comment by veloute** [comment]
https://github.com/omarroth/invidious/pull/66

**Comment by Zero3K** [comment]
Its different than the one on Greasyfork.

**Comment by veloute** [comment]
Does your one have any improvements to the other?

**Comment by Zero3K** [comment]
It doesn't send requests to Youtube when redirecting embedded videos to Invidious.

**Comment by Zero3K** [comment]
Its not mine.

**Comment by omarroth** [comment]
Looks like a duplicate of the script in #66, so I'm going to close this. If there's a project page for this script anywhere then feel free to open a PR.

**Comment by Zero3K** [comment]
Its not a complete duplicate.
