### ISSUE TITLE
[Feature Request] Channels descriptions displayed on the channels pages

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#657]
Right now the only possible way to see (only some part of) a channel description is to search for it : 
![Screenshot](https://user-images.githubusercontent.com/47571719/62248677-3b420100-b3d8-11e9-831a-8f052b112bbc.png)

In my opinion it should be displayed directly on the channel page like this : 
![this](https://user-images.githubusercontent.com/47571719/62248869-ab508700-b3d8-11e9-8437-5221410e56aa.png)

Previously : 
![old](https://user-images.githubusercontent.com/47571719/62249013-03878900-b3d9-11e9-94d2-491966fd005f.png)

**Comment by omarroth** [comment]
Added with f71d5c429d4e3abc4e6a7eaf461fd46587316121. See also: #483.

**Comment by TheFrenchGhosty** [comment]
This has been implemented.
