### ISSUE TITLE
Pictures are broken in the community page

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#659]
If a picture is supposed to be displayed on the community page, the browser will not load it (tested with Icecat and Tor Browser), I guess it's a problem with the format of it (.webp)

![bug](https://user-images.githubusercontent.com/47571719/62250320-236c7c00-b3dc-11e9-9d1c-6c9ea65198e8.png)

The link to the missing picture of this screenshot : https://invidio.us/ggpht/WeZAfkgT6rPT8Zrj1GJ2Wc8JUwUQKiDIvm6s2_qllIt1v9xFFQTKawBMUWRmjygZ-enwV5xJtgbt_w=w361-h361-p-nd-rwa

**Comment by cloudrac3r** [comment]
Chrome and Firefox are supposed to both support webp without any special treatment, though it's relatively new compared to png and jpg.

I think Invidious is serving the wrong content-type for it.

**Comment by omarroth** [comment]
The latest version of Icecat appears to be based on Firefox 60.7.0esr, which [doesn't support webp](https://caniuse.com/#search=webp). Should be fixed with dce5816b18e201a66419010a1b2e0e7e24a6f1db.

**Comment by TheFrenchGhosty** [comment]
Fixed.
