### ISSUE TITLE
Icon near number of views broken if websites not allowed to choose their own fonts

### ISSUE THREAD

**Issue by jones137** [omarroth/invidious#666]
![Selection_001](https://user-images.githubusercontent.com/50827887/62290047-dd510000-b44f-11e9-83e7-5fb54e56b57b.png)
As you can see, the eye icon is broken if you untick "allow pages to choose their own fonts" in Firefox. Unticking this option helps a lot with anti-fingerprinting. It's a cosmetic issue, but I would be glad if it would be solved.

**Comment by omarroth** [comment]
I expect this'll be a `wontfix` unfortunately.

[Ionicons](https://github.com/ionic-team/ionicons) needs a custom font in order to provide icons. I don't think it's possible to fix without some quite instrusive changes to that library.

**Comment by leonklingele** [comment]
I wonder why it shows icons for 👍 and 👎 though.

**Comment by omarroth** [comment]
Testing in Firefox (blocking fonts with NoScript), I see:
![image](https://user-images.githubusercontent.com/14208607/62425811-251b9580-b6a3-11e9-86c8-01eec84aec1c.png)

I expect it's somehow able to still use `ionicons.svg` or another file as a fallback, although I'm a bit confused why the eye icon isn't also used in that case.
