### ISSUE TITLE
Error resolving db (~> 0.5.0, ~> 0.6.0)

### ISSUE THREAD

**Issue by yungdan1** [omarroth/invidious#669]
Get this error message when running shards update. I'm seeing that there was a new release of crystal-db two days ago, not sure if that's the reason or not. How to fix?

**Comment by leonklingele** [comment]
Fixed once https://github.com/omarroth/invidious/pull/655 is merged. Otherwise apply https://github.com/omarroth/invidious/commit/7f8eeb38a1d612acb0d40b24eb97f366459a7d26.patch

**Comment by yungdan1** [comment]
Now, shards update returns `Error resolving pg (-> 0.17.0)` after applying the patch.

**Comment by yungdan1** [comment]
824150f closes this.
