### ISSUE TITLE
Make likes of a comment more easier to understand

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#67]
It took me a bit to understand that the number shown next to the user's name is the number of likes. I think adding a symbol (such as a thumbs up) would help tell the viewer that its the amount of likes the comment has received.

**Comment by omarroth** [comment]
This is what I'm seeing:
![image](https://user-images.githubusercontent.com/14208607/43647743-2e0f51e2-96fe-11e8-8911-d026197bab38.png)

So it seems what you're asking for has already been added. If there is an issue with **loading** the icons (thumbs up, eye, thumbs down), then that should be a new issue.

**Comment by Zero3K** [comment]
No, I mean the comments section below the description of the video.

**Comment by dimqua** [comment]
Fixed by 1fb0e19. 👍
