### ISSUE TITLE
Unable to build Docker image

### ISSUE THREAD

**Issue by Stolz** [omarroth/invidious#681]
I'm trying to build the new Alpine based docker image. After a fresh repo clone `docker-compose build` command fails with this error:

    Step 8/20 : RUN crystal build --static --release     -Dmusl     ./src/invidious.cr
    ---> Running in 46791d53f6a8
    Error in src/invidious.cr:19: while requiring "kemal"

    require "kemal"
    ^

    in lib/kemal/src/kemal.cr:6: while requiring "./kemal/helpers/*"

    require "./kemal/helpers/*"
    ^

    in lib/kemal/src/kemal/helpers/helpers.cr:1: while requiring "mime": can't find file 'mime'

    If you're trying to require a shard:
    - Did you remember to run `shards install`?
    - Did you make sure you're running the compiler in the same directory as your shard.yml?

    require "mime"
    ^

    ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build --static --release     -Dmusl     ./src/invidious.cr' returned a non-zero code: 1

It seems `kemal` requires `mime` which is not installed by `shards install`. I manually edited `shard.yml` file and added `mime` as dependency:

      mime:
        github: icyleaf/mime.cr

But when I try again with `docker-compose build` I get these errors:

    Step 8/20 : RUN crystal build --static --release     -Dmusl ./src/invidious.cr
    ---> Running in f5ddb485fdb9
    Error in src/invidious.cr:31: instantiating 'Config.class#from_yaml(String)'

    CONFIG   = Config.from_yaml(File.read("config/config.yml"))
    ^~~~~~~~~

    in /usr/lib/crystal/core/yaml/from_yaml.cr:2: instantiating 'parse_yaml(String)'

    new(YAML::ParseContext.new, parse_yaml(string_or_io))
    ^~~~~~~~~~

    in /usr/lib/crystal/core/yaml/from_yaml.cr:12: instantiating 'YAML::Nodes:Module#parse(String)'

    document = YAML::Nodes.parse(string_or_io)
    ^~~~~

    in /usr/lib/crystal/core/yaml/nodes.cr:13: instantiating 'YAML::Nodes::Parser.class#new(String)'

    Parser.new string_or_io, &.parse
    ^~~

    in /usr/lib/crystal/core/yaml/nodes/parser.cr:9: instantiating 'new(String)'

    parser = new(content)
    ^~~

    in /usr/lib/crystal/core/yaml/nodes/parser.cr:4: instantiating 'super(String)'

    super
    ^~~~~

    in /usr/lib/crystal/core/yaml/parser.cr:4: instantiating 'YAML::PullParser.class#new(String)'

    @pull_parser = PullParser.new(content)
    ^~~

    in /usr/lib/crystal/core/yaml/pull_parser.cr:27: instantiating 'IO+#read(Slice(UInt8))'

    actual_read_bytes = io.read(slice)
    ^~~~

    in /usr/lib/crystal/core/zip/checksum_reader.cr:12: instantiating 'IO+#read(Slice(UInt8))'

    read_bytes = @io.read(slice)
    ^~~~

    in /usr/lib/crystal/core/io/buffered.cr:67: instantiating 'unbuffered_read(Slice(UInt8))'

    return unbuffered_read(slice[0, count]).to_i
    ^~~~~~~~~~~~~~~

    in /usr/lib/crystal/core/zlib/reader.cr:67: instantiating 'Flate::Reader#read(Slice(UInt8))'

    read_bytes = @flate_io.read(slice)
    ^~~~

    in /usr/lib/crystal/core/io/buffered.cr:67: instantiating 'unbuffered_read(Slice(UInt8))'

    return unbuffered_read(slice[0, count]).to_i
    ^~~~~~~~~~~~~~~

    in /usr/lib/crystal/core/flate/reader.cr:70: instantiating 'IO+#peek()'

    @peek = @io.peek
    ^~~~

    in /usr/lib/crystal/core/zip/checksum_reader.cr:24: instantiating 'IO+#peek()'

    @io.peek
    ^~~~

    in /usr/lib/crystal/core/http/content.cr:103: instantiating 'next_chunk()'

    next_chunk
    ^~~~~~~~~~

    in /usr/lib/crystal/core/http/content.cr:134: instantiating 'read_crlf()'

    read_crlf unless @chunk_remaining == -1 # -1 is the initial value
    ^~~~~~~~~

    in /usr/lib/crystal/core/http/content.cr:144: instantiating 'IO+#read_char()'

    char = @io.read_char
    ^~~~~~~~~

    in /usr/lib/crystal/core/io.cr:309: instantiating 'read_char_with_bytesize()'

    info = read_char_with_bytesize
    ^~~~~~~~~~~~~~~~~~~~~~~

    in /usr/lib/crystal/core/io.cr:316: instantiating 'IO+#peek()'

    if !decoder && (peek = self.peek)
        ^~~~
        
        in /usr/lib/crystal/core/http/content.cr:37: instantiating 'IO+#peek()'
        
        @io.peek
        ^~~~
        
        in /usr/lib/crystal/core/io/buffered.cr:90: instantiating 'fill_buffer()'
        
        fill_buffer
        ^~~~~~~~~~~
        
        in /usr/lib/crystal/core/io/buffered.cr:227: instantiating 'unbuffered_read(Slice(UInt8))'
        
        size = unbuffered_read(Slice.new(in_buffer, BUFFER_SIZE)).to_i
        ^~~~~~~~~~~~~~~
        
        in /usr/lib/crystal/core/gzip/reader.cr:89: instantiating 'IO+#read_bytes(UInt32.class, IO::ByteFormat::LittleEndian:Module)'
        
        crc32 = @io.read_bytes(UInt32, IO::ByteFormat::LittleEndian)
        ^~~~~~~~~~
        
        in /usr/lib/crystal/core/io.cr:889: instantiating 'UInt32.class#from_io(IO+, IO::ByteFormat::LittleEndian:Module)'
        
        type.from_io(self, format)
        ^~~~~~~
        
        in /usr/lib/crystal/core/int.cr:516: instantiating 'IO::ByteFormat::LittleEndian:Module#decode(UInt32.class, IO+)'
        
        format.decode(self, io)
            ^~~~~~
            
            in /usr/lib/crystal/core/io/byte_format.cr:131: expanding macro
            
            {% for mod in %w(LittleEndian BigEndian) %}
            ^
            
            in macro 'macro_139786817926688' /usr/lib/crystal/core/io/byte_format.cr:131, line 160:
            
            [REDACTED]
            
            instantiating 'IO+#read_fully(Slice(UInt8))'
            in /usr/lib/crystal/core/io.cr:513: instantiating 'read_fully?(Slice(UInt8))'
            
            read_fully?(slice) || raise(EOFError.new)
            ^~~~~~~~~~~
            
            in /usr/lib/crystal/core/io.cr:530: instantiating 'read(Slice(UInt8))'
            
            read_bytes = read slice
            ^~~~
            
            in /usr/lib/crystal/core/http/content.cr:78: instantiating 'IO+#read(Slice(UInt8))'
            
            bytes_read = @io.read slice[0, to_read]
            ^~~~
            
            in /usr/lib/crystal/core/http/content.cr:29: instantiating 'IO+#read(Slice(UInt8))'
            
            @io.read(slice)
            ^~~~
            
            in /usr/lib/crystal/core/openssl/digest/digest_io.cr:38: instantiating 'IO+#read(Slice(UInt8))'
            
            read_bytes = io.read(slice)
            ^~~~
            
            in /usr/lib/crystal/core/io/stapled.cr:36: instantiating 'IO+#read(Slice(UInt8))'
            
            @reader.read(slice)
            ^~~~
            
            in /usr/lib/crystal/core/io/sized.cr:32: instantiating 'IO+#read(Slice(UInt8))'
            
            bytes_read = @io.read slice[0, count]
            ^~~~
            
            in /usr/lib/crystal/core/io/hexdump.cr:30: instantiating 'IO+#read(Slice(UInt8))'
            
            @io.read(buf).tap do |read_bytes|
            ^~~~
            
            in /usr/lib/crystal/core/io/delimited.cr:59: instantiating 'IO+#read_byte()'
            
            byte = @io.read_byte
            ^~~~~~~~~
            
            in /usr/lib/crystal/core/http/content.cr:93: instantiating 'IO+#read_byte()'
            
            byte = @io.read_byte
            ^~~~~~~~~
            
            in src/invidious/helpers/handlers.cr:206: undefined local variable or method 'ensure_send_continue'
            
            ensure_send_continue
            ^~~~~~~~~~~~~~~~~~~~
            
            ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build --static --release     -Dmusl ./src/invidious.cr' returned a non-zero code: 1

**Comment by leonklingele** [comment]
@Stolz hmm, it works just fine for me on a clean install without any Docker residue. Maybe you're using an outdated version of `alpine:latest`?

Please post the full output of `docker-compose build` to pinpoint the issue.
This is how it looks on my side:

```
Building postgres
Step 1/6 : FROM postgres:10
10: Pulling from library/postgres
0a4690c5d889: Pull complete
723861590717: Pull complete
db019468bdf4: Pull complete
91cb81a60371: Pull complete
a2a4ab07588d: Pull complete
a7ccdc2a5f31: Pull complete
93687df2bb93: Pull complete
f00839cf3313: Pull complete
0a1990a69022: Pull complete
10a84fa55cfe: Pull complete
0ccb80d000d0: Pull complete
c7a335f5eddf: Pull complete
d80bf77c5993: Pull complete
5cfe9a29dc89: Pull complete
Digest: sha256:473c72d4eff3e2d30857a4f7fe55319add123ddee7aedeef86538b81a03488df
Status: Downloaded newer image for postgres:10
 ---> 092b8d6e3163
Step 2/6 : ENV POSTGRES_USER postgres
 ---> Running in 311a359a74bb
Removing intermediate container 311a359a74bb
 ---> 006f8d6b4355
Step 3/6 : ADD ./config/sql /config/sql
 ---> 3be202000e4a
Step 4/6 : ADD ./docker/entrypoint.postgres.sh /entrypoint.sh
 ---> 8cde6ca11bdd
Step 5/6 : ENTRYPOINT [ "/entrypoint.sh" ]
 ---> Running in 82905c209d08
Removing intermediate container 82905c209d08
 ---> 6815c6acce5a
Step 6/6 : CMD [ "postgres" ]
 ---> Running in 5e856b18be89
Removing intermediate container 5e856b18be89
 ---> 5dde4cc66e17
Successfully built 5dde4cc66e17
Successfully tagged invidious_postgres:latest
Building invidious
Step 1/20 : FROM alpine:latest AS builder
latest: Pulling from library/alpine
050382585609: Pull complete
Digest: sha256:6a92cd1fcdc8d8cdec60f33dda4db2cb1fcdcacf3410a8e05b3741f44a9b5998
Status: Downloaded newer image for alpine:latest
 ---> b7b28af77ffe
Step 2/20 : RUN apk add -u crystal shards libc-dev     yaml-dev libxml2-dev sqlite-dev sqlite-static zlib-dev openssl-dev
 ---> Running in ada3dbad8a6c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/54) Upgrading musl (1.1.22-r2 -> 1.1.22-r3)
(2/54) Installing gc (8.0.4-r0)
(3/54) Installing libgcc (8.3.0-r0)
(4/54) Installing libstdc++ (8.3.0-r0)
(5/54) Installing libgc++ (8.0.4-r0)
(6/54) Installing pkgconf (1.6.1-r1)
(7/54) Installing gc-dev (8.0.4-r0)
(8/54) Installing libatomic_ops (7.6.10-r1)
(9/54) Installing libbz2 (1.0.6-r7)
(10/54) Installing expat (2.2.7-r0)
(11/54) Installing libffi (3.2.1-r6)
(12/54) Installing gdbm (1.13-r1)
(13/54) Installing ncurses-terminfo-base (6.1_p20190518-r0)
(14/54) Installing ncurses-terminfo (6.1_p20190518-r0)
(15/54) Installing ncurses-libs (6.1_p20190518-r0)
(16/54) Installing readline (8.0.0-r0)
(17/54) Installing sqlite-libs (3.28.0-r0)
(18/54) Installing python2 (2.7.16-r1)
(19/54) Installing libevent (2.1.10-r0)
(20/54) Installing libevent-dev (2.1.10-r0)
(21/54) Installing libevent-static (2.1.10-r0)
(22/54) Installing binutils (2.32-r0)
(23/54) Installing gmp (6.1.2-r1)
(24/54) Installing isl (0.18-r0)
(25/54) Installing libgomp (8.3.0-r0)
(26/54) Installing libatomic (8.3.0-r0)
(27/54) Installing mpfr3 (3.1.5-r1)
(28/54) Installing mpc1 (1.1.0-r0)
(29/54) Installing gcc (8.3.0-r0)
(30/54) Installing libgmpxx (6.1.2-r1)
(31/54) Installing gmp-dev (6.1.2-r1)
(32/54) Installing libpcre16 (8.43-r0)
(33/54) Installing libpcre32 (8.43-r0)
(34/54) Installing pcre (8.43-r0)
(35/54) Installing libpcrecpp (8.43-r0)
(36/54) Installing pcre-dev (8.43-r0)
(37/54) Installing llvm5-libs (5.0.2-r1)
(38/54) Installing crystal (0.29.0-r0)
(39/54) Installing musl-dev (1.1.22-r3)
(40/54) Installing libc-dev (0.7.1-r0)
(41/54) Installing zlib-dev (1.2.11-r1)
(42/54) Installing libxml2 (2.9.9-r2)
(43/54) Installing libxml2-dev (2.9.9-r2)
(44/54) Installing openssl-dev (1.1.1c-r0)
(45/54) Installing ca-certificates (20190108-r0)
(46/54) Installing nghttp2-libs (1.38.0-r0)
(47/54) Installing libcurl (7.65.1-r0)
(48/54) Installing pcre2 (10.33-r0)
(49/54) Installing git (2.22.0-r0)
(50/54) Installing yaml (0.2.2-r1)
(51/54) Installing shards (0.9.0-r0)
(52/54) Installing sqlite-dev (3.28.0-r0)
(53/54) Installing sqlite-static (3.28.0-r0)
(54/54) Installing yaml-dev (0.2.2-r1)
Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 260 MiB in 67 packages
Removing intermediate container ada3dbad8a6c
 ---> fe1b00a4817f
Step 3/20 : WORKDIR /invidious
 ---> Running in 9d5ebe1bcccb
Removing intermediate container 9d5ebe1bcccb
 ---> 749f8b3f470f
Step 4/20 : COPY ./shard.yml ./shard.yml
 ---> 677132b6e98e
Step 5/20 : RUN shards update && shards install
 ---> Running in 6cd503f7692f
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Installing pg (0.18.0)
Installing sqlite3 (0.13.0)
Installing kemal (0.25.2)
Installing radix (0.3.9)
Installing exception_page (0.1.2)
Installing db (0.6.0)
Installing kilt (0.4.0)
Writing shard.lock
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Using pg (0.18.0)
Using sqlite3 (0.13.0)
Using kemal (0.25.2)
Using radix (0.3.9)
Using exception_page (0.1.2)
Using db (0.6.0)
Using kilt (0.4.0)
Writing shard.lock
Removing intermediate container 6cd503f7692f
 ---> e018878dfb1e
Step 6/20 : COPY ./src/ ./src/
 ---> 139c2e476ce8
Step 7/20 : COPY ./.git/ ./.git/
 ---> cfa5f59f300a
Step 8/20 : RUN crystal build --static --release     -Dmusl     ./src/invidious.cr
 ---> Running in 14e177091805
Removing intermediate container 14e177091805
 ---> a2e9771833fa
Step 9/20 : FROM alpine:latest
 ---> b7b28af77ffe
Step 10/20 : RUN apk add -u imagemagick ttf-opensans
 ---> Running in 5637b4df6510
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/58) Upgrading musl (1.1.22-r2 -> 1.1.22-r3)
(2/58) Installing libxau (1.0.9-r0)
(3/58) Installing libbsd (0.9.1-r0)
(4/58) Installing libxdmcp (1.1.3-r0)
(5/58) Installing libxcb (1.13.1-r0)
(6/58) Installing libx11 (1.6.8-r0)
(7/58) Installing libxext (1.3.4-r0)
(8/58) Installing libbz2 (1.0.6-r7)
(9/58) Installing expat (2.2.7-r0)
(10/58) Installing libpng (1.6.37-r1)
(11/58) Installing freetype (2.10.0-r0)
(12/58) Installing libuuid (2.33.2-r0)
(13/58) Installing fontconfig (2.13.1-r0)
(14/58) Installing lcms2 (2.9-r1)
(15/58) Installing libltdl (2.4.6-r6)
(16/58) Installing libxml2 (2.9.9-r2)
(17/58) Installing imagemagick-libs (7.0.8.49-r2)
(18/58) Installing libxrender (0.9.10-r3)
(19/58) Installing pixman (0.38.4-r0)
(20/58) Installing cairo (1.16.0-r2)
(21/58) Installing libffi (3.2.1-r6)
(22/58) Installing libintl (0.19.8.1-r4)
(23/58) Installing libblkid (2.33.2-r0)
(24/58) Installing libmount (2.33.2-r0)
(25/58) Installing pcre (8.43-r0)
(26/58) Installing glib (2.60.4-r0)
(27/58) Installing dbus-libs (1.12.16-r0)
(28/58) Installing avahi-libs (0.7-r2)
(29/58) Installing gmp (6.1.2-r1)
(30/58) Installing nettle (3.4.1-r1)
(31/58) Installing p11-kit (0.23.16.1-r0)
(32/58) Installing libtasn1 (4.14-r0)
(33/58) Installing libunistring (0.9.10-r0)
(34/58) Installing gnutls (3.6.8-r0)
(35/58) Installing cups-libs (2.2.11-r0)
(36/58) Installing jbig2dec (0.16-r0)
(37/58) Installing libjpeg-turbo (2.0.2-r0)
(38/58) Installing tiff (4.0.10-r0)
(39/58) Installing ghostscript (9.27-r1)
(40/58) Installing libgcc (8.3.0-r0)
(41/58) Installing libstdc++ (8.3.0-r0)
(42/58) Installing libde265 (1.0.3-r0)
(43/58) Installing x265-libs (3.0-r0)
(44/58) Installing libheif (1.3.2-r2)
(45/58) Installing libxft (2.3.3-r0)
(46/58) Installing fribidi (1.0.5-r1)
(47/58) Installing graphite2 (1.3.13-r1)
(48/58) Installing harfbuzz (2.5.1-r0)
(49/58) Installing pango (1.42.4-r1)
(50/58) Installing libcroco (0.6.13-r1)
(51/58) Installing shared-mime-info (1.12-r0)
(52/58) Installing gdk-pixbuf (2.38.1-r0)
(53/58) Installing librsvg (2.40.20-r0)
(54/58) Installing libwebp (1.0.2-r0)
(55/58) Installing imagemagick (7.0.8.49-r2)
(56/58) Installing libfontenc (1.1.4-r0)
(57/58) Installing mkfontscale (1.2.1-r1)
(58/58) Installing ttf-opensans (1.10-r0)
Executing ttf-opensans-1.10-r0.post-install
Executing busybox-1.30.1-r2.trigger
Executing fontconfig-2.13.1-r0.trigger
Executing shared-mime-info-1.12-r0.trigger
Executing gdk-pixbuf-2.38.1-r0.trigger
Executing mkfontscale-1.2.1-r1.trigger
OK: 99 MiB in 71 packages
Removing intermediate container 5637b4df6510
 ---> 74fc05269d09
Step 11/20 : WORKDIR /invidious
 ---> Running in 13b6dc24eb55
Removing intermediate container 13b6dc24eb55
 ---> bd8b18029ead
Step 12/20 : RUN addgroup -g 1000 -S invidious &&     adduser -u 1000 -S invidious -G invidious
 ---> Running in 7197bd50093b
Removing intermediate container 7197bd50093b
 ---> a4b0af129c1b
Step 13/20 : COPY ./assets/ ./assets/
 ---> e3c127a41899
Step 14/20 : COPY ./config/config.yml ./config/config.yml
 ---> 67e1e2f39e28
Step 15/20 : COPY ./config/sql/ ./config/sql/
 ---> 5bb9dc08398c
Step 16/20 : COPY ./locales/ ./locales/
 ---> 2ea353435806
Step 17/20 : RUN sed -i 's/host: localhost/host: postgres/' config/config.yml
 ---> Running in 566adf286845
Removing intermediate container 566adf286845
 ---> c5aa9d4be014
Step 18/20 : COPY --from=builder /invidious/invidious .
 ---> ac8f62bec1e9
Step 19/20 : USER invidious
 ---> Running in 7771a3079594
Removing intermediate container 7771a3079594
 ---> 921e4d8ca57e
Step 20/20 : CMD [ "/invidious/invidious" ]
 ---> Running in 7a6f11315a93
Removing intermediate container 7a6f11315a93
 ---> 74b8444ccba7
Successfully built 74b8444ccba7
Successfully tagged invidious_invidious:latest
```

**Comment by leonklingele** [comment]
I've opened https://github.com/omarroth/invidious/pull/682 which ensures our Docker build succeeds as well.

**Comment by Stolz** [comment]
@leonklingele you are right. It seems I had an older image of Alpine. Once I downloaded version b7b28af77ffe it build fine. Sorry for the inconvenience.
