### ISSUE TITLE
Youtube video is not listed

### ISSUE THREAD

**Issue by SicroAtGit** [omarroth/invidious#683]
This Youtube video does not exist in Invidious:

> Die Kunst des Hackens | Doku | ARTE
> https://www.youtube.com/watch?v=7JysTL0UEgI

After a little scrolling you can find the video in this list:
https://www.youtube.com/user/ARTEde/videos

But not in Invidious:
https://invidio.us/channel/UCLLibJTCy3sXjHLVaDimnpQ

**Comment by omarroth** [comment]
Geo-blocked videos are hidden from the channel list, see #181. Viewing the channel on a German instance (e.g. https://de.invidious.snopyta.org/channel/UCLLibJTCy3sXjHLVaDimnpQ) displays all videos as expected.

**Comment by SicroAtGit** [comment]
I didn't suspect geo-blocking at all with this video.

Your mentioned workaround with the German instance works. I use the program FreeTube and there it is fortunately possible to change the instance.

Thanks a lot!
