### ISSUE TITLE
Autohide control bar if no focus on player frame (youtube player style)

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#685]
YouTube automatically hides the control bar if focus is not anymore on the player frame.

**Comment by leonklingele** [comment]
This works just fine for me, however the control bar is hidden with a 2–3 second delay.

**Comment by Perflyst** [comment]
Seems like it was bugged for me yesterday, works as expected.

**Comment by atahanacar** [comment]
Could this be related to #718?
