### ISSUE TITLE
"Video unavailable." on every video: again?

### ISSUE THREAD

**Issue by cy8aer** [omarroth/invidious#686]
I again have the video unavailable error. Server is in germany. Machine worked at morning hours but yet in the evening every video fails with this error 500.

I cannot reproduce the errors on other known instances. Is there a possibility to debug this?

Buster, psql 11+200++deb10u1, Apache
 0.19.1-b63f469 master

**Comment by omarroth** [comment]
Would you mind running:
```
$ curl --ipv6 'https://www.youtube.com/watch?v=ukDht4jRcT0&gl=US&hl=en&disable_polymer=1&has_verified=1&bpctr=9999999999' -o ukDht4jRcT0.html
```

and checking that `player_response` is present in the resulting file? If it’s not present, you may be getting rate-limited, in which case try setting `force_resolve: ipv4` in `config.yml`.

**Comment by cy8aer** [comment]
hm, it looked like a temporary problem and is working again. Today curl both - ipv4 and ipv6 return a `player_respond` element. But I will keep your testing advice in mind for the next "incident".

Closing it because works for me by now.

**Comment by cy8aer** [comment]
Forgot a: Thank you!
