### ISSUE TITLE
Fullscreen shortcuts results in buggy behaviour

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#688]
Currently with shift + f you get the video in fullscreen. But you also sometimes get the video in fullscreen with ctrl + f. This does not seem to be intended and is also buggy (see screenshot below)

![Screenshot_20190810_115619](https://user-images.githubusercontent.com/26308977/62820544-e46dc180-bb65-11e9-8790-974d3bf0cca0.png)

**Comment by leonklingele** [comment]
I bet https://github.com/omarroth/invidious/pull/678 will resolve this.

**Comment by omarroth** [comment]
Resolved by #678 :+1:
