### ISSUE TITLE
Subscription not showing

### ISSUE THREAD

**Issue by ankitdahiya95** [omarroth/invidious#690]
Preferences:
![s2](https://user-images.githubusercontent.com/13098318/62824688-70f89e00-bbbf-11e9-84f3-a1f7dbd77752.JPG)

Subsciption feed:
![Screenshot (50)](https://user-images.githubusercontent.com/13098318/62824709-9d141f00-bbbf-11e9-95be-47017b048700.png)

My user id is ankitdahiya95@gmail.com

**Comment by ankitdahiya95** [comment]
Update: So, there is a delay in updating subscription feed. Now the feed is alive but only wrt videos 8-9 hours ago. Also, if I subscribe a channel recently, it's videos won't show up instantly.

**Comment by ankitdahiya95** [comment]
Update2: Subscription feed updating slowly is definitely the issue here. When I subscribe/ unsubscribe a channel, it takes ~10 hours to update in feed.
I realise I never thanked you, so thanks @omarroth and others. I love it.
Another query I want to ask is how can be save playlist? Is there another platform (discord, telegram, etc. ) for asking these questions?

**Comment by Gingerskittles** [comment]
My subscription feed has also not updated in two days

**Comment by ankitdahiya95** [comment]
While feed updates the next day, Subscription icon is working fine. Is there any other forum for invidious community?

**Comment by omarroth** [comment]
I expect this is a duplicate #674. As mentioned there it's something I'm currently looking into.

> Is there any other forum for invidious community?

Sure, there's a [Matrix Server](https://riot.im/app/#/room/#invidious:matrix.org) if you'd like to chat.

**Comment by omarroth** [comment]
Closing in favor of #674.
