### ISSUE TITLE
Autoplay videos when they are loaded

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#7]
It would be nice if it could do that for ones that aren't embedded (or just have them all play when loaded and offer the ability to stop the auto-play by adding &autoplay=0 or ?autoplay=0 to the end of the URL).

**Comment by omarroth** [comment]
Seems like it would make more sense for the default to be no autoplay and then add `autoplay=1`.

**Comment by omarroth** [comment]
Actually, it might make more sense to be an option for #6.

**Comment by Zero3K** [comment]
Does the auto-play option only affect videos that aren't embedded?

**Comment by omarroth** [comment]
@Zero3K Yep, player preferences are only used on `/watch` page.

**Comment by omarroth** [comment]
Thank you very much for the device information. I'm having trouble finding details on what Naked Browser does and does not support, but 8861d31 should fix it if the issue is with running JavaScript. Also to note if this is the issue: you will not be able to use player offset, volume, and speed without JavaScript.

**Comment by Zero3K** [comment]
The option has stopped working in Pale Moon for a few days now.

**Comment by gitaarik** [comment]
Doesn't seem to work in Firefox for me, tested it on Chrome and it works. I'm testing it on the invidio.us website.

**Comment by elypter** [comment]
maybe mozilla added an exception for them

**Comment by omarroth** [comment]
Autoplay appears to be disabled by default in Firefox beginning [March 19th](https://www.computerworld.com/article/3338108/firefox-set-to-silence-auto-play-audio-with-march-upgrade.html).

From some quick tests, it seems YouTube is *not* exempt from Firefox's autoplay policy, however it appears it's able to detect when it is able to play (for example, after a user has clicked or interacted with the tab) and immediately start playback.

There's some information on how Chrome handles autoplay [here](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

Unfortunately there doesn't look like there's much to be done here on Invidious's side. As mentioned above there is a [support page provided by Mozilla](https://support.mozilla.org/en-US/kb/block-autoplay#w_add-sites-to-your-list-to-autoplay-media) to whitelist sites.

**Comment by gitaarik** [comment]
Maybe a nice idea to add this information to the autoplay setting on the invidious settings page? This information can then contain a link to the Firefox support page. Maybe use browser detection to only show this message for Firefox?

**Comment by omarroth** [comment]
There's been some mention of adding an `/about` page for things exactly like this (see #227). Unfortunately I haven't time to add it, but I think something like that would be very helpful here.

**Comment by gitaarik** [comment]
Ok, do you mean to create the `/about` page and adding the message there or adding it to the autoplay setting on the settings page?

**Comment by omarroth** [comment]
Adding it as an item for an `/about` page.
