### ISSUE TITLE
Issue with viewing a video

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#70]
I get an error when viewing https://www.invidio.us/watch?v=CCu1qkIc-18. It works when using https://www.invidio.us/embed/CCu1qkIc-18&raw=1, though.

**Comment by omarroth** [comment]
They both appear to be working fine now. Let me know if the problem persists, otherwise I'll probably close this.

**Comment by Zero3K** [comment]
I wonder what was causing it. I'll let you know if it happens again.

**Comment by omarroth** [comment]
Appears to be fixed by 9ed72a8dade3716a772d2fdda81893b65f06d6a9, which should be going live now. 

The only issue that remains appears to be fixing the displayed thumbnail. Playing the video appears to work fine though.
