### ISSUE TITLE
Videos of "Topic" channels are displayed with 0 views

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#715]
When searching for a videos contained on "Topic" channels they are displayed with 0 views, 

![1](https://user-images.githubusercontent.com/47571719/63403884-a461d680-c3d0-11e9-97cd-1a30d8870178.png)

When it's displayed correctly on the video pages themselves : 
![2](https://user-images.githubusercontent.com/47571719/63403912-bcd1f100-c3d0-11e9-9328-d028677db8e9.png)

**Comment by omarroth** [comment]
Should be fixed with 9f9cc1ffb5abdb9c0b4331a1f69039f0e77ae667.

**Comment by TheFrenchGhosty** [comment]
Fixed.
