### ISSUE TITLE
Suggestion regarding livestreams

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#717]
If one is offline, it should no longer show up in the search results, etc.

**Comment by omarroth** [comment]
I'm not sure this makes sense, since a livestream usually becomes a regular video once it has ended. If it's not possible for them to be viewed I'm surprised they still show up in search results. Would you mind providing an example?

**Comment by Zero3K** [comment]
It happens in the Subscriptions page.

**Comment by omarroth** [comment]
I'm afraid in that case this will be `wontfix` unfortunately. AFAIK it's not currently possible to quickly detect when livestreams have ended, other than checking each one, which isn't practical given the number of streams it would need to check.

**Comment by Zero3K** [comment]
So, the offline stream will stay in the Subscription page for a while before its removed? I checked the second and so on pages and none of them are showing.

**Comment by omarroth** [comment]
Closing in favor of #726.
