### ISSUE TITLE
Default language of captions

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#72]
Is it possible to implement an option to set a default language(s) for closed captions?

**Comment by omarroth** [comment]
Maybe implemented as a drop-down?

**Comment by dimqua** [comment]
I think it should be on preferences page. Ideally languages should be prioritized like this:
1. English (if available)
2. English (auto-generated)
3. ...
4. ...

So user can define more than just one prefered languages. But I'm not sure if it's possible at all. :-)

**Comment by omarroth** [comment]
I think I can manage a default and a fallback. YouTube already provides a list of all the languages it supports, so listing them shouldn't be an issue.

**Comment by dimqua** [comment]
Can you add 2 fallback languages?
