### ISSUE TITLE
Apache2 configuration

### ISSUE THREAD

**Issue by RoiArthurB** [omarroth/invidious#730]
Hello,

I've install Invidious on a DigitalOcean droplet (if you try to do so, install invidious in a 2Go RAM droplet, and resize it to a 1Go RAM, it do the trick 😉 )

My question may sounds stupid but I would like to tweak my apache2 settings but I don't find it... Apache2 doesn't look to be installed at all and so I can't do what I want... 

Have I missed something somewhere? Does Invidious is not using Apache2? If so why [this wiki page?](https://github.com/omarroth/invidious/wiki/Apache2-Reverse-Proxy)

Thanks all :)

**Comment by Perflyst** [comment]
Of course you need to install apache manually. If you run Debian or similar, just install with "apt install apache2"

**Comment by RoiArthurB** [comment]
But so, how invidious is managing http requests? And should I move anything from invidious in my apache folder? 🤔

I'm sorry for that very basic questions, but I don't understand how that part works ^^"

**Comment by RoiArthurB** [comment]
Ok, I succeeded in setting up my invidious installed and handle the HTTP requests with apache2.

But I'm still curious to know what Invidious use to manage it all. If you can just give me a short answer (I'll do my own research after that :smiley:  )

Anyway, thanks a lot for Invidious! I love it :heart_eyes:

**Comment by Perflyst** [comment]
Apache forwards everything to Invidious. You could also expose Invidious directly and forward it to 443 with iptables but than you cannot put anything else on port 443.

**Comment by RoiArthurB** [comment]
My question was more about how Invidious manage web request, not how to wrap Apache around Invidious ^^"

But ok, thanks ^^
