### ISSUE TITLE
Ability to hide all videos on the official instance's home page

### ISSUE THREAD

**Issue by tdeeb** [omarroth/invidious#738]
One thing I dislike about YouTube is its insistence on showing you videos on the homepage with no option to turn them off. To work around this, I use browser add-ons to disable them. After finding out about the official Invidious instance, https://invidio.us/, I looked for a setting to disable the videos on the home page, but I wasn't able to find it in preferences.

Unfortunately, this is the main draw preventing me from using Invidious over YouTube right now. Is there a way to completely disable these recommendations in the official instance?

**Comment by omarroth** [comment]
Not currently, I expect this will be added as part of #295.

**Comment by tdeeb** [comment]
This was added in https://github.com/omarroth/invidious/commit/7524b5e349ca403d49d4c35c55e9dc161a4e7d59 and works perfectly. Thank you!
