### ISSUE TITLE
Ciphered videos unavailable in higher resolutions

### ISSUE THREAD

**Issue by Seneral** [omarroth/invidious#747]
So I noticed this issue in my own frontend, but found the same issue in invidio.us: Some (maybe all) ciphered videos are only available in 360p or lower. On invidio.us, this means the player will silently fall back to 360p and downloading at 720p will simply do nothing.

First I thought the ciphering was incorrect, but verified both mine and invidio.us correctly cipher (to my knowledge). Playing these videos on YouTube at high resolutions is no problem. 

The server error is 404 - unlike when you fail to cipher correctly or similar, which would return access denied. Since the parameters are the only variables, that means the servers actively deny access but choose to return 404 instead - bad news?

So I compared requests and most notably, youtube requests add the following to each request:
&alr=yes
&sig=   // signature, url-encoded
&cpn=   // client playback nonce - similar to client screen nonce (csn) - probably can be figured out
&cver=2.20190905.06.00   // Client version, easy enough
&sq=---&rn=---&rbuf=--- // Probably segmenting?

whereas invidious sends
&host=  // host name as found in the URL
&sig= // signature, not url-encoded

For now I'd assume that maybe adding alr, encoding the sig properly (notice how = become %3D), figuring out cpn and adding cver would maybe suffice.
But maybe this is related to some other stuff I saw, where you said higher resolutions require proxying or something. I couldn't verify that yet in my own frontend, so maybe this is it? But you said you had a solution for that (that is, proxying) so I assume not.

**Comment by Seneral** [comment]
Ok a bit dissappointed cpn is 100% randomly generated...
16 characters of "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
Will test now if that yields any results...

**Comment by omarroth** [comment]
[This comment](https://github.com/TeamNewPipe/NewPipe/issues/2415#issuecomment-515543289) will probably be useful for you. Essentially YouTube is providing something like a "template" URL, so an additional `/sq/SEQ` or `&sq=SEQ` needs to be added for it to be considered a valid.

Unfortunately I'm not able to test without an example, but you might check that the Invidious URL with `&quality=dash` (e.g. `/watch?v=ID&quality=dash`) allows you to play 720p.

**Comment by Seneral** [comment]
Ah I just tested aswell with SQ=0 and 404 went away - though now I get the CORS denied that I was expecting from previous comments.
Anyway, now I know that I won't get farther without MSE - and since that is quite a rewrite, I'll do that later/after release.

Although I'd like to add you can get the dashManifest directly from youtube if you need, it's in player_config.args.player_response.streamingData.dashManifestURL. The URLS even seem to be signed, although the format of the URLs are different so I can't tell 100%.

**Comment by Seneral** [comment]
Oh and yes, with &quality=dash it works - didn't realize invidious used legacy streams by default. Seems the playback options aren't even displayed without quality=dash. Is this intended or what is the reasoning for this?
Anyway yes, didn't realize it was possible, so I'll close this. Thanks!
