### ISSUE TITLE
Some annontations display incorrectly (especially when the text is big)

### ISSUE THREAD

**Issue by Natester1986** [omarroth/invidious#759]
I noticed this on a few videos since yesterday (I just started using Invidious since the annontations extention for Firefox stopped working since YouTube deleted the code to render annontations).  Most annontations are ok but some such as this one display incorrectly.
![Annontations display incorrectly](https://user-images.githubusercontent.com/55558399/65276104-b082a600-daec-11e9-8a2e-f5e409a6ca5c.jpg)

Another problem is the fact that the hallow annontations (the type of annontations that display text when you move your cursor over them) does not display any text at all.  Example is below:
![Test should display when the mouse is over this type of annontation](https://user-images.githubusercontent.com/55558399/65276007-803b0780-daec-11e9-8774-65e5414408b6.png)

Can this be fixed?

**Comment by Natester1986** [comment]
Nevermind, afrmtbl is the one who gave the code to Invidious (as I just found out on TrashDump discord).  Closing this.

**Comment by omarroth** [comment]
Apologies for the delay. I'd recommend opening a new issue in [afrmtbl/videojs-youtube-annotations](https://github.com/afrmtbl/videojs-youtube-annotations) with the above examples (along with video IDs) to test with.
