### ISSUE TITLE
Issue with a userscript that I mentioned in an earlier issue

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#76]
I just noticed that its not working on an embed found in https://www.resetera.com/threads/toonami-julaug18-do-not-interrupt-the-grillmaster.52676/page-275. Other embeds in that link do redirect properly. The userscript can be found in Issue #65.

**Comment by omarroth** [comment]
Could you link directly to the embed?

**Comment by Zero3K** [comment]
I see why its happening. Its because its not redirecting https://youtu.be/ozosGipsoNE to http://www.invidio.us/embed/ozosGipsoNE.

**Comment by omarroth** [comment]
I'm assuming it's an issue with the userscript then? If so, then we can close this.

**Comment by Zero3K** [comment]
It is. It would be nice if someone could fix it.
