### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Shoe444** [omarroth/invidious#760]
I'm not sure where to post this error, but I keep getting this error when I try to view videos on YouTube:

The media could not be loaded, either because the server or network failed or because the format is not supported.

How can I fix this? Thanks in advance.

**Comment by Zero3K** [comment]
That error has always been a problem with it. I hope that it can get completely fixed soon.

**Comment by Shoe444** [comment]
It does seem to be random throughout YouTube. I hope they fix it soon too.

**Comment by Shoe444** [comment]
It's happening more and more now. I would say that I can't watch over 50% of the videos now. Any idea of when this might get fixed, or is there anything I can do to prevent the error message?

**Comment by omarroth** [comment]
I would recommend testing either `local=true` or `quality=dash`. Depending on your region you might also look through [the list of available instances](https://github.com/omarroth/invidious/wiki/Invidious-Instances) to see if there is one in your region.
