### ISSUE TITLE
[Feature Request] Having a way to see at which time a video was released

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#761]
Right now the only videos where users can see when exactly they were released, are the one that came out less than a day before, and this doesn't appears on the video pages itself.

Example: 

Channel Pages / Search Pages display it like that:
![1](https://user-images.githubusercontent.com/47571719/65352461-40eae480-dbda-11e9-9249-f3e345534fbd.png)

While the video page itself display it like any other video:
![2](https://user-images.githubusercontent.com/47571719/65352498-5b24c280-dbda-11e9-8e80-7948e6facfe4.png)

This is why today I'm requesting to have a way to see at which exact time a video was released in a day: 
- either using ``Shared: September 19, 2019 or 1 day, 12 hours 35 minutes ago`` 
- or using ``Shared September 19, 2019 at 14:35``.

This second option however require supporting 24 and 12 time format and supporting custom timezone (or a fixed one? even if I don't think that's a good implementation) making (in my opinion) things a lot harder to implement but while providing far better information (I guess this is a long term objective for this request).

PS: I'm already sorry for the work that will be required if you decide to implement it.
PS-2: YouTube don't even have this feature

**Comment by omarroth** [comment]
YouTube does not provide enough information on the watch page to accurately provide a published date:
![image](https://user-images.githubusercontent.com/14208607/65354318-3d953000-dbbd-11e9-8b3d-cb82c2233fba.png)

So I don't think this is possible to implement.
