### ISSUE TITLE
iframe embeds that are 250x250 produce a scrollbar

### ISSUE THREAD

**Issue by qtpichan** [omarroth/invidious#770]
For some reason if embeds are at approx 250x250, the iframe produces a scrollbar near the bottom. my guess is the interface isn't scaling with the actual interface

![embed](https://i.imgur.com/Smpyh27.png "embeds are squished")

**Comment by omarroth** [comment]
Should be fixed with e03b4b7505f7757a9b5c2a4ea5d8232b7a68c66e.
