### ISSUE TITLE
getaddrinfo: System error

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#781]
I got quite much errors like
`UCOVzRGlVSRUb0ItTmTXLKaw : getaddrinfo: System error`

It stopped after some time and worked again, what exactly happened here? This is the only entry in the log, there is no exception or something else.

**Comment by omarroth** [comment]
`System error` would indicate an issue in name resolution (which is handled by the OS). My guess might be if the DNS server times out, or if high load causes some sort of failure.

**Comment by Perflyst** [comment]
Could be, yes. Does invidious cycle through all DNS servers available in /etc/hosts?

**Comment by omarroth** [comment]
Invidious doesn't handle name resolution. Anything like that would be handled by the OS.
