### ISSUE TITLE
Request: Video descriptions in RSS entries

### ISSUE THREAD

**Issue by lkhd** [omarroth/invidious#796]
Hello!

As seen in the image below, RSS feeds contain the link to the video and the thumbnail, but it would be great to have the video's description added as well, if applicable.

![Feed entry](https://i.imgur.com/meuwLE8.png)

**Comment by omarroth** [comment]
Added with c0796ac3d63823f00a5895007fbc7643af6c31a5.

**Comment by lkhd** [comment]
Thank you!
