### ISSUE TITLE
Vacuum mode for database

### ISSUE THREAD

**Issue by Dryusdan** [omarroth/invidious#799]
Hi,

Today I'm very surprising after discover my database size : 7GB only for videos table.
After analyse, I found an IP who load all comments of lot of videos (This ip generate more than 72 000 request in 8 hours).

In the futur, other bot can do this and increase size of my database.
Is it possible to add a vacuum mode for database, for exemple "delete videos older than 7 days in DB" or "Remove comments" ?

Regard

**Comment by omarroth** [comment]
`videos` is used mainly as a cache for retrieved videos. You can run `psql invidious -c "TRUNCATE TABLE videos" > /dev/null` to empty it. I'd recommend taking a look through [Database Maintainence](https://github.com/omarroth/invidious/wiki/Database-Information-and-Maintenance) for more info.

**Comment by Perflyst** [comment]
Maybe this cleanup should be somehow done by default if Invidious is running.

**Comment by Dryusdan** [comment]
Thank you for you answer :)

I save the page of wiki in my bookmark

**Comment by omarroth** [comment]
> Maybe this cleanup should be somehow done by default if Invidious is running.

I believe this is out of scope for the project. As mentioned in #506 I trust the database administrator for how best to manage their database.
