### ISSUE TITLE
Search not working in api-only branch

### ISSUE THREAD

**Issue by bitnol** [omarroth/invidious#800]
All search results are blank. Please check it.

**Comment by omarroth** [comment]
I'm not able to reproduce this locally. Would you mind running:

```
$ curl 'https://www.youtube.com/results?search_query=test&disable_polymer=1
```

I expect you're being rate-limited by Google.

**Comment by bitnol** [comment]
You are right. Curl is working and search started working too. It should be rate-limitation by YouTube.

**Comment by Agaclar** [comment]
hi.I install api-only.but api-only using crystal 0.32.0.but i cant install crystal 0.32.0.how can fix this problem?
