### ISSUE TITLE
Video timeline does not reach the end on very short videos

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#803]
This is another edge case:
![2019-10-07_07-31](https://user-images.githubusercontent.com/26308977/66287102-ad512d80-e8d4-11e9-96e4-f5d1ece9278c.png)

Example video: https://invidio.us/watch/?v=BLzxGwO7H-0

**Comment by omarroth** [comment]
I would call this intended behavior, since YouTube doesn't provide any storyboards for the above video.
