### ISSUE TITLE
Bug when entering youtube URL in search field

### ISSUE THREAD

**Issue by n0-1** [omarroth/invidious#804]
Hi,

When looking for a way to quickly open a video in invidio.us I tried entering the full Youtube URL into search field which led to the "Looks like you've found a bug in Invidious." message. The URL in question was: https://www.youtube.com/watch?v=tC_vYJBhJuc

Cheers, Phil

**Comment by omarroth** [comment]
I'm having trouble reproducing this, would you mind providing the search URL that produced the error?

Something like https://invidio.us/search?q=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DtC_vYJBhJuc

**Comment by n0-1** [comment]
Hi Omar,
Neither can I. So either the problem was something else and I just happened to trigger it or it happened for an older version of the software. Either way, I'm good. Thanks for looking into it!
Cheers, Phil
