### ISSUE TITLE
RSS feed in the .onion domain show bad URL

### ISSUE THREAD

**Issue by emanruse** [omarroth/invidious#805]
Currently the RSS feeds show:

https://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion:8081/watch?v=<....>

and such URL cannot be opened. It must not be https but http and without 8081 port.

**Comment by omarroth** [comment]
Appears to have been a configuration error. Should be fixed.
