### ISSUE TITLE
Region URL parameter can issue HTTP 504 error

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#807]
I tried to access this url `https://invidio.us/watch?v=Pwqs5Ko7lAU` with region URL parameters.

`https://invidio.us/watch?v=Pwqs5Ko7lAU&region=DN` works.
`https://invidio.us/watch?v=Pwqs5Ko7lAU&region=FR` does not work. More, it returns a HTTP 504 error.

**Comment by omarroth** [comment]
The `region` parameter is ignored if the provided region is invalid or there are no valid proxies for the desired region (in this case `DN` is being ignored). The 504 issue should be fixed with the latest version.
