### ISSUE TITLE
HTTP Error 500 - impossible to watch any video

### ISSUE THREAD

**Issue by emanruse** [omarroth/invidious#809]
Yesterday everything worked fine.
Today I get HTTP Error 500 on all video pages and no video shows.

**Comment by Perflyst** [comment]
invidio.us (and also other instances) are currently facing issues probably due to #772 and#778
Try to use [another Instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances) for the moment to watch videos.

**Comment by omarroth** [comment]
Should now be resolved if you'd like to confirm.
