### ISSUE TITLE
Alternative timestamps

### ISSUE THREAD

**Issue by narcolepticinsomniac** [omarroth/invidious#81]
Currently, I only see  `.vjs-remaining-time-display`. It'd be nice if there were options for total time, and counting progress in the opposite direction. If prefs are complicated, a decent alternative would be to include the others and hide them by default, allowing them to be hidden/revealed with user CSS,

**Comment by omarroth** [comment]
Looks like VideoJS already [provides them](https://docs.videojs.com/tutorial-components.html#default-component-tree), so this should be added fairly quickly.

**Comment by omarroth** [comment]
Added with 06af43c95e3d13262e05c940acb4ead05277c357.
