### ISSUE TITLE
Embed live stream does not work

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#812]
I faced an issue while checking embeds in Invidition.

`https://invidio.us/embed/KGEekP1102g` does not work where `https://invidio.us/watch?v=KGEekP1102g` works.

The youtube version of the embed is `https://youtube.com/embed/KGEekP1102g`.

I tried with another random live stream and it was working on both `https://www.invidio.us/embed/0fKyrdQ15gs` and `https://www.invidio.us/watch?v=0fKyrdQ15gs`.

**Comment by omarroth** [comment]
`https://invidio.us/embed/KGEekP1102g` also plays for me. Are there any errors being logged in devtools?

**Comment by Booteille** [comment]
It seems to be bound to `quality=dash` option. It's redirecting me to the homepage when I add this parameter to the embed.

I guess it's because it's a live stream.

Is it possible to ignore the parameter instead of making a redirection?

**Comment by omarroth** [comment]
Yep, should be fixed with 2a04a48b891835ce3d68ff883c7b88a6b2e37508.
