### ISSUE TITLE
Add option in settings to clean up the interface (remove recommendations, top, subscriptions, etc)? 

### ISSUE THREAD

**Issue by 21dax2lxkcsun3lvdgggizr2a** [omarroth/invidious#818]
Any chance you could add an option in the settings to  remove popular, top, trending and subscriptions recommendations? I love invidio.us, and stumbled upon through trying to minimize my distractions on the Youtube, so it would be a great QOL addition!

Something like this I guess:
<img width="1439" alt="Screenshot 2019-10-13 at 23 05 17" src="https://user-images.githubusercontent.com/56490797/66722474-b6268f80-edfd-11e9-8924-39558f50de5c.png">

**Comment by omarroth** [comment]
Should be added as part of #295.

**Comment by dimqua** [comment]
Do you really need to remove subscriptions? Why?
