### ISSUE TITLE
Support local subscriptions?

### ISSUE THREAD

**Issue by SoniEx2** [omarroth/invidious#821]
I don't understand why we need to store everything on a server. Just store things locally tbh.

Bonus points for syncing through WebRTC/p2p/QR code you can scan with your phone.

**Comment by omarroth** [comment]
The main issue is that it won't work without JS, which is one of the primary goals of this project.

If you would like to store your subscriptions locally I can recommend [CloudTube](https://github.com/cloudrac3r/cadencegq), [FreeTube](https://github.com/FreeTubeApp/FreeTube), or [NewPipe](https://github.com/TeamNewPipe/NewPipe) (although there are others).

Currently I consider this feature out-of-scope for the project.

**Comment by elypter** [comment]
arent cookies read and written on every request?
