### ISSUE TITLE
PR_END_OF_FILE_ERROR 

### ISSUE THREAD

**Issue by stemy2** [omarroth/invidious#837]
ello,

I can't browse without seeing this error message. I have to reload the pages every time, this is a bit annoying.

**Comment by Progman-DT** [comment]
google is probably heavily ddosing them rn

**Comment by omarroth** [comment]
Currently https://invidio.us is being moved over to a custom load-balancer, which I expect is causing the issue.

I've made a couple changes and no longer encounter this on the official instance. Would you mind checking to confirm @stemy2?

**Comment by stemy2** [comment]
It works !
