### ISSUE TITLE
Distraction-free mode

### ISSUE THREAD

**Issue by Magi-max** [omarroth/invidious#841]
For me, youtube is the best source of learning materials, but its still can be pretty distracting. When you open it, there is a lot of suggestions, and subscription updates, so instead of learning you may end up watching your favorite shows.
I think it will be a cool feature, to have distraction-free mode, where you will have only search bar on main page, and fill suggestions in player page only with materials from education category (or disable everything except videos from current channel).

**Comment by omarroth** [comment]
For an empty homepage, you can set both `Default homepage:` and `Feed menu:` to empty in your preferences.

Currently there isn't a practical way to provide alternative suggestions, but you can disable them by disabling `Show related videos:`.
