### ISSUE TITLE
Constant stream of DNS queries for www.youtube.com

### ISSUE THREAD

**Issue by 2secslater** [omarroth/invidious#847]
Hi,
Rougly every second, Invidious makes a DNS query for www.youtube.com. I think this is unneeded. Could Invidious cache the IP address for a period of time?

![GIF of DNS queries](https://i.imgur.com/9RLWxCu.gif)

**Comment by Perflyst** [comment]
This is not the job of Invidious. This is the job of the OS. Use dnsmasq or similar for caching.

**Comment by 2secslater** [comment]
dnsmasq is already caching the IP address, Invidious is constantly making queries for www.youtube.com and will receive the same response every time.

**Comment by omarroth** [comment]
Would you mind checking to see if 6930570fa2d3c6a3ef82bb3e529b5989fc706b3c fixes the issue for you?

**Comment by 2secslater** [comment]
Nope, Invidious is still constantly making DNS queries for www.youtube.com after updating to the latest commit

**Comment by omarroth** [comment]
Gotcha, check to see that bdeb325bad15ea32a3f039de39418a88a6ab6180 fixes the issue for you.

**Comment by 2secslater** [comment]
That seems to have sorted it. Thanks!
