### ISSUE TITLE
Subscription vidéos missing

### ISSUE THREAD

**Issue by Blob159159** [omarroth/invidious#849]
Hi (and sorry for my English)
I have a little problem:
When I follow a Youtube channel (channel/UC4peNo-31r7fhQZgu0_JRIA for example), one part of the videos don't appear on the subscription page. The 20/30 last videos appear after hours or minutes, sometimes other older ones,  but "never" the totality of the channel.
I tested with a blank account, or on other instances, but the result is the same.

**Comment by Pyros65** [comment]
Same problem with nigahiga:
8-12 month old videos are missing in the subscriptions tabs.
[channel](https://image.noelshack.com/fichiers/2019/44/1/1572286387-channel.jpg)
[subscriptions](https://image.noelshack.com/fichiers/2019/44/1/1572286386-subscriptions.jpg)

**Comment by omarroth** [comment]
Generally it's impractical to get all videos for all channels subscribed to on an instance. If you are running your own instance, you can set `full_refresh: true` in your config to get this behavior, although it will take longer for newer videos to appear.
