### ISSUE TITLE
Account for hashtags used instead of question marks in params

### ISSUE THREAD

**Issue by narcolepticinsomniac** [omarroth/invidious#85]
Example:

https://invidio.us/embed/_pRZaNSnGHA#t=13m40s?fs=1&autoplay=1&enablejsapi=1&start=0

Autoplay is ignored, and if you start the vid manually, the start time is ignored.

**Comment by dimqua** [comment]
>The media could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by narcolepticinsomniac** [comment]
Hmm. I have no issues with it loading if I click it manually, it's just that the parameters are ignored. I assume it's bc question marks are expected to begin params, so hashtags screw things up. If I replace the hashtag with a question mark, params work as expected.

**Comment by dimqua** [comment]
Even https://www.invidio.us/watch?v=_pRZaNSnGHA does not work for me in Mozilla Firefox at least.

**Comment by omarroth** [comment]
It appears to be working for me in Safari, although the thumbnail doesn't load currently.

It appears that YouTube ignores the params as well. I'm looking at [this](https://youtube.com/embed/_pRZaNSnGHA#t=13m40s?fs=1&autoplay=1&enablejsapi=1&start=0).

My understanding is that a hashtag signifies something like a comment, in that everything after it is ignored.

**Comment by narcolepticinsomniac** [comment]
Well, it's used in the wild. I came across it on Reddit. I doubt the intention is to "comment out" the parameters.

**Comment by omarroth** [comment]
That's fair enough. I suppose my main point was that YouTube itself doesn't appear to support it.

**Comment by narcolepticinsomniac** [comment]
You're right, YT embeds also ignore params. I hadn't really tested that in particular. I was referring actually clicking the link to open the vid on YT vs Invidious. 

YT redirects:

https://youtu.be/_pRZaNSnGHA#t=13m40s

to:

https://www.youtube.com/watch?v=_pRZaNSnGHA&feature=youtu.be#t=13m40s 

which makes the start time work. 

AFAICT, unfortunately you're currently stripping params on top level URLs opened on your website. Should I open another issue to whine about that? =)

Original thread for that link, in case it's helpful:
https://old.reddit.com/r/videos/comments/94mffd/sir_patrick_stewart_has_just_announced_he_will/

**Comment by narcolepticinsomniac** [comment]
Hmm. Seems YT has yet another start time param: `?time_continue=` which is stripped in their own embeds (or in Reddit's conversion to embed URLs), but works on the top level.

Example:

https://www.youtube.com/watch?time_continue=111&v=Z4b6BPaO944

Thread:

https://old.reddit.com/r/videos/comments/94lnyd/kiss_guy_yayo_sanchez_plays_monkeywrench_w_foo/

**Comment by omarroth** [comment]
In case anyone is curious: [URL](https://en.wikipedia.org/wiki/URL#Syntax) and [Fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier). It appears that the fragment is only processed client-side, which is something I'd like to avoid for usability on older browsers.

I'm curious what you mean by stripping params from top level URLs. 

https://invidio.us/_pRZaNSnGHA?listen=1&start=10
appears to redirect properly, to 
https://invidio.us/watch?v=_pRZaNSnGHA&listen=1&start=10
if that's what you mean.

`time_continue` doesn't seem to be [documented](https://developers.google.com/youtube/player_parameters), but then again neither is `t`, so I wouldn't have a problem adding it.

I wouldn't have a problem processing `#13m40s` server-side either, but it would have to come at the end of a URL, e.g. `https://invidio.us/_pRZaNSnGHA#13m10s`

**Comment by narcolepticinsomniac** [comment]
>I'm curious what you mean by stripping params from top level URLs.

Yeah, now I'm curious what I meant too. =) 

Clicking those two links you posted was the first time I've seen start time params work on links opened directly on your site. If I click them from here, start times work, but if I click them from Reddit they're stripped. My only guess is that something about Reddit's tracking redirects to `out.reddit.com` somehow jacks up the conversion of the redirector extension I'm using. The regex keeps the whole end of the string, so maybe their tracking redirects are doing the stripping before they're even converted.

![redirects](https://user-images.githubusercontent.com/14100003/43681918-69d144b4-9830-11e8-934c-5079dc5adc50.png)

**Comment by narcolepticinsomniac** [comment]
Figured it out, and it was my own fault, of course. I had an extra top level redirect for `youtu.be`:

![bad redirect](https://user-images.githubusercontent.com/14100003/43682316-9510eb20-983f-11e8-80d1-1bc562862765.png)

`youtu.be` already redirects on its own, so I guess it unnecessary and buggy. Disabling it seems to resolve the stripping of params. Apologies for the confusion. Real glad they actually work though, so I'm happy I brought it up. 

`time_continue` is also more popular than I would've guessed, because I found a handful while looking for test URLs.

**Comment by narcolepticinsomniac** [comment]
Yup, those are the relevant issues. I created the other one all on my own. Only thing I'd add is that isn't necessarily the same string for hashtags as the original example, like: `#t=`.

**Comment by narcolepticinsomniac** [comment]
Apparently hashtags aren't the only characters which cause params to be ignored. This one has a plus sign that does the same:

`https://old.reddit.com/r/videos/comments/2dnbbz/a_sad_day_indeed_the_original_rick_roll_video_has/`

`https://invidio.us/embed/dQw4w9WgXcQ+?fs=1&autoplay=1&enablejsapi=1&start=0`

**Comment by omarroth** [comment]
Funnily enough https://www.youtube.com/embed/dQw4w9WgXcQ+?fs=1&autoplay=1&enablejsapi=1&start=0 throws an error.

As a follow-up to `#t=`, the client doesn't actually send those to the server, the only way to handle it would be client-side, which I would prefer not to do. I think a good way to handle it would be to replace `#t=` with `&start=` in URLs.

**Comment by narcolepticinsomniac** [comment]
I don't get an error, it just strips params and I get https://invidio.us/embed/dQw4w9WgXcQ

The question mark is still there, so simply deleting the plus sign works here.

>I think a good way to handle it would be to replace `#t=` with `&start=`

Yeah, seems like the way to go. It might also need to be `?start=` if it begins a string with other params though, if I understand the syntax correctly.

**Comment by omarroth** [comment]
I was comparing the YouTube embed link to Invidious, which throws an error instead of stripping params :).

**Comment by narcolepticinsomniac** [comment]
Oh, gotcha. All of this is YT's fault, with multiple parameters that do the same thing, and allowing garbage characters to be inserted randomly in parameters.

**Comment by omarroth** [comment]
I think I'll close this then, unless there's a need to process any other params server-side (adding another `time_continue`, for example).

**Comment by narcolepticinsomniac** [comment]
Have you addressed reinterpreting random parameter characters like `#` or `+` yet?

**Comment by omarroth** [comment]
Currently it looks like Invidious handles them the same way YouTube does: This https://www.youtube.com/watch?v=dQw4w9WgXcQ+&start=10 redirects to https://www.youtube.com/watch?v=dQw4w9WgXcQ, and Invidious works the same way.

As for `#t=2m30s` syntax, I could add it client-side, but it wouldn't function without JavaScript.

**Comment by omarroth** [comment]
4f3d8a8ef641ab48b9dbffb6292b3d260cb15f9f makes it so e.g. `/watch?v=8n5XNYSLSag+abc+++&start=1m` redirects to `/watch?v=8n5XNYSLSag&start=1m` and similarly with embedded videos, but that's about all that can be done on my end (I could be wrong though). 

Keep in mind that a plus/hashes are valid characters in URLs, so it's not possible to strip them away. For example `/watch?+++=10+` means that key `   ` (three spaces) is equal to `10 ` (10 and space). As for `#&id=1252`, Invidious never receives anything that comes after a hash, browsers appear to automatically strip them away before they're even sent to Invidious, so it's not really possible to figure out what the user meant by `/watch?v=8n5XNYSLSag#&start=10m` when all Invidious receives is `/watch?v=8n5XNYSLSag`.

**Comment by narcolepticinsomniac** [comment]
>Keep in mind that a plus/hashes are valid characters in URLs,

Alright, but are they ever useful in YT URLs? I suppose I'll try using negative lookaheads for problematic characters to exempt them from the main redirect, and then make separate redirects for them where I'll strip/replace those characters, like:

`(.*)\+\?` = `$1?`

**Comment by omarroth** [comment]
> Alright, but are they ever useful in YT URLs?
Sure, searching for `Big Buck Bunny`, sends a request to `/search?q=Big+Buck+Bunny`. I'm assuming the problem you're trying to fix is user-error?

**Comment by narcolepticinsomniac** [comment]
I meant Youtube `watch/embed` video URLs. They appear to accomplish nothing except breaking functionality.  Seems both examples here can be fixed by stripping `+` characters preceding `?` characters, and swapping `#` characters for `?` characters if they begin parameters. I must be oversimplifying though, because it seems so obvious in my mind.

**Comment by omarroth** [comment]
I was afraid of doing that for fear of breaking some functionality I hadn't considered. I've been playing around a bit though, and it seems everything is working fine. Unless I see any problems, I'll probably push 32036e7914241835774a81d8e772faa0354ef367 live sometime tomorrow. As for `#`, that's something that'll have to be handled as a script, but I think your solution should be fine.

Example:
`/watch?v++=+aqz-KE-bpKQ++&listen=++1++` redirects to `/watch?v=aqz-KE-bpKQ&listen=1`

**Comment by omarroth** [comment]
Now that 32036e7 I think I'll close this, unless there are any other concerns.

**Comment by narcolepticinsomniac** [comment]
Yeah man, LGTM. Thanks again.
