### ISSUE TITLE
High pitched / low pitched audio?

### ISSUE THREAD

**Issue by MKs2w7cBxTRP3e2ivnYBddxc** [omarroth/invidious#860]
This is one of the strangest tech issues I've had. I opened up my whonix VM today which I use for browsing and watching freetube/invidious, and noticed every video on freetube sounded like the person inhaled helium. Next, I opened up the videos inside invidious as well as youtube-nocookie in the tor browser and noticed the same thing. 

No issues on youtube itself though, nor any issues with anything whatsoever on my host machine on the clearnet. I restarted the whonix VM, and it was the same issue in all the same places again, except the voices were extremely deep this time. After a 3rd restart, everything now seems to be back to normal.

Any clue what the heck this even is??

edit: it's too close to halloween for this shit.

**Comment by omarroth** [comment]
Since it affected FreeTube, Invidious, and youtube-nocookie I would suspect an issue with the VM, rather than with any of those applications. Unfortunately I'm not familiar enough with Whonix to be any more help in what the issue may have been.
