### ISSUE TITLE
Playlists list broken on a channel

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#863]
The playlists list of this channel https://invidio.us/channel/cubex55 / https://invidio.us/channel/UCVi6ofFy7QyJJrZ9l0-fwbQ trigger "Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com. "

This is the only channel where I can reproduce this bug.

The page is working on youtube.

**Comment by omarroth** [comment]
Should be fixed with b58950c574fae491b7194594d93df13c3c972c3c.

**Comment by TheFrenchGhosty** [comment]
Fixed.
