### ISSUE TITLE
CSS Automatic Dark/Light Mode

### ISSUE THREAD

**Issue by ttrv65ebyng** [omarroth/invidious#867]
Support for automatic switching between light and dark mode with the system's respective modes (macOS, iOS, etc.). Seems to be able to be implemented with "prefers-color-scheme" in CSS.

Any thoughts?

**Comment by elypter** [comment]
the switch should toggle between on/off/auto

**Comment by ttrv65ebyng** [comment]
Doesn't seem to work here. Even tried setting the "    " (blank) option in settings under the Theme option. The toggle also just switches between 2 modes for me. If it were on/off/auto, I imagine it should appear to switch between Dark/Light/Light or Dark/Dark/Light at some point during the day.

macOS 10.15.1 (19B88)
Firefox Quantum 70.0.1 / Safari 13.0.3
––
iOS 13.2
MobileSafari
––
Neither the invidio.us and dev.invidio.us automatically switch. When checking, it does work on other sites supporting the feature (such as DuckDuckGo)

Please let me know if I can provide any additional information to help debug this!

**Comment by elypter** [comment]
sorry, that was a misunderstanding. i meant it as a suggestion how to implement the feature

**Comment by ttrv65ebyng** [comment]
Oh, no you're fine! Sorry about the understanding on my part!

**Comment by omarroth** [comment]
This has already been added with #601. Appears to not been working due to a configuration error, should be fixed with bcdb8cd770cfaf32c2b0a9b454d7eb04433204e2.

**Comment by ttrv65ebyng** [comment]
Seems to work now, but still requires a refresh of the page and in dark mode, the page flashes white before going dark which can be pretty jarring in low light scenarios.
