### ISSUE TITLE
Mark videos as watched according to local history

### ISSUE THREAD

**Issue by heartlessglasses** [omarroth/invidious#868]
Hello!

Thank you for your great work here, I've only started using Invidious today and just finishing up setting up the infrastructure I need to fully switch to it from YouTube.

I was wondering if it's possible to add a functionality to mark videos as being watched if that video id (watch?v=id in URL across both Invidious sites and YouTube) is present in the browser history, or something similar? I guess functionality akin to that of the [YouTube Watchmarker](https://addons.mozilla.org/en-US/firefox/addon/yourect/) addon. (I considered adapting the addon to Invidious for my own use, but that's a bit beyond me at the moment.) I can see it being useful if one doesn't want to use an account on Invidious (kind of the reason I'm trying to replace YouTube in the first place), but still wants some local way to see what videos have been watched already.

Thanks.

**Comment by elypter** [comment]
that won't be possible as a feature of invidio.us. Websites cannot access the browser history(for a good reason). That feature would have to be integrated into an addon. You should open a feature suggestion [over there](https://github.com/sniklaus/youtube-watchmarker/issues) or try to help out yourself and submit a pull request

**Comment by heartlessglasses** [comment]
Oh, duh, silly me, I completely forgot about that fact! Nonetheless, thank you for your quick response and for directing me to their GitHub page, I'll make sure to see what can be done there or if I could find the time to contribute, myself. :)
