### ISSUE TITLE
docker compose build failed

### ISSUE THREAD

**Issue by kletellier** [omarroth/invidious#872]
Hi,

On master branch docker-compose build failed for creating builder service : 

```
ERROR: unsatisfiable constraints:
  so:libevent-2.1.so.6 (missing):
    required by: shards-0.9.0-r0[so:libevent-2.1.so.6]
                 crystal-0.31.1-r0[so:libevent-2.1.so.6]
```

On Step 2/20

`Step 2/20 : RUN apk add --no-cache crystal shards libc-dev     yaml-dev ldev sqlite-dev zlib-dev openssl-dev     sqlite-static zlib-static openssltatic`

**Comment by omarroth** [comment]
Would you mind testing with:
```
$ docker-compose build --pull
```

**Comment by kletellier** [comment]
Same issue => 
![image](https://user-images.githubusercontent.com/8279846/68160973-2d5ec780-ff55-11e9-9035-4d69ffc4785f.png)

**Comment by kletellier** [comment]
Strange i've no problem two weeks ago...

**Comment by omarroth** [comment]
The [shards](https://pkgs.alpinelinux.org/package/edge/community/x86_64/shards) package has been flagged as out of date, so I expect it hasn't been updated to use the latest version of libevent provided by Alpine.

**Comment by StephanStanisic** [comment]
I've had the same issue. After a lot of trying `docker-compose build --no-cache --pull` worked for me.

**Comment by m4teh** [comment]
That command doesn't at all fix the problem for me.
What's the solution? Continuously keep trying to build until one day it just eventually works?

**Comment by atahanacar** [comment]
I tried to solve the problem by upgrading Alpine from 3.10 to edge but even after getting the latest version, I still have the same problem.
