### ISSUE TITLE
How can  change theme ???

### ISSUE THREAD

**Issue by yaskammm** [omarroth/invidious#873]
Hello i want change theme how can this ???

**Comment by omarroth** [comment]
This button should allow you to change your theme:

![Screenshot_20191104_164539-1](https://user-images.githubusercontent.com/14208607/68160986-e952cf00-ff22-11e9-83e1-6859e7207639.png)

It's also possible to change your theme in `/preferences`, under `Theme: `:
![image](https://user-images.githubusercontent.com/14208607/68161075-156e5000-ff23-11e9-9c63-3b24738c9304.png)
