### ISSUE TITLE
Unable to play some videos 2

### ISSUE THREAD

**Issue by ffytczuthp** [omarroth/invidious#874]
Hello.

This video can not be played
https://invidio.us/watch?v=26TDp3vLa0w
https://invidio.us/watch?v=26TDp3vLa0w&listen=0
https://invidio.us/watch?v=26TDp3vLa0w&quality=dash
but video  https://www.youtube.com/watch?v=26TDp3vLa0w  plays well.

Other videos on **Youtube** and on **Invidio** played well.

I know that the video  https://www.youtube.com/watch?v=26TDp3vLa0w  requires 18 years of age, but other YT-videos, which require 18 years, perfectly played by **Invidio**.

The console has an error string
`GET https://invidio.us/api/v1/storyboards/26TDp3vLa0w?height=90 404 (Not Found)`
When viewing other videos on **Invidio** such an error does not occur.

Next video in the playlist on the same channel ( https://invidio.us/watch?v=OadTGyBvsoc ) plays well.

Option **"Proxy videos"** does not change the situation.

Browsers: Firefox 52.9 ESR  and  UCBrowser 7 (in fact it is Google Chrome 49).
OS: Windows XP SP3.

Thank you very much.

**Comment by omarroth** [comment]
Some 18+ videos can only played by logging in.

Youtube-dl is also not able to play the linked video.

```
$ youtube-dl 26TDp3vLa0w   
[youtube] 26TDp3vLa0w: Downloading webpage
[youtube] 26TDp3vLa0w: Downloading embed webpage
[youtube] 26TDp3vLa0w: Refetching age-gated info webpage
ERROR: Content Warning
This video may be inappropriate for some users.
       Sign in to confirm your age
g webpage
[youtube] 26TDp3vLa0w: Downloading embed webpage
[youtube] 26TDp3vLa0w: Refetching age-gated info webpage
ERROR: Content Warning
This video may be inappropriate for some users.
       Sign in to confirm your age
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Content Warning
This video may be inappropriate for some users.
       Sign in to confirm your age
```

**Comment by simoniz0r** [comment]
I am unable to watch any videos at all on any instances.  The API seems to be returning this for every video I try:
```
{"error":"Video unavailable."}
```
I am just going to the popular link and clicking videos there, and none of them are working.

**Comment by gerroon** [comment]
I see this on my own instaance too.  It just started today it seems.

**Comment by omarroth** [comment]
> I am unable to watch any videos at all on any instances.

This is a different issue, see #811.

**Comment by elypter** [comment]
> Some 18+ videos can only played by logging in, and are therefore not playable on Invidious.

couldn't this be done if the user uses proxy mode and invidio.us accesses youtube with an account?

**Comment by omarroth** [comment]
Potentially yes. Currently I consider that out of scope for this project.
