### ISSUE TITLE
Youtube: Download is disabled

### ISSUE THREAD

**Issue by teatimetom** [omarroth/invidious#883]
I cant download Videos on Youtube. It says "Download is disabled".

**Comment by tuxayo** [comment]
It seems intentional. Maybe an instance can decide that to spare bandwidth

**Comment by tuxayo** [comment]
To no load an invidious instance, I recommend using youtube-dl:
https://mrs0m30n3.github.io/youtube-dl-gui/

**Comment by omarroth** [comment]
This is intentional. As mentioned in Matrix the bandwidth usage has been getting quite high for the official instance.

**Comment by elypter** [comment]
couldn't you reenable downloads without the proxy. as far as i remember the only problem was the wrong name of the downloaded file but maybe the invidition addon could help with that.

**Comment by dimqua** [comment]
Sounds like a good idea.
