### ISSUE TITLE
You can support me i paid you 50 dollar ?

### ISSUE THREAD

**Issue by yaskammm** [omarroth/invidious#885]
You can support me i paid you 50 dollar ?
I need 3 support
1) change my ip address ipv6 because google block my ipv4 adress
2) i want add invidous my  html template (you help me how adding my code )
3) How using a lot of domain other template one server
You agre i now sent you 50 dollar.If agree sent me you fb,skype or whatsapp
number for online chating you
…

**Comment by Booteille** [comment]
Hi.

Just a reminder that donations are a gift, not something implicating someone owe you something back. So, the developper of Invidious does not owe you a support.
If he wanted to make paid support available, he would have tell it on the readme.

Anyway, I can't recommend you enough to check the [Wiki](https://github.com/omarroth/invidious/wiki) before asking for support.
As an example, the answer of your first need seems to be found in [Configuration](https://github.com/omarroth/invidious/wiki/Configuration) section of the Wiki.

**Comment by yaskammm** [comment]
> Hi.
> 
> Just a reminder that donations are a gift, not something implicating someone owe you something back. So, the developper of Invidious does not owe you a support.
> If he wanted to make paid support available, he would have tell it on the readme.
> 
> Anyway, I can't recommend you enough to check the [Wiki](https://github.com/omarroth/invidious/wiki) before asking for support.
> As an example, the answer of your first need seems to be found in [Configuration](https://github.com/omarroth/invidious/wiki/Configuration) section of the Wiki.

You can help me paid support ?????
1) change my ip address ipv6 because google block my ipv4 adress
2) i want add invidous my html template (you help me how adding my code )
3)How using a lot of domain other template one server

**Comment by elypter** [comment]
in addition to what @Booteille said the developer time to do this support is worth quite a lot more on the market

**Comment by omarroth** [comment]
I am happy to provide assistance freely and I have already tried my best to help you in #840. As @Booteille mentioned please read through the wiki or the linked issue #811 for help with your issue.

**Comment by yaskammm** [comment]
Why not reply ? i want paid support itis very simply problems but i dont uderstund.
I need 3 support
1) change my ip address ipv6 because google block my ipv4 adress
2) i want add invidous my  html template (you help me how adding my code )
3) How using a lot of domain other template one server
If not enough 50 dollar i can extend paid.Please help me
