### ISSUE TITLE
Workaround reCAPTCHA

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#886]
Since this was only discussed in the invidious room this issue is now created.

Googles "block" is always done through presenting the user a captcha.
After solving it, the block is gone for 3 hours.
The invidious user should have the ability to solve this captcha for the instance if this is possible.

@TheFrenchGhosty suggested https://anti-captcha.com/ which has an API to solve Captchas and it is very cheap too. This can be used to automatically solve the captcha each 3 hours.

Let's calc
$ Price per 1000
min: 2.36, max: 3.37

I will use 3$ / 1000 reCAPTCHAs
1 CAPTCHA -> 0.003 $
1 day = 8 CAPTACHAs -> 0.024 $
7 days = 56 CAPTACHAs -> 0.168 $
30 days = 240 CAPTCHAs -> 0.72 $
1 year (365 days) = 2920 CAPTACHAs -> 8.76 $

**Comment by elypter** [comment]
this sounds reasonable but it is impossible to predict youtubes behavior in the future und thus in unexpected drastic increases of captcha solving. if it is technicaly possible without to much work just let one random user solve it and make it an opt-in option in the preferences. even if just 1% of the users chose to be willing to do this then it would still happen very rarely.

**Comment by omarroth** [comment]
Added with 71bc9eea28ed6fb22992d774443f64ce1d1551be. If you have an API key you can add it to your config as `captcha_key: aaaaaaaa`.

Through some more testing it does not appear to consistently resolve the issue for blocked instances. It may be possible the issue is in submitting or saving cookies between requests.

> The invidious user should have the ability to solve this captcha for the instance if this is possible.

It is not possible to embed or present CAPTCHAs to random users.

**Comment by Perflyst** [comment]
Thank you. As already mentioned in the chat the longest time the instance was working through anti captcha was 4 minutes.

Also the "redirect captcha block" is not handled yet
```
$ curl -s https://www.youtube.com/watch?v=QmyhcjpsF6E -4
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3Fv%3DQmyhcjpsF6E&amp;q=EgRf2BjmGJKaoO4FIhkA8aeDSwTc2PRqzI476Aa-2iHKmGCVxucTMgFy">here</A>.
</BODY></HTML>
```

**Comment by Perflyst** [comment]
Both endpoints were added, workaround reCAPTCHA is successful.

**Comment by haizrul** [comment]
> 1 day = 8 CAPTACHAs -> 0.024 $
7 days = 56 CAPTACHAs -> 0.168 $
30 days = 240 CAPTCHAs -> 0.72 $
1 year (365 days) = 2920 CAPTACHAs -> 8.76 $

My anti-captcha usage statistics are doubled from what you suggest. Is this normal?

**Comment by TheFrenchGhosty** [comment]
@haizrul What you spend depend on your bid, and it doesn't look that different

**Comment by Perflyst** [comment]
I have around the same usage, 15-20 captchas a day. Still 0.04$ a day is nothing.
