### ISSUE TITLE
Views count broken in the homepage / popular page

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#890]
The video views count of the homepage / popular page is broken and is displaying some random numbers.

From my testing, every other pages displaying this number seem to be working correctly.

![view count](https://user-images.githubusercontent.com/47571719/68490205-7b6b1800-0240-11ea-95ff-053b8a798fc0.png)

**Comment by omarroth** [comment]
This is the expected behavior. Invidious can be notified of new videos immediately when they are uploaded, which is the view count number that is displayed in popular and the subscription page.

Generally this number is updated at a later point through polling, although it can take more time.

**Comment by TheFrenchGhosty** [comment]
Some videos came out yesterday and are still displayed with 0 views, and as I said the count is working and every other page.

Is the homepage handled differently?

**Comment by omarroth** [comment]
Yes. For invidio.us, videos on the popular page and subscription pages are updated using [push notifications](https://developers.google.com/youtube/v3/guides/push_notifications) provided by YouTube.

The view count you see on the popular page is the view count of the video almost immediately after it was uploaded.
