### ISSUE TITLE
I am deady paid 200 $ please help m3

### ISSUE THREAD

**Issue by seyretbiz** [omarroth/invidious#891]
I need 3 support and itis very simple but i dont understund
1) How work you https://invidio.us video page data but my server not
2) i want add invidous my  html template (you help me how adding my code )
3) How using a lot of domain other template one server
You agre i now sent you 200 dollar.

**Comment by Booteille** [comment]
Please, everyone already answered to you. Could you stop spamming the issue tracker and keep it clean?

Thanks.

**Comment by seyretbiz** [comment]
> Please, everyone already answered to you. Could you stop spamming the issue tracker and keep it clean?
> 
> Thanks.

You can help me ?

**Comment by seyretbiz** [comment]
i paid you not possible ?
