### ISSUE TITLE
403 Forbidden for YouTube Music videos via API

### ISSUE THREAD

**Issue by lnjX** [omarroth/invidious#898]
When I request YouTube Music content via the Invidious API I get invalid links for the adaptive formats (HTTP 403 Forbidden):
https://invidio.us/api/v1/videos/gT66YftqxyM

So currently I need to enjoy the silence...

It works in other players (youtube-dl, newpipe) and also even in the Invidious player though:
https://invidio.us/watch?v=gT66YftqxyM

Other videos give no result at all, although they are available on youtube.com and work in other players:
https://invidio.us/api/v1/videos/i_friC7j588
https://invidio.us/watch?v=i_friC7j588
https://www.youtube.com/watch?v=i_friC7j588

The latter is probably a different issue.

**Comment by KonoromiHimaries** [comment]
@lnjX https://instances.invidio.us/

**Comment by lnjX** [comment]
@KonoromiHimaries What do you want to say? I also get a 403 with the other instances.

**Comment by omarroth** [comment]
I expect both issues are #92. I'm able to view adaptive formats for the first example. If you're outside the US then you may not be able to view the video even if you're in a region where the video is available.

The second video you provided is not available in the US (where invidio.us is hosted).
