### ISSUE TITLE
My subscriptions feed showcases videos for channels I am not subscribed to.

### ISSUE THREAD

**Issue by dotMavriQ** [omarroth/invidious#903]
![image](https://user-images.githubusercontent.com/7146796/68673993-4b2fbc00-0555-11ea-92a3-d62068a1cac0.png)
Reloading the page does nothing. 
Clicking the link does not take me to Hot Ones, it takes me to this .. french youtuber that plays Pokemon.... that I've never seen, heard of or nor care for.

**Comment by omarroth** [comment]
Would you mind providing your username (either here or omarroth@protonmail.com)?

**Comment by dotMavriQ** [comment]
I emailed omar and we didn't find the solution, it seems to have sorted itself out.

It might have something to do with caching? 

I can not even confirm that the bug specifically came from code related to Invidious. 

Next time I will attempt to provide API requests and more conclusive information on what browser I used and when I noticed the bug.
