### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS for channel and RSS links on the .onion domain

### ISSUE THREAD

**Issue by emanruse** [omarroth/invidious#911]
The issue is for:

http://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion/

Clicking on any channel link or trying to update an RSS feed for any channel gives many many 302 redirects.

**Comment by omarroth** [comment]
Appears to be related to #811. Check that the issue is fixed for you.

**Comment by emanruse** [comment]
Seems to work at the moment.

**Comment by emanruse** [comment]
Broken again.
