### ISSUE TITLE
Unable to load closed captions on any video

### ISSUE THREAD

**Issue by comicsads** [omarroth/invidious#916]
Captions do not appear at all on invidio.us, even on videos confirmed to have captions on YouTube.
Tested on Windows 10, Google Chrome and Brave browser.

**Comment by Zero3K** [comment]
I also can confirm that captions have been broken for a couple of weeks.

**Comment by omarroth** [comment]
Should be fixed with 062867a38dc111fe981e2c65239b557191daa7fa.
