### ISSUE TITLE
Annotations have suddenly stopped working on several videos.

### ISSUE THREAD

**Issue by AgentGrady** [omarroth/invidious#918]
There are several videos on Annotations have suddenly stopped working and it seem to be all on one single channel:

https://dev.invidio.us/channel/UnoriginalMaterial

This is really quite alarming as this is one of my favourite channels that used annotations. Here are some examples of videos that no longer seem to be working:

https://dev.invidio.us/watch?v=FBeuzMM7HSc&iv_load_policy=1

https://dev.invidio.us/watch?v=hf3CHubs_Wc

https://dev.invidio.us/watch?v=j64LcepmarY

**Comment by omarroth** [comment]
They appear to be working as expected for me. What browser are you using?

**Comment by AgentGrady** [comment]
The situation is resolved now, I found that the videos work on invidious.snopyta.org even when they do not work on dev.invidio.us. I don’t know why they suddenly stopped working on there, but they now seem to be working on dev.invidio.us as well. I am sorry for the slow response; I have been busy with university work and so it slipped my mind. If I have any further troubles I will say so but at the moment it seems to be fine.
