### ISSUE TITLE
No Video Playback (Only Sound) on Firefox?

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [omarroth/invidious#920]
I am having issues on Firefox with Invidious. Upon clicking a video, it just stays as the thumbnail and the audio plays, no video. uMatrix and uBlockO aren't blocking anything. Unless it's some issue with an about:config setting, but I'm not sure where to even start.

also unsure if releated, but sometimes pages just seem to completely get stuck loading and only refreshing seems to fix. no issues on any other sites.

**Comment by Z3ROGRAV1TYx** [comment]
ok so my bad, I guess the issue with the video was "listen by default" was checked and it wasn't loading videos. I had unchecked it and tested it before but I guess it didn't save.

Still didn't solve my issue with pages getting stuck with loading, they also just seem kinda slow loading. For a lightweight page, something doesn't seem right.  Like all page loading is just kinda slow and feel a bit bloated.

**Comment by omarroth** [comment]
I'm glad you found what was causing the issue. I expect the issue you're encountering with pages loading slowly is related to how many people are using the site, rather than the size of the page.
