### ISSUE TITLE
Google Analytics Tracking Code Not Working

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#922]
I have a problem using google analytics to track number of users online on my instance. I can see the tracking code when i view the source code of any page on my website, i can see google analytics tracking code, but its not working when i view on google analytics website. I also planning to add sharethis share button on my website. Please help.

**Comment by Perflyst** [comment]
Are you kidding?
You add google analytics to a project made to NOT track users as they are tracked on youtube.com and then you even ask for support on this?!
