### ISSUE TITLE
Service is currently unavailable, please try again later

### ISSUE THREAD

**Issue by seonwoolee** [omarroth/invidious#924]
I'm getting the error message in the title for the main https://invidio.us instance

**Comment by Zero3K** [comment]
How long till its fixed?

**Comment by dch** [comment]
reminder that there are other public instances you can use - https://github.com/omarroth/invidious/wiki/Invidious-Instances and if you're so inclined you can set up your own as well.

**Comment by gwennshinguji** [comment]
> reminder that there are other public instances you can use

most of them are either foreign, down, or blocked.

**Comment by elypter** [comment]
but i have my subscription feed on the main instance. i am already using another instance with invidition.

**Comment by elypter** [comment]
https://dev.invidio.us/ is down as well

**Comment by gloschtla** [comment]
automated forwarding to another instance would be great.
i just posted this [suggestion here on github.](https://github.com/omarroth/instances.invidio.us/issues/6)

**Comment by Zero3K** [comment]
Its back up :)

**Comment by simoniz0r** [comment]
> reminder that there are other public instances you can use - https://github.com/omarroth/invidious/wiki/Invidious-Instances and if you're so inclined you can set up your own as well.

It's not fun to setup an account on each of these and import all of my settings and such.

**Comment by Zero3K** [comment]
Its down again for 5+ hours and counting.

**Comment by elypter** [comment]
> It's not fun to setup an account on each of these and import all of my settings and such.

It would be much less painful if you could sync accounts
