### ISSUE TITLE
Subscriptions not updating

### ISSUE THREAD

**Issue by m4teh** [omarroth/invidious#927]
Since updating to 20.1 (I don't think this happened on 20.0).
After a fresh install, all feeds are pulled and video subscriptions are up to date. This seems to be the last time they refresh.
I can browse to individual channels manually to watch newly uploaded videos, but they don't appear in the subscriptions feed.

I've reinstalled 3 x times on fresh boxes to replicate this issue. 
No warnings or issues in logs, it doesn't seem. Any idea?

**Comment by omar-elnaggar** [comment]
Can confirm I am also getting this issue on the same version.

**Comment by BlipRanger** [comment]
I found that unsubscribing and then resubscribing to a single channel caused all channel subscriptions to be updated.

**Comment by m4teh** [comment]
I wish I could say the same thing. Unfortunately that trick doesn't work
for me. Very frustrating. I'm still on a rolled back version of
0.20.0-e561291 (which luckily hasn't been blocked in a while.)

**Comment by unixfox** [comment]
Thank you for the trick @BlipRanger, it worked for me!

**Comment by BlipRanger** [comment]
> 
> 
> Thank you for the trick @BlipRanger, it worked for me!

Good to know, hopefully this is a clue as to why it isn't working in general.

**Comment by Caboose700** [comment]
I can confirm the issue on 0.20.1-588fc6d, and unfortunately the trick @BlipRanger posted does not work for me either.

**Comment by omarroth** [comment]
Closing in favor of #674.
