### ISSUE TITLE
Leverage browser caching for thumbnails images

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#930]
I tested https://invidio.us on https://gtmetrix.com/reports/invidio.us/HZk7WDum

All seems okay but Gtmetrix recommend one thing to be fix which is leverage browser caching for thumbnails images. Screenshot : https://i.imgur.com/ovthUCD.png .

**Comment by omarroth** [comment]
See #456. Invidious will automatically use the caching headers provided by ytimg.com (namely `etag`), which means the image will generally be cached much longer than 5 minutes.

**Comment by haizrul** [comment]
Oo i see. Ok thanks a lot! 👍
