### ISSUE TITLE
Invidious onion service is not in https

### ISSUE THREAD

**Issue by stemy2** [omarroth/invidious#933]
Hello,

To be fully secure and privacy-friendly, an onion service must be in https too, as well as the duckduckgo onion service, for example. But the onion adress of the main instance is not in https.

**Comment by andretiagogr** [comment]
According to Matt Traudt, HTTPS isn't necessary on onion links

https://matt.traudt.xyz/p/o44SnkW2.html

**Comment by Perflyst** [comment]
As @andretiagogr said, HTTPS is not needed on onion services.
@stemy2 anything else unclear? Otherwise please close.
