### ISSUE TITLE
Invidious doesn't work at all

### ISSUE THREAD

**Issue by jones137** [omarroth/invidious#937]
For about a week, I have seen "download is disabled" in every video, so you couldn't download any video directly. As of today, when trying to watch any video on any instance, including onion, I get "Could not extract video info. Instance is likely blocked.".

I see Google has been working hard on breaking Invidious. Is there any workaround currently available aside from using youtube-dl?

**Comment by mperez01** [comment]
Hello, to download videos you could still right click on the video and download it.
But the blocked seems similar to issue #811

**Comment by haizrul** [comment]
> But the blocked seems similar to issue #811

I thought [Hotfix 0.20.1](https://github.com/omarroth/invidious/releases/tag/0.20.1) already fixed that problem. Right?

**Comment by mperez01** [comment]
> > But the blocked seems similar to issue #811
> 
> I thought [Hotfix 0.20.1](https://github.com/omarroth/invidious/releases/tag/0.20.1) already fixed that problem. Right?

Yes, it seems so, but the issue is not closed and that was a workaround

**Comment by Perflyst** [comment]
Duplicate of #811

**Comment by jones137** [comment]
Seems to work but download is still disabled for me. But okay, closing this now
