### ISSUE TITLE
Error: undefined method 'destroy_engine' for QUIC::Client

### ISSUE THREAD

**Issue by unixfox** [omarroth/invidious#941]
While building the latest commit (https://github.com/omarroth/invidious/commit/3fea1976c835ecd181bbf4c2ca02ee88d61370a1) with `docker-compose up` I got this error:
```
Step 9/18 : RUN crystal build --release --warnings all --error-on-warnings     -Dmusl     ./src/invidious.cr
 ---> Running in 8f823b46373d
Showing last frame. Use --error-trace for full trace.

In src/invidious/helpers/utils.cr:34:14

 34 | conn.destroy_engine
           ^-------------
Error: undefined method 'destroy_engine' for QUIC::Client
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build --release --warnings all --error-on-warnings     -Dmusl     ./src/invidious.cr' returned a non-zero code: 1
```

It seems that falling back to 0.20.1 resolve the error.

**Comment by Fincer** [comment]
Yeah, this happens on Arch Linux (without Docker), too.

**Comment by unixfox** [comment]
I'm going to guess that this commit resolve my issue: https://github.com/omarroth/invidious/commit/a017574f74665edc9645b9e1c0414e0a34e13f41

**Comment by Fincer** [comment]
Yes, the issue is fixed now, invidious compiles successfully.
