### ISSUE TITLE
Rebulding does not working

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#947]
I changed something in config file and save. I rebuild using these 3 commands :

cd /home/invidious/invidious
crystal build src/invidious.cr --release
sudo systemctl restart invidious.service

But nothings changed. I don't know why. Please help.

**Comment by tleydxdy** [comment]
what's the error? 😑

**Comment by Perflyst** [comment]
Likely duplicate of #917

**Comment by gled-rs** [comment]
probably the same as https://github.com/omarroth/invidious/issues/917#issuecomment-562273603

**Comment by omarroth** [comment]
Closing in favor of #917. Try building without `--release`.
