### ISSUE TITLE
[QUESTION] How to forward IP:PORT to registered domain name?

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#950]
I've installed invidious on server running on Debian 10. But right now i can only access invidious on my server using IP:PORT ,e.g : 1.1.1.1:3000 . How do i forward port 3000 to port 80 and connect it with my domain. Please help.

**Comment by ncaos** [comment]
```
      ProxyPreserveHost On
      ProxyPass / http://ip:3000/
      ProxyPassReverse / http://ip:3000/
      ServerName host
      ServerAlias www.host

```

**Comment by haizrul** [comment]
> ```
>       ProxyPreserveHost On
>       ProxyPass / http://ip:3000/
>       ProxyPassReverse / http://ip:3000/
>       ServerName host
>       ServerAlias www.host
> ```
> 
> apache2

Is it possible to do this without using apache reverse proxy?

**Comment by ncaos** [comment]
Sure, with another program that will provide a reverse proxy.

**Comment by haizrul** [comment]
Ok thanks a lot bro. 👍
