### ISSUE TITLE
Docker build fails in a git submodule with not a git repository

### ISSUE THREAD

**Issue by seonwoolee** [omarroth/invidious#951]
I made sure to run 
```
docker-compose stop
docker-compose rm
docker system prune -a
```
before `docker-compose up -d`.

I'm getting the error 
```
Step 10/22 : RUN crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"
 ---> Running in c7eb2349c343
fatal: not a git repository (or any of the parent directories): .git
Showing last frame. Use --error-trace for full trace.

In src/invidious.cr:62:25

 62 | CURRENT_VERSION = {{ "#{`git describe --tags --abbrev=0`.strip}" }}
                              ^
Error: error executing command: git describe --tags --abbrev=0, got exit status 128
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"' returned a non-zero code: 1
```

**Comment by tleydxdy** [comment]
yes, because build will use git to determine the current version. it's documented in the Dockerfile https://github.com/omarroth/invidious/blob/master/docker/Dockerfile

**Comment by seonwoolee** [comment]
I'm not sure what you mean. Am I supposed to run `docker-compose build` first? Because that fails with the exact same error

**Comment by tleydxdy** [comment]
you need to build from a git repo. or you need to modify the line in the source code to be whatever version you want.

**Comment by seonwoolee** [comment]
If I'm understanding you correctly, this is my issue:

I have this git repo as a git submodule to my own repo that houses all my Dockerfile and docker-compose.yml's. I can't expect docker-compose up to work as is with it as a submodule.

**Comment by tleydxdy** [comment]
submodules should have their own .git folders also.

**Comment by seonwoolee** [comment]
They do, but the .git folder is found under the `.git/modules/invidious` folder of my parent repo, and in the submodule's folder, there's only a `.git` file that contains `gitdir: ../.git/modules/invidious` (it's not a symlink).

So then https://github.com/omarroth/invidious/blob/master/docker/Dockerfile#L20 copies this one line file that isn't a symlink.

**Comment by seonwoolee** [comment]
Anyways I fully understand the issue now and the workaround. Closing
