### ISSUE TITLE
Video page broken

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#952]
My instance have some problem. Video page is broken, some elements are not load. E.g: comments, related videos, also some images are not loaded. Top page and Popular page also not working. This happen suddenly. Please take a look at my instance http://viraltube.my/watch?v=2lAe1cqCOXo

**Comment by tleydxdy** [comment]
works fine from here

**Comment by haizrul** [comment]
Still broken from my end. :/

**Comment by Perflyst** [comment]
>  Could not extract video info. Instance is likely blocked. 

This is because you are blocked by google. If you have IPv6, try force_resolve: ipv6 otherwise get a new IP. You can also try to use https://anti-captcha.com and set your api token with `captcha_key: token`

**Comment by haizrul** [comment]
> > Could not extract video info. Instance is likely blocked.
> 
> This is because you are blocked by google. If you have IPv6, try force_resolve: ipv6 otherwise get a new IP. You can also try to use https://anti-captcha.com and set your api token with `captcha_key: token`

Tried checking with das_capcha but don't seems to be blocked on both ipv4 and ipv6. But i will try use https://anti-captcha.com and see how it goes.
![Screenshot_7](https://user-images.githubusercontent.com/8771582/70389357-6af1bd00-19f9-11ea-8d25-c8d817fd643a.png)

**Comment by haizrul** [comment]
> captcha_key: token

I should put this on config.yml right?

**Comment by haizrul** [comment]
Update : After using https://anti-captcha.com instance seems to be working again. Thanks a lot @Perflyst for the suggestion 👍

**Comment by Perflyst** [comment]
Also grep for "sorry", there are two different blocks.
