### ISSUE TITLE
IPv6 on invidio.us

### ISSUE THREAD

**Issue by unixfox** [omarroth/invidious#956]
Is it possible to add IPv6 on invidio.us?
It seems that invidio.us is hosted on DigitalOcean and DigitalOcean does support IPv6: https://www.digitalocean.com/docs/networking/ipv6/how-to/enable/.

**Comment by omarroth** [comment]
IPv6 should now be supported.

**Comment by unixfox** [comment]
Thank you! It is indeed working great on IPv6.

**Comment by unixfox** [comment]
@omarroth can you also add support for IPv6 on instances.invidio.us?
Thank you :)
