### ISSUE TITLE
Postgres: table privacy is created after being referenced in playlists

### ISSUE THREAD

**Issue by edgd1er** [omarroth/invidious#962]
Privacy should be created before being referenced:

https://github.com/omarroth/invidious/blob/588fc6df85e4bdcd1caff3c3d544a55a234362ee/docker/entrypoint.postgres.sh#L24

L24 should be in L15, in ordrer to create the privacy table and then reference is in playlists.

see errors in #926

**Comment by omarroth** [comment]
Fixed with #1042. Thanks @leonklingele!
