### ISSUE TITLE
Cannot view channels or subscribe

### ISSUE THREAD

**Issue by m4teh** [omarroth/invidious#963]
- Fresh install
- Docker master 0.20.1-588fc6d
- Everything builds and installs perfectly, included fix from #962 for database errors
- Instance isn't banned, can watch videos fine via search function
- When searching a channel name, clicking on it gives "Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com." with no log output
- Importing subscriptions from json/opml doesn't work
- Tested on multiple different IPs yielding identical results (one on a completely different range and which has never used Invidious before)
- This probably explains #927 
- Searching a video belonging to the same channel, hitting the 'Subscribe" on that page gives an error:

> Exception: Could not extract channel info. Instance is likely blocked. (Exception)
>
  >from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
>
>2019-12-20 07:31:48 UTC 500 POST /subscription_ajax?action_create_subscription_to_channel=1&redirect=false&c=UCIYoc_redacted_cw 720.87ms

**Comment by unixfox** [comment]
I've the same exact issue as you on my instance (https://yewtu.be), really strange error.
I still need to investigate if it's really a block from Google or the results that are different so Invidious can't parse it.
The thing is changing IP fixes the issue but it comes back after a few minutes.

**Comment by unixfox** [comment]
Another log related to that issue:
````
invidious_1  | Exception: Unexpected char '<' at 1:1 (JSON::ParseException)
invidious_1  |   from ???
invidious_1  |   from ???
invidious_1  |   from ???
invidious_1  |   from ???
invidious_1  |   from ???
invidious_1  |   from ???
invidious_1  |   from ???
invidious_1  |   from ???
invidious_1  |   from ???
invidious_1  |   from ???
````

**Comment by Perflyst** [comment]
Your IP is blocked quite sure. Please curl a youtube video url and grep for captcha

**Comment by unixfox** [comment]
No it isn't. Videos load perfectly fine.
You can test on my instance: https://yewtu.be/
As you can see a video load fine: https://yewtu.be/watch?v=mhrkdHshb3E but not channels: https://yewtu.be/channel/spacexchannel

**Comment by Perflyst** [comment]
okay, then this is something interested i also noticed
for example on my instance everything works except comments / likes

it looks like it is partly blocked only

**Comment by unixfox** [comment]
Ok so after investigations I found by MITM the connections of invidious that my instance is indeed partially blocked:
![2020-01-21_10-47_1](https://user-images.githubusercontent.com/4016501/72793984-1c0f8800-3c33-11ea-85f5-0cf4d0adcff8.png)

I guess Google is blocking instances pretty quick now.

**Comment by unixfox** [comment]
I think it's safe to say that this issue can closed because it's related to Google blocking pretty quick if there are too many requests to their servers.
The solution is to unfortunately using anti-captcha
