### ISSUE TITLE
getClientRects Fingerprinting !!!!!!! Warning

### ISSUE THREAD

**Issue by coolcoderplus** [omarroth/invidious#965]
I have the canvasBlocker plugin on firefox and on your official instance we can see an attempt to recover a domRect fingerprint for our browsers.
https://invidio.us is impacted and onions site too :)
It's pretty perverse considering that the tor browser is not yet immune to this type of fingerprinting !
see:
https://browserleaks.com/rects#further-reading
http://jcarlosnorte.com/security/2016/03/06/advanced-tor-browser-fingerprinting.html

Can you explain why you are doing this on your official invidio instance knowing that other instances like this one have no tracker.

We await your response...

**Comment by Perflyst** [comment]
What the actual f?
