### ISSUE TITLE
Clicking on genre gives error

### ISSUE THREAD

**Issue by ChaseHall** [omarroth/invidious#968]
Video it occurred on: https://www.invidio.us/watch?v=1n_cPIhag28

Simply clicking the "Entertainment" hyperlink, which goes [here](https://www.invidio.us/channel/UCi-g4cjqGV7jvU8aeSuj0jQ) produces the error.

**Comment by omarroth** [comment]
Should be fixed with 4aada65dae72d1f563a6f3f816afd2299d66a3dc.

**Comment by ChaseHall** [comment]
Works perfectly, Thank you so much.
