### ISSUE TITLE
issue with `view_all_playlists` on a fresh install

### ISSUE THREAD

**Issue by zapashcanon** [omarroth/invidious#972]
Hi,

I just installed invidious [on my server](https://invidious.zapashcanon.fr), when clicking on the `Playlists` link, I've got the following:

```txt
Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com.
```

I quickly searched in the issues and found nothing about this. Let me know if you need me to provide anything, or if it's a known issue.

**Comment by leanderseidlitz** [comment]
Hey,
stubled upon the same issue, seems like there are psql commands missing in the installation description (compared to the dockerfile). Executing

psql invidious kemal < /home/invidious/invidious/config/sql/privacy.sql
psql invidious kemal < /home/invidious/invidious/config/sql/playlists.sql
psql invidious kemal < /home/invidious/invidious/config/sql/playlist_videos.sql

fixes the issue.
