### ISSUE TITLE
Put the docker image on hub.docker.com

### ISSUE THREAD

**Issue by PureTryOut** [omarroth/invidious#977]
Currently the most used Invidious image on hub.docker.com is an Arch Linux based image with 100k+ downloads. I would prefer using an image based on the official Dockerfile in this repo (I love myself some Alpine Linux) but that does mean I have to build it myself everytime there is an update.

If the official image were to be put on Docker hub, I could modify my docker-compose file to just pull the official image.

**Comment by unixfox** [comment]
Hello, I created an image on Quay synced with the master branch of invidious: https://quay.io/repository/unixfox/invidious

I didn't use Docker Hub because only quay is able to use a git as a source for building an image.

**Comment by leonklingele** [comment]
@omarroth unfortunately we can't really help you with this. Here's a simple 4-step tutorial: https://docs.docker.com/docker-hub/
Then there's [this tutorial](https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry) on how to auto-push images from Travis CI once they're built.

In case you're interested, I just claimed the `invidious` user on Docker Hub.

**Comment by unixfox** [comment]
You don't need any of that. The default docker hub builder works fine.
Just create an account on hub.docker.com then create a new repository and link it to the github repository. Finally add a build rule at the bottom.
That's it!

**Comment by unixfox** [comment]
@omarroth 
1. Signup on https://hub.docker.com/signup
2. Create a repository: https://hub.docker.com/repository/create
3. Fill out the fields and click on the `+` just near to `BUILD RULES`. You will probably have to authorize the Docker hub app just after clicking on the github icon.
![image](https://user-images.githubusercontent.com/4016501/73680886-067b7300-46b5-11ea-99e4-2569aba9fa0a.png)
4. Click on "create and build"
![image](https://user-images.githubusercontent.com/4016501/73680969-3d518900-46b5-11ea-99d3-5c2f3e139ce4.png)

That's it!

**Comment by omarroth** [comment]
Should be available here: https://hub.docker.com/r/omarroth/invidious.

**Comment by PureTryOut** [comment]
Awesome, it works great! Thank you very much for the effort!

**Comment by leonklingele** [comment]
Nice! @omarroth it would be nice if you could create Docker tags for each of the upcoming releases.
