### ISSUE TITLE
Allow to set custom settings for embeded videos

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#98]
Since embeded videos do not respect user-defined settings such as default subtitle settings, it's probably a good idea to implement a possibility to set user settings without using cookies, e.g.
`https://www.invidio.us/embed/XXXXXX?sub=en,ru&speed=1.5`

Such URLs can be used by user.js scripts for embeding invidious videos.

**Comment by omarroth** [comment]
Currently you can set `autoplay`, `loop`, and `quality` for embedded, I like the idea of setting without cookies, and only doing them as params, which would need to include `subs`, `speed`, `volume`.

**Comment by omarroth** [comment]
7fd0f93d029b8bd69409256c39bb0ead7929aa3a adds support for preferences as query params. It exposes:

- speed (e.g. `&speed=1.43`)
- volume (e.g. `&volume=85`)
- subtitles (e.g. `&subtitles=en,ru,es`)

You can use all of these on the `/watch` page as well. They will override user preferences if you're logged in.
