### ISSUE TITLE
Error: you've found a bug in the Crystal compiler.

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#981]
I update the latest commit. When try to recompile, this error occur :

![error](https://user-images.githubusercontent.com/8771582/72051355-11cdbf80-32fe-11ea-99b5-b43fc592c7f4.png)

**Comment by Perflyst** [comment]
run as all the stuff as root :1st_place_medal: 

please change owner and group to invidious:invidious, then use invidious user to compile stuff
also please run `shards install && shards update && crystal build src/invidious.cr`

**Comment by haizrul** [comment]
> please change owner and group to invidious:invidious, then use invidious user to compile stuff
also please run shards install && shards update && crystal build src/invidious.cr

Thanks for your help sir. Its working now. 👍 

> which crystal version are you using?

crystal: 0.32.0
