### ISSUE TITLE
XML Parsing Error on Invidio.us

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#987]
A really small number of videos don't play on Invidio.us but do play on other instances.

Example: https://invidio.us/watch?v=yP5SQq5mfR8

The browser is reporting:

![screenshot](https://user-images.githubusercontent.com/47571719/72321937-0b906800-369d-11ea-89d1-37cecaccea71.png)

I'm guessing that it's a problem caused by the fact that invidio.us uses a "unique" setup (20+ servers) and that something gets lost along the way.

It seems to be working on Chromium based browser though.

**Comment by omarroth** [comment]
Should already be fixed with 7b88d0efe3db6d1c288bf04991f3386c61e445d1.

**Comment by TheFrenchGhosty** [comment]
It seems to work, however the comments trigger a 500.

![s](https://user-images.githubusercontent.com/47571719/72366923-22fa4000-36f3-11ea-9a95-924409f38cbf.png)

**Comment by omarroth** [comment]
The linked video doesn't appear to have any comments, which would explain the error. Seems like a separate issue though.
