### ISSUE TITLE
Links to channels without /channel/ doesn't work

### ISSUE THREAD

**Issue by ToughGuyKunio** [omarroth/invidious#988]
On YouTube you can link to channel pages directly, like: https://youtube.com/pewdiepie - on invidious this doesn't work.

Links to channel pages like https://invidio.us/pewdiepie doesn't work, only links with /channel/ or /user/, like https://invidio.us/channel/pewdiepie works.

This becomes an issue when using redirect extensions, like https://github.com/SimonBrazell/privacy-redirect/issues/7

**Comment by omarroth** [comment]
Should be fixed with 7baced75e555f094daaff3bfb06e34a9653408ab.

**Comment by ToughGuyKunio** [comment]
Yes seems to work now, thanks!
