### ISSUE TITLE
Invidious Bug

### ISSUE THREAD

**Issue by TC9898** [omarroth/invidious#990]
Apparently it said that had found a bug on the website and told me to contact you, also the bug might be that currently right now everytime I open a video to watch it just says Error on the invidious tab and nothing shows

**Comment by krrisztian** [comment]
invidio.us has been down and up in the last three hours (starting at ~12:00 on 15th of Jan) with very slow response time and usually giving a "500 Internal Server Error" message.
Just for clarification for the admin.

**Comment by haizrul** [comment]
Looks fine now.
