### ISSUE TITLE
Change link and button color

### ISSUE THREAD

**Issue by TheFoxStudio** [omarroth/invidious#995]
Hello,

I am running invidious on an LXC container. Pretty happy with it as I am using it alone with my wife so there is not a lot of traffic. invidio.us has been down all evening today unfortunatly. So I can't grab my subscriptions yet.

Anyway. I am done with setting everything up. The only thing I would like to change is the color of buttons, links and the progress bar from this blue-ish color to a red. 
How is it possible? I found .ecr files that seem to contain the actual web layout but changes to the template for example are not even been displayed. 
How do I change things like the color? And why do my changes in the .ecr not take affect.
Example: I renamed the title from "Invidious" to "Invidious Portal" but the web UI stays the same.

Help much appreciated.

**Comment by afrmtbl** [comment]
You'll need to recompile Invidious for changes to the `.ecr` files to take effect.

As for changing colors, I believe the relevant files are:
`assets/css/default.css` (main one)
`assets/css/lighttheme.css`
`assets/css/darktheme.css`

I don't think recompiling is necessary if only changing the css.
Restarting Invidious should be enough.

**Comment by TheFoxStudio** [comment]
Thanks for your reply. 
recompile means run `crystal build src/invidious.cr --release` ?

I will have a look at it this week so thanks so far tho.

**Comment by afrmtbl** [comment]
Yep, that will recompile.
Glad to help :slightly_smiling_face:

**Comment by TheFoxStudio** [comment]
Worked perfect. I appreciate the help!
